export const cambodiaDestinations = [
  {
    slug: 'angkor-wat',
    name: 'Angkor Wat',
    country: 'Cambodia',
    region: 'Cambodia',
    tagline: 'The World\'s Largest Religious Monument',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/asia/angkor-wat.jpg',
    highlights: ['Angkor Wat', 'Bayon Temple', 'Ta Prohm', 'Angkor Thom', 'Banteay Srei', 'Sunrise'],
    bestTime: 'Nov–Mar',
    duration: '2–3 nights',
    from: '$380',
    description: "Angkor Wat is the world's largest religious monument — a 400-square-kilometer complex of 72 major temples built by the Khmer Empire (802-1431 AD), the largest pre-industrial city in the world. Angkor Wat itself is the most famous temple — a 5-towered, 65-meter-high temple built for King Suryavarman II in the 12th century, oriented to the west (symbolizing death, so some believe it was a funerary temple). The best time to see Angkor Wat is at sunrise — the sun rises behind the central tower, reflecting the outline of the temple in the lotus pond (arrive at 4:30 am for the best spot). Bayon Temple is in the center of Angkor Thom — 54 towers, each with 4 faces (representing the Bodhisattva Avalokitesvara, probably a portrait of King Jayavarman VII), looking in all 4 directions. Ta Prohm is the 'Tomb Raider Temple' (Angelina Jolie filmed here) — strangler fig trees and silk cotton trees have grown over and through the temple ruins, their roots wrapping around stone walls. Angkor Thom is the last capital of the Khmer Empire — 3 kilometers of wall, 5 monumental gates (each topped with 4 faces), and the Terrace of the Elephants (350 meters of elephant carvings). Banteay Srei is a 10th-century temple made of pink sandstone — the most intricate carvings in Angkor (the 'jewel of Khmer art'), a 40-minute drive from Angkor Wat (worth the trip). Angkor is hot and humid — carry water, wear sunscreen, and cover your shoulders and knees (the temple guards enforce dress codes). A 3-day Angkor Pass costs $62 (9 days validity).",
    experiences: [
      'Angkor Wat sunrise',
      'Bayon 54 faces',
      'Ta Prohm tree roots',
      'Angkor Thom elephant terrace',
      'Banteay Srei pink temple',
      'Phnom Bakheng sunset',
    ],
    camps: ['Raffles Grand Hotel d\'Angkor', 'Belmond La Résidence', 'Shinta Mani Angkor', 'Sofitel Angkor Phokeethra', 'Anantara Angkor'],
    unesco: true,
  },
  {
    slug: 'phnom-penh',
    name: 'Phnom Penh',
    country: 'Cambodia',
    region: 'Cambodia',
    tagline: 'The Charming Capital',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/asia/phnom-penh.jpg',
    highlights: ['Royal Palace', 'Silver Pagoda', 'Tuol Sleng Genocide Museum', 'Killing Fields', 'Independence Monument'],
    bestTime: 'Nov–Mar',
    duration: '2–3 nights',
    from: '$280',
    description: "Phnom Penh is Cambodia's capital — a city of French colonial architecture, the Royal Palace, and a tragic history that every visitor should understand. The Royal Palace was built in 1866 — the Silver Pagoda (Wat Preah Keo) is inside the palace, with a floor of 5,000 silver tiles (each weighing 1 kilogram), a 90-kilogram gold Buddha covered in 2,084 diamonds, and a 17th-century emerald Buddha (made of crystal). Tuol Sleng Genocide Museum (S-21) was a high school turned into a Khmer Rouge prison (1975-1979) — 17,000 prisoners (men, women, children) passed through, only 7 survived. The museum has 4 buildings of torture rooms, photographs of victims, and (1,000+ skulls of the last prisoners). The Killing Fields (Choeung Ek) are a 15-kilometer drive from Phnom Penh — a former orchard where the Khmer Rouge executed 17,000 prisoners (mostly from S-21). A memorial stupa holds 5,000 skulls, organized by gender (men, women, children). The audio tour (available at the entrance) is essential (English, French, German, Japanese). The Independence Monument is a 37-meter, lotus-shaped stupa built to celebrate Cambodia's independence from France in 1953 — the monument is lit at night and is a popular meeting place for locals. The Phnom Penh riverfront (Sisowath Quay) is 3 kilometers of parks, restaurants, and bars — the best place for sunset drinks with views of the Mekong River.",
    experiences: [
      'Royal Palace Silver Pagoda',
      'Tuol Sleng S-21 prison',
      'Killing Fields audio tour',
      'Independence Monument lights',
      'Sisowath Quay sunset',
      'Russian Market bargains',
    ],
    camps: ['Raffles Hotel Le Royal', 'Sofitel Phnom Penh', 'Rosewood Phnom Penh', 'Hyatt Regency Phnom Penh', 'Plantation Urban Resort'],
    unesco: false,
  },
]