export const indiaDestinations = [
  {
    slug: 'agra',
    name: 'Agra & Taj Mahal',
    country: 'India',
    region: 'India',
    tagline: 'The Monument of Love',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/asia/taj-mahal.jpg',
    highlights: ['Taj Mahal', 'Agra Fort', 'Itmad-ud-Daulah', 'Mehtab Bagh', 'Fatehpur Sikri', 'Marble Inlay'],
    bestTime: 'Oct–Mar',
    duration: '2–3 nights',
    from: '$380',
    description: "The Taj Mahal is the most beautiful building ever built — a white marble mausoleum built by Emperor Shah Jahan for his wife Mumtaz Mahal (who died giving birth to their 14th child), taking 22 years and 20,000 workers to complete (1632-1654). The Taj's marble changes colour throughout the day — pinkish at dawn, dazzling white at noon, golden at sunset, and on full moon nights, the marble glows silver. The best time to visit is at sunrise (6-7 am) — the crowds are smaller, and the light is perfect for photography. The Taj Mahal is open 6 am-7 pm daily except Friday (prayer day, only open to mosque visitors). You can buy tickets online (1,000 rupees for foreigners, 50 rupees for locals). Agra Fort (also called Red Fort) is a 2.5-kilometer red sandstone fortress on the Yamuna River — you can see the Taj Mahal from the fort's balconies (where Shah Jahan was imprisoned by his son for 8 years). Itmad-ud-Daulah (Baby Taj) is a smaller marble tomb with delicate pietra dura (marble inlay) work — the first tomb to be built entirely of white marble in India. Mehtab Bagh is the 'Moonlight Garden' across the Yamuna River from the Taj — the best place for sunset photos of the Taj without the crowds. Fatehpur Sikri is a 1-hour drive from Agra — a abandoned Mughal capital built in 1571, abandoned after 14 years because of water shortages (a 'ghost city' of red sandstone palaces).",
    experiences: [
      'Taj Mahal at sunrise (6 am)',
      'Agra Fort balcony view',
      'Baby Taj marble inlay',
      'Mehtab Bagh sunset photos',
      'Fatehpur Sikri ghost city',
      'Marble inlay workshop',
    ],
    camps: ['Oberoi Amarvilas', 'ITC Mughal Agra', 'Trident Agra', 'The Gateway Hotel', 'Taj Hotel & Convention Centre'],
    unesco: true,
  },
  {
    slug: 'jaipur',
    name: 'Jaipur',
    country: 'India',
    region: 'India',
    tagline: 'The Pink City',
    gradient: 'linear-gradient(160deg,#1c0c00,#2e1800,#402200)',
    image: '/images/asia/jaipur.jpg',
    highlights: ['Hawa Mahal', 'Amber Fort', 'City Palace', 'Jantar Mantar', 'Jal Mahal', 'Elephant Village'],
    bestTime: 'Oct–Mar',
    duration: '3–4 nights',
    from: '$320',
    description: "Jaipur is the Pink City — the capital of Rajasthan, painted terracotta pink in 1876 to welcome the Prince of Wales. Hawa Mahal (Palace of Winds) is the most photographed building in Jaipur — a 5-story pyramid of 953 small windows (jharonkas) built for the royal women to watch street processions without being seen. Amber Fort is a 10-kilometer drive from Jaipur — a 16th-century fort on a hill, best reached by jeep (or you can walk 30 minutes up the ramp). The fort has Sheesh Mahal (Mirror Palace) with thousands of tiny mirrors embedded in the walls. City Palace is still the residence of the Jaipur royal family — you can tour the museums (textiles, weapons, paintings) and visit the Pritam Niwas Chowk (Peacock Gate) with its four gates (symbolizing spring, summer, autumn, winter). Jantar Mantar is a UNESCO World Heritage site of 19 astronomical instruments (built 1724) — the Samrat Yantra (World's Largest Sundial) is 27 meters tall and accurate to 2 seconds. Jal Mahal (Water Palace) is a 5-story palace in the middle of Man Sagar Lake — only the top floor is visible (the other four are underwater), best viewed from the road (no access). Elephant Village is an ethical elephant sanctuary where you can bathe, feed, and paint elephants (no riding).",
    experiences: [
      'Hawa Mahal photo at sunrise',
      'Amber Fort jeep ride',
      'City Palace Peacock Gate',
      'Jantar Mantar sundial',
      'Jal Mahal sunset view',
      'Elephant painting experience',
    ],
    camps: ['Rambagh Palace', 'Raj Palace', 'Jai Mahal Palace', 'Samode Haveli', 'Fairmont Jaipur'],
    unesco: true,
  },
  {
    slug: 'kerala',
    name: 'Kerala Backwaters',
    country: 'India',
    region: 'India',
    tagline: 'God\'s Own Country',
    gradient: 'linear-gradient(160deg,#001c10,#002c1a,#003c22)',
    image: '/images/asia/kerala.jpg',
    highlights: ['Houseboat', 'Alleppey Backwaters', 'Kumarakom', 'Kochi', 'Vembanad Lake', 'Ayurveda'],
    bestTime: 'Oct–Feb',
    duration: '3–5 nights',
    from: '$280',
    description: "Kerala is 'God's Own Country' — a tropical state of palm-fringed beaches, tea plantations, and 1,500 kilometers of backwaters (lagoons, lakes, and canals). The Alleppey Backwaters are the most famous — a 3-hour drive from Kochi, with 900 kilometers of waterways, 44 rivers, and 2,000 houseboats. A houseboat (kettuvallam) is a converted rice barge — 60-100 feet long, with 2-3 bedrooms, a kitchen, and a rooftop deck. The 1-night cruise (24 hours, 3 meals included) is the classic experience — you sail from 12 pm to 5 pm (sunset views), anchor for the night (you hear the frogs and birds), and wake up for sunrise. Kumarakom is a quieter alternative to Alleppey — on the shores of Lake Vembanad (the longest lake in India, 96 kilometers). The Kumarakom Bird Sanctuary has migratory birds from Siberia (October-March). Kochi (Cochin) is the gateway to the backwaters — Fort Kochi has Chinese fishing nets (introduced by Chinese traders 600 years ago), the 16th-century St. Francis Church (the oldest European church in India), and the Mattancherry Palace (Dutch Palace). Kerala is famous for Ayurveda (traditional Indian medicine) — treatments include herbal massages, steam baths, and 'shirodhara' (warm oil poured on the forehead).",
    experiences: [
      'Alleppey houseboat overnight',
      'Kumarakom bird sanctuary',
      'Fort Kochi Chinese fishing nets',
      'Kerala Ayurvedic massage',
      'Kochi spice market',
      'Vembanad Lake sunset cruise',
    ],
    camps: ['Kumarakom Lake Resort', 'Punnamada Resort', 'The Zuri Kumarakom', 'Coconut Lagoon', 'Taj Malabar Resort'],
    unesco: false,
  },
]