export const indonesiaDestinations = [
  {
    slug: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    region: 'Indonesia',
    tagline: 'Island of the Gods',
    gradient: 'linear-gradient(160deg,#001c10,#00301a,#004424)',
    image: '/images/asia/bali.jpg',
    highlights: ['Rice Terraces', 'Ubud', 'Beach Clubs', 'Temples', 'Yoga Retreats'],
    bestTime: 'Apr–Oct',
    duration: '5–8 nights',
    from: '$850',
    description: "Bali has been seducing travellers for a century — volcanic mountains, spice-scented jungle, rice paddies terraced into impossible green slopes, and a Hindu culture that permeates every aspect of life. The Tegalalang Rice Terraces are the most famous in Bali — the subak (irrigation system) has been used for 1,000 years and is a UNESCO World Heritage site. Ubud is the cultural heart of Bali — the Sacred Monkey Forest has 700 crab-eating macaques (hold your belongings tight, they steal sunglasses and phones), the Ubud Palace has evening Legong dance performances, and the Campuhan Ridge Walk is a free sunrise hike. Bali has world-class beach clubs — Potato Head in Seminyak has an infinity pool and sunset DJ sets, while Sundays Beach Club in Uluwatu is on a private cove. The Tanah Lot Temple is the most photographed temple in Bali — the 15th-century Hindu temple sits on a rock formation just off the coast, best visited at sunset. Bali is a surfer's paradise — Kuta Beach (beginner waves), Uluwatu (expert reef breaks), and Padang Padang (consistent barrels). Yoga retreats are everywhere — The Yoga Barn in Ubud is the most famous, with 15 classes daily, organic cafes, and Kirtan chanting. Nusa Penida is a 45-minute fast boat from Bali — Kelingking Beach ('T-Rex') viewpoint is the most Instagrammed spot in Bali, with a 400-step staircase down to the beach.",
    experiences: [
      'Tegalalang Rice Terrace sunrise',
      'Sacred Monkey Forest in Ubud',
      'Sunset at Uluwatu Temple with Kecak fire dance',
      'Mount Batur sunrise trek',
      'Spa and yoga retreat in Ubud',
      'Beach day at Seminyak or Nusa Dua',
    ],
    camps: ['Mandapa Ritz-Carlton Reserve', 'Four Seasons Sayan', 'Capella Ubud', 'The Edge Bali', 'Amandari'],
    unesco: true,
  },
  {
    slug: 'komodo',
    name: 'Komodo National Park',
    country: 'Indonesia',
    region: 'Indonesia',
    tagline: 'Home of the Komodo Dragon',
    gradient: 'linear-gradient(160deg,#001c14,#002c1e,#004028)',
    image: '/images/asia/komodo.jpg',
    highlights: ['Komodo Dragons', 'Pink Beach', 'Padar Island', 'Manta Rays', 'Snorkeling', 'Labuan Bajo'],
    bestTime: 'Apr–Dec',
    duration: '4–6 nights',
    from: '$950',
    description: "Komodo National Park is a UNESCO World Heritage site — home to the Komodo dragon, the world's largest lizard, growing up to 3 meters long and weighing 150 kilograms. There are about 1,700 Komodo dragons in the park, on Komodo Island and Rinca Island (your guide carries a forked stick to fend off dragons). The Komodo dragons eat deer, water buffalo, and occasionally humans (three attacks in the last 50 years, one fatal). Pink Beach (Pantai Merah) is one of only 7 pink sand beaches in the world — the pink color comes from crushed red coral mixed with white sand. Padar Island has the most spectacular viewpoint in Indonesia — a 1-hour hike to the summit of Padar Island gives you a 360-degree view of the 3 bays (white sand, black sand, and pink sand beaches). Manta rays are common in Komodo waters — Manta Point (near Komodo Island) has a cleaning station where manta rays (3-5 meters wide) gather to be cleaned by small fish. Snorkeling and diving are world-class — the waters around Komodo have 1,000+ fish species, 260 species of coral, and strong currents that attract large marine life. Labuan Bajo is the gateway town on Flores Island — you can book multi-day liveaboard trips (3-5 days) that sleep on a boat, visiting all the major sites. Komodo National Park is accessible by air from Bali (1.5-hour flight to Labuan Bajo, then a 2-hour boat ride to Komodo Island).",
    experiences: [
      'Komodo dragon trek on Rinca Island',
      'Pink Beach swimming',
      'Padar Island sunrise viewpoint',
      'Manta Point snorkeling',
      'Liveaboard 3-day trip',
      'Kalong Island fruit bat sunset',
    ],
    camps: ['Ayana Komodo Resort', 'Plataran Komodo', 'Laprima Hotel Labuan Bajo', 'Sudamala Resort', 'Liveaboard boats'],
    unesco: true,
  },
]