export const japanDestinations = [
  {
    slug: 'kyoto',
    name: 'Kyoto',
    country: 'Japan',
    region: 'Japan',
    tagline: 'Japan\'s Cultural Heart',
    gradient: 'linear-gradient(160deg,#1a0a1a,#2d142d,#401e40)',
    image: '/images/asia/kyoto.jpg',
    highlights: ['Fushimi Inari', 'Arashiyama Bamboo', 'Geisha Culture', 'Kiyomizu-dera', 'Tea Ceremonies'],
    bestTime: 'Mar–May (Cherry Blossom) · Oct–Nov (Autumn)',
    duration: '4–6 nights',
    from: '$1,200',
    description: "Kyoto is Japan's most beautiful city — the cultural heart of the nation with over 1,600 Buddhist temples, 400 Shinto shrines, and 17 UNESCO World Heritage sites. Unlike Tokyo's frantic energy, Kyoto moves at a contemplative pace, where centuries-old traditions like geisha performances and tea ceremonies are still part of daily life. The Fushimi Inari Shrine's thousands of vermilion torii gates create a tunnel through the forested mountain. The Arashiyama Bamboo Grove feels otherworldly, with light filtering through towering green stalks. Kiyomizu-dera Temple offers spectacular views over the city from its wooden stage. Spring brings cherry blossoms that transform the Philosopher's Path into a pink tunnel. Autumn paints the temples in brilliant reds and golds. Kyoto is not just a destination — it's the soul of traditional Japan, a living museum where every corner reveals something ancient and beautiful.",
    experiences: [
      'Fushimi Inari Shrine — 10,000 red torii gates up the mountain',
      'Arashiyama Bamboo Grove at sunrise — before the crowds',
      'Traditional tea ceremony in Gion district',
      'Kiyomizu-dera Temple sunset overlooking Kyoto',
      'Golden Pavilion (Kinkaku-ji) in morning light',
      'Philosopher\'s Path cherry blossom walk',
    ],
    camps: ['Aman Kyoto', 'The Ritz-Carlton Kyoto', 'Hoshinoya Kyoto', 'Four Seasons Kyoto', 'Park Hyatt Kyoto'],
    unesco: true,
  },
  {
    slug: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    region: 'Japan',
    tagline: 'The World\'s Greatest Metropolis',
    gradient: 'linear-gradient(160deg,#0a1428,#142040,#1e2c58)',
    image: '/images/asia/tokyo.jpg',
    highlights: ['Shibuya Crossing', 'Senso-ji Temple', 'Tsukiji Market', 'Shinjuku', 'Akihabara'],
    bestTime: 'Mar–May · Oct–Nov',
    duration: '5–7 nights',
    from: '$1,400',
    description: "Tokyo is a city of 37 million people that somehow works perfectly — ultra-modern neon skyscrapers beside ancient temples, the world's finest restaurants, and a sense of order that feels almost miraculous. Shibuya Crossing is the world's busiest pedestrian crossing, where hundreds of people cross from all directions at once. Senso-ji Temple is Tokyo's oldest temple, with the famous Kaminarimon (Thunder Gate) and a bustling market street leading to the main hall. The Tsukiji Outer Market (the inner market moved to Toyosu) still has incredible street food — fresh sushi, grilled seafood, tamagoyaki (sweet egg omelet), and matcha everything. Shinjuku is Tokyo's entertainment district — the Tokyo Metropolitan Government Building offers free observation decks with city views. Akihabara is the center of otaku culture — anime, manga, video games, maid cafes, and electronics. Tokyo has more Michelin-starred restaurants than any other city in the world (over 200). The city's public transport is immaculate — the JR Yamanote Line loops around the city center, connecting all major districts.",
    experiences: [
      'Shibuya Crossing — the world\'s busiest pedestrian scramble',
      'Senso-ji Temple in Asakusa — Tokyo\'s oldest temple',
      'Tsukiji Outer Market — tuna auction and sushi breakfast',
      'Shinjuku Golden Gai — tiny bars in post-war buildings',
      'Meiji Shrine — forested sanctuary in the city centre',
      'TeamLab Borderless — immersive digital art museum',
    ],
    camps: ['Aman Tokyo', 'Hoshinoya Tokyo', 'Andaz Tokyo', 'Park Hyatt Tokyo', 'The Tokyo Edition'],
    unesco: false,
  },
  {
    slug: 'osaka',
    name: 'Osaka',
    country: 'Japan',
    region: 'Japan',
    tagline: 'Japan\'s Kitchen — Street Food Capital',
    gradient: 'linear-gradient(160deg,#1a0a00,#2c1400,#3e1e00)',
    image: '/images/asia/osaka.jpg',
    highlights: ['Dotonbori', 'Osaka Castle', 'Universal Studios', 'Shinsekai', 'Kushikatsu', 'Okonomiyaki'],
    bestTime: 'Mar–May · Oct–Nov',
    duration: '3–5 nights',
    from: '$980',
    description: "Osaka is Japan's kitchen — the street food capital of the country, where every alley has a takoyaki stall (octopus balls), okonomiyaki (savory pancake) sizzles on hot plates, and kushikatsu (deep-fried skewers) are dipped in sauce. Dotonbori is the heart of Osaka — a neon-lit canal street with the famous Glico Running Man sign, giant mechanical crabs, and the best food in Japan. Osaka Castle (Osakajo) is the city's most important historical landmark — built in 1583 by Toyotomi Hideyoshi, the castle has a museum inside and a panoramic view of the city from the top floor. Universal Studios Japan has the world's only Super Nintendo World — Mario Kart ride, Yoshi's Adventure, and a Power-Up Band that interacts with the park. Shinsekai ('New World') is a retro district built in 1912 — the Tsutenkaku Tower (103 meters) has an outdoor observation deck, and the area is famous for kushikatsu and cheap beer. Osaka is a shopper's paradise — Shinsaibashi (covered shopping arcade), Amerikamura ('Amemura', the Harajuku of Osaka), and the underground shopping malls. Osaka is 30 minutes from Kyoto by express train — you can base yourself in Osaka and day-trip to Kyoto, Nara, and Kobe.",
    experiences: [
      'Dotonbori neon lights and takoyaki',
      'Osaka Castle history museum',
      'Super Nintendo World at USJ',
      'Shinsekai kushikatsu tasting',
      'Kuromon Market seafood walk',
      'Namba Yasaka Shrine lion head',
    ],
    camps: ['St. Regis Osaka', 'Conrad Osaka', 'W Osaka', 'The Ritz-Carlton Osaka', 'Swissotel Nankai Osaka'],
    unesco: false,
  },
]