export const malaysiaDestinations = [
  {
    slug: 'kuala-lumpur',
    name: 'Kuala Lumpur',
    country: 'Malaysia',
    region: 'Malaysia',
    tagline: 'Twin Towers & Street Food Paradise',
    gradient: 'linear-gradient(160deg,#0a0a15,#1a1a2e,#16213e)',
    image: '/images/asia/kuala-lumpur.jpg',
    highlights: ['Petronas Towers', 'Batu Caves', 'KL Tower', 'Bukit Bintang', 'Central Market', 'Jalan Alor'],
    bestTime: 'May–Jul · Dec–Feb',
    duration: '3–5 nights',
    from: '$420',
    description: "Kuala Lumpur is Malaysia's modern capital — a skyline of skyscrapers, Islamic architecture, and the world's best street food (malatang, nasi lemak, satay, and roti canai). The Petronas Towers (452 meters, 88 floors) were the world's tallest buildings from 1998-2004 — the Skybridge on the 41st floor is 170 meters long, and you can walk between the two towers (book tickets online in advance). Batu Caves is a 400-million-year-old limestone hill with 3 Hindu temples — a 272-step rainbow-painted staircase leads to the main cave, where a 43-meter-tall gold statue of Lord Murugan stands at the entrance. KL Tower (421 meters) has an observation deck (276 meters) and a revolving restaurant — the views are better than the Petronas Towers because you can see the towers themselves. Bukit Bintang is the shopping and entertainment district — 5 malls (Pavilion, Berjaya Times Square, Lot 10), a food street (Jalan Alor), and the Pavilion KL fountain show (8 pm, 9 pm, 10 pm). Central Market is a 1936 Art Deco building — 200+ stalls selling batik (traditional Malaysian fabric), pewter crafts, souvenirs, and food. Jalan Alor is KL's famous food street — open until 2 am, with 30+ outdoor restaurants serving satay (chicken or beef skewers with peanut sauce), grilled fish, noodles, and durian (the 'stinky fruit').",
    experiences: [
      'Petronas Towers Skybridge',
      'Batu Caves rainbow stairs',
      'KL Tower revolving restaurant',
      'Bukit Bintang shopping',
      'Jalan Alor night food market',
      'Batik painting workshop',
    ],
    camps: ['Mandarin Oriental KL', 'Four Seasons KL', 'St. Regis KL', 'The Ritz-Carlton KL', 'Grand Hyatt KL'],
    unesco: false,
  },
  {
    slug: 'penang',
    name: 'Penang',
    country: 'Malaysia',
    region: 'Malaysia',
    tagline: 'The Pearl of the Orient',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/asia/penang.jpg',
    highlights: ['George Town', 'Street Art', 'Penang Hill', 'Kek Lok Si Temple', 'Food', 'Chew Jetty'],
    bestTime: 'Nov–Mar',
    duration: '3–4 nights',
    from: '$380',
    description: "Penang is the Pearl of the Orient — a Malaysian island of 1 million people, famous for its UNESCO World Heritage capital George Town, delicious street food, and Chinese colonial architecture. George Town is a UNESCO World Heritage site of 2,000+ pre-war shophouses, Chinese clan jetties, and Indian Muslim mosques — the best way to explore is on foot (the 'Heritage Trail' has 50 marked sites). Street art (Murals) is the main attraction — Lithuanian artist Ernest Zacharevic painted 9 murals in 2012 (Children on a Bicycle, Boy on a Chair, Little Girl in a Window), and other artists have added dozens more. Penang Hill (Bukit Bendera) is a 833-meter hill with a funicular railway (the 1.8-kilometer track takes 10 minutes) — the top has panoramic views of the island and mainland, a small owl museum, and a colonial-era bungalow. Kek Lok Si Temple is the largest Buddhist temple in Malaysia — a 30-meter, 7-tiered 'Pagoda of Rama VI' (Thai, Burmese, and Chinese architecture), and the 'Goddess of Mercy' statue (30 meters). Penang is the food capital of Malaysia — char koay teow (stir-fried flat noodles with prawns, cockles, Chinese sausage), assam laksa (sour fish noodle soup, ranked 7th in CNN's World's 50 Best Foods), nasi lemak (rice cooked in coconut milk with anchovies, peanuts, hard-boiled egg), and cendol (shaved ice dessert with green rice flour jelly and palm sugar).",
    experiences: [
      'George Town heritage walk',
      'Street art photo scavenger hunt',
      'Penang Hill funicular',
      'Kek Lok Si pagoda',
      'Gurney Drive hawker centre',
      'Chew Jetty clan houses',
    ],
    camps: ['Eastern & Oriental Hotel', 'Shangri-La Rasa Sayang', 'The Edison George Town', 'Macalister Mansion', 'Sofitel Penang'],
    unesco: true,
  },
]