export const nepalDestinations = [
  {
    slug: 'kathmandu',
    name: 'Kathmandu Valley',
    country: 'Nepal',
    region: 'Nepal',
    tagline: 'The City of Temples',
    gradient: 'linear-gradient(160deg,#1c1000,#2c1a00,#402600)',
    image: '/images/asia/kathmandu.jpg',
    highlights: ['Swayambhunath', 'Boudhanath Stupa', 'Pashupatinath', 'Durbar Square', 'Thamel', 'Living Goddess'],
    bestTime: 'Sep–Nov · Mar–May',
    duration: '3–5 nights',
    from: '$320',
    description: "Kathmandu is the City of Temples — a UNESCO World Heritage site of 7 monuments, centuries-old pagodas, and the gateway to Mount Everest. Swayambhunath (Monkey Temple) is a 2,500-year-old Buddhist stupa on a hilltop — the 'Buddha eyes' painted on 4 sides watch over the valley, and hundreds of monkeys (rhesus macaques) live in the temple (hold onto your glasses, they steal them). Boudhanath Stupa is the largest stupa in Nepal (36 meters tall, 100 meters diameter) — a Tibetan Buddhist pilgrimage site with 50+ monasteries, the 'Buddha eyes' painted on all 4 sides, and a spinning of prayer wheels at the base. Pashupatinath is the most important Hindu temple in Nepal (dedicated to Lord Shiva) — on the banks of the Bagmati River, you can watch open-air cremations (the bodies are wrapped in white cloth and placed on wood pyres). The main temple is open to Hindus only, but you can see everything from the other side of the river. Kathmandu Durbar Square is the old royal palace — the Hanuman Dhoka (Stone Monkey Gate) is the entrance, the Kumari Ghar is the home of the Living Goddess (a young girl worshipped as the incarnation of the goddess Taleju). Patan Durbar Square (Lalitpur) has the 17th-century Krishna Temple (stone, 21 spires) and the Patan Museum (the best museum in Nepal). Thamel is the tourist district — 10 blocks of trekking shops, restaurants, bars, and hotels (budget, mid-range, luxury). Thamel is loud, crowded, and chaotic — the center of all pre-Everest and post-Everest activity.",
    experiences: [
      'Swayambhunath monkey temple',
      'Boudhanath stupa prayer wheel',
      'Pashupatinath cremation ghats',
      'Kumari Living Goddess sighting',
      'Patan Krishna Temple',
      'Thamel trekking shopping',
    ],
    camps: ['Dwarika\'s Hotel', 'Hotel Yak & Yeti', 'Kathmandu Guest House', 'Himalayan Hotel', 'Aloft Kathmandu'],
    unesco: true,
  },
  {
    slug: 'pokhara',
    name: 'Pokhara',
    country: 'Nepal',
    region: 'Nepal',
    tagline: 'Gateway to the Annapurnas',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/asia/pokhara.jpg',
    highlights: ['Phewa Lake', 'Annapurna Range', 'World Peace Stupa', 'Sarangkot', 'Devi\'s Falls', 'Paragliding'],
    bestTime: 'Sep–Nov · Mar–May',
    duration: '3–5 nights',
    from: '$280',
    description: "Pokhara is the gateway to the Annapurna mountain range — a lakeside city of 250,000 people, with a view of 3 of the world's 10 highest mountains (Annapurna I, 8,091 meters; Annapurna II, 7,937 meters; Annapurna III, 7,555 meters). Phewa Lake is the second-largest lake in Nepal (4.43 square kilometers) — the reflection of the Annapurna mountains in the calm water is the classic Pokhara postcard. You can rent a rowboat ($10-15 per hour) to visit the Tal Barahi Temple (2-story pagoda on an island in the lake). The World Peace Stupa is a 115-meter-high white Buddhist stupa on a hill overlooking Phewa Lake — built by Japanese Buddhists in 2000, the views of the Annapurna mountains are spectacular. Sarangkot is a hilltop village (1,600 meters) above Pokhara — the 4:30 am sunrise view is the best photo of the Annapurna mountains (the sun turns the mountains gold for 10 minutes). Paragliding is the #1 activity in Pokhara — 1-hour tandem flights from Sarangkot (1,600 meters) land at the shores of Phewa Lake (the views of the mountains, lake, and forests are unforgettable). The Annapurna Base Camp trek (7-10 days) starts from Pokhara — the 'ABC' trek is easier than Everest Base Camp (4,130 meters elevation, no technical climbing). Devi's Falls (Patale Chango) is a 500-foot waterfall that disappears into a tunnel in the rock — the water emerges 500 meters later, forming a 'subterranean river'.",
    experiences: [
      'Phewa Lake sunrise rowboat',
      'World Peace Stupa hike',
      'Sarangkot sunrise paraglide',
      'Annapurna Base Camp trek',
      'Devi\'s Falls underground tunnel',
      'Gupteshwor Cave Shiva lingam',
    ],
    camps: ['Tiger Mountain Pokhara Lodge', 'Fish Tail Lodge', 'Shangri-La Village Resort', 'Atithi Resort', 'Hotel Barahi'],
    unesco: false,
  },
]