export const philippinesDestinations = [
  {
    slug: 'palawan',
    name: 'Palawan',
    country: 'Philippines',
    region: 'Philippines',
    tagline: 'The Last Frontier of the Philippines',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/asia/palawan.jpg',
    highlights: ['Underground River', 'El Nido', 'Big Lagoon', 'Small Lagoon', 'Coron', 'Kayangan Lake'],
    bestTime: 'Nov–May',
    duration: '5–7 nights',
    from: '$520',
    description: "Palawan is the 'Last Frontier' of the Philippines — a 420-kilometer-long island of limestone karsts, turquoise lagoons, and the world's most beautiful island (Conde Nast Traveler 2020). The Puerto Princesa Underground River is a UNESCO World Heritage site — an 8.2-kilometer navigable river inside a limestone cave, with 1.5 kilometers open to the public (45-minute boat tour). The cave has stalactites, stalagmites, and a 'cathedral' chamber (60 meters high). El Nido is the most famous destination in Palawan — a Bacuit Bay of 45 limestone islands with hidden lagoons. The Tour A boat tour is the most popular — the Big Lagoon (you kayak through a narrow entrance into a lagoon surrounded by 100-meter cliffs), the Small Lagoon (you swim or kayak through a hole in the rock), Secret Lagoon (a small pool inside a cave), and Shimizu Island (snorkeling with clownfish, parrotfish, and sea turtles). Coron is the other famous destination in Palawan — Kayangan Lake is the cleanest lake in the Philippines (a 10-minute hike from the jetty, then 150 steps down to the emerald-green lake). Twin Lagoon is two lagoons connected by a 10-meter underwater tunnel (you can swim through at low tide). The Skeleton Wreck is a Japanese supply ship sunk by US air attack in 1944 — you can snorkel (the wreck is 5-10 meters deep) or dive (25 meters to the engine room).",
    experiences: [
      'Underground river paddle',
      'El Nido Big Lagoon kayak',
      'Coron Kayangan Lake swim',
      'Twin Lagoon underwater tunnel',
      'Skeleton wreck snorkel',
      'Nacpan Beach sunset',
    ],
    camps: ['El Nido Resorts Lagen', 'Apulit Island Resort', 'Club Paradise Coron', 'Huma Island Resort', 'Two Seasons Coron'],
    unesco: true,
  },
  {
    slug: 'boracay',
    name: 'Boracay',
    country: 'Philippines',
    region: 'Philippines',
    tagline: 'The White Beach Paradise',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/asia/boracay.jpg',
    highlights: ['White Beach', 'Puka Shell Beach', 'Bulabog Beach', 'Willy\'s Rock', 'Ariel\'s Point', 'D\'Mall'],
    bestTime: 'Nov–May',
    duration: '4–6 nights',
    from: '$480',
    description: "Boracay is the most famous beach in the Philippines — a 7-kilometer teardrop-shaped island with White Beach (4 kilometers of powder-fine white sand, rated one of the best beaches in the world). White Beach is divided into 3 stations — Station 1 (luxury resorts, Willy's Rock), Station 2 (the main strip with restaurants, bars, and D'Mall), Station 3 (budget accommodations). Willy's Rock is a volcanic rock formation at the northern end of White Beach — at low tide, you can walk to the rock and climb the stairs to a small statue of the Virgin Mary. Puka Shell Beach is on the northern tip of the island — the sand is made of crushed puka shells (white with shell fragments), much quieter than White Beach. Bulabog Beach is on the eastern side — the windsurfing and kiteboarding capital of the Philippines (best wind from November-March). Ariel's Point is a cliff-jumping spot on the mainland — a 45-minute boat ride from Boracay, with 3, 5, 8, and 15-meter jump platforms, plus kayaking and snorkeling (day trip with unlimited drinks and lunch). Boracay was closed for 6 months in 2018 for rehabilitation (the government enforced environmental laws) — it's now cleaner with limited visitor numbers (19,000 per day). The best time to visit is November-March (dry season with less rain and lower humidity).",
    experiences: [
      'White Beach sunset sail',
      'Willy\'s Rock photo',
      'Puka Shell Beach walk',
      'Bulabog kitesurfing',
      'Ariel\'s Point cliff jump',
      'D\'Mall souvenir hunting',
    ],
    camps: ['Shangri-La Boracay', 'Crimson Resort', 'The Lind Boracay', 'Henann Regency', 'Discovery Shores'],
    unesco: false,
  },
]