export const southKoreaDestinations = [
  {
    slug: 'seoul',
    name: 'Seoul',
    country: 'South Korea',
    region: 'South Korea',
    tagline: 'K-Pop, Kimchi & Palaces',
    gradient: 'linear-gradient(160deg,#0a0a15,#1a1a2e,#16213e)',
    image: '/images/asia/seoul.jpg',
    highlights: ['Gyeongbokgung Palace', 'Myeongdong', 'N Seoul Tower', 'Bukchon Hanok', 'Hongdae', 'DMZ'],
    bestTime: 'Apr–Jun · Sep–Nov',
    duration: '4–6 nights',
    from: '$580',
    description: "Seoul is a city of neon lights and ancient palaces, K-pop beats and Buddhist temples, world-class skincare and kimchi fried rice. The capital of South Korea is one of Asia's most dynamic and technologically advanced cities. Gyeongbokgung Palace is the largest of the Five Grand Palaces built during the Joseon Dynasty — watch the changing of the royal guard ceremony and rent a hanbok (traditional Korean dress) for free entry. Myeongdong is Seoul's shopping mecca — 10 blocks of skincare shops (Innisfree, Etude House, Laneige), street food (tteokbokki, hotteok, egg bread), and the Myeongdong Cathedral. N Seoul Tower sits on Namsan Mountain in the center of Seoul — the 'Locks of Love' fence has thousands of padlocks left by couples, and the observation deck has 360-degree views of the city. Bukchon Hanok Village has 900 traditional Korean houses (hanok) between Gyeongbokgung and Changdeokgung palaces — the best photos are from the uphill alleys. Hongdae is the university district — indie bands play in the streets, clubs stay open until dawn, and the 'Hongdae Free Market' sells handmade crafts on weekends. The DMZ (Demilitarized Zone) is a half-day tour from Seoul — see the Third Infiltration Tunnel (discovered 1978), the Dora Observatory (view into North Korea), and Dorasan Station (the last station before the North Korean border).",
    experiences: [
      'Gyeongbokgung Palace guard ceremony',
      'Myeongdong skincare shopping',
      'N Seoul Tower sunset padlock',
      'Bukchon Hanok photo walk',
      'Hongdae street music',
      'DMZ Third Tunnel tour',
    ],
    camps: ['Four Seasons Seoul', 'The Shilla Seoul', 'Grand Hyatt Seoul', 'Signiel Seoul', 'Lotte Hotel Seoul'],
    unesco: true,
  },
  {
    slug: 'busan',
    name: 'Busan',
    country: 'South Korea',
    region: 'South Korea',
    tagline: 'Korea\'s Second City by the Sea',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/asia/busan.jpg',
    highlights: ['Haeundae Beach', 'Gamcheon Culture Village', 'Jagalchi Market', 'Haedong Yonggungsa', 'Songdo Cable Car'],
    bestTime: 'May–Oct',
    duration: '3–4 nights',
    from: '$420',
    description: "Busan is South Korea's second-largest city and largest port — a coastal metropolis of beaches, mountains, seafood markets, and a more relaxed vibe than Seoul. Haeundae Beach is the most famous beach in Korea — 1.5 kilometers of white sand, umbrellas in summer, and the Busan International Film Festival (BIFF) in October. Gamcheon Culture Village is the 'Machu Picchu of Busan' — a hillside village of pastel-colored houses stacked on top of each other, with murals, sculptures, and a labyrinth of staircases. The Little Prince statue is the most photographed spot. Jagalchi Fish Market is the largest seafood market in Korea — 300+ vendors sell everything from live octopus (sannakji, still moving) to eel, abalone, and sea squirt. You can eat at the market — choose your fish, they kill it at a stall, and the restaurant upstairs cooks it. Haedong Yonggungsa Temple is a Buddhist temple on the rocks by the sea — the most scenic temple in Korea (the 108 steps lead to a statue of the Buddha). Songdo Marine Cable Car is a 1.5-kilometer cable car over the ocean — the 'Crystal Cruise' car has a glass floor, and the Songdo Skywalk is a glass bridge 20 meters above the waves.",
    experiences: [
      'Haeundae Beach sunrise',
      'Gamcheon Culture Village photo',
      'Jagalchi live octopus',
      'Haedong Yonggungsa sea temple',
      'Songdo glass floor cable car',
      'BIFF Square street food',
    ],
    camps: ['Park Hyatt Busan', 'Signiel Busan', 'Grand Josun Busan', 'Ananti Cove', 'Haeundae Paradise Hotel'],
    unesco: false,
  },
  {
    slug: 'jeju',
    name: 'Jeju Island',
    country: 'South Korea',
    region: 'South Korea',
    tagline: 'Korea\'s Hawaii',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/asia/jeju.jpg',
    highlights: ['Hallasan Mountain', 'Manjanggul Cave', 'Seongsan Ilchulbong', 'Olle Trail', 'Jeju Stone Grandfathers'],
    bestTime: 'Apr–Jun · Sep–Oct',
    duration: '3–4 nights',
    from: '$480',
    description: "Jeju Island is South Korea's honeymoon island — a volcanic island of 360 parasitic cones, 7,000 steps to the summit of Hallasan Mountain, 1.7-kilometer lava tube caves, and the 'Jeju Olle' coastal walking trail. Hallasan Mountain is a 1,947-meter shield volcano in the center of the island — the 9.6-kilometer Baengnokdam Trail is a 5-hour climb (round trip) to the crater lake (white deer lake). Manjanggul Cave is one of the longest lava tubes in the world (13.4 kilometers, 1 kilometer open to the public) — you'll see lava stalactites, lava columns, and a 7.6-meter lava pillar (the tallest in the world). Seongsan Ilchulbong ('Sunrise Peak') is a 182-meter volcanic tuff cone at the eastern tip of Jeju — a 30-minute climb to the crater for sunrise views over the ocean. The Jeju Olle Trail is a 437-kilometer coastal walking path divided into 27 courses — each course takes 4-8 hours, and you can walk sections with stamps in your Olle Passport. Jeju Stone Grandfathers (Dol Hareubang) are volcanic rock statues found only on Jeju — the 'grandfathers' have long noses and hands on their stomachs, symbolizing protection and fertility.",
    experiences: [
      'Hallasan summit hike',
      'Manjanggul lava tube',
      'Seongsan Ilchulbong sunrise',
      'Olle Trail coastal walk',
      'Jeju Stone Grandfathers',
      'Osulloc Tea Museum',
    ],
    camps: ['Jeju Shinhwa World', 'Lotte Hotel Jeju', 'Maison Glad Jeju', 'Grand Hyatt Jeju', 'Parnas Hotel Jeju'],
    unesco: true,
  },
]