export const thailandDestinations = [
  {
    slug: 'bangkok',
    name: 'Bangkok',
    country: 'Thailand',
    region: 'Thailand',
    tagline: 'The Most Exhilarating Chaos in Asia',
    gradient: 'linear-gradient(160deg,#1a0a00,#2c1400,#3e1e00)',
    image: '/images/asia/bangkok.jpg',
    highlights: ['Grand Palace', 'Floating Markets', 'Tuk Tuks', 'Street Food', 'Night Markets'],
    bestTime: 'Nov–Feb',
    duration: '4–6 nights',
    from: '$520',
    description: "Bangkok assaults every sense in the best possible way — the heat, the smells, the traffic, the temples, the street food, the shopping, and a nightlife that never stops. It is gloriously, chaotically alive. The Grand Palace is the city's most important landmark — the Temple of the Emerald Buddha (Wat Phra Kaew) houses the most revered Buddha image in Thailand, carved from a single block of jade. Wat Arun (Temple of Dawn) is best visited at sunset — climb the steep porcelain-tiled prang (Khmer-style tower) for views over the Chao Phraya River. The floating markets (Damnoen Saduak is the most famous) are touristy but fun — buy coconut ice cream, fresh fruit, and noodle soup from boats. Street food is Thailand's national cuisine — pad thai (stir-fried noodles), tom yum goong (spicy shrimp soup), som tam (green papaya salad), mango sticky rice, and fresh spring rolls. Tuk tuks are the iconic three-wheeled taxis — negotiate the price before getting in (should be 50-100 baht for short trips). Bangkok's night markets (Chatuchak Weekend Market, the world's largest weekend market) have thousands of stalls selling everything from designer knockoffs to vintage furniture. The city has a sophisticated sky bar scene — Lebua's Sky Bar (from 'The Hangover 2') is the most famous, with 360-degree city views.",
    experiences: [
      'Grand Palace and Wat Phra Kaew (Emerald Buddha)',
      'Wat Arun at sunset — climb the porcelain tower',
      'Chinatown street food walk (Yaowarat)',
      'Floating market day trip (Damnoen Saduak)',
      'Lumphini Park monitor lizards at dusk',
      'Sky bar at Lebua (Hangover movie)',
    ],
    camps: ['Mandarin Oriental Bangkok', 'The Siam', 'Capella Bangkok', 'Four Seasons Bangkok', 'Rosewood Bangkok'],
    unesco: false,
  },
  {
    slug: 'chiang-mai',
    name: 'Chiang Mai',
    country: 'Thailand',
    region: 'Thailand',
    tagline: 'The Rose of the North',
    gradient: 'linear-gradient(160deg,#1a1000,#2c2000,#3e3000)',
    image: '/images/asia/chiang-mai.jpg',
    highlights: ['Doi Suthep', 'Night Bazaar', 'Elephant Sanctuary', 'Temples', 'Cooking Classes'],
    bestTime: 'Nov–Feb',
    duration: '4–6 nights',
    from: '$420',
    description: "Chiang Mai is Thailand's cultural capital — 300+ Buddhist temples, a weekly Sunday night market that transforms the old city, jungles outside the city limits, and the friendliest people in Thailand. Doi Suthep is the most important temple in northern Thailand — the golden chedi (stupa) is visible from the city below, and the 309-step naga (serpent) staircase is the classic approach (there's also a tram). The temple has a panoramic view over Chiang Mai and the surrounding mountains. The Sunday Night Market is the biggest in Thailand — Ratchadamnoen Road closes to traffic, and hundreds of vendors sell handicrafts, clothing, street food, and live music. Elephant Nature Park is the most ethical elephant sanctuary in Thailand — no riding, no hooks, no chains. You can feed, walk with, and bathe rescued elephants in the river. Chiang Mai is famous for its cooking schools — a half-day class includes a market tour, instruction on 4-5 Thai dishes (pad thai, green curry, tom yum soup, mango sticky rice), and eating your creations. Chiang Mai has a laid-back cafe culture — Nimmanhaemin Road is the hipster district, with art galleries, coffee shops, and boutique hotels. The Yi Peng Lantern Festival (November, date varies by lunar calendar) releases 10,000 lanterns into the sky — one of Asia's most magical experiences.",
    experiences: [
      'Doi Suthep — golden chedi overlooking the city',
      'Elephant Nature Park — ethical sanctuary',
      'Sunday Night Market — the biggest in Thailand',
      'Thai cooking class with market tour',
      'Monk chat at Wat Phra Singh',
      'Zip-lining through the jungle canopy',
    ],
    camps: ['Four Seasons Chiang Mai', 'Anantara Chiang Mai', '137 Pillars House', 'Rachamankha', 'Villa Mahabhirom'],
    unesco: false,
  },
  {
    slug: 'phuket',
    name: 'Phuket',
    country: 'Thailand',
    region: 'Thailand',
    tagline: 'The Pearl of the Andaman',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/asia/phuket.jpg',
    highlights: ['Phi Phi Islands', 'James Bond Island', 'Big Buddha', 'Patong Beach', 'Phi Phi Leh', 'Snorkeling'],
    bestTime: 'Nov–Apr',
    duration: '5–7 nights',
    from: '$650',
    description: "Phuket is Thailand's largest island — a tropical paradise of white sand beaches, limestone karsts rising from emerald water, and world-class diving in the Andaman Sea. The Phi Phi Islands (Phi Phi Don and Phi Phi Leh) are the most beautiful islands in Thailand — Maya Bay (made famous by 'The Beach' movie with Leonardo DiCaprio) is closed for rehabilitation (reopening 2025), but you can still see it from a boat, and the surrounding snorkeling sites are spectacular. James Bond Island (Khao Phing Kan) was featured in 'The Man with the Golden Gun' — the limestone stack rising from the water is the most photographed spot in Phang Nga Bay. The Big Buddha is a 45-meter white marble statue at the top of Nakkerd Hill — the views over Phuket and the Andaman Sea are spectacular, and you can see Phuket Town, the west coast beaches, and the airport. Patong Beach is the most famous beach on Phuket — it's crowded, noisy, and the center of nightlife (Bangla Road has gogo bars, clubs, and street performers). Diving in the Similan Islands (a 2-hour boat ride) is world-class — whale sharks (seasonal), manta rays, sea turtles, and pristine coral reefs. Phi Phi Leh has the Viking Cave (with ancient ship paintings) and Pileh Lagoon (a saltwater lake surrounded by 100-meter cliffs).",
    experiences: [
      'Phi Phi Islands speedboat tour',
      'James Bond Island canoe',
      'Big Buddha sunset views',
      'Patong Beach nightlife',
      'Similan Islands diving',
      'Phi Leh Lagoon swimming',
    ],
    camps: ['Rosewood Phuket', 'InterContinental Phuket', 'Keemala', 'Sri Panwa', 'The Surin Phuket'],
    unesco: false,
  },
]