export const vietnamDestinations = [
  {
    slug: 'hanoi',
    name: 'Hanoi',
    country: 'Vietnam',
    region: 'Vietnam',
    tagline: 'The Soul of Old Vietnam',
    gradient: 'linear-gradient(160deg,#1a0a00,#2c1400,#3e1e00)',
    image: '/images/asia/hanoi.jpg',
    highlights: ['Old Quarter', 'Ha Long Bay', 'Egg Coffee', 'Hoan Kiem Lake', 'Street Food'],
    bestTime: 'Oct–Dec · Mar–Apr',
    duration: '4–6 nights',
    from: '$380',
    description: "Hanoi is Vietnam's elegant, chaotic capital — a thousand-year-old city of lakes, shaded boulevards, centuries-old temples, French colonial architecture, and the best street food on earth. The Old Quarter (36 ancient streets) is a maze of narrow alleyways, each street historically selling one product (silver street, silk street, paper street). The Hoan Kiem Lake (Lake of the Restored Sword) is the heart of Hanoi — the red Huc Bridge leads to Ngoc Son Temple, and locals do tai chi at sunrise and dance in the evenings. Egg coffee (ca phe trung) was invented at Cafe Giang in 1946 — a sweet, frothy egg yolk and condensed milk mixture on top of strong Vietnamese coffee. Ha Long Bay is a 2.5-hour bus ride from Hanoi — 1,600 limestone karsts (islands) rise from emerald water, a UNESCO World Heritage site. An overnight cruise is the best way to see the bay — kayak through lagoons, visit Sung Sot Cave (Surprise Cave), and watch sunset from the top deck. Street food is Vietnam's best — pho (noodle soup with beef or chicken), bun cha (grilled pork with noodles, Obama ate this with Anthony Bourdain), banh mi (baguette sandwich), and cha ca (turmeric fish with dill). The Water Puppet Theatre is a traditional Vietnamese art form — puppets act out legends on water, with live traditional music and singing.",
    experiences: [
      'Hoan Kiem Lake and Ngoc Son Temple at dawn',
      'Old Quarter walking tour — 36 ancient streets',
      'Egg coffee at Cafe Giang (original since 1946)',
      'Ha Long Bay overnight cruise — limestone karsts',
      'Train Street — houses inches from passing trains',
      'Water puppet theatre — traditional Vietnamese art',
    ],
    camps: ['Sofitel Legend Metropole', 'Capella Hanoi', 'Hotel de l\'Opera', 'Peridot Grand', 'Apricot Hotel'],
    unesco: true,
  },
  {
    slug: 'hoi-an',
    name: 'Hoi An',
    country: 'Vietnam',
    region: 'Vietnam',
    tagline: 'The Lantern City',
    gradient: 'linear-gradient(160deg,#1c1000,#2c1a00,#402600)',
    image: '/images/asia/hoi-an.jpg',
    highlights: ['Ancient Town', 'Lantern Festival', 'Tailors', 'Japanese Bridge', 'Banh Mi', 'Thu Bon River'],
    bestTime: 'Feb–Apr · Aug–Oct',
    duration: '3–4 nights',
    from: '$280',
    description: "Hoi An is Vietnam's most beautiful town — a UNESCO World Heritage site of yellow-painted Chinese shophouses, Japanese covered bridges, and French colonial buildings, all lit by 10,000 silk lanterns at night. The Ancient Town is the heart of Hoi An — the Japanese Covered Bridge (Chua Cau) was built in 1595 by the Japanese community, connecting the Japanese and Chinese quarters. Hoi An is famous for custom tailoring — you can have a suit, dress, or shirt made in 24 hours for $50-150 (choose your fabric, get measured, return for a fitting). The Full Moon Lantern Festival is held on the 14th day of each lunar month — the Ancient Town turns off its electric lights, and the only light comes from silk lanterns floating on the Thu Bon River. Hoi An is a street food paradise — banh mi (the best in Vietnam is at Banh Mi Phuong, made famous by Anthony Bourdain), cao lau (noodles with pork and crispy croutons, only made with water from the Ba Le Well), and white rose dumplings (bahn bao banh vac). The Hoi An Night Market is on the riverfront — hundreds of stalls sell lanterns, souvenirs, food, and clothing. My Son Sanctuary is a 1-hour drive from Hoi An — a UNESCO World Heritage site of Hindu temples built by the Champa Kingdom between the 4th and 14th centuries (the 'Angkor Wat of Vietnam'). An Bang Beach is a 10-minute bike ride from Hoi An — a quieter alternative to Cua Dai Beach, with beachfront restaurants, lounge chairs, and calm water.",
    experiences: [
      'Ancient Town sunset walk — yellow buildings and lanterns',
      'Tailor-made clothing — suit or dress in 24 hours',
      'Full Moon Lantern Festival (monthly)',
      'Banh Mi Phuong — Anthony Bourdain\'s favourite',
      'My Son Sanctuary sunrise tour',
      'An Bang Beach sunset swim',
    ],
    camps: ['Four Seasons Hoi An', 'Anantara Hoi An', 'Hotel de la Coupole', 'La Siesta Hoi An', 'Boutique Hoi An Resort'],
    unesco: true,
  },
]