export const australiaDestinations = [
  {
    slug: 'sydney',
    name: 'Sydney',
    country: 'Australia',
    region: 'Australia',
    tagline: 'The Harbour City — Where the World Wants to Live',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/pacific/sydney.jpg',
    highlights: ['Opera House', 'Harbour Bridge', 'Bondi Beach', 'The Rocks', 'Manly Ferry', 'Blue Mountains'],
    bestTime: 'Sep–Nov · Mar–May',
    duration: '5–8 nights',
    from: '$740',
    description: "Sydney is the city that makes people question every life decision that brought them somewhere else — a spectacular harbour, world-class beaches within the city limits, extraordinary food, and a quality of life that consistently ranks among the world's highest. The Sydney Opera House is a UNESCO World Heritage site and a masterpiece of modern architecture — Jørn Utzon's shell design is one of the most recognizable buildings on earth. The Sydney Harbour Bridge ('The Coathanger') can be climbed to the top (1,332 steps, 134 meters high) for panoramic views of the harbour, Opera House, and Blue Mountains on clear days. Bondi Beach is Australia's most famous beach — the 1-kilometer crescent of golden sand is perfect for surfing, swimming, and people-watching from the Bondi Icebergs pool (saltwater ocean pool). The Rocks is Sydney's oldest neighborhood — cobblestone streets, sandstone buildings, markets on weekends, and the oldest pub in Australia (Lord Nelson Brewery Hotel). The Manly Ferry is a 30-minute ride from Circular Quay — the best harbor tour for $10, with views of the Opera House, Harbour Bridge, and million-dollar waterfront homes. The Blue Mountains are a 2-hour train ride from Sydney — the Three Sisters rock formation, Katoomba Scenic Railway (steepest passenger railway in the world, 52-degree incline), and hiking trails through eucalyptus forest (the blue haze is from eucalyptus oil evaporating in the sun).",
    experiences: [
      'Sydney Opera House tour or performance',
      'Harbour Bridge climb at sunset',
      'Bondi to Coogee coastal walk',
      'The Rocks pub crawl',
      'Manly Ferry to Shelly Beach',
      'Blue Mountains Katoomba railway',
    ],
    camps: ['Park Hyatt Sydney', 'Four Seasons Sydney', 'Shangri-La Sydney', 'QT Sydney', 'The Langham Sydney'],
    unesco: true,
  },
  {
    slug: 'great-barrier-reef',
    name: 'Great Barrier Reef',
    country: 'Australia',
    region: 'Australia',
    tagline: 'The Living Wonder Visible From Space',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/pacific/great-barrier-reef.jpg',
    highlights: ['Diving & Snorkelling', 'Whitsunday Islands', 'Whitehaven Beach', 'Liveaboard Diving', 'Sea Turtles', 'Cairns'],
    bestTime: 'Jun–Oct',
    duration: '5–8 nights',
    from: '$680',
    description: "The Great Barrier Reef is the world's largest coral ecosystem — 2,300 kilometers of living reef containing more species of fish, coral, and marine life than almost anywhere on earth, visible from space. Snorkelling or diving here for the first time is a life-changing experience. The reef has 2,900 individual reefs and 900 islands, with over 1,500 species of fish (clownfish, parrotfish, angelfish, Maori wrasse), 400 species of coral (brain coral, staghorn coral, table coral), and 30 species of marine mammals (dolphins, dugongs, migrating humpback whales). The Whitsunday Islands are 74 islands in the heart of the reef — the most beautiful is Whitsunday Island with Whitehaven Beach (7 kilometers of pure silica sand so white it doesn't retain heat, you can walk barefoot in the sun). Hill Inlet is the viewpoint for the swirling sand patterns at the north end of the beach — the most photographed spot in the Whitsundays. Liveaboard diving is the best way to experience the outer reef — overnight boats (3-5 days) reach sites unreachable on day trips (Cod Hole, SS Yongala wreck). Daintree Rainforest (the oldest rainforest on earth, 180 million years old) meets the reef at Cape Tribulation — the only place in the world where two UNESCO World Heritage sites touch.",
    experiences: [
      'Outer reef snorkel tour from Cairns',
      'Whitehaven Beach and Hill Inlet',
      'Liveaboard diving (3-5 days)',
      'Whitsunday Islands sailing',
      'Daintree Rainforest walk',
      'Scenic flight over Heart Reef',
    ],
    camps: ['Qualia Resort', 'Lizard Island Resort', 'Hamilton Island Reef View', 'Silky Oaks Lodge', 'Thala Beach Nature Reserve'],
    unesco: true,
  },
  {
    slug: 'uluru',
    name: 'Uluru & Red Centre',
    country: 'Australia',
    region: 'Australia',
    tagline: 'The Sacred Heart of the Continent',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/pacific/uluru.jpg',
    highlights: ['Uluru Sunrise', 'Kata Tjuta Domes', 'Aboriginal Culture', 'Milky Way Stargazing', 'Desert Walk', 'Field of Light'],
    bestTime: 'May–Sep',
    duration: '3–4 nights',
    from: '$580',
    description: "Uluru (Ayers Rock) is one of the world's most sacred and spiritually powerful places — a 348-meter sandstone monolith rising from the Australian desert, changing colour from ochre to blood red to violet as the sun moves across the sky. Nothing prepares you for the scale or the silence. Uluru is 3.6 kilometers long, 2.4 kilometers wide, and 862 meters above sea level — it extends at least 2.5 kilometers underground. The rock is sacred to the Anangu people, who have lived in the area for at least 30,000 years — climbing Uluru has been prohibited since 2019 (respect the wishes of traditional owners). The Base Walk is 10.6 kilometers around the entire rock — takes 3-4 hours, the best way to see the caves, waterfalls (after rain), and ancient rock art (some paintings are 5,000 years old). Kata Tjuta (The Olgas) is a group of 36 domed rock formations 25 kilometers west of Uluru — the Valley of the Winds walk is 7.4 kilometers with views of the domes and the desert. Field of Light is an art installation of 50,000 solar-powered lights on the desert floor — the lights change colour in the darkness, looking like a field of desert flowers. Stargazing in the Red Centre is some of the best in the world — no light pollution for 500 kilometers, the Milky Way is visible in stunning detail.",
    experiences: [
      'Uluru sunrise from Talinguru Nyakunytjaku',
      'Base Walk (10.6km)',
      'Kata Tjuta Valley of Winds',
      'Field of Light at sunset',
      'Desert stargazing tour',
      'Anangu cultural centre',
    ],
    camps: ['Longitude 131°', 'Sails in the Desert', 'Desert Gardens Hotel', 'Uluru Camel Camp', 'Outback Hotel'],
    unesco: true,
  },
  {
    slug: 'melbourne',
    name: 'Melbourne',
    country: 'Australia',
    region: 'Australia',
    tagline: 'The World\'s Most Liveable City',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/pacific/melbourne.jpg',
    highlights: ['Laneways', 'Great Ocean Road', 'Federation Square', 'Queen Vic Market', 'Sporting Events', 'Coffee Culture'],
    bestTime: 'Mar–May · Sep–Nov',
    duration: '4–6 nights',
    from: '$620',
    description: "Melbourne is consistently ranked the world's most liveable city — a cosmopolitan capital of laneways, coffee, sport, and the best food scene in Australia. The Laneways are Melbourne's soul — Hosier Lane (graffiti-covered, changing weekly), Degraves Street (European-style cafes), Hardware Lane (Italian restaurants), and Centre Place (vintage shops and street art). Great Ocean Road is a 243-kilometer coastal drive — the Twelve Apostles (limestone stacks rising from the ocean), Loch Ard Gorge (shipwreck site), and the Gibson Steps (beach access). Federation Square is Melbourne's cultural heart — the Ian Potter Centre (Australian art, free entry), ACMI (screen culture museum), and the square's unique architecture (ziggurat design with 1,600 bins of angles). Queen Victoria Market is the largest open-air market in the southern hemisphere — 600+ vendors selling meat, cheese, bread, seafood, and souvenirs (the donuts at the American Doughnut Kitchen are legendary). Melbourne is Australia's sporting capital — the Australian Open (tennis, January), the Melbourne Cup (horse racing, November), the Boxing Day Test (cricket, December), and the Formula 1 Grand Prix (March). Coffee culture is religion in Melbourne — the city is home to some of the world's best coffee roasters (Market Lane, Proud Mary, Padre), and you'll find espresso bars in every laneway.",
    experiences: [
      'Hosier Lane street art',
      'Great Ocean Road road trip',
      'Queen Vic Market donuts',
      'MCG sports tour',
      'Federation Square galleries',
      'Laneway coffee crawl',
    ],
    camps: ['Crown Towers Melbourne', 'The Langham Melbourne', 'W Melbourne', 'QT Melbourne', 'Park Hyatt Melbourne'],
    unesco: false,
  },
  {
    slug: 'perth',
    name: 'Perth & Rottnest Island',
    country: 'Australia',
    region: 'Australia',
    tagline: 'The World\'s Most Isolated City',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/pacific/perth.jpg',
    highlights: ['Rottnest Island', 'Quokkas', 'Swan Valley', 'Fremantle', 'Kings Park', 'Sunset Coast'],
    bestTime: 'Sep–Nov · Mar–May',
    duration: '4–6 nights',
    from: '$580',
    description: "Perth is the world's most isolated capital city (2,100 kilometers from the next city of Adelaide) — a Mediterranean climate, white sand beaches, a sparkling Swan River, and a laid-back lifestyle that makes it one of Australia's most desirable places to live. Rottnest Island ('Rotto') is a 25-minute ferry from Perth — the island is car-free, with 63 beaches, 20 bays, and the world's largest population of quokkas (the 'world's happiest animal', they smile for photos). Rottnest is perfect for biking (the 10-kilometer loop takes 3 hours). Swan Valley is Australia's second-oldest wine region (1830) — 40 wineries, with chocolate, cheese, and beer tasting (Sandalford Wines is the largest, with free tastings). Fremantle ('Freo') is a port city with a maritime museum (home of the America's Cup-winning boat), the Fremantle Prison (a UNESCO World Heritage site, built by convicts in 1850, closed 1991), and the Fremantle Markets (built 1897). Kings Park is one of the world's largest inner-city parks (400 hectares) — the Lotterywest Federation Walkway is a 620-meter treetop bridge with views of the city and Swan River. Sunset Coast is 19 kilometers of beaches — Cottesloe Beach is the most famous (white sand, clear water, iconic 1930s rotunda), with sunset sessions at the Indiana Tea House.",
    experiences: [
      'Rottnest quokka selfie',
      'Swan Valley wine tasting',
      'Fremantle Prison tour',
      'Kings Park treetop walk',
      'Cottesloe sunset swim',
      'Perth Mint gold tour',
    ],
    camps: ['COMO The Treasury', 'QT Perth', 'The Ritz-Carlton Perth', 'Fremantle Hotel', 'Rottnest Lodge'],
    unesco: true,
  },
  {
    slug: 'kakadu',
    name: 'Kakadu National Park',
    country: 'Australia',
    region: 'Australia',
    tagline: 'Ancient Rock Art & Crocodile Rivers',
    gradient: 'linear-gradient(160deg,#001c10,#002c1a,#003c22)',
    image: '/images/pacific/kakadu.jpg',
    highlights: ['Ubirr Rock Art', 'Yellow Water Billabong', 'Nourlangie Rock', 'Jim Jim Falls', 'Crocodiles', 'Aboriginal Culture'],
    bestTime: 'May–Sep',
    duration: '3–4 nights',
    from: '$520',
    description: "Kakadu National Park is a UNESCO World Heritage site for both its natural and cultural significance — 20,000 square kilometers of wetlands, escarpments, and ancient Aboriginal rock art dating back 20,000 years. Ubirr is the most famous rock art gallery — the 'Rainbow Serpent' painting (Namarrgarn, the lightning man) is 20,000 years old, and the climb to the top of Ubirr Rock offers panoramic views of the floodplains (best at sunset). Yellow Water Billabong is the best place to see wildlife — take the sunrise boat cruise to see saltwater crocodiles (3-5 meters long), wild brumbies (horses), wallabies, jabiru birds (Australia's only stork), and thousands of magpie geese. Nourlangie Rock has a 1.5-kilometer loop walk passing the Anbangbang Gallery (5,000-year-old 'Lightning Man' painting) and the lookout for views of the escarpment. Jim Jim Falls is a 200-meter waterfall plunging into a deep plunge pool — the 4WD road is rough, and the 900-meter walk to the falls is steep and challenging (dry season only). Kakadu has more than 10,000 crocodiles — saltwater 'salties' can grow to 7 meters and weigh 1,000 kilograms, and you'll see them on every river and billabong. The Aboriginal people of Kakadu (Bininj/Mungguy) have lived here for 65,000 years — the Warradjan Cultural Centre explains their culture, art, and connection to the land.",
    experiences: [
      'Ubirr rock art sunset',
      'Yellow Water croc cruise',
      'Nourlangie lookout walk',
      'Jim Jim Falls plunge pool',
      'Warradjan Cultural Centre',
      'Maguk waterfall swim',
    ],
    camps: ['Cooinda Lodge', 'Mercure Kakadu Crocodile', 'Anbinik Kakadu Resort', 'Bamurru Plains', 'Kakadu Lodge'],
    unesco: true,
  },
]