export const cookIslandsDestinations = [
  {
    slug: 'aitutaki',
    name: 'Aitutaki',
    country: 'Cook Islands',
    region: 'Cook Islands',
    tagline: 'The Most Beautiful Lagoon in the Pacific',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/pacific/aitutaki.jpg',
    highlights: ['Aitutaki Lagoon', 'One Foot Island', 'Motu Cruise', 'Honeymoon Island', 'Giant Trevally', 'Snorkeling'],
    bestTime: 'May–Oct',
    duration: '5–7 nights',
    from: '$920',
    description: "Aitutaki is the most beautiful lagoon in the Pacific — a 15-kilometer triangular lagoon of turquoise water, encircled by a coral reef with 15 motu (small islands), and a 2-kilometer main island with a single road. The lagoon is 5-10 meters deep, with 200 species of tropical fish, coral gardens, and the most beautiful sandbar in the world (Honeymoon Island, a 2-kilometer sandbar that appears at low tide). Aitutaki Lagoon Cruise is the main activity — a full-day cruise to 5 motu (One Foot Island, Honeymoon Island, Akaiami, Tekopua, Moturakau) with lunch, snorkeling at 'Giant Trevally Corner' (where you can feed the fish), and a walk to the post office on One Foot Island (you can stamp your passport here). One Foot Island is the most famous motu — the sand is soft and white, the water is crystal-clear, and you can see the 'one foot' footprint carved into the sand by a giant who left his footprint. Giant Trevally (GT) are the largest fish in the lagoon — they grow to 1 meter in length and 30 kilograms, and you can feed them by hand (the guides have fish food). Honeymoon Island (Motu Akaiami) is a sandbar that appears at low tide — you can walk 2 kilometers across the sandbar to the ocean reef, with water on both sides at waist-level. The island has a plane wreck (a 1950s TEAL flying boat) that crashed in the lagoon. Aitutaki has a single road around the main island — rent a scooter or bicycle to explore: the highest point is 124 meters (Mount Maunga Pu) with 360-degree lagoon views. Aitutaki is 50 kilometers by air from Rarotonga (45-minute flight, $400 round trip).",
    experiences: [
      'Aitutaki Lagoon Cruise',
      'One Foot Island passport stamp',
      'Honeymoon Island sandbar',
      'Giant trevally feeding',
      'Motu Akaiami plane wreck',
      'Mount Maunga Pu view',
    ],
    camps: ['Aitutaki Lagoon Private Island Resort', 'Pacific Resort Aitutaki', 'Tamanu Beach Resort', 'Aitutaki Escape', 'Aitutaki Village'],
    unesco: false,
  },
  {
    slug: 'rarotonga',
    name: 'Rarotonga',
    country: 'Cook Islands',
    region: 'Cook Islands',
    tagline: 'The South Pacific\'s Most Underrated Island',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/pacific/rarotonga.jpg',
    highlights: ['Cross Island Walk', 'Punanga Nui Market', 'Muri Beach', 'Te Rua Manga Needle', 'Aroa Marine Reserve', 'Island Night'],
    bestTime: 'May–Oct',
    duration: '5–7 nights',
    from: '$720',
    description: "Rarotonga is the Cook Islands' main island — a 32-kilometer ring road (the circumference of the island) encircling a volcanic interior with 4,000-foot peaks, 15 tropical valleys, and a lagoon that wraps around the entire island. The Cross Island Walk (Te Rua Manga Track) is the most popular hike — a 3-hour, 4.5-kilometer trek from the north coast to the south coast, passing through the jungle, crossing the 'Needle' (Te Rua Manga, a 200-meter pinnacle of rock), and emerging at the southern village of Papua. The view from the Needle is the best photo on the island (the pinnacle is 200 meters above sea level). Punanga Nui Market (Saturdays 6 am-12 pm) is the cultural center — you'll find Cook Islands dancing, carving, weaving, black pearls, and food stalls: ika mata (raw tuna in coconut milk), rukau (taro leaves with coconut cream), and fresh tropical fruit. Muri Beach is the most popular beach — a 1-kilometer crescent of white sand on the southeast coast, with 4 motu (small islands) in the lagoon, watersports rentals (kayaks, SUPs, glass-bottom kayaks), and beach bars. Aroa Marine Reserve is the best snorkeling spot — located at the west end of the island, the lagoon has 25 fish species, 10 coral species, and a 50-meter 'snorkel trail' with underwater signs naming fish and coral. The Island Night (Te Vara Nui Village) is the best cultural show — a buffet dinner with 10 dishes (you'll eat local food like taro, rice, fish, and pork), followed by a 1-hour dance show (the 'drummers' are spectacular). Rarotonga is a 4-hour flight from New Zealand (Auckland) or 9 hours from Los Angeles — it's easier to reach than French Polynesia and much cheaper.",
    experiences: [
      'Cross Island Walk to Needle',
      'Punanga Nui Saturday market',
      'Muri Beach kayaking',
      'Aroa Marine Reserve snorkel trail',
      'Island Night cultural show',
      'Circular island drive',
    ],
    camps: ['The Rarotongan Beach Resort', 'Pacific Resort Rarotonga', 'Muri Beach Club Hotel', 'Te Manava Luxury Villas', 'Nautilus Resort'],
    unesco: false,
  },
  {
    slug: 'atiu',
    name: 'Atiu',
    country: 'Cook Islands',
    region: 'Cook Islands',
    tagline: 'The Island of Caves & Birds',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/pacific/atiu.jpg',
    highlights: ['Anatakitaki Cave', 'Kopeka Bird', 'Atiu Coffee', 'Cave Tours', 'Marble Beach', 'Birdwatching'],
    bestTime: 'Apr–Nov',
    duration: '3–4 nights',
    from: '$580',
    description: "Atiu is the Cook Islands' most unique island — a 'raised coral atoll' (meaning the coral reef has lifted above sea level), with 6 caves, 25 species of birds, and a population of 400 people (the least visited of the Cook Islands). Anatakitaki Cave is the most spectacular cave on Atiu — a 30-minute guided tour through a limestone cave with stalactites, stalagmites, and a hidden stream (you'll see 1000-year-old coral fossils, formed when the island was underwater). The Kopeka bird (Atiu Swiftlet) is found only on Atiu — the small bird navigates in the dark using echolocation (like bats), and you can see the birds in the caves at sunrise and sunset. Atiu Coffee is grown and roasted on the island — the coffee is organic, and you can visit the plantation (Atiu Coffee Plantation) for a tour and tasting (the coffee is $20-30 per bag). Atiu has 6 caves — besides Anatakitaki, visit Vai Marere Cave (an underground river), Te Ana-Pou Cave (with native eels), and Rimarau Cave (with a pool for swimming). Marble Beach (Papa-Nui Beach) is a 2-kilometer beach of white sand and crushed coral — the sand is pink at sunset, and you can swim in the lagoon (the water is cold but refreshing). Atiu is a birdwatcher's paradise — you'll see the Cook Islands Fruit Dove (rare), the Chattering Kingfisher (loud call), and the Atiu Warbler (found only here). Atiu is 1 hour by air from Rarotonga (Air Rarotonga, $400 round trip, 3 flights per week).",
    experiences: [
      'Anatakitaki Cave tour',
      'Kopeka bird watching',
      'Atiu Coffee tasting',
      'Vai Marere underground river',
      'Marble Beach sunset',
      'Bird watching walk',
    ],
    camps: ['Atiu Villas', 'Atiu Homestay', 'Tamarind House', 'Mama\'s Beach House', 'Kia Orana Lodge'],
    unesco: false,
  },
]