export const fijiDestinations = [
  {
    slug: 'fiji-main',
    name: 'Fiji Islands',
    country: 'Fiji',
    region: 'Fiji',
    tagline: 'Bula — The World\'s Friendliest Islands',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/pacific/fiji.jpg',
    highlights: ['Yasawa Islands', 'Beqa Lagoon Diving', 'Village Kava Ceremony', 'Taveuni Garden Island', 'Manta Rays', 'Overwater Bure'],
    bestTime: 'May–Oct',
    duration: '7–10 nights',
    from: '$620',
    description: "Fiji is the Pacific's warmest welcome — 330 islands of extraordinary beauty, a culture built around joy and hospitality, world-class diving in the Coral Triangle, and resorts ranging from backpacker surf camps to ultra-luxury private islands. The Yasawa Islands are the most beautiful — a chain of 20 volcanic islands with turquoise lagoons, white sand beaches, and the famous Sawa-i-Lau Cave (a limestone cave with a pool of blue water, featured in the movie 'Blue Lagoon'). Yasawa resorts are more remote and authentic — you can island-hop by ferry (Awesome Adventures Fiji) or seaplane. Beqa Lagoon is Fiji's best diving — the Shark Dive is world-famous: you'll see bull sharks (up to 25), tiger sharks (occasionally), lemon sharks, and reef sharks on a single dive (book through Aqua-Trek, optional cage diving). Fiji is the 'Soft Coral Capital of the World' — the Rainbow Reef (between Taveuni and Vanua Levu) has colorful soft corals in every colour: purple, pink, yellow, blue. The Somosomo Strait (the most nutrient-rich water in the South Pacific) is where you find the Great White Wall (a coral wall covered in white soft corals). The village kava ceremony is a cultural ritual — drink kava (kava root ground into powder and mixed with water) from a bilo (half coconut shell) with the village chief. The ceremony involves clapping, saying 'Bula!' (cheers), and drinking the entire shell in one go. Taveuni is the 'Garden Island' of Fiji — the Bouma National Park has 3 beautiful waterfalls (Tavoro Falls, 30 meters), and the international date line passes through the island (you can stand in tomorrow and yesterday at the same time).",
    experiences: [
      'Yasawa Islands sailing',
      'Beqa Lagoon shark dive',
      'Village kava ceremony',
      'Taveuni Bouma Falls hike',
      'Rainbow Reef scuba diving',
      'Overwater bure sunset',
    ],
    camps: ['Likuliku Lagoon Resort', 'Tokoriki Island Resort', 'Laucala Island', 'Vomo Island Resort', 'Six Senses Fiji'],
    unesco: false,
  },
  {
    slug: 'cloud-break',
    name: 'Cloud Break',
    country: 'Fiji',
    region: 'Fiji',
    tagline: 'Fiji\'s Legendary Surf Wave',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/pacific/cloudbreak.jpg',
    highlights: ['Cloud Break Wave', 'Surf Charter', 'Lefty\'s', 'Restaurant Waves', 'Tavarua Island', 'Pro Surfer'],
    bestTime: 'Mar–Oct',
    duration: '7–14 nights',
    from: '$1,200',
    description: "Cloud Break (Namotu Left) is one of the world's most legendary waves — a perfect, barreling left-hand reef break located 15 minutes by boat from Nadi, consistently rated among the best waves on earth. The wave breaks over a shallow coral reef (you can touch the coral at low tide), with a steep, hollow barrel that can hold up to 15-foot faces. Cloud Break was featured in the surfing film 'Step into Liquid' and is a bucket-list wave for advanced surfers. The wave breaks for 200 meters, with the best surf at mid to high tide (low tide exposes the reef, making it dangerous). The wave can be paddled from Namotu Island Resort (the closest accommodation, a 5-minute boat ride) or from Tavarua Island Resort (10 minutes). Marine life is abundant — sea turtles swim through the channel between sets, and you can see dolphins in the channel (named 'Suck-it-Up' for the paddle out). Tavarua Island is a heart-shaped island with luxury bures (Fijian cottages), all-inclusive with meals and unlimited boat trips to Cloud Break and other spots (Restaurants, Namotu Left, Wilkes Passage). Navutu ('Cloud Break's little sister') is a more forgiving wave for intermediate surfers, located just behind Cloud Break. The best time for Cloud Break is March to October (southwest swell season) — the waves are consistent, with solid 6-10 foot sets (October is the peak for large swells). Fiji's surf season attracts pro surfers from Australia, Hawaii, and the US — you'll see world champions in the water at Tavarua.",
    experiences: [
      'Cloud Break dawn patrol',
      'Tavarua Island Resort',
      'Namotu Left barrel',
      'Restaurants wave',
      'Wilkes Passage channel',
      'Surf charter boat day trip',
    ],
    camps: ['Tavarua Island Resort', 'Namotu Island Resort', 'Fiji Surf Academy', 'Matava Resort', 'The Remote Resort'],
    unesco: false,
  },
  {
    slug: 'taveuni',
    name: 'Taveuni',
    country: 'Fiji',
    region: 'Fiji',
    tagline: 'The Garden Island of Fiji',
    gradient: 'linear-gradient(160deg,#001c10,#002c1a,#003c22)',
    image: '/images/pacific/taveuni.jpg',
    highlights: ['Rainbow Reef', 'Bouma Falls', 'International Date Line', 'Lavena Coastal Walk', 'Waitavala Water Slide', 'Tavoro Falls'],
    bestTime: 'Jul–Sep',
    duration: '3–5 nights',
    from: '$580',
    description: "Taveuni is the 'Garden Island' of Fiji — a volcanic island of lush rainforest, 3 beautiful waterfalls, and the best soft coral diving in the world. Rainbow Reef is the most famous dive site — the 'Great White Wall' is a coral wall covered in white soft corals, only found in the Somosomo Strait (the nutrient-rich water between Taveuni and Vanua Levu). Purple, pink, yellow, and blue corals cover every surface — it's like swimming through an underwater rainbow. Bouma National Park has 3 waterfalls (Tavoro Falls) — a 30-minute walk from the park entrance to the first waterfall (30 meters), with a swimming hole. The second and third waterfalls are 45 minutes and 90 minutes further (lunch at the third waterfall). The International Date Line passes through Taveuni — you can stand at the '180° Meridian' marker at Waiyevo, with one foot in Wednesday and one foot in Thursday (the village uses Fiji time, not the date line). Lavena Coastal Walk is a 6-kilometer loop — the first 2 kilometers is beach, then you cross a river, pass the Lavena village, and reach a waterfall at the end. Waitavala Water Slide is a natural rock slide — locals and tourists slide down a 10-meter smooth rock face into a pool (requires high river flow, ask at the resort). Taveuni is also known for taro (dalo) — the island produces most of Fiji's taro, and you'll see taro fields on every hillside.",
    experiences: [
      'Rainbow Reef Great White Wall',
      'Bouma Falls swimming',
      'International Date Line photo',
      'Lavena Coastal Walk',
      'Waitavala water slide',
      'Taro farm visit',
    ],
    camps: ['Taveuni Palms Resort', 'Paradise Taveuni Resort', 'Qamea Resort and Spa', 'Taveuni Dive Resort', 'Rainbow Reef Resort'],
    unesco: false,
  },
  {
    slug: 'beqa-lagoon',
    name: 'Beqa Lagoon',
    country: 'Fiji',
    region: 'Fiji',
    tagline: 'World-Famous Shark Encounter',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/pacific/beqa.jpg',
    highlights: ['Bull Shark Dive', 'Shark Reef', 'Beqa Island', 'Firewalking', 'South Pacific Cruises', 'Soft Coral Diving'],
    bestTime: 'Apr–Oct',
    duration: '2–3 nights',
    from: '$480',
    description: "Beqa Lagoon is Fiji's most famous diving destination — the Shark Dive (Shark Reef Marine Reserve) is the world's best shark encounter, with up to 100 sharks visible on a single dive. Bull sharks are the stars — you'll see 10-25 bull sharks (the most aggressive shark species), but they're not aggressive during the dive (the dive masters feed them by hand, which attracts them). Tiger sharks (5-7 meters long) are occasional guests — the 'Big Momma' tiger shark visits the reef occasionally. Lemon sharks, tawny nurse sharks, whitetip reef sharks, and blacktip reef sharks are also present. The dive is an 'interactive shark feed' — the dive masters place a large fish bin in the center of the reef, and the sharks swim around you in circles (you sit on the bottom in a circle). Beqa Island is known for firewalking — the Sawau tribe performs the firewalking ceremony, walking on white-hot stones (the secret is kept within the tribe). Beqa Island has 6 traditional Fijian villages — you can stay at a local guesthouse (homestay) for an authentic experience. Soft coral diving in Beqa Lagoon is excellent — the 'Fantasy Reef' and 'Mellow Yellow' dive sites have purple, pink, and yellow corals. The South Pacific Cruises from Pacific Harbour take you to the Navua River — you'll visit 3 villages, see waterfalls, and eat a traditional 'lovo' (underground earth oven) lunch. Beqa Lagoon is located off the southern coast of Viti Levu, accessible from Pacific Harbour (the 'Adventure Capital of Fiji', 3 hours from Nadi).",
    experiences: [
      'Beqa Lagoon shark dive',
      'Bull shark feeding interaction',
      'Beqa Island firewalking',
      'Navua River village cruise',
      'Soft coral snorkeling',
      'Pacific Harbour jet boat',
    ],
    camps: ['The Pearl Resort Fiji', 'Beqa Lagoon Resort', 'The Warwick Fiji', 'Bedarra Beach Inn', 'Uprising Beach Resort'],
    unesco: false,
  },
]