export const frenchPolynesiaDestinations = [
  {
    slug: 'bora-bora',
    name: 'Bora Bora',
    country: 'French Polynesia',
    region: 'French Polynesia',
    tagline: 'The Pearl of the Pacific',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/pacific/bora-bora.jpg',
    highlights: ['Overwater Bungalows', 'Mount Otemanu', 'Lagoon Snorkelling', 'Shark Feeding', 'Manta Rays', 'Sunset Cruises'],
    bestTime: 'May–Oct',
    duration: '7–10 nights',
    from: '$1,200',
    description: "Bora Bora is what the word paradise was invented to describe — a volcanic peak rising from a luminescent turquoise lagoon, encircled by a coral reef, with overwater bungalows hanging above water so clear you can see every fish from your bed. The island is the most famous of French Polynesia's 118 islands, often called the 'Pearl of the Pacific.' Mount Otemanu is a 727-meter volcanic peak (dormant) at the center of the island — you can hike to the summit (4-5 hours, guide required) for 360-degree views of the lagoon and ocean. The lagoon is the most beautiful in the world — it's a 'saltwater lake' inside the coral reef, 40 kilometers of turquoise water with an average depth of 10 meters. Coral gardens (for snorkeling) are located throughout the lagoon — you'll see colorful fish, sea turtles, manta rays, and eagle rays. Shark feeding is a popular activity — the sharks (blacktip and whitetip reef sharks) are not aggressive, and you can snorkel with them (keep 2 meters distance). Manta rays are best seen from August to October — the rays come to the lagoon to feed on plankton, and you can snorkel with them (they grow to 5 meters wide). Stingrays are everywhere — you can feed them by hand (the guides will show you how). Overwater bungalows were invented in Bora Bora (1967) — the first bungalows were built at the Hotel Bora Bora (now closed), and today every major resort has overwater villas with glass floors. The best bungalows are at the St. Regis, Four Seasons, Conrad, and InterContinental (all on the eastern side of the island, facing Mount Otemanu).",
    experiences: [
      'Overwater bungalow sunrise',
      'Mount Otemanu guided hike',
      'Lagoon snorkeling and manta rays',
      'Shark feeding interaction',
      'Sunset catamaran cruise',
      '4x4 island tour',
    ],
    camps: ['The St. Regis Bora Bora', 'Four Seasons Bora Bora', 'Conrad Bora Bora', 'InterContinental Bora Bora', 'Le Bora Bora'],
    unesco: false,
  },
  {
    slug: 'moorea',
    name: 'Moorea',
    country: 'French Polynesia',
    region: 'French Polynesia',
    tagline: 'Bora Bora\'s More Beautiful and Less Visited Sister',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/pacific/moorea.jpg',
    highlights: ['Cook\'s Bay', 'Dolphin Watching', 'Belvedere Lookout', 'Pineapple Wine', 'Snorkelling', 'Whale Season'],
    bestTime: 'May–Oct',
    duration: '4–6 nights',
    from: '$680',
    description: "Moorea is what travelers discover when they want Bora Bora without the crowds or the price — a jagged volcanic island of extraordinary beauty just 17 kilometers from Tahiti, with two spectacular bays, wild hinterland, and some of the Pacific's best snorkeling. Cook's Bay is the most beautiful bay on Moorea — the sapphire water reflects the jagged peak of Mount Mouaputa (the 'spire' mountain) and the pineapple fields on the hillside. Opunohu Bay (the 'other' bay) is equally beautiful but less developed — the bays are separated by a 5-kilometer road, and you can see both from the Belvedere Lookout (Belvédère). Belvedere Lookout is a 15-minute drive from Cook's Bay — the view of both bays, the coral reef, and the Pacific Ocean is the most photographed in French Polynesia. Dolphin watching is best from the Moorea Dolphin Center (at the InterContinental Hotel) — the center has a lagoon where 5 dolphins live, and you can swim with them ($250 per person). Humpback whales (July–November) migrate from Antarctica to French Polynesia to give birth — Moorea is the best place to see them, with boats and guides for 'swimming with whales' (ethical operators only). Pineapple wine is unique to Moorea — the island produces 80% of French Polynesia's pineapples, and you can taste pineapple wine at the Rotui Juice Factory (free samples). Snorkeling is excellent at the 'Coral Garden' (near the Sofitel) — you'll see clownfish (Nemo), butterflyfish, angelfish, and sea turtles. Moorea has a 2-day, 60-kilometer hiking trail around the island (4 days if you stay overnight at the beach bungalows) — the trail passes through pineapple fields and jungle, with stunning views of the bays.",
    experiences: [
      'Cook\'s Bay drive',
      'Belvedere Lookout sunset',
      'Dolphin swimming encounter',
      'Whale watching (Jul-Nov)',
      'Pineapple wine tasting',
      'Coral Garden snorkeling',
    ],
    camps: ['Hilton Moorea Lagoon Resort', 'Sofitel Kia Ora Moorea', 'InterContinental Moorea', 'Manava Beach Resort', 'Les Tipaniers'],
    unesco: false,
  },
  {
    slug: 'tahiti',
    name: 'Tahiti',
    country: 'French Polynesia',
    region: 'French Polynesia',
    tagline: 'The Heart of Polynesia',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/pacific/tahiti.jpg',
    highlights: ['Papeete Market', 'Marae Arahurahu', 'Faarumai Waterfalls', 'Point Venus', 'Museum of Tahiti', 'Black Sand Beach'],
    bestTime: 'May–Oct',
    duration: '3–5 nights',
    from: '$520',
    description: "Tahiti is the heart of French Polynesia — the largest island in the Society Islands, the capital (Papeete) of French Polynesia, and the international gateway to all the other islands. Papeete Market (Le Marché) is the cultural center of Tahiti — open daily 5 am-4 pm (Sunday 5 am-12 pm), with tifaifai (quilted fabrics), vanilla, pearls, carved wood, and fresh fish (poisson cru, raw tuna marinated in lime juice and coconut milk). The market is best at 5 am when the fishermen sell their catch. Marae Arahurahu is the best-preserved 'marae' (open-air temple) in French Polynesia — a stone platform where ancient Polynesian priests conducted ceremonies (including human sacrifice, replaced with pig sacrifice by European missionaries). The site is 100% restored and very beautiful (15 minutes from Papeete). Faarumai Waterfalls are 3 waterfalls on the island's north coast — the third waterfall (4 hours one way) is the most beautiful (30 meters), with a pool at the bottom for swimming. Point Venus is a black sand beach on the north coast — the location of Captain James Cook's 1769 observatory (to observe the transit of Venus), now a lighthouse and black sand beach. The Museum of Tahiti and Her Islands is the best museum in French Polynesia — pre-European artifacts, a replica of a Polynesian double-hulled canoe, and the history of European contact and French colonization. Black sand beaches (Pointe Vénus) are made of volcanic lava (the sand is basalt), which is why the sand is black (the water is still turquoise, but the beach looks dramatic). The inner island has tropical rainforest with guava, mango, and hibiscus — you can rent a car and drive around the island in 4 hours (the coastline road is 120 kilometers).",
    experiences: [
      'Papeete Market early morning',
      'Marae Arahurahu temple',
      'Faarumai waterfall hike',
      'Point Venus black sand',
      'Museum of Tahiti',
      'Circle island drive',
    ],
    camps: ['InterContinental Tahiti', 'Hilton Hotel Tahiti', 'Le Tahiti by Pearl Resorts', 'Manava Suite Resort', 'Fare Suisse'],
    unesco: false,
  },
  {
    slug: 'rangiroa',
    name: 'Rangiroa',
    country: 'French Polynesia',
    region: 'French Polynesia',
    tagline: 'The Largest Atoll in Polynesia',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/pacific/rangiroa.jpg',
    highlights: ['Tiputa Pass', 'Dolphin Pass', 'Aquarium Reef', 'Pink Sand Beach', 'Blue Lagoon', 'Kia Ora Resort'],
    bestTime: 'Jul–Oct',
    duration: '5–7 nights',
    from: '$880',
    description: "Rangiroa is the largest atoll in French Polynesia and the second-largest atoll in the world (after Kwajalein in the Marshall Islands) — a 80-kilometer long ring of 415 motu (islets) surrounding a 1,000 square-kilometer lagoon, with one of the world's best dive sites. Tiputa Pass is the main channel between the lagoon and the ocean — the current runs fast (up to 10 knots), bringing nutrients into the lagoon, which attracts hundreds of dolphins and sharks. Dolphin pass is the nickname for Tiputa — you'll see spinner dolphins jumping out of the water, swimming in the current, and surfing the waves. The 'Tiputa Drift' dive is world-famous — you drift from the ocean into the lagoon through the pass, surrounded by grey reef sharks (50-100), barracuda, Napoleon wrasse, eagle rays, and manta rays. Aquarium Reef is a shallow dive site inside the lagoon — the coral is less colorful than the outer reef, but the fish are abundant: clownfish, butterflyfish, angelfish, and boxfish. Pink Sand Beach (Les Sables Roses) is on the east side of the atoll — the sand is pink from crushed coral, the water is turquoise, and there's a famous coconut tree that grows sideways (leaning into the water). Blue Lagoon (Lagoon Bleu) is a swimming area inside the lagoon — the water is bright turquoise, with starfish everywhere (hundreds on the sandbar). Kia Ora Resort is the most famous hotel on Rangiroa — overwater bungalows with glass floors, an infinity pool, and a world-class dive center (the Top Dive shop is on the property).",
    experiences: [
      'Tiputa Pass drift dive',
      'Dolphin watching at sunset',
      'Pink Sand Beach day trip',
      'Blue Lagoon sandbar walk',
      'Kia Ora Resort snorkeling',
      'Biking the motu road',
    ],
    camps: ['Kia Ora Resort & Spa', 'Hôtel Maitai Rangiroa', 'Le Sauvage Rangiroa', 'Vaimoe Lodge', 'Pension Turiroa'],
    unesco: false,
  },
]