export const hawaiiDestinations = [
  {
    slug: 'hawaii-big-island',
    name: 'Hawaii Island (Big Island)',
    country: 'USA (Hawaii)',
    region: 'Hawaii',
    tagline: 'Active Volcanoes & Black Sand Beaches',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/pacific/big-island.jpg',
    highlights: ['Volcanoes National Park', 'Kīlauea Eruption', 'Mauna Kea', 'Black Sand Beach', 'Green Sand Beach', 'Waipio Valley'],
    bestTime: 'Apr–Jun · Sep–Nov',
    duration: '5–7 nights',
    from: '$680',
    description: "The Big Island of Hawaii (Hawaiʻi Island) is the largest island in the Hawaiian archipelago — twice the size of all other islands combined, with 11 of the world's 13 climate zones (from tropical rainforest to alpine desert) and the world's most active volcano. Hawaiʻi Volcanoes National Park is the main attraction — Kīlauea volcano has been erupting continuously since 1983 (the current eruption is in Halemaʻumaʻu crater at the summit). You can see the glowing lava at night from the Jaggar Museum lookout (the best free view), or hike the 4-mile round-trip to the active flow (only when it's safe, check with rangers). Mauna Kea is a 4,207-meter dormant volcano — the highest point in Hawaii, and the best place on earth for stargazing (the summit has 13 telescopes, including the Keck Observatory). You can drive to the Visitor Center (2,800 meters) for free, but need a 4WD for the summit (the road is gravel and steep). Punaluʻu Black Sand Beach is the most famous black sand beach — the sand is made of basalt (lava rock), and Hawaiian green sea turtles (honu) rest on the sand (keep 3 meters distance). Papakōlea Green Sand Beach is the only green sand beach in the United States — the sand is green from olivine crystals (a volcanic mineral), accessible only by a 5.6-kilometer round-trip hike (you can hire a local 4WD truck for $20-40). Waipiʻo Valley is a 6-kilometer deep canyon with waterfalls, taro farms, and a black sand beach — you can drive down if you have 4WD (the road is 25-degree gradient, the steepest in Hawaii), or take a guided horseback tour.",
    experiences: [
      'Kīlauea crater night glow',
      'Mauna Kea sunset & stars',
      'Punaluʻu black sand turtles',
      'Papakōlea green sand hike',
      'Waipiʻo valley horseback',
      'Coffee farm tour (Kona)',
    ],
    camps: ['Four Seasons Hualalai', 'Mauna Lani Resort', 'Fairmont Orchid', 'Volcano House', 'Hilton Waikoloa'],
    unesco: true,
  },
  {
    slug: 'maui',
    name: 'Maui',
    country: 'USA (Hawaii)',
    region: 'Hawaii',
    tagline: 'The Valley Isle — Road to Hana & Haleakalā',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/pacific/maui.jpg',
    highlights: ['Haleakalā Sunrise', 'Road to Hana', 'Waianapanapa Beach', 'Lahaina Town', 'Molokini Crater', 'Whale Watching'],
    bestTime: 'Apr–May · Sep–Nov',
    duration: '5–7 nights',
    from: '$720',
    description: "Maui is the second-largest Hawaiian island — known as the 'Valley Isle' for the isthmus between two volcanoes, Haleakalā (3,055 meters) and the West Maui Mountains. Haleakalā National Park is the main attraction — sunrise at the summit (3,055 meters) is a pilgrimage: you see the sun rise above the clouds, with the crater floor 800 meters below you. Reservations are required ($1 per car, book 2 months ahead). The bike ride down the volcano (2,000 meters of descent in 35 kilometers) is a popular activity (Book with a tour company, they drive you to the top). The Road to Hana is a 105-kilometer winding road with 617 curves and 59 bridges (most are one-lane) — it takes 3-5 hours each way, but you'll pass 100+ waterfalls, bamboo forests, and black sand beaches. Waianapanapa State Park is the most beautiful stop — a black sand beach with a sea cave, freshwater pools, and blowholes (best after rain). Lahaina (the historic whaling village) was the capital of the Hawaiian Kingdom in the 19th century, with the Banyan Tree (planted 1873, one of the largest banyan trees in the US). Lahaina was destroyed by the 2023 wildfire (the town is being rebuilt, but most historic buildings are gone). Molokini Crater is a half-sunken volcanic crater 5 kilometers off Maui's coast — the best snorkeling in Hawaii, with 200+ fish species, 60% visibility (the crater protects the water from wind and waves). Humpback whales (December–April) migrate from Alaska to Hawaii to give birth — the 'Auʻau Channel' between Maui and Lānaʻi has the highest concentration of whales in Hawaii.",
    experiences: [
      'Haleakalā sunrise reservation',
      'Road to Hana waterfall stops',
      'Waianapanapa black sand',
      'Molokini Crater snorkeling',
      'Lahaina banyan tree',
      'Whale watch (Dec-Apr)',
    ],
    camps: ['Four Seasons Maui', 'Andaz Maui at Wailea', 'Grand Wailea Resort', 'Ritz-Carlton Kapalua', 'Hotel Wailea'],
    unesco: false,
  },
  {
    slug: 'kauai',
    name: 'Kauai',
    country: 'USA (Hawaii)',
    region: 'Hawaii',
    tagline: 'The Garden Isle — Na Pali Coast',
    gradient: 'linear-gradient(160deg,#001c10,#002c1a,#003c22)',
    image: '/images/pacific/kauai.jpg',
    highlights: ['Na Pali Coast', 'Waimea Canyon', 'Helicopter Tour', 'Kalalau Trail', 'Queen’s Bath', 'Hanalei Bay'],
    bestTime: 'Apr–Jun · Sep–Nov',
    duration: '5–7 nights',
    from: '$650',
    description: "Kauai is the oldest and most beautiful Hawaiian island — known as the 'Garden Isle' for its lush rainforest, 5,000-foot cliffs, and the wettest spot on earth (Mount Waiʻaleʻale, 11,500mm of rain per year). The Na Pali Coast is the most dramatic coastline in Hawaii — 27 kilometers of sheer cliffs (1,200 meters high) cut by 4 valleys, accessible only by helicopter, boat, or the Kalalau Trail (the 35-kilometer round trip is the most famous backpacking route in Hawaii). The Kalalau Trail is 18 kilometers one-way to Kalalau Beach — the first 3.2 kilometers (to Hanakāpīʻai Beach) is a day hike (2-3 hours), with a waterfall (Hanakāpīʻai Falls) another 3.2 kilometers inland. Permits are required for camping ($35), and the trail is closed for bad weather (check with the park). Waimea Canyon is the 'Grand Canyon of the Pacific' — 1,100 meters deep, 16 kilometers long, and 3 kilometers wide, carved by erosion (the canyon is red, brown, and green from volcanic rock, soil, and vegetation). The Waimea Canyon Lookout (1,070 meters) is the best view. Helicopter tours are the best way to see Kauai — the 50-minute 'Doors Off' tours (Mauna Loa) fly you over the Na Pali Coast, Waimea Canyon, and the 'Jurassic Park' waterfall (Manawaiopuna Falls, featured in the opening scene of Jurassic Park). Queen's Bath is a natural tide pool on the north shore — swim only when the ocean is calm (the waves can sweep you out to sea in winter). Hanalei Bay is the most beautiful bay on Kauai — a crescent of golden sand, turquoise water, and 1,000-foot green cliffs behind the beach (the bay is 3 kilometers wide).",
    experiences: [
      'Na Pali Coast helicopter',
      'Kalalau Trail day hike',
      'Waimea Canyon lookout',
      'Hanalei Bay swimming',
      'Queen’s Bath (calm ocean)',
      'Wailua River kayak',
    ],
    camps: ['1 Hotel Hanalei Bay', 'Koʻa Kea Resort', 'Grand Hyatt Kauai', 'The Ritz-Carlton, Kapalua (not on Kauai, but similar)', 'Kauai Marriott'],
    unesco: false,
  },
]