export const newZealandDestinations = [
  {
    slug: 'queenstown',
    name: 'Queenstown',
    country: 'New Zealand',
    region: 'New Zealand',
    tagline: 'The Adventure Capital of the World',
    gradient: 'linear-gradient(160deg,#001c14,#002c1e,#004028)',
    image: '/images/pacific/queenstown.jpg',
    highlights: ['Bungee Jumping', 'Milford Sound', 'Remarkables Skiing', 'Lake Wakatipu', 'Fiordland', 'Wine Country'],
    bestTime: 'Jun–Aug (Skiing) · Dec–Mar (Summer)',
    duration: '5–8 nights',
    from: '$820',
    description: "Queenstown is adventure made permanent — every activity ever invented for adrenaline lives here, surrounded by mountain scenery so dramatic it looks like a film set. Because it is — Lord of the Rings was filmed in almost every direction. Bungee jumping was invented in Queenstown — the Kawarau Bridge Bungy (43 meters, 1988) is the original, and the Nevis Bungy (134 meters) is the highest in New Zealand (8 seconds of freefall). The Shotover Jet is a jet boat through a narrow canyon — the driver spins 360-degree turns within meters of rock walls. The Remarkables ski area has 30 kilometers of slopes — the views over Lake Wakatipu and Queenstown are spectacular. Milford Sound is a day trip (4-hour drive each way) — the fiord (15 kilometers long) is surrounded by sheer granite cliffs up to 1,200 meters high, with waterfalls cascading into the water (Stirling Falls drops 155 meters). Lake Wakatipu is New Zealand's third-largest lake (80 kilometers long) — the TSS Earnslaw steamship (1912) crosses the lake to Walter Peak High Country Farm for sheep shearing and barbecue lunch. Central Otago wine region produces world-class Pinot Noir — vineyards are a 20-minute drive from Queenstown (Gibbston Valley, Peregrine, Amisfield).",
    experiences: [
      'Nevis bungee jump',
      'Shotover Jet canyon',
      'Milford Sound cruise',
      'Remarkables skiing',
      'TSS Earnslaw farm visit',
      'Central Otago wine tour',
    ],
    camps: ['Eichardt\'s Hotel', 'Matakauri Lodge', 'The Rees Hotel', 'Kamana Lakehouse', 'Blanket Bay'],
    unesco: true,
  },
  {
    slug: 'milford-sound',
    name: 'Milford Sound & Fiordland',
    country: 'New Zealand',
    region: 'New Zealand',
    tagline: 'Rudyard Kipling Called It the Eighth Wonder',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/pacific/milford-sound.jpg',
    highlights: ['Fiord Cruise', 'Mitre Peak', 'Underwater Observatory', 'Milford Track', 'Doubtful Sound', 'Waterfalls'],
    bestTime: 'Oct–Apr',
    duration: '2–3 nights',
    from: '$680',
    description: "Milford Sound (Piopiotahi) is one of the world's most spectacular places — sheer granite cliffs rising 1,200 meters from a fiord carved by glaciers, waterfalls plunging directly into dark sea water, and a silence and scale that makes human beings feel appropriately small. Rudyard Kipling called it the Eighth Wonder of the World. The fiord is 15 kilometers long and receives 7 meters of rain per year (rainy days are the best — the waterfalls multiply from dozens to hundreds). Mitre Peak is the most famous mountain in the fiord — a 1,692-meter pyramid of rock that dominates the view. The Milford Sound Cruise (1 hour 45 minutes) takes you to the Tasman Sea and back, passing Stirling Falls (155 meters) and Lady Bowen Falls (162 meters). The underwater observatory (Milford Deep) is a floating observation deck 10 meters below the surface — you'll see black coral (found in deeper water elsewhere, but here at 10 meters), sea stars, and a variety of fish. The Milford Track is the 'finest walk in the world' — a 4-day, 53.5-kilometer trek from Glade Wharf to Sandfly Point, through rainforest, suspension bridges, and Mackinnon Pass (1,069 meters). Doubtful Sound is three times longer and three times deeper than Milford Sound — it's less visited, accessed via a boat across Lake Manapouri and a bus over Wilmot Pass. The Manapouri Power Station is a hydroelectric station inside a mountain (you take a bus 2 kilometers underground).",
    experiences: [
      'Milford Sound cruise',
      'Underwater observatory',
      'Milford Track guided or self-guided',
      'Doubtful Sound overnight',
      'Lake Manapouri crossing',
      'Homer Tunnel engineering',
    ],
    camps: ['Milford Sound Lodge', 'Fiordland Lodge', 'Lake Te Anau Lodge', 'Real Journeys House', 'Te Anau Lakeview'],
    unesco: true,
  },
  {
    slug: 'rotorua',
    name: 'Rotorua',
    country: 'New Zealand',
    region: 'New Zealand',
    tagline: 'Smoking Geysers & Maori Culture',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/pacific/rotorua.jpg',
    highlights: ['Te Puia Geyser', 'Maori Village', 'Polynesian Spa', 'Redwood Forest', 'Zorbing', 'Whakarewarewa'],
    bestTime: 'Year-round',
    duration: '2–3 nights',
    from: '$480',
    description: "Rotorua is New Zealand's cultural and geothermal heart — a city of smoking geysers, boiling mud pools, and the best place to experience Maori culture. Te Puia is the most famous geothermal area — the Pōhutu Geyser erupts up to 30 meters (the largest active geyser in the southern hemisphere), and the boiling mud pools bubble and pop. The Kiwi House has two North Island brown kiwi (the national bird), but you can't photograph them (no flash, to protect their eyes). The New Zealand Maori Arts and Crafts Institute trains carvers and weavers in traditional Maori skills. Whakarewarewa (the 'living Maori village') has been continuously inhabited for 200 years — residents use geothermal heat for cooking (in a 'hāngī' steam box) and bathing, and you can take a guided tour. Tamaki Maori Village is a commercial 'village' (not an actual village) but offers the most entertaining cultural evening — the pōwhiri (welcoming ceremony) with warrior challenge, haka (war dance), concert with poi balls, and a buffet hāngī dinner (food cooked underground). Rotorua has a sulfur smell (rotten eggs) — you get used to it. Polynesian Spa is the most famous hot springs — the Priest Pool (42°C) and the Duchess Pool (38°C) overlook Lake Rotorua. Zorbing was invented in Rotorua — roll down a hill inside a giant inflatable ball (you can add water to create an inside-water slide). The Redwood Forest has 6 kilometers of walking and biking trails through giant California redwoods (planted in 1901) — the Treewalk suspension bridges are 6-12 meters high between the trees.",
    experiences: [
      'Te Puia Pōhutu Geyser',
      'Whakarewarewa village tour',
      'Tamaki Maori Village hāngī',
      'Polynesian Spa hot pools',
      'Redwoods Treewalk',
      'Zorbing adventure',
    ],
    camps: ['Solitaire Lodge', 'Treetops Lodge', 'The Black Swan', 'Regent of Rotorua', 'Pullman Rotorua'],
    unesco: false,
  },
  {
    slug: 'tongariro',
    name: 'Tongariro Alpine Crossing',
    country: 'New Zealand',
    region: 'New Zealand',
    tagline: 'New Zealand\'s Best Day Hike',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/pacific/tongariro.jpg',
    highlights: ['Emerald Lakes', 'Mount Doom', 'Red Crater', 'Blue Lake', 'Volcanic Terrain', 'Soda Springs'],
    bestTime: 'Nov–Apr',
    duration: '1 day hike',
    from: '$220',
    description: "The Tongariro Alpine Crossing is New Zealand's best day hike — a 19.4-kilometer, 7-9 hour trek across an active volcanic plateau, passing crater lakes, steaming vents, and Mount Doom itself (the film location for Mordor in Lord of the Rings). The hike has a 1,200-meter elevation gain (starting at 1,120 meters, highest point at 1,886 meters at Red Crater). The Red Crater is the highest point — the view of the Emerald Lakes (three bright green lakes below) is the most rewarding photo of the crossing. The Emerald Lakes get their colour from minerals (iron, copper, magnesium) leaching from the geothermal area. The Blue Lake is a sacred tapu (taboo) lake — swimming is prohibited, but the view from the rim is worth the climb. Mount Doom (Mt. Ngāuruhoe, 2,291 meters) is not part of the main crossing (it's a 3-4 hour side trip), but you'll see the perfect volcanic cone from the trail. Soda Springs is a 20-minute side trip from the start — a waterfall in a small canyon (the only water source on the crossing). The crossing is open November-April (summer) — winter conditions are dangerous (snow, ice, avalanche risk). There are no toilets on the track after the first 45 minutes, and no water supply except at Soda Springs. The weather changes fast — pack rain gear, warm layers, sunscreen (the UV is extreme in the thin atmosphere), and 3 litres of water. Shuttle buses run from National Park Village to the trailhead at Mangatepopo and from the finish at Ketetahi back to your car.",
    experiences: [
      'Red Crater to Emerald Lakes',
      'Mount Doom photo',
      'Blue Lake sacred view',
      'Soda Springs waterfall',
      'Volcanic steam vents',
      'Sunrise shuttle from National Park',
    ],
    camps: ['Chateau Tongariro Hotel', 'Holiday Inn National Park', 'The Park Hotel', 'Plateau Lodge', 'Adventure Lodge'],
    unesco: true,
  },
  {
    slug: 'abel-tasman',
    name: 'Abel Tasman National Park',
    country: 'New Zealand',
    region: 'New Zealand',
    tagline: 'Golden Sand & Kayaking Paradise',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/pacific/abel-tasman.jpg',
    highlights: ['Seal Colony', 'Split Apple Rock', 'Awaroa Bay', 'Cleopatra\'s Pool', 'Coastal Track', 'Water Taxi'],
    bestTime: 'Dec–Mar',
    duration: '3–5 nights',
    from: '$520',
    description: "Abel Tasman National Park is New Zealand's smallest but most beautiful national park — a coastal paradise of golden sand beaches, granite headlands, and crystal-clear turquoise water. The Abel Tasman Coast Track is one of New Zealand's Great Walks — 60 kilometers along the coast, taking 3-5 days, with options to kayak parts and use water taxis to shorten sections. The track is mostly flat (no mountain passes), with tidal crossings at Awaroa (you must check tide times). The Tonga Island Marine Reserve has a fur seal colony — you can see the seals from the Coastal Track at Tonga Quarry or kayak closer (keep 50 meters distance). Split Apple Rock is a large granite boulder split in two, located just off the coast near Kaiteriteri — best seen from a kayak or water taxi. Cleopatra's Pool is a natural swimming hole (at low tide) with a natural rock slide — located a short walk from the Torrent Bay car park. Awaroa Bay has the most beautiful beach in the park — 2 kilometers of golden sand, accessible only by water taxi or hiking. You can stay overnight at the Awaroa Lodge (the only accommodation inside the park). Kayaking is the best way to explore the park — you can rent sea kayaks from Kaiteriteri or Marahau for 1-5 days, with full day and half day tours. Water taxis (AquaTaxi, Abel Tasman, Wilson's) drop you at any beach and pick you up — a great way to start a one-way hike. Marine life includes little blue penguins (kōrurā, the smallest penguins in the world), New Zealand fur seals (kekeno), bottlenose dolphins, and if you're lucky, orca (killer whales) in summer.",
    experiences: [
      'Coast Track 3-5 day hike',
      'Kayak to Tonga Island seals',
      'Split Apple Rock paddle',
      'Cleopatra\'s Pool rock slide',
      'Awaroa Bay overnight',
      'Water taxi to secluded beaches',
    ],
    camps: ['Awaroa Lodge', 'Kimberley House', 'Ratanui Lodge', 'Kaiteriteri Reserve Camp', 'Abel Tasman Lodge'],
    unesco: false,
  },
]