export const samoaDestinations = [
  {
    slug: 'samoa-main',
    name: 'Samoa (Upolu & Savaii)',
    country: 'Samoa',
    region: 'Samoa',
    tagline: 'The Treasured Islands of the South Pacific',
    gradient: 'linear-gradient(160deg,#001c14,#002c1e,#004028)',
    image: '/images/pacific/samoa.jpg',
    highlights: ['To Sua Ocean Trench', 'Alofaaga Blowholes', 'Sopoaga Waterfall', 'Lalomanu Beach', 'Robert Louis Stevenson Museum', 'Papaseea Sliding Rocks'],
    bestTime: 'May–Oct',
    duration: '7–10 nights',
    from: '$520',
    description: "Samoa is the 'Treasured Islands' of the South Pacific — a Polynesian kingdom of 2 main islands (Upolu and Savaii) with traditional culture (fa'a Samoa, the Samoan way), untouched beaches, and the famous To Sua Ocean Trench. To Sua Ocean Trench is the most photographed spot in Samoa — a 30-meter deep sinkhole filled with ocean water (reached by a 30-meter ladder), with a 15-meter by 15-meter pool of turquoise water (you can swim in the trench, but the water is cold, 22°C). The trench is accessible for $20 per person, with a changing room, restaurant, and gardens. Alofaaga Blowholes (Savaii) are the most powerful blowholes in the Pacific — water shoots 20 meters into the air through cracks in the lava rock (coconut shells thrown into the blowhole will explode into fragments). Sopoaga Waterfall (Upolu) is a 100-meter waterfall in a lush green canyon — you can swim in the pool at the base (best after rain, when the water is flowing). Lalomanu Beach (Upolu) is the most beautiful beach in Samoa — a 5-kilometer crescent of white sand, turquoise water, and shade from coconut trees. Robert Louis Stevenson Museum (Apia) is the former home of the Scottish author (who died in Samoa in 1894) — you can tour the restored house, gardens, and see his tomb on Mount Vaea (a 1-hour uphill hike). Papaseea Sliding Rocks (Upolu) is a natural water slide — you slide down a 10-meter smooth rock face into a pool (the rocks are slippery, wear water shoes).",
    experiences: [
      'To Sua Ocean Trench swim',
      'Alofaaga blowhole coconut',
      'Sopoaga waterfall swim',
      'Lalomanu beach day',
      'Robert Louis Stevenson museum',
      'Papaseea rock sliding',
    ],
    camps: ['Saletoga Sands Resort', 'Taumeasina Island Resort', 'Sheraton Samoa Beach Resort', 'Coconuts Beach Club', 'Le Vasa Resort'],
    unesco: false,
  },
  {
    slug: 'savaii',
    name: 'Savaii',
    country: 'Samoa',
    region: 'Samoa',
    tagline: 'Samoa\'s Wild and Untouched Island',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/pacific/savaii.jpg',
    highlights: ['Falealupo Canopy Walk', 'Mu Pagoa Waterfall', 'Saleaula Lava Fields', 'Mosque Beach', 'Taga Blowholes', 'Diving with Turtles'],
    bestTime: 'May–Oct',
    duration: '3–4 nights',
    from: '$480',
    description: "Savaii is the largest and wildest island in Samoa — a volcanic island with a single road (80 kilometers), few resorts, and a traditional way of life (fa'a Samoa) untouched by mass tourism. The Falealupo Canopy Walk is a suspension bridge 40 meters above the rainforest floor — the bridge is 25 meters long, and you can climb a 20-meter tower to view the rainforest canopy (at sunset, you can see the ocean on both sides of the island). Mu Pagoa Waterfall (Afu Aau Falls) is a 10-meter waterfall with a deep swimming pool — the water is fresh (mountain water) and cold (the best way to cool off after a day of driving). Saleaula Lava Fields cover 50 acres of black lava rock — the 1905 eruption destroyed 3 villages, and the lava flow is up to 10 meters thick. You can see the ruins of the church (a Catholic church buried to its roof in lava) and the 'Virgin's Grave' (an untouched grave of a woman who died before the eruption, the lava flowed around it). Mosque Beach (Mosque Fish Reserve) is a marine reserve with white sand and clear water — you'll see tropical fish (clownfish, parrotfish, angelfish) at the 'Mosque' rock (named for its dome shape). Taga Blowholes (Alofaaga Blowholes) are even more powerful than the blowholes on Upolu — water shoots 30 meters into the air through 2 blowholes, and locals throw coconuts into the blowholes to demonstrate their power.",
    experiences: [
      'Falealupo canopy walk',
      'Mu Pagoa waterfall swim',
      'Saleaula lava church',
      'Mosque Beach snorkeling',
      'Taga blowhole coconut',
      'Savaii island drive',
    ],
    camps: ['Savaii Lagoon Resort', 'Stevenson at Savaii', 'Amoa Resort', 'Le Lagoto Resort', 'Jet Over Hotel'],
    unesco: false,
  },
  {
    slug: 'samoa-apia',
    name: 'Apia & Upolu',
    country: 'Samoa',
    region: 'Samoa',
    tagline: 'The Capital with a Conscience',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/pacific/apia.jpg',
    highlights: ['Apia Harbour', 'Fleamarket', 'Piula Cave Pool', 'Papaseea Sliding Rocks', 'Palolo Deep Marine Reserve', 'Samoa Cultural Village'],
    bestTime: 'May–Oct',
    duration: '2–3 nights',
    from: '$380',
    description: "Apia is the capital of Samoa — a small, laid-back city on the north coast of Upolu, with a waterfront harbor, a lively market, and a fascinating history of colonialism, independence, and the first Pacific Island nation to gain independence (1962). Apia Harbour is the main port — you'll see fishing boats, cargo ships, and the 'Aggie Grey's' (the oldest hotel in Samoa, famous for American GIs during WWII). The Flea Market (Apia Flea Market) is the main souvenir market — you'll find 'ie lavalava (sarong), t-shirts, carved wooden bowls, and food (fresh fruit, donuts, chop suey). Piula Cave Pool is a freshwater swimming pool inside a lava tube — the pool is 10 meters deep, with small fish nibbling your feet (the water is cold, 20°C), and you can see a waterfall inside the cave. Palolo Deep Marine Reserve is a snorkeling spot 50 meters from shore — you'll see 100+ fish species (clownfish, butterflyfish, trumpetfish), sea cucumbers, giant clams (you're not allowed to touch them), and 10-20 meter coral walls. Samoa Cultural Village (Apia) is a free 2-hour tour (Monday-Friday 10:30 am-12 pm) — you'll learn about Samoan tattooing (pe'a), weaving (tapa cloth), cooking (umu, underground oven), and dancing (siva).",
    experiences: [
      'Apia Harbour walk',
      'Flea Market shopping',
      'Piula Cave Pool swim',
      'Palolo Deep snorkeling',
      'Cultural Village tour',
      'Aggie Grey\'s sunset',
    ],
    camps: ['Taumeasina Island Resort', 'Sheraton Samoa Beach Resort', 'Aggie Grey\'s Hotel', 'Tanoa Tusitala Hotel', 'Lynn\'s Getaway'],
    unesco: false,
  },
]