export const argentinaChileDestinations = [
  {
    slug: 'patagonia',
    name: 'Torres del Paine',
    country: 'Chile',
    region: 'Patagonia',
    tagline: 'The End of the World',
    gradient: 'linear-gradient(160deg,#001c14,#002c1e,#004028)',
    image: '/images/americas/torres-del-paine.jpg',
    highlights: ['Torres del Paine', 'W Trek', 'Grey Glacier', 'French Valley', 'Salto Grande', 'Condors'],
    bestTime: 'Nov–Mar',
    duration: '5–8 nights',
    from: '$680',
    description: "Torres del Paine National Park is Patagonia's crown jewel — a 181,000-hectare wilderness of granite towers, turquoise lakes, glaciers, and wind so strong it pushes you sideways. The Torres del Paine (the Towers) are the park's iconic peaks — three granite spires (South Tower 9,500 feet, Central Tower 9,300 feet, North Tower 8,700 feet), best viewed from the base of the towers (a 4-hour round-trip hike from Hotel Las Torres). The W Trek is the classic 5-day, 50-mile route that covers the park's highlights — the W shape covers the three valleys of the French Valley, Grey Glacier, and the Torres. The full circuit (O Trek) is 7-9 days, 70 miles — requires a guide for the back side (North) and more advanced logistics. Grey Glacier is a 4-mile-wide, 15-mile-long glacier at the southern end of the park — you can kayak to the glacier's face (incredible, but you need neoprene boots and a dry suit) or take a catamaran cruise across Grey Lake. French Valley (Valle Francés) is the most beautiful valley in the park — a 3-hour hike (one-way) from the Italian Camp to the French Lookout (Mirador Francés), with views of the French Glacier and the Cuernos ('Horns') mountains. Salto Grande is a powerful waterfall between Lake Nordenskjöld and Pehoé Lake — the 15-minute walk from the parking lot is the park's best accessible view. Patagonia is famous for wind — 50-100 mph is normal, pack layers, waterproof everything, and be prepared to get blown over.",
    experiences: [
      'Base of the Towers hike',
      'W Trek 5 days',
      'Grey Glacier kayak',
      'French Valley lookout',
      'Salto Grande waterfall',
      'Condor spotting',
    ],
    camps: ['Explora Patagonia', 'Awasi Patagonia', 'Hotel Las Torres', 'Tierra Patagonia', 'Rio Serrano Hotel'],
    unesco: true,
  },
  {
    slug: 'perito-moreno',
    name: 'Perito Moreno Glacier',
    country: 'Argentina',
    region: 'Patagonia',
    tagline: 'The Living Glacier',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/americas/perito-moreno.jpg',
    highlights: ['Glacier Front', 'Catwalk System', 'Mini-Trekking', 'Boat Tour', 'Iceberg Calving', 'Ruinas de los Glaciares'],
    bestTime: 'Oct–Apr',
    duration: '2–3 nights',
    from: '$520',
    description: "Perito Moreno Glacier is the world's most spectacular glacier — a 250-square-mile wall of blue ice that is one of the few glaciers on earth still advancing (5 feet per day). The glacier is 3 miles wide and 240 feet high above the water (its total depth is 550 feet) — the sheer size of it is overwhelming. The catwalk system (5,000 meters of walkways) gives panoramic views of the glacier from multiple angles — the best view is from the north side (Solitude), where you can see the glacier calve into Brazo Rico. Glacier calving is the main attraction — the sound of ice cracking and crashing into the water sounds like thunder, sending spray 50 feet into the air. You can witness a big calving 5-10 times an hour (the sound precedes the fall). Mini-trekking is a 2-hour walk on the glacier itself (1.5 hours of actual ice walking) — you wear crampons and walk on the 200-foot-thick ice, seeing crevasses and moulins (ice drains). Boat tours (15 minutes) from the catwalk system get you closer to the glacier's face — the boat goes within 500 feet, close enough to see the blue ice and feel the cold spray. The Ruinas de los Glaciares (Glacier Ruins) is a 45-minute walk through the forest to the ruins of the old glacier (where the ice has retreated).",
    experiences: [
      'Catwalk system south side',
      'Mini-trekking ice walking',
      'Boat tour to glacier face',
      'Calving thunder sound',
      'Ruinas de los Glaciares',
      'El Calafate town lamb',
    ],
    camps: ['Explora El Calafate', 'Eolo Lodge', 'Los Ponchos Hotel', 'Xelena Hotel', 'Design Suites Calafate'],
    unesco: true,
  },
  {
    slug: 'el-chalten',
    name: 'El Chaltén',
    country: 'Argentina',
    region: 'Patagonia',
    tagline: 'The Hiking Capital of Patagonia',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/americas/el-chalten.jpg',
    highlights: ['Mount Fitz Roy', 'Laguna de los Tres', 'Cerro Torre', 'Laguna Torre', 'Mirador de los Cóndores', 'Lago del Desierto'],
    bestTime: 'Nov–Mar',
    duration: '3–5 nights',
    from: '$580',
    description: "El Chaltén is Argentina's trekking capital — a purpose-built village at the base of Mount Fitz Roy and Cerro Torre, with free camping, no cell phone signal, and the best day hikes in Patagonia. Mount Fitz Roy (3,405 meters) is the iconic granite spire that inspired the Patagonia logo — the classic 13-mile hike to Laguna de los Tres (the lake at the base) is an 8-hour round trip, with the final hour a 1,300-foot uphill boulder scramble. The best time to reach the lake is 6 am (sunrise hits Fitz Roy before clouds form) — the view of the granite needles reflected in the turquoise lake is worth the early start. Cerro Torre (3,128 meters) is the second famous peak — an improbable 1,000-foot vertical ice-covered rock spire, the hardest mountain to climb in Patagonia (only 10 people have reached the true summit). The 12-mile hike to Laguna Torre (the lake at the base) is flatter and easier (5-6 hours round trip), with views of the glacier at the lake's edge. The Mirador de los Cóndores is a 30-minute hike from town — the best place for sunset photos of Fitz Roy and Cerro Torre. Lago del Desierto is a 45-minute drive from town (or 4-hour hike) — you can kayak or take a boat to the far end of the lake, then hike back to town (a 12-mile loop). Argentine pizza (at La Cervecería) and craft beer are the post-hike rewards (the lamb is also excellent).",
    experiences: [
      'Laguna de los Tres sunrise',
      'Cerro Torre boulder scrambling',
      'Mirador de los Cóndores sunset',
      'Lago del Desierto kayak',
      'La Cervecería pizza',
      'Free camping by the river',
    ],
    camps: ['Explora El Chaltén', 'Destino Sur', 'Senderos Patagonia', 'Posada Los Ñires', 'Hotel Poincenot'],
    unesco: false,
  },
  {
    slug: 'buenos-aires',
    name: 'Buenos Aires',
    country: 'Argentina',
    region: 'Argentina',
    tagline: 'The Paris of South America',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/americas/buenos-aires.jpg',
    highlights: ['Tango', 'La Boca', 'Recoleta Cemetery', 'Palermo Soho', 'San Telmo Market', 'Steak Dinner'],
    bestTime: 'Oct–Dec · Mar–May',
    duration: '5–7 nights',
    from: '$280',
    description: "Buenos Aires is South America's most sophisticated city — European architecture, passionate tango, the world's finest beef, and a café culture that makes Paris look hurried. Tango is the soul of Buenos Aires — the dance was born in the working-class neighborhoods of the 19th century, and you can see it live at a tango show (Café Tortoni is historic) or dance it at a milonga (local dance party) where anyone can join. La Boca is the most colorful neighborhood — the Caminito (a street museum of corrugated metal painted in bright colors) is the most famous postcard image of Buenos Aires, and the Boca Juniors soccer stadium (La Bombonera) is a pilgrimage site for soccer fans. Recoleta Cemetery is the world's most beautiful cemetery — 4,700 above-ground vaults, with the tomb of Eva Perón (Evita) the most visited, plus dozens of other Argentine presidents and celebrities. Palermo Soho is the hippest neighborhood — cobblestone streets, boutiques, art galleries, and the best restaurants in the city (Don Julio is world-class). San Telmo Market is a Sunday antique market — the street of Defensa becomes a pedestrian fair selling everything from vintage records to mate gourds. Argentine steak (asado) is a religion — order a bife de chorizo (sirloin) or ojo de bife (ribeye), cooked 'a punto' (medium), with chimichurri sauce and a bottle of Malbec.",
    experiences: [
      'Tango show at Café Tortoni',
      'La Boca Caminito photos',
      'Recoleta Cemetery Evita',
      'Palermo Soho restaurant',
      'San Telmo Sunday market',
      'Steak dinner with Malbec',
    ],
    camps: ['Alvear Palace Hotel', 'Four Seasons Buenos Aires', 'Park Hyatt Buenos Aires', 'Faena Hotel', 'Casa Calma'],
    unesco: false,
  },
  {
    slug: 'santiago',
    name: 'Santiago',
    country: 'Chile',
    region: 'Chile',
    tagline: 'The Snow-Capped Capital',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/americas/santiago.jpg',
    highlights: ['Cerro San Cristóbal', 'La Moneda Palace', 'Lastarria', 'Museo de la Memoria', 'Valparaíso Day Trip', 'Cajón del Maipo'],
    bestTime: 'Oct–Apr',
    duration: '3–5 nights',
    from: '$320',
    description: "Santiago is Chile's sophisticated capital — a modern city of 7 million set in a valley with snow-capped Andes peaks on the horizon, 90 minutes from beach and mountains. Cerro San Cristóbal is a 2,800-foot hill in the center of the city — take the funicular (built 1925) to the top for 360-degree views of the city and the Andes (the smog can be bad, best views after rain or in winter). The statue of the Virgin Mary (22-meter-high) is visible from everywhere in Santiago. La Moneda Palace is Chile's presidential palace — the 18th-century building is where President Salvador Allende died during the 1973 military coup (you can see the bullet holes in the walls). Changing of the guard (even-numbered days) is a spectacle. Lastarria is the most bohemian neighborhood — cobblestone streets, bookstores, boutique shops, and the best restaurants (Salvador Cocina y Café). Museo de la Memoria (Memory Museum) is a stark memorial to the human rights abuses of the Pinochet regime (1973-1990) — the building alone (the black box) is chilling. Valparaíso is a 90-minute bus ride from Santiago — the colorful port city of 42 hills, street art, and historic funiculars (a UNESCO World Heritage site). Cajón del Maipo is a 2-hour drive into the Andes — the Maipo River canyon has hiking, white water rafting, and the Embalse El Yeso (a turquoise reservoir at 8,000 feet).",
    experiences: [
      'Cerro San Cristóbal funicular',
      'La Moneda changing of guard',
      'Lastarria restaurant dinner',
      'Museo de la Memoria',
      'Valparaíso street art',
      'Cajón del Maipo rafting',
    ],
    camps: ['The Ritz-Carlton Santiago', 'Mandarin Oriental Santiago', 'Noi Vitacura', 'W Santiago', 'Hotel Bidasoa'],
    unesco: false,
  },
  {
    slug: 'atacama',
    name: 'Atacama Desert',
    country: 'Chile',
    region: 'Chile',
    tagline: 'The Driest Non-Polar Desert on Earth',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/americas/atacama.jpg',
    highlights: ['Valle de la Luna', 'Tatio Geysers', 'Salar de Atacama', 'Laguna Cejar', 'Death Valley', 'Stargazing'],
    bestTime: 'Mar–Nov',
    duration: '4–6 nights',
    from: '$480',
    description: "The Atacama Desert is the driest non-polar desert on earth — some weather stations have never recorded rainfall, and the landscape resembles Mars so closely that NASA tests their rovers here. Valle de la Luna (Moon Valley) is the most famous landscape — a 45-minute drive from San Pedro de Atacama, with salt-crusted rocks, sand dunes, and a sunset view that looks like the surface of the moon. The Tatio Geysers (El Tatio) is the highest geothermal field in the world (14,000 feet) — 80 geysers erupting at dawn (5-7 am) when the temperature difference between the steam (185°F) and the freezing air (14°F) creates the most dramatic effect. Salar de Atacama is the largest salt flat in Chile — the Chaxa Lagoon is the best place to see flamingos (James, Chilean, Andean) feeding on brine shrimp in the shallow salt water. Laguna Cejar is a salt lake where you float like the Dead Sea (30% salinity) — the water is freezing but floating is effortless. Death Valley (Valle de la Muerte) is a 30-minute hike from San Pedro — the sand dunes and rock formations are perfect for sandboarding (rent a board in town). Stargazing is the Atacama's superpower — the driest air and high altitude (8,000 feet) create the clearest skies on earth, with 300+ clear nights a year (the ALMA observatory is here).",
    experiences: [
      'Valle de la Luna sunset',
      'Tatio Geysers at dawn',
      'Chaxa Lagoon flamingos',
      'Laguna Cejar floating',
      'Death Valley sandboarding',
      'Stargazing ALMA',
    ],
    camps: ['Awasi Atacama', 'Explora Atacama', 'Tierra Atacama', 'Alto Atacama', 'Nayara Alto Atacama'],
    unesco: false,
  },
]