export const brazilDestinations = [
  {
    slug: 'rio',
    name: 'Rio de Janeiro',
    country: 'Brazil',
    region: 'Brazil',
    tagline: 'The Marvelous City',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/americas/rio.jpg',
    highlights: ['Christ the Redeemer', 'Sugarloaf Mountain', 'Copacabana', 'Ipanema', 'Carnival', 'Lapa Steps'],
    bestTime: 'Dec–Mar (Carnival) · May–Sep (Dry)',
    duration: '5–7 nights',
    from: '$560',
    description: "Rio de Janeiro is one of the world's most dramatically beautiful cities — a bay of 365 islands, 50 miles of beach, and mountains rising from the sea, all framed by the world's tallest Art Deco statue. Christ the Redeemer (Cristo Redentor) is a 98-foot concrete-and-soapstone statue on top of Corcovado Mountain (2,300 feet) — the view from his feet is the iconic Rio postcard (Sugarloaf, Copacabana, Guanabara Bay). Sugarloaf Mountain (Pão de Açúcar) is a 1,299-foot granite monolith at the entrance of Guanabara Bay — ride the two-stage cable car for 360-degree views of the bay, the city, and the statue (sunset is the best time). Copacabana is the world's most famous beach — 2.5 miles of black-and-white wave-patterned promenade, beach volleyball, and kiosks selling caipirinhas (cachaça, lime, sugar). Ipanema is the beach from the song 'The Girl from Ipanema' — it's more fashionable, with separate surfing and swimming areas, and sunset at Arpoador rock is a daily celebration with applause. Carnival (Carnevale) is the world's largest party — 2 million people on the streets every day for 5 days before Ash Wednesday, with Samba Parades at the Sambódromo (reserve tickets months ahead). Lapa's Escadaria Selarón is a 250-step mosaic staircase covered in 2,000 tiles from 60 countries — the Chilean artist Selarón covered the steps as a tribute to the Brazilian people.",
    experiences: [
      'Christ statue early morning (avoid crowds)',
      'Sugarloaf sunset cable car',
      'Copacabana caipirinha',
      'Ipanema sunset applause',
      'Carnival samba parade (Feb-Mar)',
      'Lapa Steps photo',
    ],
    camps: ['Belmond Copacabana Palace', 'Fasano Rio', 'Hotel Santa Teresa', 'Fairmont Rio', 'Grand Hyatt Rio'],
    unesco: true,
  },
  {
    slug: 'iguazu-falls',
    name: 'Iguazu Falls',
    country: 'Brazil/Argentina',
    region: 'Brazil',
    tagline: 'Devil\'s Throat',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/americas/iguazu.jpg',
    highlights: ['Devil\'s Throat', 'Garganta do Diabo', 'Lower Circuit', 'Upper Circuit', 'Boat Ride', 'Train Ride'],
    bestTime: 'Apr–May · Sep–Oct',
    duration: '2–3 nights',
    from: '$450',
    description: "Iguazu Falls is one of the world's most powerful waterfalls — a 1.7-mile-wide, 80-meter-high curtain of 275 falls, shared by Argentina (80%) and Brazil (20%). The Devil's Throat (Garganta del Diablo) is the largest fall — 150 feet high, 2,600 feet wide, and the volume of water (450,000 cubic feet per second) creates a constant cloud of mist that rises 500 feet. The Brazilian side offers the panoramic view — a 1-mile walkway that ends 50 feet from the falls, rainbows on sunny days, and views of the Argentine side. The Argentine side offers the up-close experience — the Upper Circuit (falls from above), Lower Circuit (at the base of the falls, get wet), Devil's Throat walkway (out over the river, ending at the edge of the abyss), and a small train connecting the circuits. Boat rides (from either side) take you to the base of the falls — you will get completely soaked, including your camera (bring waterproof bags). Iguazu is on the border of Brazil and Argentina — you can see both sides in two days (check visa requirements, especially for US citizens needing Argentina visa).",
    experiences: [
      'Brazilian side panoramic view',
      'Argentine side Devil\'s Throat',
      'Lower Circuit get wet',
      'Boat ride under falls',
      'Rainforest birdwatching',
      'Itaipu Dam tour (largest hydroelectric)',
    ],
    camps: ['Belmond Hotel das Cataratas', 'Gran Meliá Iguazú', 'Loi Suites Iguazú', 'Awasi Iguazú', 'Spa da Aldeia'],
    unesco: true,
  },
  {
    slug: 'amazon',
    name: 'Amazon Rainforest',
    country: 'Brazil',
    region: 'Brazil',
    tagline: 'The Lungs of the Earth',
    gradient: 'linear-gradient(160deg,#001c10,#002c1a,#003c22)',
    image: '/images/americas/amazon.jpg',
    highlights: ['Meeting of Waters', 'Jaguar Spotting', 'Canopy Walkway', 'Pink River Dolphins', 'Anavilhanas Archipelago', 'Jungle Lodge'],
    bestTime: 'Jun–Nov',
    duration: '5–7 nights',
    from: '$680',
    description: "The Amazon Rainforest is the world's largest tropical rainforest — 2.1 million square miles across 9 countries, producing 20% of the world's oxygen, containing 10% of all known species, and still being explored (a new species discovered every 3 days). The Brazilian Amazon is the largest portion (60%), accessible from Manaus (the capital of Amazonas state). The Meeting of Waters (Encontro das Águas) is where the blackwater Rio Negro (75°F, 2-3 mph) and the whitewater Rio Solimões (84°F, 4-5 mph) flow side-by-side for 4 miles without mixing — due to their different temperatures, speeds, and sediment loads (the Negro is black because of decaying vegetation, the Solimões is sandy because of Andean sediment). Anavilhanas Archipelago is the world's largest river archipelago — 400 islands in the Rio Negro, with flooded forests (igapó) during high water (May-July) and sandy beaches during low water (October-November). Pink river dolphins (boto) are found only in the Amazon — they're more flexible than sea dolphins (they can turn their heads 90 degrees to navigate flooded forests), and you can swim with them (ethical operators only). Jaguars are the Amazon's top predator — spotting them requires an experienced guide and luck (the Pantanal in southern Brazil has higher visibility).",
    experiences: [
      'Meeting of Waters boat tour',
      'Anavilhanas flooded forest',
      'Pink dolphin swim (ethical)',
      'Canopy walkway (birdwatching)',
      'Jaguar tracking (Pantanal better)',
      'Jungle lodge hiking',
    ],
    camps: ['Anavilhanas Jungle Lodge', 'Juma Amazon Lodge', 'Pousada Rio Negro', 'Amazon Ecopark Lodge', 'Ariaú Amazon Towers'],
    unesco: true,
  },
  {
    slug: 'salvador',
    name: 'Salvador',
    country: 'Brazil',
    region: 'Brazil',
    tagline: 'The Afro-Brazilian Soul',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/americas/salvador.jpg',
    highlights: ['Pelourinho', 'Elevador Lacerda', 'São Francisco Church', 'Capoeira', 'Acarajé', 'Forte de São Marcelo'],
    bestTime: 'Sep–Mar',
    duration: '4–6 nights',
    from: '$380',
    description: "Salvador is Brazil's Afro-Brazilian soul — a 500-year-old city of cobblestone hills, baroque churches, capoeira in the streets, and the most African city outside Africa. Pelourinho ('Pillory') is the historic center — a UNESCO World Heritage site of colorful colonial mansions, steep alleys, and the Terreiro de Jesus square. The name comes from the whipping post where slaves were publicly punished. The Elevador Lacerda is a 236-foot elevator connecting the Cidade Alta (Upper City) and Cidade Baixa (Lower City) — built in 1873, it's the first urban elevator in the world (carries 28,000 people daily). São Francisco Church (Igreja de São Francisco) is the most baroque church in Brazil — its interior is covered in 400 pounds of gold leaf (the 17th-century Portuguese found gold in Minas Gerais and spent it on churches). Capoeira is an Afro-Brazilian martial art disguised as dance — enslaved people practiced it as a form of resistance (musicians play the berimbau, drum, and pandeiro). Acarajé is Salvador's signature street food — a black-eyed pea fritter (deep-fried in dende palm oil) filled with shrimp, vatapá (spicy paste), and caruru (okra stew), sold by women in white dresses (baianas de acarajé).",
    experiences: [
      'Pelourinho alleys',
      'Elevador Lacerda ride',
      'São Francisco gold church',
      'Capoeira performance (Terça Feira)',
      'Acarajé street food',
      'Forte São Marcelo island',
    ],
    camps: ['Fera Palace Hotel', 'Hotel Villa Bahia', 'Aram Yami Hotel', 'Zank by Toque Hotel', 'Pestana Convento do Carmo'],
    unesco: true,
  },
  {
    slug: 'florianopolis',
    name: 'Florianópolis',
    country: 'Brazil',
    region: 'Brazil',
    tagline: 'The Island of Magic',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/americas/floripa.jpg',
    highlights: ['Lagoa da Conceição', 'Praia Mole', 'Jurere Internacional', 'Costão do Santinho', 'Fortresses', 'Dune Sandboarding'],
    bestTime: 'Dec–Mar',
    duration: '5–7 nights',
    from: '$320',
    description: "Florianópolis ('Floripa') is Brazil's most sophisticated beach destination — a 34-mile island with 42 beaches, a charming colonial center, and a reputation for quality of life (one of Brazil's highest HDI). Lagoa da Conceição is the island's central lagoon — kite surfers, windsurfers, and stand-up paddleboarders fill the lagoon, while sunset caipirinhas at the Lagoa's restaurants are the daily ritual. Praia Mole is the most beautiful beach in southern Brazil — a 1-mile curve of white sand framed by granite hills, with consistent waves for surfing (the surf school at Mole teaches beginners). Jurere Internacional is Brazil's most expensive neighborhood — gated condos, luxury hotels, and high-end restaurants (the 'Brazilian St. Tropez'). The Costão do Santinho (Rocky Coast) is a 500-meter stretch of ancient rock art (petroglyphs) carved by the Sambaqui people 4,500 years ago — the 'Battle of the Mounds' shows warriors and animals. The Azorean forts (São José da Ponta Grossa, Santo Antônio, Santa Cruz) protected the island from Spanish pirates — the views of the island and ocean are spectacular. Sandboarding at the dunes of Joaquina Beach (the sandboard capital of Brazil) — rent a board and slide down 100-foot dunes.",
    experiences: [
      'Lagoa da Conceição SUP',
      'Praia Mole surfing lesson',
      'Jurere Internacional dinner',
      'Costão do Santinho petroglyphs',
      'Fortaleza São José sunset',
      'Joaquina sandboarding',
    ],
    camps: ['Jurerê Beach Village', 'Hotel Costão do Santinho', 'VOA Hotel Ilhas da Magic', 'Novotel Florianópolis', 'Majestic Palace Hotel'],
    unesco: false,
  },
]