export const canadaDestinations = [
  {
    slug: 'banff',
    name: 'Banff & Lake Louise',
    country: 'Canada',
    region: 'Canada',
    tagline: 'The Jewel of the Canadian Rockies',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/americas/banff.jpg',
    highlights: ['Lake Louise', 'Moraine Lake', 'Icefields Parkway', 'Banff Town', 'Peyto Lake', 'Hot Springs'],
    bestTime: 'Jun–Sep',
    duration: '5–7 nights',
    from: '$520',
    description: "Banff National Park is Canada's first national park (1885) — a UNESCO World Heritage site in the heart of the Canadian Rockies, with turquoise glacial lakes, towering peaks, and abundant wildlife. Lake Louise is the most famous lake — the Fairmont Chateau sits on its shore, and the water color is from rock flour (glacially-ground rock suspended in the water), which reflects green and blue wavelengths. Canoeing on Lake Louise ($150/hour) is expensive but unforgettable. Moraine Lake is even more beautiful — the 'Twenty Dollar View' (it appeared on the back of the Canadian $20 bill in 1969-1979), best seen from the Rockpile trail (easy 15-minute walk). The Icefields Parkway (Highway 93) is one of the world's most scenic drives — 144 miles from Banff to Jasper, passing the Columbia Icefield (Athabasca Glacier, accessible by Ice Explorer vehicle), Peyto Lake (wolf-head shape), and Bow Lake. Banff Town is a mountain resort town with hotels, restaurants, and the Banff Gondola (Sulphur Mountain, 2,281 meters). Wildlife is everywhere — elk graze in town, bighorn sheep stand on cliffs, grizzly bears are seen from the Parkway, and wolves and moose are in the valleys.",
    experiences: [
      'Lake Louise canoe sunrise',
      'Moraine Lake Rockpile hike',
      'Icefields Parkway drive',
      'Athabasca Glacier Ice Explorer',
      'Banff Gondola sunset',
      'Banff Upper Hot Springs',
    ],
    camps: ['Fairmont Chateau Lake Louise', 'Fairmont Banff Springs', 'Moraine Lake Lodge', 'Post Hotel & Spa', 'The Rimrock'],
    unesco: true,
  },
  {
    slug: 'jasper',
    name: 'Jasper National Park',
    country: 'Canada',
    region: 'Canada',
    tagline: 'The Wild Heart of the Rockies',
    gradient: 'linear-gradient(160deg,#001c14,#002c1e,#004028)',
    image: '/images/americas/jasper.jpg',
    highlights: ['Maligne Lake', 'Spirit Island', 'Athabasca Falls', 'Jasper SkyTram', 'Dark Sky Preserve', 'Whistlers Mountain'],
    bestTime: 'Jun–Sep',
    duration: '3–5 nights',
    from: '$450',
    description: "Jasper National Park is the largest park in the Canadian Rockies (4,200 square miles) — wilder and less crowded than Banff, with equally spectacular scenery. Maligne Lake is the second-largest glacier-fed lake in the world, with Spirit Island at its end — the 90-minute boat tour is the only way to reach the island (reserve ahead). Maligne Canyon is a limestone gorge with six bridges crossing it, waterfalls, and fossils in the rock (you can see ammonites and marine reptiles from 100 million years ago). Athabasca Falls is a 75-foot waterfall where the Athabasca River has carved a canyon through quartzite — the most powerful falls in the park. The Jasper SkyTram is Canada's highest and longest aerial tramway (2,263 meters at the top, 7-minute ride), with a 1.5-hour hike to the summit of Whistlers Mountain (2,464 meters) for 360-degree views. Jasper is a Dark Sky Preserve — the second-largest in the world, with no light pollution, perfect for stargazing (the Milky Way is visible on moonless nights). Wildlife is more visible here than in Banff — caribou, moose, elk, bighorn sheep, mountain goats, black bears, grizzlies, and wolves.",
    experiences: [
      'Maligne Lake boat to Spirit Island',
      'Maligne Canyon bridge walk',
      'Athabasca Falls power',
      'Jasper SkyTram to Whistlers',
      'Dark Sky Preserve stargazing',
      'Wildlife spotting Pyramid Lake',
    ],
    camps: ['Fairmont Jasper Park Lodge', 'Maligne Lodge', 'Pyramid Lake Resort', 'Tonquin Inn', 'Alpine Village'],
    unesco: true,
  },
  {
    slug: 'vancouver',
    name: 'Vancouver',
    country: 'Canada',
    region: 'Canada',
    tagline: 'The City of Glass',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/americas/vancouver.jpg',
    highlights: ['Stanley Park', 'Granville Island', 'Grouse Mountain', 'Capilano Bridge', 'Gastown', 'Whistler Day Trip'],
    bestTime: 'May–Sep',
    duration: '4–6 nights',
    from: '$390',
    description: "Vancouver is Canada's most beautiful city — surrounded by mountains (Grouse, Cypress, Seymour) and the Pacific Ocean, with a 1,000-acre urban park, a working harbor, and a skyline of glass condos (the 'City of Glass'). Stanley Park is a 1,000-acre rainforest on a peninsula — the 5.5-mile seawall path is Vancouver's most popular activity (walk, bike, rollerblade), with views of downtown, the North Shore mountains, and cruise ships. Granville Island is a former industrial area turned food market — the Public Market has fresh salmon, oysters, cheese, bread, and produce, plus artisan studios and a brewery. Grouse Mountain ('The Peak of Vancouver') is a 15-minute gondola ride from the city to 1,200 meters — the Grizzly Bear Habitat has rescued orphaned bears (Coola and Grinder), and the Lumberjack Show is corny but fun. Capilano Suspension Bridge is a 450-foot-long, 230-foot-high bridge across a river canyon — touristy but spectacular (book online to save time). Gastown is Vancouver's oldest neighborhood — cobblestone streets, the Steam Clock (whistles every 15 minutes), and excellent restaurants. Whistler (90 minutes north) is North America's largest ski resort (summer hiking and mountain biking) and was the host of the 2010 Winter Olympics.",
    experiences: [
      'Stanley Park seawall walk',
      'Granville Island Market food tour',
      'Grouse Mountain gondola',
      'Capilano Bridge cliffwalk',
      'Gastown Steam Clock',
      'Whistler Olympic village',
    ],
    camps: ['Fairmont Pacific Rim', 'Rosewood Hotel Georgia', 'Shangri-La Vancouver', 'The Wedgewood', 'Loden Hotel'],
    unesco: false,
  },
  {
    slug: 'quebec-city',
    name: 'Quebec City',
    country: 'Canada',
    region: 'Canada',
    tagline: 'A Taste of Europe in North America',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/americas/quebec.jpg',
    highlights: ['Old Quebec', 'Château Frontenac', 'Plains of Abraham', 'Montmorency Falls', 'Citadelle', 'Petit Champlain'],
    bestTime: 'May–Oct',
    duration: '3–5 nights',
    from: '$320',
    description: "Quebec City is the only walled city in North America north of Mexico — a UNESCO World Heritage site of cobblestone streets, stone buildings, and French-speaking charm that feels like Europe. Old Quebec is divided into the Upper Town (Haute-Ville) on the cliff and the Lower Town (Basse-Ville) by the river. The Château Frontenac is the most photographed hotel in the world — a 1893 railway hotel that dominates the skyline, offering tours of its grand lobby and history. The Plains of Abraham (2.5 square miles) are the site of the 1759 battle between British General Wolfe and French General Montcalm, which decided the fate of Canada — the park is now a National Historic Site with cannons and interpretive trails. Montmorency Falls (275 feet, 100 feet higher than Niagara Falls) is 15 minutes from the city — take the cable car to the top, walk the suspension bridge over the falls, or climb the 487 steps. The Citadelle (built 1820) is a star-shaped fortress on the city's highest point — the changing of the guard (June-August) and a museum of the Royal 22e Régiment. Quartier Petit Champlain is the city's oldest commercial district — narrow streets, craft shops, and restaurants serving poutine (fries, cheese curds, gravy), tourtière (meat pie), and maple everything.",
    experiences: [
      'Old Quebec walls walk',
      'Château Frontenac lobby tour',
      'Plains of Abraham battlefield',
      'Montmorency Falls cable car',
      'Citadelle guard ceremony',
      'Petit Champlain maple taffy',
    ],
    camps: ['Fairmont Château Frontenac', 'Auberge Saint-Antoine', 'Hôtel de Glace', 'Le Capitole Hotel', 'Monsieur Jean'],
    unesco: true,
  },
  {
    slug: 'toronto',
    name: 'Toronto',
    country: 'Canada',
    region: 'Canada',
    tagline: 'The Most Multicultural City on Earth',
    gradient: 'linear-gradient(160deg,#0a0a15,#1a1a2e,#16213e)',
    image: '/images/americas/toronto.jpg',
    highlights: ['CN Tower', 'Niagara Falls Day Trip', 'Royal Ontario Museum', 'St Lawrence Market', 'Distillery District', 'Ripley\'s Aquarium'],
    bestTime: 'May–Oct',
    duration: '3–5 nights',
    from: '$340',
    description: "Toronto is Canada's largest city and one of the most multicultural cities on earth (over 200 ethnicities, 180 languages). The CN Tower is a 553-meter concrete communications tower (the world's tallest from 1976-2010) — the glass floor (113 stories) is terrifying, the EdgeWalk (outdoors, no railing) is for adrenaline junkies. Niagara Falls is 90 minutes from Toronto — Horseshoe Falls is the largest of the three waterfalls (188 feet high, 2,600 feet wide), with boat tours (Journey Behind the Falls, Hornblower), a casino, and the tacky Clifton Hill (wax museums, haunted houses). The Royal Ontario Museum (ROM) is the largest museum in Canada — dinosaur skeletons (the new Bat Cave), Chinese art (the Ming Tomb), and the Samuel European Galleries. St. Lawrence Market is a 19th-century market with 120 vendors — the 'World's Best Market' by National Geographic, famous for the peameal bacon sandwich at Carousel Bakery. The Distillery District is a pedestrian-only village of Victorian industrial buildings turned into art galleries, craft distilleries (Spirit of York), and restaurants (El Catrin for Mexican, Cluny for French).",
    experiences: [
      'CN Tower glass floor',
      'Niagara Falls day trip',
      'ROM dinosaur gallery',
      'St Lawrence peameal bacon',
      'Distillery District walking tour',
      'Ripley\'s Aquarium jellyfish',
    ],
    camps: ['Four Seasons Toronto', 'The Ritz-Carlton', 'Shangri-La Toronto', 'Trump International', 'Hotel X Toronto'],
    unesco: false,
  },
  {
    slug: 'whistler',
    name: 'Whistler',
    country: 'Canada',
    region: 'Canada',
    tagline: 'North America\'s Largest Ski Resort',
    gradient: 'linear-gradient(160deg,#001c14,#002c1e,#004028)',
    image: '/images/americas/whistler.jpg',
    highlights: ['Peak 2 Peak Gondola', 'Whistler Blackcomb', 'Skiing', 'Mountain Biking', 'Whistler Village', 'Scandinave Spa'],
    bestTime: 'Dec–Mar (Ski) · Jun–Sep (Hike/Bike)',
    duration: '4–6 nights',
    from: '$580',
    description: "Whistler is North America's largest ski resort — two mountains (Whistler and Blackcomb), 8,171 acres of skiable terrain, 16 alpine bowls, 200+ marked trails, and 37 lifts, including the record-breaking Peak 2 Peak Gondola (2.7 miles long, 1,427 feet high, 3 world records). The Peak 2 Peak connects Whistler and Blackcomb at the top — the glass-floor cars (15 of 34) are terrifying and exhilarating. Ski season runs November to May — Whistler is known for its long runs (7 miles from the peak to the base) and the 'firn' (snow that stays icy all day). Mountain biking in summer — the bike park has 70 trails (green to double black), with lift-accessed downhill riding (flow trails like Crank It Up, technical trails like Dirt Merchant). Whistler Village is a pedestrian-only village of hotels, restaurants, and gear shops — the apres-ski scene is legendary (Merlin's for live music, Longhorn for sun patio, Garibaldi Lift Company for cheap beer). Scandinave Spa is a Scandinavian-style spa with outdoor hot pools (100-104°F), cold plunges (56°F), and quiet lounges (no talking, no phones) — the best way to recover after skiing.",
    experiences: [
      'Peak 2 Peak glass-floor gondola',
      'Whistler Blackcomb skiing',
      'Summer mountain biking',
      'Whistler Village apres-ski',
      'Scandinave Spa silence',
      'Vallea Lumina night walk',
    ],
    camps: ['Fairmont Chateau Whistler', 'Four Seasons Whistler', 'Nita Lake Lodge', 'The Westin Whistler', 'Pan Pacific Whistler'],
    unesco: false,
  },
]