export const caribbeanDestinations = [
  {
    slug: 'cuba-havana',
    name: 'Havana',
    country: 'Cuba',
    region: 'Caribbean',
    tagline: 'Frozen in the Most Beautiful Possible Moment',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/americas/havana.jpg',
    highlights: ['Old Havana', 'Malecón', 'Classic Cars', 'Live Salsa', 'Viñales Valley', 'Mojitos'],
    bestTime: 'Nov–Apr',
    duration: '5–7 nights',
    from: '$460',
    description: "Havana is unlike anywhere else on earth — a city of crumbling baroque grandeur, 1950s American cars polished to a shine, salsa spilling from every doorway, and a warmth of spirit that no embargo has diminished. Old Havana (Habana Vieja) is a UNESCO World Heritage site — 1,000 buildings of Spanish colonial architecture, including the Plaza Vieja (the most beautiful square), the Cathedral (baroque with two unequal towers), and the Castillo del Morro (the 16th-century fortress guarding the harbor). The Malecón is a 5-mile seawall promenade — the social heart of Havana, where families fish, couples kiss, and teenagers jump into the waves (the sunsets are spectacular). Classic American cars (from the 1950s) are everywhere — Chevrolets, Fords, Plymouths, Cadillacs, kept running by the ingenuity of Cuban mechanics (who can fix anything with parts from washing machines). A convertible classic car tour ($30-50 per hour) is essential. Salsa music is the soul of Havana — the Buena Vista Social Club (named after the famous 1996 album) still performs, and Casa de la Música (Miramar) has live salsa bands every night (Cubans dance better than anyone). Viñales Valley (a 3-hour drive west) is a UNESCO World Heritage site of limestone mogotes (rounded hills), tobacco farms (the best cigars in the world, rolled on the thighs of Cuban women), and the largest cave system in Cuba (Cueva del Indio). Mojitos (rum, mint, lime, sugar, soda water) are the national drink — La Bodeguita del Medio (Ernest Hemingway's favorite bar) makes the most famous version ($5).",
    experiences: [
      'Old Havana walking tour',
      'Malecón sunset waves',
      'Classic car convertible',
      'Buena Vista Social Club',
      'Viñales tobacco farm',
      'La Bodeguita mojito',
    ],
    camps: ['Hotel Nacional de Cuba', 'Iberostar Parque Central', 'Melia Cohiba', 'Gran Hotel Manzana Kempinski', 'El Almendares'],
    unesco: true,
  },
  {
    slug: 'dominican-republic',
    name: 'Punta Cana',
    country: 'Dominican Republic',
    region: 'Caribbean',
    tagline: 'The All-Inclusive Capital',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/americas/punta-cana.jpg',
    highlights: ['Bávaro Beach', 'Saona Island', 'Hoyo Azul', 'Zip-lining', 'Dune Buggy', 'Santo Domingo Day Trip'],
    bestTime: 'Dec–Apr',
    duration: '5–7 nights',
    from: '$380',
    description: "Punta Cana is the all-inclusive capital of the Caribbean — 30 miles of white-sand beach, 50 all-inclusive resorts, and the Dominican Republic's busiest airport. Bávaro Beach is the most beautiful beach — powder-white sand, palm trees bent by trade winds, and water so clear you can see starfish 10 feet down. Saona Island (Isla Saona) is a 1-hour catamaran ride from Punta Cana — a national park of untouched beaches, blue lagoons, and starfish pools (the best Instagram spot in the DR). The boat trip includes open bar, lunch, and a visit to the natural swimming pool (waist-deep water in the middle of the sea). Hoyo Azul (Blue Hole) is a 100-foot deep cenote (sinkhole) at the base of a 250-foot limestone cliff — the water is electric blue from mineral content, and you can swim (the water is cold, 72°F). Zip-lining at Scape Park (12 lines, the longest 2,400 feet) is the best in the Dominican Republic — the last line ends in a plunge pool. Dune buggies (Buggies) are a 4-hour tour through the countryside — you drive your own 4x4 buggy through mud, rivers, and sugarcane fields (prepare to get filthy). Santo Domingo (2 hours west) is the oldest continuously inhabited European settlement in the Americas (1496) — the Zona Colonial (UNESCO) has the first cathedral (Catedral Primada de América), the first hospital, and the first university in the New World.",
    experiences: [
      'Bávaro Beach swimming',
      'Saona Island catamaran',
      'Hoyo Azul cenote',
      'Zip-lining jungle',
      'Dune buggy mud',
      'Santo Domingo cathedral',
    ],
    camps: ['Eden Roc Cap Cana', 'Zoetry Agua Punta Cana', 'Secrets Cap Cana', 'Finest Punta Cana', 'Hyatt Ziva Cap Cana'],
    unesco: false,
  },
  {
    slug: 'jamaica',
    name: 'Montego Bay',
    country: 'Jamaica',
    region: 'Caribbean',
    tagline: 'Jerk Chicken & Reggae on the Beach',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/americas/montego-bay.jpg',
    highlights: ['Doctor\'s Cave Beach', 'Hip Strip', 'Rose Hall', 'Luminous Lagoon', 'Bob Marley Experience', 'Jerk Chicken'],
    bestTime: 'Dec–Apr',
    duration: '5–7 nights',
    from: '$420',
    description: "Jamaica is the soul of the Caribbean — reggae music, jerk chicken, blue mountains, and a laid-back vibe that says 'don't worry, be happy.' Montego Bay (MoBay) is Jamaica's tourism capital — Doctor's Cave Beach is the most famous beach (clear turquoise water, white sand, and a beach club with bars and restaurants). The Hip Strip (Gloucester Avenue) is the main road for shopping, bars, and restaurants — most famous is Margaritaville (Jimmy Buffett's theme restaurant) with a waterslide from the patio into the ocean. Rose Hall is a 18th-century plantation house with a ghost story — the 'White Witch' (Annie Palmer) allegedly murdered three husbands and countless slaves, and visitors report her ghost roaming the halls. Luminous Lagoon (Glistening Waters) is a bioluminescent bay 30 minutes from Montego Bay — microscopic organisms (dinoflagellates) light up when disturbed, creating a blue glow around your body when swimming at night (the brightest bioluminescence in the Caribbean). Bob Marley Experience (Kingston) is a 3-hour drive from Montego Bay — the Bob Marley Museum is his former home and recording studio (the bedroom where he survived an assassination attempt in 1976). Jerk chicken is Jamaica's signature dish — Scotchies (in Montego Bay) is the most famous jerk shack (chicken, pork, sausage, jerk sauce, festival bread). Appleton Estate (2.5 hours east) is the oldest rum distillery in Jamaica (1749) — tours include tasting of Appleton 21-year (overproof rum is dangerous).",
    experiences: [
      'Doctor\'s Cave Beach day',
      'Hip Strip Margaritaville',
      'Rose Hall ghost tour',
      'Luminous Lagoon night swim',
      'Bob Marley Museum',
      'Scotchies jerk chicken',
    ],
    camps: ['Half Moon Bay', 'Round Hill Hotel', 'Sandals Montego Bay', 'Jewel Grande', 'Jamaica Inn'],
    unesco: false,
  },
  {
    slug: 'puerto-rico',
    name: 'Old San Juan',
    country: 'Puerto Rico',
    region: 'Caribbean',
    tagline: 'The Walled City of the Caribbean',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/americas/san-juan.jpg',
    highlights: ['El Morro', 'San Cristóbal', 'Paseo de la Princesa', 'Calle del Cristo', 'Bacardí Distillery', 'El Yunque'],
    bestTime: 'Dec–Apr',
    duration: '4–6 nights',
    from: '$360',
    description: "Old San Juan is a 500-year-old walled city — a UNESCO World Heritage site of cobblestone streets (the blue cobblestones were cast from iron furnace slag), pastel-colored buildings, and two massive Spanish fortresses. El Morro (Castillo San Felipe del Morro) is the most famous fortress — built 1539-1787, 6 levels, 140-foot walls, and a lighthouse (built 1908) at the tip of the peninsula. The view from the fort over the bay is spectacular — look for the Puerto Rican flag flying (the largest flag in the Caribbean). San Cristóbal is the largest Spanish fort built in the New World (built 1634-1790) — it has a 5-level dungeon and a 360-degree view of the city. Paseo de la Princesa is a 19th-century promenade along the city walls — the Raíces Fountain (Fuente Raíces) has sculptures representing Puerto Rico's Taino, African, and Spanish heritage. Calle del Cristo is a pedestrian street lined with shops, restaurants, and the San Juan Cathedral (the second-oldest cathedral in the Americas, built 1540). Bacardí Distillery (Casa Bacardi) is a 15-minute ferry ride from Old San Juan — the world's largest rum distillery, with tours and tastings of Bacardi Superior (white) and Bacardi Oakheart (spiced). El Yunque National Forest is a 45-minute drive from San Juan — the only tropical rainforest in the US National Forest System, with 240 species of trees, 200 feet of annual rainfall, and La Mina Falls (a 50-foot waterfall you can swim in).",
    experiences: [
      'El Morro lighthouse',
      'San Cristóbal dungeon',
      'Paseo de la Princesa',
      'Calle del Cristo shops',
      'Bacardi distillery tour',
      'El Yunque La Mina Falls',
    ],
    camps: ['El Convento Hotel', 'Condado Vanderbilt', 'La Concha Renaissance', 'The Ritz-Carlton San Juan', 'Hotel El Convento'],
    unesco: true,
  },
]