export const centralAmericaDestinations = [
  {
    slug: 'costa-rica',
    name: 'Costa Rica',
    country: 'Costa Rica',
    region: 'Central America',
    tagline: 'Pura Vida — The World\'s Best Eco-Tourism',
    gradient: 'linear-gradient(160deg,#001c10,#002c1a,#003c22)',
    image: '/images/americas/costa-rica.jpg',
    highlights: ['Arenal Volcano', 'Manuel Antonio', 'Monteverde', 'Tortuguero', 'Zip-lining', 'Hot Springs'],
    bestTime: 'Dec–Apr',
    duration: '7–10 nights',
    from: '$420',
    description: "Costa Rica perfected the art of eco-tourism — a country the size of West Virginia that contains 5% of the world's biodiversity, with active volcanoes, cloud forests, Pacific and Caribbean beaches, and wildlife so accessible it is almost absurd. Arenal Volcano is Costa Rica's most iconic landmark — an almost-perfect cone that erupted constantly from 1968-2010 (now quiet enough to hike). The Arenal Observatory Lodge is built on the old lava flow (you can see the 1968 eruption site). Monteverde Cloud Forest is the most magical ecosystem — the Sky Walk (8 suspension bridges through the canopy) offers the best views, and the Zip Lines (the longest in Costa Rica, 5,000 feet) are the most thrilling. The Resplendent Quetzal (the sacred bird of the Maya and Aztec) is found only in this forest (March-July). Manuel Antonio National Park is Costa Rica's most beautiful beach — white sand, turquoise water, and monkey-filled forest meeting the sea. The park is small (5 square miles) but has 3 beaches, 109 mammal species, and 184 bird species (the best guide is a local, tip $20). Tortuguero National Park is the most important turtle nesting site in the Caribbean (July-October) — four species of sea turtles (green, hawksbill, leatherback, loggerhead) lay eggs on the black sand beach at night (guided tours only).",
    experiences: [
      'Arenal hot springs',
      'Monteverde cloud forest zip-line',
      'Manuel Antonio monkey beach',
      'Tortuguero turtle nesting',
      'White water rafting Pacuare',
      'Sloth sanctuary (Limon)',
    ],
    camps: ['Nayara Springs', 'Tabacón Thermal Resort', 'El Silencio Lodge', 'Andaz Costa Rica', 'Four Seasons Costa Rica'],
    unesco: false,
  },
  {
    slug: 'panama',
    name: 'Panama Canal',
    country: 'Panama',
    region: 'Central America',
    tagline: 'The 50-Mile Shortcut Between Oceans',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/americas/panama.jpg',
    highlights: ['Panama Canal', 'Miraflores Locks', 'Casco Viejo', 'Bocas del Toro', 'San Blas Islands', 'Rainforest'],
    bestTime: 'Dec–Apr',
    duration: '5–7 nights',
    from: '$380',
    description: "The Panama Canal is a 50-mile shortcut between the Atlantic and Pacific Oceans — one of the greatest engineering achievements in human history, completed by the US in 1914 (after France tried and failed). Miraflores Locks is the best place to see ships pass — the visitor center has a museum, a 3D movie, and a viewing platform just feet from the locks (the ships are lifted 54 feet in three stages). Miraflores is busy from 9 am-11 am and 3 pm-5 pm (the best time to see ships is 10 am and 4 pm). Casco Viejo is Panama City's historic district — a UNESCO World Heritage site of Spanish colonial architecture, rooftop bars (the view of the city skyline at sunset), and French embassy (the building where France planned the canal). Bocas del Toro is an archipelago on the Caribbean side — the main town (Bocas Town) has colorful wooden houses built on stilts over the water, and Starfleet Beach (the most beautiful) is a 20-minute water taxi away. San Blas Islands (Guna Yala) is an autonomous territory of the Guna indigenous people — 365 islands (one for each day of the year), many with a single family and a few palm trees. The Guna women still wear mola blouses (reverse-applique embroidery) and control their own tourism (you must book through a Guna-owned agency).",
    experiences: [
      'Miraflores Locks ship watching',
      'Casco Viejo rooftop sunset',
      'Bocas del Toro water taxi',
      'San Blas island overnight',
      'Rainforest zip-line (Gamboa)',
      'Emberá village visit',
    ],
    camps: ['American Trade Hotel', 'Sofitel Legend Casco Viejo', 'Tantalo Hotel', 'Bocas del Toro Resort', 'San Blas Island Cabins'],
    unesco: true,
  },
  {
    slug: 'tikal',
    name: 'Tikal',
    country: 'Guatemala',
    region: 'Central America',
    tagline: 'The Lost Mayan Empire',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/americas/tikal.jpg',
    highlights: ['Temple IV', 'Temple I', 'Lost World', 'Plaza of Seven Temples', 'Monkey Howl', 'Sunrise'],
    bestTime: 'Nov–Apr',
    duration: '2–3 nights',
    from: '$420',
    description: "Tikal is the most spectacular Mayan site in Central America — a 222-square-mile city in the middle of the Guatemalan jungle, with 3,000+ structures (only 5% excavated), 90-foot temples, and howler monkeys screaming in the canopy. Temple IV (the tallest at 212 feet) is the best viewpoint — climb the wooden stairs (a 45-minute hike) to see the jungle poking through the top of the other temples (Temple I, Temple II, Temple III). Temple I (the Temple of the Grand Jaguar) is 145 feet tall and covers the tomb of Jasaw Chan K'awiil (the king who conquered Calakmul in 695 AD). You can see the roof comb from the Great Plaza. The Lost World (Mundo Perdido) is the oldest complex in Tikal (700 BC) — the pyramid is 100 feet tall, and a small museum explains the history of the site. The Plaza of Seven Temples (a smaller complex) is the best place to hear howler monkeys at dawn — the monkeys are loud, and their call echoes through the jungle for miles. Sunrise (5-6 am) is the best time to visit — the park opens at 4 am for the sunrise tour (book ahead), and the jungle is waking up with birds, monkeys, and cooler temperatures. The site is 1.5 hours by road from Flores (the nearest town) — stay overnight in Flores or at the Jungle Lodge inside the park.",
    experiences: [
      'Temple IV sunrise',
      'Great Plaza Temple I',
      'Lost World pyramid',
      'Howler monkey dawn',
      'Jungle night walk',
      'Sunset at Temple III',
    ],
    camps: ['Jungle Lodge Tikal', 'Hotel Tikal Inn', 'Flores Island Hotel', 'Las Lagunas Boutique Hotel', 'Maya Tikal Hostel'],
    unesco: true,
  },
]