export const colombiaDestinations = [
  {
    slug: 'cartagena',
    name: 'Cartagena',
    country: 'Colombia',
    region: 'Colombia',
    tagline: 'The Jewel of the Caribbean Coast',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/americas/cartagena.jpg',
    highlights: ['Walled City', 'Rosario Islands', 'Getsemaní', 'Street Food', 'La Popa Hill', 'San Felipe Castle'],
    bestTime: 'Dec–Apr',
    duration: '4–6 nights',
    from: '$340',
    description: "Cartagena is Colombia's most seductive city — a perfectly preserved 16th-century walled city of colorful colonial architecture, bougainvillea-draped balconies, Caribbean beaches, and one of South America's most vibrant food scenes. The Walled City (Ciudad Amurallada) is a UNESCO World Heritage site — 13 kilometers of stone walls (built 1586-1796) enclose a maze of cobblestone streets, churches, and plazas, including Plaza de los Coches (the entrance under the Clock Tower), Plaza de la Aduana (the largest), and Plaza Santo Domingo (with Botero's 'Gorda' sculpture). Getsemaní is the bohemian neighborhood outside the walls — the most authentic area of Cartagena, where Calle del Arsenal has 8 painted doors representing different parts of Colombian culture (flowers, coffee, vallenato music). Rosario Islands (Islas del Rosario) are a 1-hour boat ride from Cartagena — a national park of 27 coral islands with crystal-clear water, perfect for snorkeling and beach clubs (book a tour, don't take a private boat). Street food (and food in general) is excellent — arepas (corn cakes with cheese), patacones (fried green plantains), ceviche, and Colombian coffee. La Popa Hill is the highest point in Cartagena (500 feet) — the monastery at the top has views of the entire city and bay (take a taxi, don't walk the dangerous road).",
    experiences: [
      'Walled City alley photography',
      'Getsemaní street art',
      'Rosario Islands snorkel',
      'Clock Tower arepas',
      'La Popa Hill view',
      'San Felipe Castle dungeon',
    ],
    camps: ['Sofitel Legend Santa Clara', 'Casa San Agustín', 'Tcherassi Hotel', 'Charleston Santa Teresa', 'Bastión Luxury Hotel'],
    unesco: true,
  },
  {
    slug: 'medellin',
    name: 'Medellín',
    country: 'Colombia',
    region: 'Colombia',
    tagline: 'The City of Eternal Spring',
    gradient: 'linear-gradient(160deg,#001c10,#002c1a,#003c22)',
    image: '/images/americas/medellin.jpg',
    highlights: ['Comuna 13', 'Metrocable', 'Plaza Botero', 'Pueblito Paisa', 'Guatapé', 'Nightlife'],
    bestTime: 'Jan–Mar · Jul–Sep',
    duration: '4–6 nights',
    from: '$320',
    description: "Medellín is the most transformed city in the world — from the murder capital of the world (1990s) to a model of urban innovation, winning the Lee Kuan Yew World City Prize (2018). Comuna 13 is the most famous transformation story — a hillside neighborhood once controlled by cartels and gangs, now transformed by graffiti, outdoor escalators (6 sections, 1,200 feet of vertical gain), and community tourism. The graffiti tour (free, tip-based) explains how art replaced violence, with new murals added every month. Metrocable is Medellín's cable car system (built 2004) connecting the poor hillside neighborhoods to the metro — Line K (Santo Domingo) is the most scenic, with views over the entire Aburrá Valley (18 miles of urban sprawl). Plaza Botero is the city's main square — 23 bronze sculptures by Fernando Botero (the Colombian artist known for giant bodies) surround the Rafael Uribe Palace of Culture. Guatapé is a 2-hour drive from Medellín — the Piedra del Peñol (El Peñol Rock) is a 650-foot granite monolith with 740 stairs to the top, offering a 360-degree view of 1,000 man-made islands (the reservoir flooded a valley in the 1970s). Guatapé town is famous for the zócalos (colored bas-relief panels on the lower half of every building). Nightlife in Medellín is famous — El Poblado district has hundreds of restaurants, bars, and clubs (street food after 11 pm, dancing until dawn).",
    experiences: [
      'Comuna 13 graffiti tour',
      'Metrocable Santo Domingo',
      'Plaza Botero sculpture',
      'Guatapé rock climb',
      'Zócalos photo walk',
      'El Poblado nightlife',
    ],
    camps: ['Charlee Hotel', 'Click Clack Hotel', 'The Wandering Paisa', 'Patio del Mundo', 'Sites Hotel'],
    unesco: false,
  },
  {
    slug: 'coffee-region',
    name: 'Coffee Region',
    country: 'Colombia',
    region: 'Colombia',
    tagline: 'Eje Cafetero',
    gradient: 'linear-gradient(160deg,#001c14,#002c1e,#004028)',
    image: '/images/americas/coffee-region.jpg',
    highlights: ['Coffee Finca', 'Valle del Cocora', 'Wax Palms', 'Salento', 'Filandia', 'Jeep Willys'],
    bestTime: 'Dec–Feb · Jul–Aug',
    duration: '4–6 nights',
    from: '$350',
    description: "Colombia's Coffee Region (Eje Cafetero) is a UNESCO World Heritage site of rolling green hills, bamboo forests, and the world's best Arabica coffee. Coffee fincas (farms) are everywhere — the best tour is Finca El Ocaso (Salento) or Hacienda Venecia (Manizales), where you walk through the plantation, pick coffee cherries, process the beans, and taste the result (90% of Colombian coffee is exported, so locals drink lower-quality 'tinto' in cafes). Valle del Cocora (Cocora Valley) is the most beautiful landscape in Colombia — a green valley of 200-foot wax palms (the national tree of Colombia), the tallest palm species in the world (grows 1 meter per year). The classic 3-4 hour loop hike starts in the valley, goes into the cloud forest (suspension bridges, hummingbirds), and returns through the palm field (the last section is the most spectacular). Salento is the main town for the valley — a colorful hill town (all houses painted with bright doors and balconies) with a main square, coffee shops, and a hill viewpoint (Alto de la Cruz). Filandia is a smaller, quieter version of Salento — the main square is less touristy, the Colina Iluminada viewpoint has a 100-foot observation tower, and Helena Adentro is the best restaurant in the region (farm-to-table). Jeep Willys (the iconic American military jeep from WWII) are the region's main transportation — you'll see them everywhere, and you can ride one to the Valle del Cocora (the 15-minute trip from Salento).",
    experiences: [
      'Coffee finca tour & tasting',
      'Valle del Cocora hike',
      'Wax palm photography',
      'Salento colorful town',
      'Filandia observation tower',
      'Jeep Willys ride',
    ],
    camps: ['Hotel Salento Real', 'Ecohabs Bambú', 'Sazagua Hotel', 'La Divisa Glamping', 'Finca El Ocaso'],
    unesco: true,
  },
  {
    slug: 'bogota',
    name: 'Bogotá',
    country: 'Colombia',
    region: 'Colombia',
    tagline: 'The World\'s Largest City at 8,600 Feet',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/americas/bogota.jpg',
    highlights: ['Gold Museum', 'Monserrate', 'La Candelaria', 'Botero Museum', 'Graffiti Tour', 'Salt Cathedral'],
    bestTime: 'Dec–Mar · Jul–Aug',
    duration: '3–5 nights',
    from: '$300',
    description: "Bogotá is the highest capital city in South America (8,600 feet) — a sprawling metropolis of 8 million people, with a colonial center, modern towers, and a cable car to the top of the mountain overlooking the city. The Gold Museum (Museo del Oro) is the best museum in South America — 55,000 pieces of pre-Columbian gold (the most famous is the Muisca Raft, a gold model of the El Dorado ceremony), and the ground floor has a video explaining how the Muisca covered their chief in gold dust before throwing himself into Lake Guatavita (the El Dorado legend). Monserrate is a 10,300-foot mountain in the middle of the city — ride the funicular (built 1929) or cable car (1955) to the top for the best view of the city (smog can be bad, best views after rain or early morning). The church at the top (17th century) has a statue of the Virgin of Monserrate. La Candelaria is the historic center — the Bolívar Square (Plaza de Bolívar) is the main plaza, with the Cathedral, the Capitol, and the Palace of Justice (toured by drug traffickers in 1985). Botero Museum (Museo Botero) is in a 16th-century mansion — 123 paintings and sculptures by Fernando Botero (Colombia's most famous artist), including his version of the Mona Lisa (inflated). Graffiti tours (free, tip-based) are excellent — La Candelaria walls are covered in political and cultural street art, and the tour explains Colombia's complicated history. The Salt Cathedral (Catedral de Sal) is a 2-hour drive from Bogotá — a cathedral built inside a salt mine (the world's first, the 180-meter tunnel is carved with a cross).",
    experiences: [
      'Gold Museum Muisca Raft',
      'Monserrate cable car',
      'La Candelaria walking tour',
      'Botero Museum Mona Lisa',
      'Graffiti tour (tip-based)',
      'Salt Cathedral tunnel',
    ],
    camps: ['Four Seasons Casa Medina', 'W Bogotá', 'Hotel de la Opera', 'B.O.G. Hotel', 'Click Clack Hotel'],
    unesco: false,
  },
]