export const ecuadorGalapagosDestinations = [
  {
    slug: 'galapagos',
    name: 'Galápagos Islands',
    country: 'Ecuador',
    region: 'Galápagos',
    tagline: 'Darwin\'s Laboratory — Still Running',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/americas/galapagos.jpg',
    highlights: ['Giant Tortoises', 'Marine Iguanas', 'Blue-Footed Boobies', 'Sea Lions', 'Snorkelling', 'Darwin\'s Finches'],
    bestTime: 'Jun–Nov (Diving) · Dec–May (Warm Water)',
    duration: '7–10 nights',
    from: '$2,200',
    description: "The Galápagos Islands are the world's most extraordinary wildlife destination — a volcanic archipelago 600 miles off Ecuador's coast, where animals have no natural predators and never learned to fear humans, allowing you to walk among giant tortoises, swim with sea lions, and step over marine iguanas. Giant tortoises (the archipelago's namesake) are the most iconic species — the 'galápago' is the Spanish word for tortoise, and their shells evolved into saddle-shape on islands with low vegetation (they stretch their necks to eat) or dome-shape on islands with high vegetation (they eat from the ground). Charles Darwin's visit in 1835 (HMS Beagle) changed biology forever — he was most influenced by the mockingbirds (different beaks on different islands) and finches (14 species with different beaks for different foods), leading to his theory of natural selection. Marine iguanas are the world's only sea-going lizards — they dive 30 feet to eat algae, sneeze salt water through their noses (the 'snorting' sound is salt expulsion), and bask in piles on black lava rocks. Blue-footed boobies are the most famous bird — their mating dance involves the male showing off his bright blue feet (the bluer the feet, the more attractive the mate). Sea lions are everywhere — on beaches, park benches, and docks (they are as curious about you as you are about them, keep 6 feet distance for your safety). Snorkeling is world-class — sea turtles, rays, white-tipped reef sharks, and penguins (the only penguin species north of the equator, the Galápagos penguin) are common sights. The Galápagos National Park charges $100 entry fee (cash only) and requires a certified guide for most sites — book through a licensed tour operator.",
    experiences: [
      'Giant tortoise reserve visit',
      'Marine iguana snorkeling',
      'Blue-footed booby dance',
      'Sea lion swimming',
      'Darwin\'s finches observation',
      'Volcanic crater hike',
    ],
    camps: ['Pikaia Lodge', 'Finch Bay Galápagos Hotel', 'Galápagos Safari Camp', 'Royal Palm Galápagos', 'Semilla Verde'],
    unesco: true,
  },
  {
    slug: 'quito',
    name: 'Quito',
    country: 'Ecuador',
    region: 'Ecuador',
    tagline: 'The Highest Capital City in the World',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/americas/quito.jpg',
    highlights: ['Old Town', 'Equator Line', 'TelefériQo', 'Panecillo', 'Plaza Grande', 'Basilica del Voto Nacional'],
    bestTime: 'Jun–Sep',
    duration: '3–5 nights',
    from: '$280',
    description: "Quito is the highest official capital city in the world (9,350 feet) — a UNESCO World Heritage site with the largest and best-preserved historic center in the Americas, stretching 2 miles north to south. The Old Town (Centro Histórico) is a mile-high maze of cobblestone streets, baroque churches, and monasteries — the Plaza Grande (Independence Square) is the center, with the Presidential Palace (changing of the guard on Mondays) and the Cathedral (where Venezuelan independence hero Antonio José de Sucre is buried). The Equator Line (Mitad del Mundo) is 30 minutes north of the city — the monument (100 feet tall) marks the spot where French scientists calculated the equator in 1736. The real equator (GPS-corrected) is 200 meters north at the Intiñán Solar Museum, where you can balance an egg on a nail, watch water drain straight down (no Coriolis effect), and stand with one foot in each hemisphere. TelefériQo is a cable car to Cruz Loma (13,000 feet) — the 2.5-mile ride takes 20 minutes, with views of the city, the Pichincha Volcano, and the Avenue of the Volcanoes (the 300-mile valley of the Andes). The Panecillo (Bread Loaf Hill) is a 660-foot hill in the center of the city — the statue of the Virgin of Quito (a winged Madonna crushing a snake) is a copy (the original is in the monastery of San Agustín). The Basilica del Voto Nacional is the largest neo-Gothic basilica in the Americas — you can climb the towers for views of the city, and gargoyles are replaced with native animals (iguanas, tortoises, Galápagos penguins).",
    experiences: [
      'Old Town walking tour',
      'Equator line egg balance',
      'TelefériQo volcano view',
      'Panecillo Virgin statue',
      'Basilica gargoyle climb',
      'Cuy (guinea pig) tasting',
    ],
    camps: ['Casa Gangotena', 'Hotel Plaza Grande', 'Swissôtel Quito', 'JW Marriott Quito', 'Casa El Edén'],
    unesco: true,
  },
  {
    slug: 'cotopaxi',
    name: 'Cotopaxi Volcano',
    country: 'Ecuador',
    region: 'Ecuador',
    tagline: 'The Highest Active Volcano in the World',
    gradient: 'linear-gradient(160deg,#001c14,#002c1e,#004028)',
    image: '/images/americas/cotopaxi.jpg',
    highlights: ['Cotopaxi Volcano', 'Refugio José Ribas', 'Glacier Hike', 'Laguna Limpiopungo', 'Mountain Biking', 'Condors'],
    bestTime: 'Jun–Sep',
    duration: '1–2 days',
    from: '$220',
    description: "Cotopaxi is the highest active volcano in the world (19,347 feet) — a nearly perfect snow-capped cone, 30 miles south of Quito, visible from the capital on clear days. The volcano has erupted 50 times since 1738 (most recently 2015-2016) — the national park is open year-round, but the last section of road (from the park entrance to the parking lot at 15,000 feet) is sometimes closed due to volcanic activity. The Refugio José Ribas (15,900 feet) is the base camp for climbers — a basic mountain hut (48 beds, $15 per night) where climbers sleep before their summit attempt. The climb from the refugio to the summit (19,347 feet) is a 3,400-foot vertical gain — 3-4 hours up, 2 hours down, on snow and ice, requiring crampons, ice axe, rope, and a certified guide (available in Quito for $200-400). Only 50% of climbers reach the summit — altitude sickness, crevasses, and weather turn most people back. Glacier hiking (no summit) is available for non-climbers — a 2-hour guided walk on the lower glacier (16,000-17,000 feet) with crampons and ice axes, safe and scenic. Laguna Limpiopungo (12,500 feet) is a glacial lake at the park entrance — the 1-hour hike around the lake is the best place to see wild horses, llamas, and (with luck) condors. Mountain biking from the parking lot (15,000 feet) back to the park entrance (12,000 feet) is a 2-hour, 15-mile descent on gravel roads — the best way to see the park without climbing.",
    experiences: [
      'Refugio José Ribas hut',
      'Glacier hike with crampons',
      'Laguna Limpiopungo walk',
      'Mountain bike descent',
      'Condor spotting',
      'Hot chocolate at refugio',
    ],
    camps: ['Tambopaxi Lodge', 'Hacienda El Porvenir', 'Hacienda La Cienega', 'The Secret Garden Cotopaxi', 'Chilcabamba Lodge'],
    unesco: false,
  },
  {
    slug: 'banos',
    name: 'Baños',
    country: 'Ecuador',
    region: 'Ecuador',
    tagline: 'The Adventure Capital of Ecuador',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/americas/banos.jpg',
    highlights: ['Pailón del Diablo', 'Casa del Árbol', 'Hot Springs', 'Ziplining', 'Canyoning', 'Rafting'],
    bestTime: 'Jun–Sep',
    duration: '3–4 nights',
    from: '$220',
    description: "Baños is Ecuador's adventure capital — a small town at 6,000 feet at the foot of the active Tungurahua Volcano, with hot springs, waterfalls, and cheap adrenaline sports. Baños means 'baths' in Spanish — the town was founded around natural hot springs (thermal pools) heated by the volcano, the most famous are La Piscina de la Virgen (the Virgin's Pool) at the edge of the waterfall, and El Salado (the most beautiful, at the base of a canyon). Pailón del Diablo (Devil's Cauldron) is the most spectacular waterfall in Ecuador — a 260-foot waterfall where you walk through the mist and behind the falling water on a narrow trail (waterproof jacket essential). Casa del Árbol (the Treehouse) is a viewpoint with a swingset at the edge of a cliff — the swing is the most Instagrammed spot in Ecuador, with views of the Tungurahua Volcano erupting (you can see smoke and ash from the distance). Ziplining (canopy) is cheap — $10 for 5 lines across a canyon, the longest line is 1,500 feet. Canyoning is descending a waterfall by rope — a 150-foot waterfall jump (optional) is available for the brave. Rafting on the Río Patate (Class III-IV) is a 2-hour trip ($20-30), the best in Ecuador outside the Amazon. Baños is also a center for cycling — rent a mountain bike ($10/day) and ride the Ruta de las Cascadas (Waterfall Route), a 30-mile road that passes 10 waterfalls (the last 5 miles are downhill).",
    experiences: [
      'Pailón del Diablo behind waterfall',
      'Casa del Árbol swing',
      'Hot springs at sunset',
      'Ziplining canyon',
      'Canyoning waterfall jump',
      'Ruta de las Cascadas biking',
    ],
    camps: ['La Casa del Molino', 'Mama Tungu Hostel', 'Casa Abuela', 'Samari Spa Resort', 'Hotel Sangay'],
    unesco: false,
  },
]
