export const mexicoDestinations = [
  {
    slug: 'chichen-itza',
    name: 'Chichen Itza',
    country: 'Mexico',
    region: 'Mexico',
    tagline: 'The Mayan Pyramid of Kukulcán',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/americas/chichen-itza.jpg',
    highlights: ['El Castillo Pyramid', 'Temple of Warriors', 'Great Ball Court', 'Sacred Cenote', 'Ossario Pyramid', 'Equinox Serpent'],
    bestTime: 'Dec–Apr',
    duration: '1–2 nights',
    from: '$280',
    description: "Chichen Itza is the most famous Mayan archaeological site — a UNESCO World Heritage site and one of the New Seven Wonders of the World, on the Yucatán Peninsula. El Castillo (Pyramid of Kukulcán) is a 98-foot, 9-level pyramid built to astronomical precision — on the spring and autumn equinoxes (March 20 and September 22), the sun creates a serpent shadow slithering down the pyramid's staircase. The pyramid has a smaller, older pyramid inside (you can see the entrance). The Temple of Warriors has 200 columns carved with warriors, with Chac Mool (a reclining figure holding a bowl) at the top. The Great Ball Court is the largest in Mesoamerica (545 feet by 225 feet) — the acoustics are so good that a whisper at one end can be heard 500 feet away. The Sacred Cenote (sinkhole) was used for human sacrifice — archaeologists have dredged thousands of jade, gold, and copper objects, plus 100 human remains. The Cenote is 60 meters in diameter, 20 meters down from ground level.",
    experiences: [
      'El Castillo equinox serpent',
      'Great Ball Court clap echo',
      'Temple of Warriors columns',
      'Sacred Cenote sacrifice history',
      'Chichen Itza light show (night)',
      'Ik Kil cenote swim',
    ],
    camps: ['Mayaland Hotel', 'Chichen Itza Hotel', 'Villa Arqueológica', 'The Lodge at Chichen Itza', 'Hotel Oka\'an'],
    unesco: true,
  },
  {
    slug: 'tulum',
    name: 'Tulum',
    country: 'Mexico',
    region: 'Mexico',
    tagline: 'Mayan Ruins Overlooking the Caribbean',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/americas/tulum.jpg',
    highlights: ['Cliffside Ruins', 'Gran Palacio', 'Templo del Dios Descendente', 'Tulum Beach', 'Coba Day Trip', 'Cenotes'],
    bestTime: 'Dec–Apr',
    duration: '3–5 nights',
    from: '$380',
    description: "Tulum is the only Mayan city built on the coast — a 13th-century walled city on 40-foot cliffs above the Caribbean Sea, with views that justify the entrance fee. The ruins are smaller than Chichen Itza but more photogenic — the Gran Palacio (elite residence), the Templo del Dios Descendente (temple with a diving god), and the El Castillo (watchtower with a lighthouse function for Mayan canoes). The beach below the ruins (Playa Ruinas) is small but you can swim. Tulum town has become a bohemian luxury destination — boutique hotels, yoga retreats, health food cafes, and DJ sets on the beach. Coba (45 minutes inland) is an underrated site — you can climb Nohoch Mul (137 feet, the tallest pyramid in Yucatán), and rent a 'triciclo' (bicycle with a roof) to ride between ruins. The Yucatán's cenotes (sinkholes) are perfect for swimming — Gran Cenote (snorkeling with turtles and fish), Dos Ojos (two connected cenotes for diving), and Ik Kil (near Chichen Itza, with vines hanging to the water).",
    experiences: [
      'Cliffside ruins sunrise',
      'Tulum beach swimming',
      'Coba pyramid climb',
      'Dos Ojos cenote dive',
      'Gran Cenote snorkel',
      'Tulum town dinner (Arca, Hartwood)',
    ],
    camps: ['Azulik Tulum', 'Nomade Tulum', 'Be Tulum', 'Habitas Tulum', 'La Valise Tulum'],
    unesco: true,
  },
  {
    slug: 'mexico-city',
    name: 'Mexico City',
    country: 'Mexico',
    region: 'Mexico',
    tagline: 'The Distrito Federal',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/americas/mexico-city.jpg',
    highlights: ['Teotihuacan', 'Zocalo', 'Frida Kahlo Museum', 'Chapultepec Park', 'Palacio de Bellas Artes', 'Lucha Libre'],
    bestTime: 'Mar–May · Oct–Nov',
    duration: '4–6 nights',
    from: '$340',
    description: "Mexico City (CDMX) is the capital of New Spain — a 21-million-person megalopolis built on the ruins of the Aztec capital Tenochtitlan, with more museums than any other city in the world (over 150). Teotihuacan ('the place where gods were created') is a 20-mile, 2,000-year-old city north of the city — the Pyramid of the Sun (246 feet, 2.5 million tons of stone) and Pyramid of the Moon (150 feet) are the highlights (climb both), and the Temple of Quetzalcoatl has feathered serpent heads. The Zócalo (Plaza de la Constitución) is the third-largest square in the world — the Metropolitan Cathedral (built 1573, 500 tons of gold inside) and the National Palace (murals by Diego Rivera of Mexican history). Frida Kahlo Museum (Casa Azul) is her family home in Coyoacán, preserved with her art, medical corsets, and ashes — book tickets weeks ahead. Chapultepec Park is twice the size of Central Park — the Chapultepec Castle (only royal castle in the Americas), the National Museum of Anthropology (Aztec Sun Stone, Olmec heads, Mayan treasures), and the zoo (panda bears). Lucha Libre is Mexican wrestling — colorful masks, high-flying acrobatics, and the ultimate tourist experience (attend at Arena Mexico on Friday nights).",
    experiences: [
      'Teotihuacan pyramid climb',
      'Zócalo cathedral gold interior',
      'Frida Kahlo Casa Azul',
      'Anthropology Museum Sun Stone',
      'Chapultepec Castle view',
      'Lucha Libre masks',
    ],
    camps: ['Four Seasons Mexico City', 'St. Regis Mexico City', 'Las Alcobas', 'Sofitel Reforma', 'Hotel Condesa DF'],
    unesco: true,
  },
  {
    slug: 'cancun',
    name: 'Cancun & Riviera Maya',
    country: 'Mexico',
    region: 'Mexico',
    tagline: 'Turquoise Caribbean & All-Inclusive Luxury',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/americas/cancun.jpg',
    highlights: ['Hotel Zone', 'Isla Mujeres', 'Xcaret Park', 'Cozumel Diving', 'Playa del Carmen', 'Whale Sharks'],
    bestTime: 'Dec–Apr',
    duration: '5–7 nights',
    from: '$420',
    description: "Cancun is Mexico's most famous beach destination — a 14-mile L-shaped barrier island of all-inclusive resorts, turquoise water, and white sand. The Hotel Zone (Zona Hotelera) is where all the big resorts are located — the water is calmer on the Caribbean side (east) and rougher on the bay side (west). Isla Mujeres ('Island of Women') is a 20-minute ferry ride — rent a golf cart, visit Playa Norte (the island's best beach), see the turtle farm (Tortugranja), and snorkel at El Farito (shallow reef with sea turtles). Xcaret Park (eco-archaeological park) is 40 minutes south — underground rivers, a butterfly pavilion, a coral reef aquarium, and a spectacular evening show (Mexico Espectacular). Cozumel is a 45-minute ferry from Playa del Carmen — the second-largest barrier reef in the world, with diving (Palancar Garden, Santa Rosa Wall) and snorkeling (Chankanaab Lagoon). Whale sharks (the world's largest fish, up to 40 feet, 40,000 pounds) visit Cancun from June to September — swimming with them is a bucket-list experience (book a licensed tour).",
    experiences: [
      'Hotel Zone beach day',
      'Isla Mujeres golf cart',
      'Xcaret underground river',
      'Cozumel Palancar dive',
      'Whale shark snorkel (Jun-Sep)',
      'Playa del Carmen 5th Avenue',
    ],
    camps: ['Nizuc Resort & Spa', 'Rosewood Mayakoba', 'Banyan Tree Mayakoba', 'Grand Velas Riviera Maya', 'Live Aqua Cancun'],
    unesco: false,
  },
  {
    slug: 'guanajuato',
    name: 'Guanajuato',
    country: 'Mexico',
    region: 'Mexico',
    tagline: 'The Most Colorful City in Mexico',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/americas/guanajuato.jpg',
    highlights: ['Alley of the Kiss', 'Mummy Museum', 'Callejón del Beso', 'Teatro Juárez', 'Valenciana Mine', 'Cervantes Festival'],
    bestTime: 'Oct–May',
    duration: '3–4 nights',
    from: '$250',
    description: "Guanajuato is Mexico's most colorful city — a UNESCO World Heritage site of winding alleys, colorful houses stacked on hillsides, underground roads (the city built over a river), and a silver mining history. El Callejón del Beso (Alley of the Kiss) is the city's most famous — the balconies are 69 centimeters apart, and legend says couples who kiss on the third step get 15 years of happiness (on the anniversary of a tragic love story). The Mummy Museum (Museo de las Momias) has 100 naturally preserved bodies from the local cemetery (1840-1950) — they were accidentally mummified by the city's dry soil and mineral-rich water. The Teatro Juárez (1903) is a magnificent theater with a Moorish facade, red velvet interior, and 102 crystal chandeliers. La Valenciana Mine is a silver mine that made the city wealthy in the 18th century — you can tour a section of the mine and see the huge Templo de San Cayetano (built 1765). The Cervantes Festival (Cervantino) is Mexico's largest arts festival (October) — 10 days of theater, music, dance, and art from 20+ countries.",
    experiences: [
      'Alley of the Kiss photo',
      'Mummy Museum (bizarre)',
      'Teatro Juárez chandeliers',
      'Valenciana mine tour',
      'Cervantes Festival (Oct)',
      'Monumento al Pípila view',
    ],
    camps: ['Hotel Boutique 1850', 'Mision Guanajuato', 'Hotel Castillo de Santa Cecilia', 'La Casona de Don Lucas', 'Casa del Rector'],
    unesco: true,
  },
]