export const peruDestinations = [
  {
    slug: 'machu-picchu',
    name: 'Machu Picchu',
    country: 'Peru',
    region: 'Peru',
    tagline: 'The Lost City of the Incas',
    gradient: 'linear-gradient(160deg,#001c10,#002c1a,#003c22)',
    image: '/images/americas/machu-picchu.jpg',
    highlights: ['Machu Picchu Citadel', 'Wayna Picchu', 'Inca Trail', 'Sun Gate', 'Temple of the Sun', 'Sacred Plaza'],
    bestTime: 'May–Sep',
    duration: '2–3 days',
    from: '$620',
    description: "Machu Picchu is one of the world's most extraordinary places — a 15th-century Inca citadel built at 7,970 feet in the Andean cloud forest, abandoned for 400 years, and rediscovered in 1911 by Hiram Bingham. The site's purpose remains debated — royal estate, religious sanctuary, or astronomical observatory — but its engineering and beauty are undeniable. The Classic Postcard view is from the Guardian's House — you've seen it a million times, but no photo prepares you for the scale. Wayna Picchu (the mountain behind the ruins) requires a separate ticket (limited to 400 people daily) — the 45-minute climb is steep and exposed but offers the best view of the entire site. The Inca Trail is the classic 4-day, 26-mile trek through the mountains, ending at Machu Picchu via the Sun Gate (Inti Punku) at sunrise — permits sell out 6 months in advance (book through a licensed tour operator). The Sun Gate is where the Inca Trail ends — you need to enter Machu Picchu from here (from Aguas Calientes) at 6 am for the sunrise view (before the crowds). Machu Picchu is strict with tickets — you choose a circuit (1, 2, 3, or 4) and have a 2-4 hour window. Book tickets 3-6 months ahead (official website or through a tour operator).",
    experiences: [
      'Wayna Picchu sunrise',
      'Inca Trail trek (4 days)',
      'Sun Gate sunrise',
      'Temple of the Sun astronomy',
      'Sacred Plaza llama photo',
      'Aguas Calientes hot springs',
    ],
    camps: ['Belmond Sanctuary Lodge', 'Sumaq Machu Picchu Hotel', 'Inkaterra Machu Picchu Pueblo', 'El Mapi Hotel', 'Casa del Sol'],
    unesco: true,
  },
  {
    slug: 'cusco',
    name: 'Cusco',
    country: 'Peru',
    region: 'Peru',
    tagline: 'The Navel of the Inca World',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/americas/cusco.jpg',
    highlights: ['Plaza de Armas', 'Sacsayhuaman', 'Qorikancha', 'San Pedro Market', '12-Angled Stone', 'Inca Trail Start'],
    bestTime: 'Apr–Oct',
    duration: '3–5 nights',
    from: '$420',
    description: "Cusco was the capital of the Inca Empire — a 11,000-foot city of Spanish baroque churches built on Inca stone foundations, with Quechua spoken in the markets and alpaca sweaters for sale everywhere. The Plaza de Armas is Cusco's main square — the Cathedral (built 1560) has a painting of the Last Supper with guinea pig (cuy) on the table, and the Church of la Compañía de Jesús (the most beautiful church in the city) is a copy of Rome's Il Gesù. Sacsayhuaman ('Sexy Woman' to English speakers) is a 13-acre Inca fortress above Cusco — the zigzag walls are made of 200-ton limestone boulders cut so precisely that a credit card can't fit between them. Qorikancha (Coricancha) was the most important Inca temple — the 'Golden Enclosure' had walls covered in 700 gold sheets (the Spanish built the Convent of Santo Domingo on its foundations). San Pedro Market is Cusco's daily market — buy fresh juice (lúcuma, cherimoya, passion fruit), see the weird potatoes (3,000 varieties), and try cuy (guinea pig) if you dare. The 12-Angled Stone is in a narrow alley off Plaza de Armas — the stone (part of the Inca palace of Inca Roca) has 12 corners and is the most famous example of Inca stonework. Cusco is the starting point for the Inca Trail and Sacred Valley tours — spend 2-3 days acclimating to the altitude before hiking or visiting Machu Picchu.",
    experiences: [
      'Plaza de Armas cathedral guinea pig',
      'Sacsayhuaman fortress stones',
      'Qorikancha Inca temple',
      'San Pedro Market juice',
      '12-Angled Stone photo',
      'Coca tea altitude remedy',
    ],
    camps: ['Belmond Palacio Nazarenas', 'Monasterio, a Belmond Hotel', 'JW Marriott Cusco', 'Inkaterra La Casona', 'Hilton Cusco'],
    unesco: true,
  },
  {
    slug: 'sacred-valley',
    name: 'Sacred Valley',
    country: 'Peru',
    region: 'Peru',
    tagline: 'The Valley of the Incas',
    gradient: 'linear-gradient(160deg,#001c14,#002c1e,#004028)',
    image: '/images/americas/sacred-valley.jpg',
    highlights: ['Ollantaytambo', 'Pisac', 'Moray', 'Maras Salt Mines', 'Chinchero', 'Alpaca Farms'],
    bestTime: 'Apr–Oct',
    duration: '2–3 days',
    from: '$380',
    description: "The Sacred Valley (Valle Sagrado) is the most fertile agricultural region of the Inca Empire — a 40-mile stretch of the Urubamba River, dotted with Inca ruins, traditional villages, and Andean markets. Ollantaytambo is the best-preserved Inca town — the ruins have a ceremonial center, terraces, and a sun temple, and the town still uses the original Inca canals and stone streets. Ollantaytambo is the starting point for the train to Machu Picchu (PeruRail and Inca Rail). Pisac has the largest and most famous market in the Sacred Valley (Sundays, Tuesdays, Thursdays) — vendors sell textiles, ceramics, jewelry, and meat on the ancient terraces (the ruins above the market are worth the hike). Moray is an archaeological site of circular terraces — 3-6 concentric rings carved into a limestone depression, the temperature difference between the top and bottom is 15°C, probably used as an agricultural laboratory for the Incas. Maras Salt Mines (Salineras) are 3,000 salt evaporation ponds worked by the same families for 500 years — the salt water (10 times saltier than the ocean) flows from a underground stream, evaporates in the sun, and turns pink from mineral content. Chinchero is a traditional weaving village — the women of the community demonstrate natural dyeing (cochineal insects for red, plants for green/yellow) and spinning llama and alpaca wool.",
    experiences: [
      'Ollantaytambo sun temple',
      'Pisac market (Sundays)',
      'Moray circular terraces',
      'Maras salt ponds',
      'Chinchero weaving demo',
      'Alpaca farm visit',
    ],
    camps: ['Tambo del Inka', 'Sol y Luna', 'Willka T\'ika', 'Explora Valle Sagrado', 'Casa Andina Premium'],
    unesco: true,
  },
  {
    slug: 'rainbow-mountain',
    name: 'Rainbow Mountain',
    country: 'Peru',
    region: 'Peru',
    tagline: 'Vinicunca — 7 Colors of the Andes',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/americas/rainbow-mountain.jpg',
    highlights: ['Vinicunca', 'Red Valley', 'Ausangate Mountain', 'Llamas', '17,000 Feet', 'Sunrise'],
    bestTime: 'May–Sep',
    duration: '1 day trip',
    from: '$350',
    description: "Rainbow Mountain (Vinicunca) is Peru's most Instagrammed natural wonder — a 17,000-foot mountain striped with 7 colors: red (clay), green (vegetation), yellow (sulfur), orange (iron), purple (minerals), white (sandstone), and turquoise (sedimentary). The colors come from 24 different minerals (iron oxide, copper sulfate, sulfur, quartz) deposited over 70 million years of tectonic uplift and erosion. The hike from the trailhead (15,500 feet) to the viewpoint (17,060 feet) is 3 miles round trip — the altitude is brutal (oxygen is 40% lower than sea level), most people take 1.5-2 hours up, 45 minutes down. Horses are available for rent ($30-50) but only go to the last 500 meters (where the steepest climb begins). The best time is sunrise (6-7 am) — the colors are most vivid when the sun first hits the mountain, and the crowds are smaller (tour buses arrive 8-10 am). The Red Valley (Valle Rojo) is an optional 1-hour loop from the viewpoint — fewer people and dramatic views of red mountains, green valleys, and the snow-capped Ausangate Mountain (20,900 feet, the highest in the Cusco region). Altitude sickness is real — spend 2-3 days in Cusco (11,000 feet) before attempting Rainbow Mountain, drink coca tea, and take Diamox (prescription).",
    experiences: [
      'Sunrise at 17,000 feet',
      'Red Valley loop hike',
      'Llama photo at the top',
      'Horse rental (ascent)',
      'Ausangate mountain view',
      'Coca leaf altitude remedy',
    ],
    camps: ['Day trip from Cusco (no overnight lodging)'],
    unesco: false,
  },
]