export const usaDestinations = [
  {
    slug: 'new-york',
    name: 'New York City',
    country: 'USA',
    region: 'USA',
    tagline: 'The City That Never Sleeps',
    gradient: 'linear-gradient(160deg,#0a0a15,#1a1a2e,#16213e)',
    image: '/images/americas/new-york.jpg',
    highlights: ['Manhattan', 'Central Park', 'Brooklyn Bridge', 'Broadway', 'MoMA', 'High Line'],
    bestTime: 'Apr–Jun · Sep–Nov',
    duration: '5–8 nights',
    from: '$420',
    description: "New York City is the energy capital of the world — a 24-hour metropolis of 8.5 million people speaking over 800 languages, where every neighborhood tells a different story. Manhattan's skyline is a modern architectural marvel, with the Empire State Building (1,454 feet) and One World Trade Center (1,776 feet, symbolizing 1776) dominating the view. Central Park is an 843-acre masterpiece of landscape architecture — more people have seen it in movies than have visited it in person. The Brooklyn Bridge (1883) was the longest suspension bridge in the world when built, connecting Manhattan and Brooklyn. Broadway is the pinnacle of live theatre — Hamilton, Wicked, and The Lion King have been running for decades. The Museum of Modern Art (MoMA) holds Van Gogh's 'Starry Night,' Picasso's 'Les Demoiselles d'Avignon,' and Warhol's 'Campbell's Soup Cans.' The High Line is a 1.5-mile elevated railway turned park, a model for urban renewal worldwide. New York's food scene is unparalleled — from dollar slices to 3-star Michelin restaurants, from Katz's Deli (pastrami sandwich) to Levain Bakery (6-ounce chocolate chip cookies).",
    experiences: [
      'Empire State Building at sunset',
      'Central Park rowboat at The Loeb Boathouse',
      'Brooklyn Bridge walk from DUMBO',
      'Broadway show (book weeks ahead)',
      'MoMA Starry Night viewing',
      'High Line sunset stroll',
    ],
    camps: ['The Ritz-Carlton Central Park', 'The Plaza', 'The Peninsula New York', 'Four Seasons Downtown', 'The Whitby Hotel'],
    unesco: false,
  },
  {
    slug: 'grand-canyon',
    name: 'Grand Canyon',
    country: 'USA',
    region: 'USA',
    tagline: 'The Most Spectacular Chasm on Earth',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/americas/grand-canyon.jpg',
    highlights: ['South Rim', 'North Rim', 'Skywalk', 'Havasu Falls', 'Colorado River', 'Helicopter Tour'],
    bestTime: 'Apr–Oct',
    duration: '3–5 nights',
    from: '$350',
    description: "The Grand Canyon is Earth's greatest geological spectacle — 277 miles long, up to 18 miles wide, and 6,000 feet deep, carved by the Colorado River over 6 million years. The canyon reveals nearly 2 billion years of Earth's history in its rock layers, from Vishnu Schist (the dark metamorphic rock at the bottom) to Kaibab Limestone (the white rock at the rim). The South Rim is open year-round and offers the most viewpoints — Mather Point (classic sunrise), Yavapai Point (geology museum), and Desert View (watchtower with 360-degree views). The North Rim is higher (8,000 feet) and cooler, with only 10% of the visitors — open May-October only. The Skywalk is a horseshoe-shaped glass bridge extending 70 feet over the edge on the West Rim (not in the national park, run by the Hualapai Tribe). Havasu Falls is on tribal land — a 100-foot waterfall with turquoise blue water, requiring a 10-mile hike and a permit lottery months in advance. Rafting the Colorado River (3-18 days) is the ultimate Grand Canyon experience — book years ahead.",
    experiences: [
      'South Rim sunrise at Mather Point',
      'North Rim (summer only)',
      'Helicopter flight to the bottom',
      'Havasu Falls permit lottery',
      'Colorado River rafting',
      'Grand Canyon Railway from Williams',
    ],
    camps: ['El Tovar Hotel', 'Phantom Ranch (bottom)', 'Bright Angel Lodge', 'Maswik Lodge', 'The Grand Hotel'],
    unesco: true,
  },
  {
    slug: 'yellowstone',
    name: 'Yellowstone',
    country: 'USA',
    region: 'USA',
    tagline: 'The World\'s First National Park',
    gradient: 'linear-gradient(160deg,#001c10,#002c1a,#003c22)',
    image: '/images/americas/yellowstone.jpg',
    highlights: ['Old Faithful', 'Grand Prismatic Spring', 'Yellowstone Lake', 'Grand Canyon of Yellowstone', 'Wildlife', 'Mammoth Hot Springs'],
    bestTime: 'May–Sep',
    duration: '4–7 nights',
    from: '$480',
    description: "Yellowstone is the world's first national park (1872) — 2.2 million acres of geysers, hot springs, waterfalls, and wildlife that define the American West. The park sits atop a supervolcano (the Yellowstone Caldera, 45 x 30 miles), with half of the world's geysers concentrated here. Old Faithful erupts every 90 minutes (within 10 minutes) to a height of 100-180 feet — it's reliable but not the biggest or most frequent. Grand Prismatic Spring is the park's most photographed feature — the largest hot spring in the US (370 feet wide, 160 feet deep), with brilliant bands of color created by thermophilic bacteria (red, orange, yellow outside; blue inside). The Grand Canyon of the Yellowstone is a 20-mile-long, 1,200-foot-deep canyon with two waterfalls (Lower Falls is 308 feet, twice the height of Niagara). Yellowstone is one of the best places in the world to see wildlife — bison (4,500 of them) stop traffic, elk bugle in fall, wolves howl in Lamar Valley, and grizzly bears fish for cutthroat trout. Mammoth Hot Springs is a travertine terrace of steaming white and orange terraces, constantly changing.",
    experiences: [
      'Old Faithful eruption schedule',
      'Grand Prismatic from Fairy Falls Trail',
      'Lamar Valley wolf spotting at dawn',
      'Grand Canyon of Yellowstone hike',
      'Mammoth Hot Springs terraces',
      'Bison traffic jam (unavoidable)',
    ],
    camps: ['Old Faithful Inn', 'Lake Yellowstone Hotel', 'Mammoth Hot Springs Hotel', 'Canyon Lodge', 'Roosevelt Lodge'],
    unesco: true,
  },
  {
    slug: 'yosemite',
    name: 'Yosemite',
    country: 'USA',
    region: 'USA',
    tagline: 'Cathedral of Granite',
    gradient: 'linear-gradient(160deg,#001c14,#002c1e,#004028)',
    image: '/images/americas/yosemite.jpg',
    highlights: ['Half Dome', 'El Capitan', 'Yosemite Falls', 'Glacier Point', 'Mariposa Grove', 'Tuolumne Meadows'],
    bestTime: 'May–Sep',
    duration: '3–5 nights',
    from: '$420',
    description: "Yosemite National Park is a cathedral of granite — vertical walls that have defined American climbing and conservation. El Capitan is a 3,000-foot vertical rock face, the most famous climbing challenge in the world — in 2019, Alex Honnold free-soloed it without ropes (documented in 'Free Solo'). Half Dome is the park's iconic shape — the 14-16 mile hike with the final 400 feet up a cable route is one of America's most competitive day hikes (permit lottery). Yosemite Falls is the tallest waterfall in North America (2,425 feet, 2,000 of which are vertical). Glacier Point (7,214 feet) offers the classic postcard view of Half Dome, Vernal Fall, and Nevada Fall. Mariposa Grove has over 500 mature giant sequoias, including the Grizzly Giant (2,700 years old, 210 feet tall). Tuolumne Meadows is the high country (8,600 feet) — accessible only July-September, with domes, wildflowers, and the Pacific Crest Trail passing through. Ansel Adams photographed Yosemite for decades; his images made the park famous worldwide.",
    experiences: [
      'El Capitan from meadow (bring binoculars)',
      'Half Dome cable permit lottery',
      'Yosemite Falls spring run-off',
      'Glacier Point sunset',
      'Mariposa Grove sequoias',
      'Tioga Road to Tuolumne (summer)',
    ],
    camps: ['Ahwahnee Hotel', 'Yosemite Valley Lodge', 'Curry Village', 'Wawona Hotel', 'White Wolf Lodge'],
    unesco: true,
  },
  {
    slug: 'las-vegas',
    name: 'Las Vegas',
    country: 'USA',
    region: 'USA',
    tagline: 'The Entertainment Capital of the World',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/americas/las-vegas.jpg',
    highlights: ['The Strip', 'Fremont Street', 'Casinos', 'Shows', 'Grand Canyon Day Trip', 'Nightlife'],
    bestTime: 'Mar–May · Sep–Nov',
    duration: '3–5 nights',
    from: '$380',
    description: "Las Vegas is America's adult playground — a desert city of excess, entertainment, and 'what happens here stays here.' The Strip is a 4.2-mile stretch of themed mega-resorts — Bellagio's fountains (choreographed to music), The Venetian's canals (gondoliers singing), Caesars Palace's Roman statues, New York-New York's roller coaster, and the Luxor's pyramid with the world's brightest beam of light (42 billion candela). Fremont Street is the original Las Vegas (downtown) — a 5-block pedestrian mall covered by a 1,500-foot video screen (Viva Vision), with zip-lining, live music, and casinos that feel more authentic. Every casino resort has a show — Cirque du Soleil has eight different productions (O at Bellagio is the most famous), plus magicians (David Copperfield, Penn & Teller), comedians (Carrot Top, Brad Garrett), and musicians (Adele's residency at Caesars). The Neon Museum preserves vintage casino signs (Stardust, Moulin Rouge) in a graveyard of lights. Vegas is also the gateway to the Grand Canyon (helicopter day trips), Hoover Dam (30 minutes), and Red Rock Canyon (hiking and climbing).",
    experiences: [
      'Bellagio fountain show every 30 minutes',
      'Fremont Street zip-line',
      'Cirque du Soleil O or KA',
      'Neon Museum boneyard',
      'Grand Canyon helicopter tour',
      'Hoover Dam power plant tour',
    ],
    camps: ['Bellagio', 'Wynn Las Vegas', 'The Venetian', 'Caesars Palace', 'The Cosmopolitan'],
    unesco: false,
  },
  {
    slug: 'san-francisco',
    name: 'San Francisco',
    country: 'USA',
    region: 'USA',
    tagline: 'Golden Gate & Cable Cars',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/americas/san-francisco.jpg',
    highlights: ['Golden Gate Bridge', 'Alcatraz', 'Cable Cars', 'Fisherman\'s Wharf', 'Chinatown', 'Painted Ladies'],
    bestTime: 'May–Oct',
    duration: '3–5 nights',
    from: '$360',
    description: "San Francisco is America's most beautiful city — a 7x7-mile peninsula of steep hills, Victorian houses, fog, and the Golden Gate Bridge, often called the world's most photographed bridge. The Golden Gate Bridge (1937) is 1.7 miles long, painted International Orange (for visibility in fog), with 746-foot towers — walk or bike across the bridge for views of the bay and Alcatraz. Alcatraz Island was a maximum-security federal prison (1934-1963) holding Al Capone and Robert 'Birdman' Stroud — the audio tour with former guards and inmates is one of the best in the world (book weeks ahead). San Francisco's cable cars are the only moving National Historic Landmark — the Powell-Hyde line is the most scenic, climbing Nob Hill and Russian Hill for views of Alcatraz and the bay. Fisherman's Wharf is touristy but essential — sea lions at Pier 39, clam chowder in sourdough bread bowls (Boudin Bakery since 1849), and ferry to Alcatraz. Chinatown (the largest outside Asia) has dim sum and the Golden Gate Fortune Cookie Factory. The Painted Ladies (Postcard Row) are Victorian houses at Alamo Square, with the city skyline behind them — the 'Full House' opening credits.",
    experiences: [
      'Golden Gate Bridge walk to Marin Headlands',
      'Alcatraz audio tour (book weeks ahead)',
      'Powell-Hyde cable car ride',
      'Fisherman\'s Wharf sea lions',
      'Chinatown dim sum lunch',
      'Painted Ladies photo at Alamo Square',
    ],
    camps: ['The Ritz-Carlton San Francisco', 'Four Seasons San Francisco', 'Fairmont San Francisco', 'The St. Regis', 'Hotel Nikko'],
    unesco: false,
  },
  {
    slug: 'new-orleans',
    name: 'New Orleans',
    country: 'USA',
    region: 'USA',
    tagline: 'The Big Easy',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/americas/new-orleans.jpg',
    highlights: ['French Quarter', 'Bourbon Street', 'Jazz', 'Mardi Gras', 'Cajun Food', 'Streetcar'],
    bestTime: 'Feb–May',
    duration: '3–5 nights',
    from: '$280',
    description: "New Orleans is America's most unique city — a blend of French, Spanish, African, and Creole cultures, founded in 1718, famous for jazz, Mardi Gras, and food. The French Quarter (Vieux Carré) is the original city, a 78-block grid of wrought-iron balconies, hidden courtyards, and the oldest cathedral in the US (St. Louis Cathedral, 1720). Bourbon Street is the neon-lit party street — 24-hour bars, daiquiri shops, and three blocks of noise and chaos. Preservation Hall is a tiny, un-air-conditioned building where the best traditional jazz musicians play nightly — no drinks, no AC, just world-class music. Mardi Gras (Fat Tuesday) is the famous carnival — two weeks of parades, krewes, and king cake (the person who finds the plastic baby buys the next cake). New Orleans invented Creole and Cajun food — gumbo (shellfish, sausage, okra), jambalaya (rice with meat and seafood), po'boys (oyster or roast beef sandwiches), beignets (fried dough with powdered sugar at Café du Monde). St. Charles Avenue streetcars (the oldest continuously operating streetcar line in the world) run through the Garden District, lined with antebellum mansions.",
    experiences: [
      'French Quarter balcony photos',
      'Bourbon Street hurricane drink',
      'Preservation Hall jazz',
      'Mardi Gras parade (Feb-Mar)',
      'Café du Monde beignets',
      'St. Charles streetcar to Garden District',
    ],
    camps: ['The Roosevelt New Orleans', 'Hotel Monteleone', 'The Ritz-Carlton', 'Windsor Court', 'Bienville House'],
    unesco: false,
  },
  {
    slug: 'washington-dc',
    name: 'Washington DC',
    country: 'USA',
    region: 'USA',
    tagline: 'America\'s Capital of Monuments',
    gradient: 'linear-gradient(160deg,#0a0a15,#1a1a2e,#16213e)',
    image: '/images/americas/washington.jpg',
    highlights: ['Lincoln Memorial', 'Washington Monument', 'US Capitol', 'White House', 'Smithsonian Museums', 'National Mall'],
    bestTime: 'Mar–May · Sep–Nov',
    duration: '3–5 nights',
    from: '$320',
    description: "Washington DC is America's capital — a city of monuments, museums, and political power. The National Mall is a 2-mile strip of monuments and museums, from the Lincoln Memorial to the US Capitol. The Lincoln Memorial (1922) has a 19-foot statue of the 16th president, with the Gettysburg Address carved on the wall — Dr. Martin Luther King Jr. gave his 'I Have a Dream' speech from its steps in 1963. The Washington Monument is a 555-foot obelisk (the tallest stone structure in the world) — take the elevator to the top for views of the city. The US Capitol has a cast-iron dome (8,909 tons) and the Statue of Freedom on top — tour the Rotunda (fresco by Brumidi) and the Crypt (meant for George Washington's tomb). The White House (1600 Pennsylvania Avenue) is the president's residence — tours are free but require a request through your Member of Congress months in advance. The Smithsonian Institution is 19 museums and galleries — the Air and Space Museum (Apollo 11 command module, Wright Brothers flyer), Natural History Museum (Hope Diamond, dinosaur bones), and American History Museum (Star-Spangled Banner, First Ladies' gowns) are free and world-class.",
    experiences: [
      'Lincoln Memorial steps at sunrise',
      'Washington Monument elevator',
      'US Capitol Rotunda tour',
      'White House tour (request months ahead)',
      'Air and Space Museum Wright Flyer',
      'Cherry Blossoms tidal basin (Mar-Apr)',
    ],
    camps: ['Willard InterContinental', 'The Hay-Adams', 'The Jefferson', 'Four Seasons Washington', 'The Watergate Hotel'],
    unesco: true,
  },
]