import type { Metadata } from 'next'
import { DestinationClient } from './DestinationClient'

const destinationData: Record<string, {
  name: string; region: string; tagline: string; desc: string
  bestTime: string; budget: string; highlights: string[]; currency?: string
}> = {
  'dubai':         { name:'Dubai',         region:'Middle East', tagline:'Gold, Desert & Infinite Luxury',      desc:'Ultramodern skylines meeting ancient desert culture. Dubai is the world\'s most audacious city — where the future is already present.',         bestTime:'Oct–Apr', budget:'$150–$500/day',  highlights:['Burj Khalifa','Desert Safari','Palm Jumeirah','Gold Souk','Dubai Frame'] },
  'abu-dhabi':     { name:'Abu Dhabi',     region:'Middle East', tagline:'Culture Meets Modern Grandeur',        desc:'The UAE\'s capital blends Islamic heritage with extraordinary modern architecture, world-class museums, and pristine coastline.',              bestTime:'Oct–Apr', budget:'$120–$400/day',  highlights:['Sheikh Zayed Mosque','Louvre Abu Dhabi','Ferrari World','Yas Island','Empty Quarter'] },
  'petra':         { name:'Petra',         region:'Middle East', tagline:'The Rose-Red City of the Nabataeans',  desc:'Carved directly into rose-red cliffs over 2,000 years ago, Petra is one of the world\'s most extraordinary archaeological sites.',            bestTime:'Mar–May', budget:'$80–$200/day',   highlights:['The Treasury','The Monastery','Siq Canyon','Royal Tombs','Little Petra'] },
  'muscat':        { name:'Muscat',        region:'Middle East', tagline:'Arabia\'s Hidden Gem',                  desc:'Oman\'s capital offers a rare window into authentic Arabian culture — magnificent mosques, souqs, and dramatic mountain scenery.',           bestTime:'Oct–Mar', budget:'$80–$250/day',   highlights:['Sultan Qaboos Mosque','Mutrah Souq','Nizwa Fort','Wahiba Sands','Wadi Shab'] },
  'serengeti':     { name:'Serengeti',     region:'Africa',      tagline:'The Greatest Show on Earth',           desc:'Home to the most spectacular wildlife migration on the planet — millions of wildebeest, zebra, and the big cats that follow them.',         bestTime:'Jun–Oct', budget:'$300–$800/day',  highlights:['Great Migration','Big Five Safari','Hot Air Balloon','Ngorongoro Crater','Maasai Village'] },
  'cape-town':     { name:'Cape Town',     region:'Africa',      tagline:'Where Mountains Meet the Ocean',       desc:'One of the world\'s most beautiful cities — Table Mountain, white beaches, vineyards, and vibrant culture all in one extraordinary place.',  bestTime:'Nov–Mar', budget:'$80–$300/day',   highlights:['Table Mountain','Cape Point','Boulders Penguins','V&A Waterfront','Cape Winelands'] },
  'marrakech':     { name:'Marrakech',     region:'Africa',      tagline:'The Red City of a Thousand Colours',   desc:'A sensory explosion of spice-filled souqs, ornate riads, and the legendary Djemaa el-Fna square that comes alive after dark.',               bestTime:'Oct–Apr', budget:'$50–$200/day',   highlights:['Djemaa el-Fna','Majorelle Garden','Medina Souqs','Bahia Palace','Sahara Day Trip'] },
  'zanzibar':      { name:'Zanzibar',      region:'Africa',      tagline:'Spice Islands & Turquoise Seas',       desc:'A dreamy archipelago off Tanzania\'s coast — pristine white beaches, turquoise waters, Stone Town\'s UNESCO heritage, and exotic spice farms.', bestTime:'Jun–Oct', budget:'$80–$300/day',   highlights:['Stone Town','Nungwi Beach','Spice Tour','Prison Island','Jozani Forest'] },
  'rwanda':        { name:'Rwanda',        region:'Africa',      tagline:'Land of a Thousand Hills & Gorillas',  desc:'Africa\'s most extraordinary wildlife experience — trekking to encounter mountain gorillas in their natural misty forest habitat.',             bestTime:'Jun–Sep', budget:'$200–$600/day',  highlights:['Gorilla Trekking','Volcanoes National Park','Kigali Museum','Lake Kivu','Nyungwe Forest'] },
  'victoria-falls':{ name:'Victoria Falls', region:'Africa',     tagline:'The Smoke That Thunders',               desc:'One of the seven natural wonders of the world — the Zambezi River plunges 108 metres creating the world\'s largest curtain of falling water.', bestTime:'Feb–May', budget:'$150–$400/day',  highlights:['Devil\'s Pool','Helicopter Flight','White Water Rafting','Bungee Jump','Sunset Cruise'] },
  'kyoto':         { name:'Kyoto',         region:'Asia',        tagline:'Where Ancient Japan Lives On',         desc:'A city of a thousand temples, geisha districts, bamboo forests, and transcendent seasonal beauty. The soul of Japan.',                      bestTime:'Mar–May', budget:'$80–$250/day',   highlights:['Fushimi Inari','Arashiyama Bamboo','Gion District','Kinkaku-ji','Tea Ceremony'] },
  'bali':          { name:'Bali',          region:'Asia',        tagline:'Island of the Gods',                   desc:'Terraced rice paddies, sacred Hindu temples, world-class surf, and a culture unlike anywhere else on earth.',                              bestTime:'Apr–Oct', budget:'$50–$200/day',   highlights:['Ubud Rice Terraces','Tanah Lot','Seminyak Beach','Mount Batur','Sacred Monkey Forest'] },
  'tokyo':         { name:'Tokyo',         region:'Asia',        tagline:'Future Meets Tradition',               desc:'The world\'s most dynamic megacity — ancient shrines next to neon-lit skyscrapers and Michelin-starred street food on every corner.',       bestTime:'Mar–May', budget:'$100–$350/day',  highlights:['Shibuya Crossing','Senso-ji Temple','Tsukiji Market','Harajuku','Mount Fuji Day Trip'] },
  'maldives':      { name:'Maldives',      region:'Asia',        tagline:'Paradise Above and Below the Water',   desc:'Overwater villas, crystal lagoons, and the world\'s finest coral reefs across 1,200 tropical islands in the Indian Ocean.',                  bestTime:'Nov–Apr', budget:'$300–$1000/day', highlights:['Overwater Bungalows','Snorkelling','Whale Shark Dive','Sunset Cruise','Private Beach'] },
  'singapore':     { name:'Singapore',     region:'Asia',        tagline:'The Lion City',                        desc:'A gleaming city-state where futuristic architecture, world-class food, and extraordinary gardens exist in perfect harmony.',                bestTime:'Feb–Apr', budget:'$120–$400/day',  highlights:['Gardens by the Bay','Marina Bay Sands','Hawker Centres','Sentosa Island','Chinatown'] },
  'bhutan':        { name:'Bhutan',        region:'Asia',        tagline:'The Last Shangri-La',                  desc:'The world\'s only carbon-negative country — a Himalayan kingdom of monasteries, dramatic mountain passes, and ancient Buddhist culture.',   bestTime:'Mar–May', budget:'$200–$500/day',  highlights:['Tiger\'s Nest Monastery','Punakha Dzong','Dochula Pass','Thimphu Festival','Haa Valley'] },
  'angkor-wat':    { name:'Angkor Wat',    region:'Asia',        tagline:'Temple Kingdom of the Khmer Empire',   desc:'The largest religious monument ever built — a vast 12th-century temple complex emerging from the Cambodian jungle.',                          bestTime:'Nov–Mar', budget:'$60–$180/day',   highlights:['Angkor Wat Sunrise','Bayon Temple','Ta Prohm','Preah Khan','Tonle Sap Lake'] },
  'amalfi-coast':  { name:'Amalfi Coast',  region:'Europe',      tagline:'Cliffside Villages Above Azure Seas',  desc:'Dramatic coastal scenery, pastel villages clinging to cliffsides, and Mediterranean cuisine along Italy\'s most iconic shore.',              bestTime:'May–Sep', budget:'$120–$400/day',  highlights:['Positano','Ravello','Capri','Path of the Gods','Limoncello Tasting'] },
  'santorini':     { name:'Santorini',     region:'Europe',      tagline:'Blue Domes & Volcanic Sunsets',        desc:'Greece\'s most iconic island — volcanic caldera views, white-washed villages, and legendary sunsets over the Aegean Sea.',                   bestTime:'Apr–Oct', budget:'$150–$500/day',  highlights:['Oia Sunset','Caldera Views','Black Sand Beaches','Wine Tasting','Ancient Akrotiri'] },
  'paris':         { name:'Paris',         region:'Europe',      tagline:'The City of Light & Love',             desc:'The Eiffel Tower, world-class cuisine, and the most romantic streets on earth. Paris never disappoints.',                                  bestTime:'Apr–Jun', budget:'$120–$400/day',  highlights:['Eiffel Tower','Louvre Museum','Montmartre','Seine River Cruise','Versailles'] },
  'iceland':       { name:'Iceland',       region:'Europe',      tagline:'Fire, Ice & Northern Lights',          desc:'Volcanoes, geysers, waterfalls, midnight sun, and some of the world\'s most dramatic and otherworldly landscapes.',                          bestTime:'Jun–Aug', budget:'$150–$500/day',  highlights:['Northern Lights','Blue Lagoon','Golden Circle','Puffin Watching','Glacier Hike'] },
  'dubrovnik':     { name:'Dubrovnik',     region:'Europe',      tagline:'The Pearl of the Adriatic',            desc:'A perfectly preserved medieval walled city rising from the crystal-clear Adriatic — one of Europe\'s most beautiful destinations.',         bestTime:'May–Sep', budget:'$100–$350/day',  highlights:['City Walls Walk','Old Town','Cable Car','Lokrum Island','Game of Thrones Tour'] },
  'swiss-alps':    { name:'Swiss Alps',    region:'Europe',      tagline:'Peaks, Powder & Pristine Lakes',       desc:'Europe\'s most majestic mountain range — world-class skiing, pristine alpine lakes, charming villages, and breathtaking scenery year-round.',  bestTime:'Dec–Mar', budget:'$200–$600/day',  highlights:['Matterhorn','Jungfraujoch','Lake Geneva','Interlaken','Zermatt'] },
  'prague':        { name:'Prague',        region:'Europe',      tagline:'The City of a Hundred Spires',         desc:'Central Europe\'s most magical city — Gothic castles, Baroque churches, and cobblestone streets all reflected in the Vltava river.',          bestTime:'Apr–Jun', budget:'$80–$250/day',   highlights:['Prague Castle','Charles Bridge','Old Town Square','Jewish Quarter','Český Krumlov'] },
  'patagonia':     { name:'Patagonia',     region:'Americas',    tagline:'At the End of the World',              desc:'Wild, untamed landscapes of glaciers, jagged peaks, and open steppe at the southern tip of South America.',                                 bestTime:'Nov–Mar', budget:'$80–$300/day',   highlights:['Torres del Paine','Perito Moreno Glacier','El Chaltén','Ushuaia','Fitz Roy'] },
  'machu-picchu':  { name:'Machu Picchu',  region:'Americas',    tagline:'The Lost City of the Incas',           desc:'One of humanity\'s greatest achievements — an ancient Inca citadel set high in the Andean cloud forest of Peru.',                          bestTime:'Apr–Oct', budget:'$80–$250/day',   highlights:['Sun Gate','Huayna Picchu','Inca Trail','Aguas Calientes','Sacred Valley'] },
  'new-york':      { name:'New York City', region:'Americas',    tagline:'The City That Never Sleeps',           desc:'The world\'s most iconic skyline, world-class museums, Broadway shows, and the most diverse food scene on the planet.',                    bestTime:'Apr–Jun', budget:'$150–$500/day',  highlights:['Central Park','Times Square','Brooklyn Bridge','Metropolitan Museum','Statue of Liberty'] },
  'galapagos':     { name:'Galápagos',     region:'Americas',    tagline:'Darwin\'s Living Laboratory',           desc:'The most biodiverse archipelago on earth — giant tortoises, marine iguanas, and blue-footed boobies with no fear of humans.',             bestTime:'Jun–Sep', budget:'$200–$600/day',  highlights:['Giant Tortoises','Marine Iguanas','Snorkelling with Sea Lions','Blue-footed Boobies','Darwin Research Station'] },
  'cuba':          { name:'Cuba',          region:'Americas',    tagline:'Revolution, Rum & Classic Cars',        desc:'A time capsule of colonial architecture, vintage American cars, world-famous cigars, and extraordinary music on every street corner.',       bestTime:'Nov–Apr', budget:'$80–$200/day',   highlights:['Old Havana','Viñales Valley','Trinidad','Classic Car Tour','Salsa Dancing'] },
  'svalbard':      { name:'Svalbard',      region:'Arctic',      tagline:'Polar Bears & Northern Lights',        desc:'One of the world\'s last true wilderness frontiers — an Arctic archipelago of raw, brutal beauty, polar bears, and infinite silence.',       bestTime:'Feb–Apr', budget:'$200–$600/day',  highlights:['Northern Lights','Dog Sledding','Polar Bear Safari','Ice Caves','Midnight Sun'] },
}

export async function generateMetadata({ params }: { params: { slug: string } }): Promise<Metadata> {
  const dest = destinationData[params.slug]
  if (!dest) return { title: 'Destination Not Found' }
  return {
    title: `${dest.name} Travel Guide — ${dest.tagline}`,
    description: dest.desc,
  }
}

export default function DestinationPage({ params }: { params: { slug: string } }) {
  const dest = destinationData[params.slug]
  if (!dest) {
    return (
      <div style={{ minHeight: '100vh', background: '#080807', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <div style={{ textAlign: 'center' as const }}>
          <h1 style={{ fontFamily: "'Cormorant Garamond',serif", fontSize: '4rem', color: '#F5EFE4', marginBottom: 16 }}>Destination Not Found</h1>
          <a href="/destinations" style={{ color: '#C8A96E', textDecoration: 'none' }}>← All Destinations</a>
        </div>
      </div>
    )
  }
  return <DestinationClient dest={dest} slug={params.slug} />
}
