export const bahrainDestinations = [
  {
    slug: 'manama',
    name: 'Manama',
    country: 'Bahrain',
    region: 'Bahrain',
    tagline: 'The Pearl of the Gulf',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/middle-east/manama.jpg',
    highlights: ['Bahrain Fort', 'Pearling Path', 'Bab Al Bahrain', 'Al Fateh Mosque', 'Bahrain National Museum'],
    bestTime: 'Nov–Mar',
    duration: '2–3 nights',
    from: '$280',
    description: "Manama is the capital of Bahrain, a small island kingdom known for its pearling history and relative liberalism. Bahrain Fort (Qal'at al-Bahrain) is a UNESCO World Heritage site with layers of civilization from the Dilmun Empire (2300 BC) to the Portuguese (1600s). The Pearling Path is another UNESCO site — a 3.5-kilometer trail through Muharraq documenting Bahrain's pearling economy. Bab Al Bahrain is the historic gateway to the Manama Souq. Al Fateh Mosque is one of the world's largest mosques, with space for 7,000 worshippers.",
    experiences: [
      'Bahrain Fort sunset views',
      'Pearling Path UNESCO walk',
      'Bab Al Bahrain souq shopping',
      'Al Fateh Mosque tour',
      'Bahrain National Museum',
    ],
    camps: ['Four Seasons Bahrain', 'Ritz-Carlton Bahrain', 'Gulf Hotel', 'Sofitel Bahrain', 'The Domain Bahrain'],
    unesco: true,
  },
  {
    slug: 'bahrain-f1',
    name: 'Bahrain International Circuit',
    country: 'Bahrain',
    region: 'Bahrain',
    tagline: 'Home of the Formula 1',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/middle-east/bahrain-f1.jpg',
    highlights: ['F1 Track', 'Go-Karting', 'Paddock Experience', 'Night Races', 'Driving Experiences'],
    bestTime: 'Nov–Mar',
    duration: '1–2 nights',
    from: '$300',
    description: "The Bahrain International Circuit is one of the world's most advanced motorsport venues, hosting the annual Formula 1 Gulf Air Bahrain Grand Prix (usually in March). The track is 5.412 kilometers long with 15 corners. Visitors can take a driving experience (sports cars or formula cars), go-karting on the track, or visit the museum. The paddock experience offers behind-the-scenes access on non-race days. The circuit is famously floodlit for night races, a spectacular sight.",
    experiences: [
      'F1 museum and tour',
      'Driving experience (Ferrari, Lamborghini)',
      'Go-karting on the track',
      'Paddock tour',
      'Night race viewing (March)',
    ],
    camps: ['The Domain Bahrain', 'Jumeirah Gulf of Bahrain', 'Sofitel Bahrain', 'Wyndham Garden Manama'],
    unesco: false,
  },
]