export const egyptDestinations = [
  {
    slug: 'cairo-pyramids',
    name: 'Cairo & Pyramids',
    country: 'Egypt',
    region: 'Egypt',
    tagline: 'The Last Wonder of the Ancient World',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/middle-east/pyramids.jpg',
    highlights: ['Great Pyramid of Giza', 'Sphinx', 'Egyptian Museum', 'Khan el-Khalili', 'Nile Felucca'],
    bestTime: 'Oct–Apr',
    duration: '4–6 nights',
    from: '$350',
    description: "Cairo is the gateway to ancient Egypt — home to the last surviving Wonder of the Ancient World, the Pyramids of Giza. Stand before the Great Pyramid of Khufu (146 meters tall, built from 2.3 million stone blocks), gaze at the enigmatic Sphinx, and explore the treasures of Tutankhamun at the Egyptian Museum. Islamic Cairo offers the bustling Khan el-Khalili bazaar, the stunning Muhammad Ali Mosque, and the historic Al-Azhar University. A felucca ride on the Nile at sunset is essential.",
    experiences: [
      'Pyramids of Giza sunrise tour',
      'Sphinx photo opportunity',
      'Egyptian Museum Tutankhamun treasures',
      'Khan el-Khalili bazaar shopping',
      'Nile felucca sunset cruise',
    ],
    camps: ['Marriott Mena House', 'Four Seasons Nile Plaza', 'The Nile Ritz-Carlton', 'Kempinski Nile', 'Sofitel Cairo'],
    unesco: true,
  },
  {
    slug: 'luxor',
    name: 'Luxor',
    country: 'Egypt',
    region: 'Egypt',
    tagline: "The World's Greatest Open-Air Museum",
    gradient: 'linear-gradient(160deg,#1c1000,#2c1a00,#402600)',
    image: '/images/middle-east/luxor.jpg',
    highlights: ['Valley of the Kings', 'Karnak Temple', 'Hot Air Balloon', 'Hatshepsut Temple', 'Luxor Temple'],
    bestTime: 'Oct–Apr',
    duration: '3–4 nights',
    from: '$300',
    description: "Luxor is often called the world's greatest open-air museum. The east bank of the Nile holds the magnificent Karnak Temple (the largest religious complex ever built) and Luxor Temple. The west bank is home to the Valley of the Kings (where Tutankhamun's tomb was found), the Valley of the Queens, and the stunning mortuary temple of Hatshepsut. A hot air balloon ride at sunrise offers a breathtaking view of this ancient landscape. Don't miss the sound and light show at Karnak at night.",
    experiences: [
      'Valley of the Kings tomb exploration',
      'Karnak Temple sound and light show',
      'Hot air balloon at sunrise',
      'Hatshepsut Temple terrace walk',
      'Luxor Temple evening illumination',
    ],
    camps: ['Sofitel Winter Palace', 'Al Moudira Hotel', 'Hilton Luxor', 'Steigenberger Nile Palace', 'Jolie Ville'],
    unesco: true,
  },
  {
    slug: 'aswan',
    name: 'Aswan',
    country: 'Egypt',
    region: 'Egypt',
    tagline: 'The Nubian Heart of Egypt',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/middle-east/aswan.jpg',
    highlights: ['Abu Simbel', 'Philae Temple', 'Nile Cruise', 'Nubian Village', 'Unfinished Obelisk'],
    bestTime: 'Oct–Apr',
    duration: '2–3 nights',
    from: '$320',
    description: "Aswan is Egypt's southernmost city, the gateway to Nubia and Lake Nasser. Abu Simbel, 280 kilometers south, is Ramses II's magnificent temple (moved stone by stone to save it from flooding). Philae Temple is dedicated to the goddess Isis, located on an island accessible by boat. A felucca ride among the granite islands at sunset is magical. Nubian villages are brightly colored and welcoming. The Unfinished Obelisk shows how ancient Egyptians carved massive monuments from granite.",
    experiences: [
      'Abu Simbel day trip (early morning)',
      'Philae Temple boat access',
      'Nile felucca sunset cruise',
      'Nubian village cultural visit',
      'Unfinished Obelisk archaeological site',
    ],
    camps: ['Sofitel Legend Old Cataract', 'Mövenpick Aswan', 'Basma Hotel', 'Pyramisa Island Hotel', 'Kato Dool Wellness'],
    unesco: true,
  },
  {
    slug: 'red-sea',
    name: 'Red Sea Riviera',
    country: 'Egypt',
    region: 'Egypt',
    tagline: 'World-Class Diving & Beaches',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/middle-east/red-sea.jpg',
    highlights: ['Diving', 'Snorkeling', 'Resorts', 'Coral Reefs', 'Thistlegorm Wreck'],
    bestTime: 'Mar–Nov',
    duration: '5–8 nights',
    from: '$400',
    description: "The Red Sea is one of the world's top diving destinations, with crystal-clear water, vibrant coral reefs, and abundant marine life. Sharm el-Sheikh, Hurghada, and Marsa Alam offer world-class resorts. The Thistlegorm wreck (a British ship sunk in 1941) is one of the world's best wreck dives. Ras Mohammed National Park has pristine reefs. For non-divers, glass-bottom boats, snorkeling trips, and desert quad biking are available. The region is perfect for a beach extension after an Egyptian cultural tour.",
    experiences: [
      'Thistlegorm wreck dive',
      'Ras Mohammed reef snorkeling',
      'Desert quad biking',
      'Glass-bottom boat tour',
      'Luxury resort days',
    ],
    camps: ['Four Seasons Sharm', 'Rixos Premium', 'Steigenberger Coraya', 'Kempinski Soma Bay', 'The Oberoi Sahl Hasheesh'],
    unesco: false,
  },
]