export const israelPalestineDestinations = [
  {
    slug: 'jerusalem',
    name: 'Jerusalem',
    country: 'Israel/Palestine',
    region: 'Israel & Palestine',
    tagline: 'The Holy City of Three Faiths',
    gradient: 'linear-gradient(160deg,#1c1000,#2c1a00,#402600)',
    image: '/images/middle-east/jerusalem.jpg',
    highlights: ['Western Wall', 'Church of Holy Sepulchre', 'Dome of the Rock', 'Via Dolorosa', 'Mahane Yehuda'],
    bestTime: 'Mar–May · Sep–Nov',
    duration: '3–4 nights',
    from: '$350',
    description: "Jerusalem is the spiritual capital of the world — sacred to Judaism, Christianity, and Islam. The Old City is divided into four quarters (Jewish, Christian, Muslim, Armenian). The Western Wall (Kotel) is the holiest site where Jews can pray. The Church of the Holy Sepulchre is where Christians believe Jesus was crucified and buried. The Dome of the Rock and Al-Aqsa Mosque are holy to Muslims. Walk the Via Dolorosa (Way of Suffering), explore the underground Western Wall tunnels, and experience the vibrant Mahane Yehuda market at night.",
    experiences: [
      'Western Wall prayer and note placement',
      'Church of the Holy Sepulchre',
      'Temple Mount / Haram al-Sharif',
      'Via Dolorosa stations walk',
      'Mahane Yehuda food market',
    ],
    camps: ['King David Hotel', 'American Colony Hotel', 'Mamilla Hotel', 'Waldorf Astoria Jerusalem', 'David Citadel'],
    unesco: true,
  },
  {
    slug: 'tel-aviv-jaffa',
    name: 'Tel Aviv & Jaffa',
    country: 'Israel',
    region: 'Israel & Palestine',
    tagline: 'Mediterranean Modernity',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/middle-east/tel-aviv.jpg',
    highlights: ['Jaffa Old City', 'Bauhaus Architecture', 'Beaches', 'Neve Tzedek', 'Carmel Market'],
    bestTime: 'Apr–Oct',
    duration: '3–4 nights',
    from: '$380',
    description: "Tel Aviv is Israel's modern, secular heart — a Mediterranean city of Bauhaus architecture (White City, UNESCO World Heritage), beautiful beaches, world-class dining, and vibrant nightlife. Jaffa (Yafo) is the ancient port city that's now merged with Tel Aviv — explore the restored Old City, the artists' quarter, and the flea market. Neve Tzedek is the city's first neighborhood outside Jaffa, now filled with boutiques and cafes. The Carmel Market is a sensory explosion of food, spices, and local life.",
    experiences: [
      'Bauhaus White City architecture walk',
      'Jaffa Old City and port',
      'Tel Aviv beach day',
      'Neve Tzedek boutique shopping',
      'Carmel Market food tour',
    ],
    camps: ['The Norman Tel Aviv', 'Jaffa Hotel', 'Setai Tel Aviv', 'David Kempinski', 'Royal Beach Tel Aviv'],
    unesco: true,
  },
  {
    slug: 'dead-sea-israel',
    name: 'Dead Sea (Israel Side)',
    country: 'Israel',
    region: 'Israel & Palestine',
    tagline: 'Floating at the Lowest Point on Earth',
    gradient: 'linear-gradient(160deg,#001c20,#003034,#004448)',
    image: '/images/middle-east/dead-sea-israel.jpg',
    highlights: ['Floating', 'Mud Baths', 'Masada', 'Ein Gedi', 'Sunset Views'],
    bestTime: 'Apr–Oct',
    duration: '1–2 nights',
    from: '$250',
    description: "The Dead Sea on the Israeli side offers the same surreal floating experience as Jordan — the water is 10 times saltier than the ocean, making swimming impossible and floating effortless. Cover yourself in mineral-rich black mud, then rinse off in the buoyant water. Overlooking the Dead Sea is Masada, King Herod's mountain fortress where Jewish rebels made their last stand against the Romans. Ein Gedi is a desert oasis with waterfalls and wildlife (ibex, hyrax). The sunsets over the Dead Sea are spectacular.",
    experiences: [
      'Floating in hypersaline water',
      'Black mud spa treatment',
      'Masada cable car and sunrise hike',
      'Ein Gedi nature reserve',
      'Dead Sea sunset views',
    ],
    camps: ['Mövenpick Dead Sea', 'Herods Dead Sea', 'David Dead Sea Resort', 'Ein Gedi Kibbutz Hotel'],
    unesco: true,
  },
  {
    slug: 'bethlehem',
    name: 'Bethlehem',
    country: 'Palestine',
    region: 'Israel & Palestine',
    tagline: 'The Birthplace of Jesus',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/middle-east/bethlehem.jpg',
    highlights: ['Church of the Nativity', 'Manger Square', 'Separation Wall', 'Banksy Art', 'Olive Wood Shops'],
    bestTime: 'Mar–May · Sep–Nov',
    duration: '1 day trip',
    from: '$180',
    description: "Bethlehem is a Palestinian city in the West Bank, sacred to Christians as the birthplace of Jesus. The Church of the Nativity is built over the grotto where Jesus was born — the oldest major church in the Holy Land (4th century). Manger Square is the city's center. The Israeli Separation Wall is covered with street art, including works by Banksy (e.g., 'The Walled Off Hotel'). Bethlehem is known for its olive wood carvings — perfect for souvenirs.",
    experiences: [
      'Church of the Nativity grotto',
      'Milk Grotto chapel',
      'Separation Wall art tour',
      'Banksy Walled Off Hotel',
      'Olive wood workshop shopping',
    ],
    camps: ['Walled Off Hotel', 'Jacir Palace', 'Bethlehem Hotel', 'Dar Sitti Aziza', 'Angel Hotel'],
    unesco: true,
  },
]