export const jordanDestinations = [
  {
    slug: 'petra',
    name: 'Petra',
    country: 'Jordan',
    region: 'Jordan',
    tagline: 'The Rose-Red City Carved in Stone',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/middle-east/petra.jpg',
    highlights: ['The Treasury', 'Monastery', 'Siq Canyon', 'Royal Tombs', 'Petra by Night'],
    bestTime: 'Mar–May · Sep–Nov',
    duration: '2–3 nights',
    from: '$300',
    description: "Petra is Jordan's greatest treasure — a Nabataean city carved into rose-red sandstone cliffs over 2,000 years ago. Enter through the 1.2-kilometer Siq canyon, a narrow gorge whose walls rise 80 meters high. The Treasury (Al-Khazneh) appears at the canyon's end — the most iconic facade in the Middle East. Beyond, explore the Street of Facades, Royal Tombs, and hike 800 steps to the Monastery (Ad Deir), even larger than the Treasury. Petra by Night is a magical candlelit experience.",
    experiences: [
      'Siq canyon walk to the Treasury',
      'Monastery hike (800 steps)',
      'Petra by Night candlelight experience',
      'High Place of Sacrifice trail',
      'Little Petra archaeological site',
    ],
    camps: ['Petra Marriott Hotel', 'Mövenpick Resort Petra', 'Petra Moon Hotel', 'Petra Guest House', 'Seven Wonders Camp'],
    unesco: true,
  },
  {
    slug: 'wadi-rum',
    name: 'Wadi Rum',
    country: 'Jordan',
    region: 'Jordan',
    tagline: 'The Valley of the Moon',
    gradient: 'linear-gradient(160deg,#2a1a00,#402800,#563600)',
    image: '/images/middle-east/wadi-rum.jpg',
    highlights: ['4x4 Desert Tour', 'Bedouin Camp', 'Sunset Views', 'Rock Climbing', 'Star Gazing'],
    bestTime: 'Mar–May · Sep–Nov',
    duration: '1–2 nights',
    from: '$180',
    description: "Wadi Rum is a protected desert wilderness in southern Jordan, known for its dramatic red sand dunes, jagged granite mountains, and ancient petroglyphs. It's been the filming location for 'Lawrence of Arabia,' 'The Martian,' 'Dune,' and 'Star Wars: The Rise of Skywalker.' Explore by 4x4 jeep, stay overnight in a Bedouin camp, climb natural rock bridges, and witness some of the darkest skies for stargazing. Sunrise and sunset transform the red sand into shades of gold and purple.",
    experiences: [
      '4x4 jeep desert tour',
      'Bedouin camp overnight',
      'Sunset viewing at Jabal Umm ad Dami',
      'Rock climbing and hiking',
      'Stargazing with local guides',
    ],
    camps: ['Wadi Rum UFO Camp', 'Sun City Camp', 'Memories Aicha Luxury Camp', 'Wadi Rum Night Camp', 'Bubble Luxotel'],
    unesco: true,
  },
  {
    slug: 'dead-sea',
    name: 'Dead Sea',
    country: 'Jordan',
    region: 'Jordan',
    tagline: 'The Lowest Point on Earth',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/middle-east/dead-sea.jpg',
    highlights: ['Floating', 'Mud Baths', 'Sunset Views', 'Waterfall Hike', 'Wellness Resorts'],
    bestTime: 'Apr–Oct',
    duration: '1–2 nights',
    from: '$200',
    description: "The Dead Sea is the lowest point on Earth at 430 meters below sea level — and one of the world's most surreal natural wonders. The water is so salty (10 times saltier than the ocean) that you float effortlessly without swimming. Cover yourself in mineral-rich black mud, float in the buoyant waters, and watch the sun set over the Jordanian hills. The air is oxygen-rich and the water's minerals are famous for their healing properties. The Dead Sea is shrinking rapidly — visit this disappearing wonder while you can.",
    experiences: [
      'Floating in the hypersaline water',
      'Black mud spa treatment',
      'Sunset view across to Israel/Palestine',
      'Mujib River waterfall hike',
      'Luxury resort spa day',
    ],
    camps: ['Kempinski Ishtar Dead Sea', 'Mövenpick Dead Sea', 'Dead Sea Marriott', 'Hilton Dead Sea', 'Spa at the Dead Sea'],
    unesco: false,
  },
  {
    slug: 'amman-jerash',
    name: 'Amman & Jerash',
    country: 'Jordan',
    region: 'Jordan',
    tagline: 'Ancient Roman Ruins & Modern City',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/middle-east/jerash.jpg',
    highlights: ['Roman Theater', 'Citadel', 'Jerash Ruins', 'Rainbow Street', 'Jordan Museum'],
    bestTime: 'Mar–May · Sep–Nov',
    duration: '2–3 nights',
    from: '$220',
    description: "Amman is a modern Arab city built on ancient foundations — the Citadel has been inhabited for over 7,000 years, with Roman, Byzantine, and Umayyad ruins. The Roman Theater (6,000 seats) is still used for performances today. Just 48 kilometers north, Jerash is one of the best-preserved Roman provincial cities in the world — walk through Hadrian's Arch, the Hippodrome, and the colonnaded Cardo Maximus. Rainbow Street offers cafes, art galleries, and a taste of modern Jordanian life.",
    experiences: [
      'Amman Citadel history tour',
      'Roman Theater and Odeon',
      'Full-day Jerash Roman ruins tour',
      'Rainbow Street cafe hopping',
      'Jordan Museum Dead Sea Scrolls',
    ],
    camps: ['Four Seasons Amman', 'St. Regis Amman', 'W Amman', 'InterContinental Jordan', 'Ritz-Carlton Amman'],
    unesco: false,
  },
]