export const kuwaitDestinations = [
  {
    slug: 'kuwait-city',
    name: 'Kuwait City',
    country: 'Kuwait',
    region: 'Kuwait',
    tagline: 'Modern Architecture by the Gulf',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/middle-east/kuwait-city.jpg',
    highlights: ['Kuwait Towers', 'Grand Mosque', 'Souq Mubarakiya', 'Seafront Promenade', 'Sadu House'],
    bestTime: 'Nov–Mar',
    duration: '2–3 nights',
    from: '$260',
    description: "Kuwait City is Kuwait's capital, known for the iconic Kuwait Towers — three blue-green spheres soaring 187 meters with a restaurant and water tower. The Grand Mosque is one of the largest in the Gulf (capacity 10,000). Souq Mubarakiya is the oldest market in Kuwait, selling everything from dates to gold. The seafront promenade (Arabian Gulf Street) is beautiful for sunset walks. Sadu House preserves traditional Bedouin weaving. Kuwait is less visited than its neighbors, offering a more authentic Gulf experience.",
    experiences: [
      'Kuwait Towers panoramic views',
      'Grand Mosque guided tour',
      'Souq Mubarakiya shopping',
      'Seafront promenade sunset',
      'Sadu House weaving exhibits',
    ],
    camps: ['Four Seasons Kuwait', 'Jumeirah Messilah Beach', 'Sheraton Kuwait', 'The Regency Kuwait', 'Symphony Style Kuwait'],
    unesco: false,
  },
  {
    slug: 'failaka-island',
    name: 'Failaka Island',
    country: 'Kuwait',
    region: 'Kuwait',
    tagline: 'Greek Ruins in the Gulf',
    gradient: 'linear-gradient(160deg,#001c14,#002c1e,#004028)',
    image: '/images/middle-east/failaka.jpg',
    highlights: ['Ancient Ikaros', 'Greek Temple', 'Portuguese Fort', 'Abandoned Village', 'Wild Beaches'],
    bestTime: 'Nov–Mar',
    duration: '1 day trip',
    from: '$200',
    description: "Failaka Island is an archaeological treasure in Kuwait Bay, named 'Ikaros' by Alexander the Great's Greeks (who built a temple here). The island also has a Portuguese fort from the 16th century and an abandoned village from the 1990 Iraqi invasion (now a ghost town). The beaches are wild and nearly empty. Ferries from Kuwait City take about an hour. It's a fascinating day trip for history buffs and those seeking something off the beaten path in the Gulf.",
    experiences: [
      'Greek temple ruins',
      'Portuguese fort exploration',
      'Abandoned village photography',
      'Wild beach walks',
      'Archaeology museum',
    ],
    camps: ['Limited accommodations — day trip recommended'],
    unesco: false,
  },
]
