export const lebanonDestinations = [
  {
    slug: 'beirut',
    name: 'Beirut',
    country: 'Lebanon',
    region: 'Lebanon',
    tagline: 'The Paris of the Middle East',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/middle-east/beirut.jpg',
    highlights: ['Pigeon Rocks', 'National Museum', 'Mohammad Al-Amin Mosque', 'Hamra Street', 'Zaitunay Bay'],
    bestTime: 'Apr–Jun · Sep–Oct',
    duration: '3–5 nights',
    from: '$300',
    description: "Beirut is a resilient, hedonistic city that has bounced back from war — the 'Paris of the Middle East' with French-style architecture, Mediterranean coastline, and legendary nightlife. Pigeon Rocks (Raouche) are dramatic sea arches off the coast. The National Museum has the world's largest collection of Phoenician artifacts. The Mohammad Al-Amin Mosque (blue mosque) is an iconic landmark. Hamra Street is a lively thoroughfare of cafes and shops. Zaitunay Bay offers waterfront dining. Beirut is a city of contrasts — ancient ruins beside modern high-rises.",
    experiences: [
      'Pigeon Rocks sunset view',
      'National Museum archaeological treasures',
      'Mohammad Al-Amin Mosque',
      'Hamra Street cafe life',
      'Zaitunay Bay seafood dining',
    ],
    camps: ['Four Seasons Beirut', 'Phoenicia Hotel', 'Saifi Suites', 'Le Gray Beirut', 'The Hilton Beirut'],
    unesco: false,
  },
  {
    slug: 'byblos',
    name: 'Byblos',
    country: 'Lebanon',
    region: 'Lebanon',
    tagline: 'The Oldest Continuously Inhabited City',
    gradient: 'linear-gradient(160deg,#1c1000,#2c1a00,#402600)',
    image: '/images/middle-east/byblos.jpg',
    highlights: ['Byblos Castle', 'Phoenician Temples', 'Old Souk', 'Fishing Port', 'Beaches'],
    bestTime: 'Apr–Oct',
    duration: '1–2 nights',
    from: '$250',
    description: "Byblos (Jbeil) claims to be the oldest continuously inhabited city in the world — inhabited for over 7,000 years. The Crusader-era Byblos Castle is built from Roman stones. The Phoenician temples (including the Temple of Baalat Gebal) date back to 2,800 BC. The old souk is a maze of narrow streets selling souvenirs and local crafts. The fishing port is beautiful at sunset. Byblos also has some of Lebanon's best beaches. UNESCO named Byblos a World Heritage site for its outstanding universal value.",
    experiences: [
      'Byblos Castle Crusader history',
      'Phoenician temple ruins',
      'Old souk shopping',
      'Fishing port sunset walk',
      'Beach day in summer',
    ],
    camps: ['Byblos Sur Mer', 'Ahiram Hotel', 'Victory Byblos', 'Douma Hotel', 'Edde Sands Resort'],
    unesco: true,
  },
  {
    slug: 'baalbek',
    name: 'Baalbek',
    country: 'Lebanon',
    region: 'Lebanon',
    tagline: 'The Grandest Roman Temples',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/middle-east/baalbek.jpg',
    highlights: ['Temple of Bacchus', 'Temple of Jupiter', 'Baalbek Stones', 'Acropolis', 'Sunset Views'],
    bestTime: 'Apr–Oct',
    duration: '1 day trip',
    from: '$280',
    description: "Baalbek (Heliopolis) is home to the largest and best-preserved Roman temples in the world — larger even than the Roman Forum. The Temple of Bacchus is incredibly well preserved, with ornate carvings of vines and grapes. The Temple of Jupiter was the largest Roman temple ever built (only six columns remain, each 19 meters tall). The Baalbek Stones (including the Stone of the Pregnant Woman) weigh over 1,000 tons each — nobody knows how they were moved. Baalbek is a UNESCO World Heritage site.",
    experiences: [
      'Temple of Bacchus walk-through',
      'Temple of Jupiter surviving columns',
      'Baalbek Stones viewing',
      'Acropolis exploration',
      'Beqaa Valley views',
    ],
    camps: ['Baalbek Palmyra Hotel', 'Beqaa Hotel', 'Massabki Hotel', 'Ermita Hotel'],
    unesco: true,
  },
]