export const omanDestinations = [
  {
    slug: 'muscat',
    name: 'Muscat',
    country: 'Oman',
    region: 'Oman',
    tagline: 'The Jewel of Arabia',
    gradient: 'linear-gradient(160deg,#001c14,#002c1e,#004028)',
    image: '/images/middle-east/muscat.jpg',
    highlights: ['Sultan Qaboos Mosque', 'Mutrah Souq', 'Royal Opera House', 'Al Alam Palace', 'Qurum Beach'],
    bestTime: 'Oct–Apr',
    duration: '3–4 nights',
    from: '$300',
    description: "Muscat is the capital of Oman, a beautiful white-washed city nestled between the Gulf of Oman and the Al Hajar Mountains. The Sultan Qaboos Grand Mosque is one of the world's most magnificent modern mosques — its main prayer carpet is the second-largest hand-knotted carpet in the world. Mutrah Souq is one of the oldest markets in Arabia, selling frankincense, silver khanjars (daggers), and Omani sweets. The Royal Opera House is a stunning example of modern Islamic architecture.",
    experiences: [
      'Sultan Qaboos Grand Mosque tour',
      'Mutrah Souq shopping',
      'Royal Opera House performance or tour',
      'Al Alam Palace photo stop',
      'Qurum Beach sunset walk',
    ],
    camps: ['Al Bustan Palace', 'The Chedi Muscat', 'Shangri-La Barr Al Jissah', 'W Muscat', 'Kempinski Muscat'],
    unesco: false,
  },
  {
    slug: 'wahiba-sands',
    name: 'Wahiba Sands',
    country: 'Oman',
    region: 'Oman',
    tagline: 'Rolling Dunes of the Sharqiya',
    gradient: 'linear-gradient(160deg,#2a1a00,#402800,#563600)',
    image: '/images/middle-east/wahiba-sands.jpg',
    highlights: ['Dune Bashing', 'Bedouin Camps', 'Sandboarding', 'Sunset Views', 'Star Gazing'],
    bestTime: 'Oct–Apr',
    duration: '1–2 nights',
    from: '$250',
    description: "Wahiba Sands (also known as Sharqiya Sands) is Oman's vast desert wilderness — rolling dunes stretching 200 kilometers into the Empty Quarter. The dunes range in color from deep red to golden yellow, changing hue with the sun. Experience dune bashing in a 4x4 vehicle, sandboarding down steep dunes, and overnight in a Bedouin-style camp. The night skies here are among the darkest in the Middle East, perfect for stargazing. Bedouin guides share stories of desert life, camel herding, and traditional hospitality.",
    experiences: [
      '4x4 dune bashing',
      'Sandboarding down red dunes',
      'Bedouin camp overnight',
      'Camel trek at sunset',
      'Stargazing with Bedouin guides',
    ],
    camps: ['Desert Nights Camp', 'Sama Al Wasil Desert Camp', 'Arabian Oryx Camp', '1000 Nights Camp', 'Magic Camps'],
    unesco: false,
  },
  {
    slug: 'musandam',
    name: 'Musandam Fjords',
    country: 'Oman',
    region: 'Oman',
    tagline: 'The Norway of Arabia',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/middle-east/musandam.jpg',
    highlights: ['Dhow Cruise', 'Dolphin Watching', 'Snorkeling', 'Mountain Views', 'Zipline'],
    bestTime: 'Oct–Apr',
    duration: '2–3 nights',
    from: '$350',
    description: "The Musandam Peninsula is a geological wonder — a exclave of Oman separated from the rest of the country by the UAE's east coast. Known as the 'Norway of Arabia' for its dramatic fjords (khors), the coastline is best explored by traditional dhow boat. Watch for dolphins playing in the turquoise water, snorkel in coral gardens, and explore the mountain villages accessible only by boat. The world's longest zipline (Khor Najd) offers stunning views over the fjords.",
    experiences: [
      'Traditional dhow cruise',
      'Dolphin watching',
      'Snorkeling in Khor Sham',
      'Khor Najd zipline (world\'s longest)',
      'Mountain village visits',
    ],
    camps: ['Atana Musandam Resort', 'Six Senses Zighy Bay', 'Khasab Hotel', 'Dibba Beach Resort', 'Musandam Camp'],
    unesco: false,
  },
  {
    slug: 'wadi-shab',
    name: 'Wadi Shab',
    country: 'Oman',
    region: 'Oman',
    tagline: 'The Most Beautiful Wadi in Oman',
    gradient: 'linear-gradient(160deg,#001c10,#002c1a,#003c22)',
    image: '/images/middle-east/wadi-shab.jpg',
    highlights: ['Gorge Hike', 'Swimming Pools', 'Secret Waterfall', 'Rock Climbing', 'Picnic Spots'],
    bestTime: 'Oct–Apr',
    duration: '1 day trip',
    from: '$150',
    description: "Wadi Shab is the most spectacular wadi in Oman — a deep canyon carved by water flowing from the mountains to the sea. The hike begins with a short boat ride across a turquoise pool, followed by a 40-minute walk through rocky terrain and palm groves. You'll encounter several deep pools perfect for swimming, culminating in a hidden waterfall inside a dark cave (accessible by swimming through a narrow gap). The water is cool and refreshing, the colors are surreal, and the adventure is unforgettable.",
    experiences: [
      'Wadi gorge hike',
      'Swimming in turquoise pools',
      'Secret waterfall cave swim',
      'Rock jumping (safely)',
      'Picnic by the pools',
    ],
    camps: ['Sama Wadi Shab Resort', 'Wadi Shab Guesthouse', 'Sur Beach Hotel', 'Turtle Beach Resort'],
    unesco: false,
  },
  {
    slug: 'salalah',
    name: 'Salalah',
    country: 'Oman',
    region: 'Oman',
    tagline: 'The Tropical Side of Arabia',
    gradient: 'linear-gradient(160deg,#002010,#003018,#004020)',
    image: '/images/middle-east/salalah.jpg',
    highlights: ['Frankincense Trees', 'Mughsail Beach', 'Al Baleed Archaeological Site', 'Monsoon Green', 'Camel Market'],
    bestTime: 'Jun–Aug (Khareef) or Oct–Apr',
    duration: '3–5 nights',
    from: '$280',
    description: "Salalah is the capital of Oman's Dhofar region, famous for the annual Khareef (monsoon) from June to September when the desert turns lush green. It's unlike anywhere else in Arabia — waterfalls, green mountains, and misty beaches. The frankincense trees of Wadi Dawkah produce the region's famous resin. Mughsail Beach has dramatic blowholes spraying seawater. Al Baleed Archaeological Site is a UNESCO World Heritage site tracing the frankincense trade route. The camel market is a unique cultural experience.",
    experiences: [
      'Frankincense tree grove visit',
      'Mughsail Beach blowholes',
      'Al Baleed UNESCO site',
      'Prophet Job\'s tomb',
      'Camel market at sunrise',
    ],
    camps: ['Alila Hinu Bay', 'Anantara Salalah', 'Salalah Rotana Resort', 'Crowne Plaza Salalah', 'Fanar Hotel'],
    unesco: true,
  },
]