export const qatarDestinations = [
  {
    slug: 'doha',
    name: 'Doha',
    country: 'Qatar',
    region: 'Qatar',
    tagline: "The Gulf's Most Cultured Capital",
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/middle-east/doha.jpg',
    highlights: ['Museum of Islamic Art', 'Souq Waqif', 'The Pearl', 'Desert Safari', 'Katara Village'],
    bestTime: 'Nov–Mar',
    duration: '3–5 nights',
    from: '$360',
    description: "Qatar has invested extraordinary resources into becoming a genuine cultural destination. The Museum of Islamic Art — designed by I.M. Pei (architect of the Louvre pyramid) — is one of the world's finest museums, with treasures spanning 1,400 years. Souq Waqif is a beautifully restored traditional market where you can buy spices, perfumes, and falcons. The Pearl is an artificial island with luxury shopping and dining. Just outside the city, a desert safari takes you to the Inland Sea (Khor Al Adaid), one of the few places where the sea meets desert dunes.",
    experiences: [
      'Museum of Islamic Art galleries',
      'Souq Waqif shopping and dining',
      'The Pearl luxury marina walk',
      'Desert safari to the Inland Sea',
      'Katara Cultural Village exhibits',
    ],
    camps: ['Banana Island Resort', 'Mondrian Doha', 'St. Regis Doha', 'Four Seasons Doha', 'The Chedi Katara'],
    unesco: false,
  },
  {
    slug: 'katara',
    name: 'Katara Cultural Village',
    country: 'Qatar',
    region: 'Qatar',
    tagline: 'Art and Culture by the Sea',
    gradient: 'linear-gradient(160deg,#001c18,#002c28,#004038)',
    image: '/images/middle-east/katara.jpg',
    highlights: ['Amphitheater', 'Mosque', 'Art Galleries', 'Beach', 'Restaurants'],
    bestTime: 'Nov–Mar',
    duration: '1 day trip',
    from: '$280',
    description: "Katara Cultural Village is Doha's hub for arts and culture — a beautifully designed seaside complex with a Roman-style amphitheater (500 seats), a stunning blue and gold mosque, multiple art galleries showcasing Middle Eastern artists, and a public beach. The Opera House hosts international performances. The beach has open-air dining. It's a place where Qatar's vision for cultural diplomacy comes alive, offering a blend of tradition and modernity.",
    experiences: [
      'Amphitheater performance or tour',
      'Katara Mosque photography',
      'Art gallery exhibitions',
      'Beach day with dining',
      'Cultural festival events',
    ],
    camps: ['Katara Hills', 'Mondrian Doha', 'The St. Regis Marsa Arabia', 'Banana Island Resort'],
    unesco: false,
  },
  {
    slug: 'inland-sea',
    name: 'Khor Al Adaid',
    country: 'Qatar',
    region: 'Qatar',
    tagline: 'The Inland Sea',
    gradient: 'linear-gradient(160deg,#001c2c,#003040,#004454)',
    image: '/images/middle-east/inland-sea.jpg',
    highlights: ['Desert Safari', 'Dune Bashing', 'Sea Meeting Desert', 'Sunset Views', 'Overnight Camp'],
    bestTime: 'Nov–Mar',
    duration: '1 overnight',
    from: '$320',
    description: "Khor Al Adaid (the Inland Sea) is a UNESCO-recognized natural wonder — one of the few places in the world where the sea meets a desert dune field. Accessible only by 4x4 vehicles across 40 kilometers of sand dunes, the journey itself is an adventure. At the site, the turquoise lagoon is surrounded by towering dunes. Spend sunset watching the colors change, then stay overnight in a desert camp for stargazing. It's a surreal landscape that feels like another planet.",
    experiences: [
      '4x4 dune bashing to reach the sea',
      'Sunset over the Inland Sea',
      'Swimming in the lagoon',
      'Overnight desert camp',
      'Stargazing in the desert',
    ],
    camps: ['Regency Inland Sea Camp', 'Desert Safari Camp', 'Sealine Beach Resort'],
    unesco: true,
  },
]