export const saudiArabiaDestinations = [
  {
    slug: 'alula',
    name: 'AlUla',
    country: 'Saudi Arabia',
    region: 'Saudi Arabia',
    tagline: "Arabia's Greatest Ancient Treasure",
    gradient: 'linear-gradient(160deg,#2a1a00,#402800,#563600)',
    image: '/images/middle-east/alula.jpg',
    highlights: ['Hegra (Mada\'in Saleh)', 'AlUla Old Town', 'Elephant Rock', 'Maraya Concert Hall', 'Dadan'],
    bestTime: 'Oct–Apr',
    duration: '3–5 nights',
    from: '$450',
    description: "AlUla is Saudi Arabia's crown jewel — a living museum of ancient civilizations. Hegra (Mada'in Saleh) is the first UNESCO World Heritage site in Saudi Arabia, with 111 monumental tombs carved into rose-red cliffs by the Nabataeans (the people who built Petra). AlUla Old Town has been inhabited for 900 years. Elephant Rock is a geological wonder that glows at sunset. Maraya is the world's largest mirrored building (9,740 square meters of glass), reflecting the desert landscape.",
    experiences: [
      'Hegra Nabataean tomb tour',
      'AlUla Old Town heritage walk',
      'Elephant Rock sunset viewing',
      'Maraya concert and dining experience',
      'Dadan archaeological site visit',
    ],
    camps: ['Habitas AlUla', 'Banyan Tree AlUla', 'Shaden Resort', 'Cloud7 Camp', 'Sahary Resort'],
    unesco: true,
  },
  {
    slug: 'riyadh',
    name: 'Riyadh',
    country: 'Saudi Arabia',
    region: 'Saudi Arabia',
    tagline: 'Where Old Arabia Meets the Future',
    gradient: 'linear-gradient(160deg,#1c1000,#2c1a00,#402600)',
    image: '/images/middle-east/riyadh.jpg',
    highlights: ['Kingdom Centre', 'Diriyah', 'National Museum', 'Al Masmak Fortress', 'Edge of the World'],
    bestTime: 'Nov–Mar',
    duration: '3–5 nights',
    from: '$350',
    description: "Riyadh is a city of contrasts — ancient fortresses beside futuristic skyscrapers. Diriyah is the birthplace of the Saudi kingdom, with the At-Turaif district now a UNESCO World Heritage site. The Kingdom Centre Tower (302 meters) offers panoramic views from its sky bridge. The National Museum is one of the Middle East's finest. Just outside the city, the Edge of the World offers dramatic escarpment views over the ancient trade route.",
    experiences: [
      'Diriyah historical district tour',
      'Kingdom Centre sky bridge views',
      'National Museum galleries',
      'Al Masmak Fortress history',
      'Edge of the World escarpment hike',
    ],
    camps: ['Four Seasons Riyadh', 'Ritz-Carlton Riyadh', 'Burj Rafal', 'Narcissus Royal', 'Al Faisaliah Hotel'],
    unesco: true,
  },
  {
    slug: 'jeddah',
    name: 'Jeddah',
    country: 'Saudi Arabia',
    region: 'Saudi Arabia',
    tagline: 'Gateway to the Red Sea',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/middle-east/jeddah.jpg',
    highlights: ['Al-Balad', 'King Fahd Fountain', 'Red Sea Diving', 'Floating Mosque', 'Tayebat Museum'],
    bestTime: 'Oct–Apr',
    duration: '3–4 nights',
    from: '$320',
    description: "Jeddah is Saudi Arabia's most cosmopolitan city, gateway to Mecca and the Red Sea. Al-Balad (Old Town) is a UNESCO World Heritage site with hundreds of coral houses built by wealthy merchants. The King Fahd Fountain is the world's tallest (312 meters). The Red Sea offers world-class diving with pristine reefs. The Floating Mosque appears to hover above the water at high tide.",
    experiences: [
      'Al-Balad heritage walk',
      'King Fahd Fountain evening show',
      'Red Sea diving or snorkeling trip',
      'Floating Mosque visit',
      'Tayebat Museum history exhibits',
    ],
    camps: ['The Ritz-Carlton Jeddah', 'Rosewood Jeddah', 'Park Hyatt Jeddah', 'Assila Hotel', 'Waldorf Astoria Jeddah'],
    unesco: true,
  },
  {
    slug: 'abha',
    name: 'Abha',
    country: 'Saudi Arabia',
    region: 'Saudi Arabia',
    tagline: 'The Green Highlands of Arabia',
    gradient: 'linear-gradient(160deg,#001c14,#002c1e,#004028)',
    image: '/images/middle-east/abha.jpg',
    highlights: ['Habala Village', 'Asir National Park', 'Fog Walkway', 'Rijal Alma Village', 'Jabal Sawda'],
    bestTime: 'Jun–Sep',
    duration: '3–4 nights',
    from: '$300',
    description: "Abha is Saudi Arabia's mountain escape — a cooler, greener world in the Asir Mountains at 2,200 meters elevation. Habala Village is a hanging village where people once lived in cliffside dwellings accessible only by rope. The Fog Walkway offers ethereal views when clouds roll in. Rijal Alma is a perfectly preserved village of stone towers. Jabal Sawda is Saudi Arabia's highest peak (3,015 meters).",
    experiences: [
      'Habala hanging village cable car',
      'Asir National Park hiking trails',
      'Fog Walkway sunrise views',
      'Rijal Alma stone tower village',
      'Jabal Sawda summit hike',
    ],
    camps: ['Abha Palace Hotel', 'Swiss Spirit Al Muhaidb', 'Courtyard Abha', 'Mena Hotel Abha', 'Asir Hotel'],
    unesco: false,
  },
  {
    slug: 'saudi-edge-world',
    name: 'Edge of the World',
    country: 'Saudi Arabia',
    region: 'Saudi Arabia',
    tagline: 'Dramatic Escarpment Views',
    gradient: 'linear-gradient(160deg,#2a1a00,#402800,#563600)',
    image: '/images/middle-east/edge-of-world.jpg',
    highlights: ['Escarpment Views', 'Fossil Hunting', 'Desert Camping', 'Sunset Photography', 'Ancient Trade Route'],
    bestTime: 'Oct–Apr',
    duration: '1–2 nights',
    from: '$200',
    description: "The Edge of the World (Jebel Fihrayn) is one of Saudi Arabia's most dramatic natural wonders — a 300-meter escarpment overlooking the ancient trade route where caravans once carried frankincense across the Arabian Peninsula. The views stretch forever across the barren valley floor. Fossil hunters can find ancient marine fossils in the rocks, evidence that this desert was once underwater. Sunset is the magical hour when the escarpment glows orange and red.",
    experiences: [
      'Escarpment hike to the viewpoint',
      'Fossil hunting in ancient seabed',
      'Sunset photography session',
      'Desert camp overnight',
      'Stargazing in dark skies',
    ],
    camps: ['Edge of World Camp', 'Riyadh Desert Camp', 'Bedouin-style Tents'],
    unesco: false,
  },
]