export const turkeyDestinations = [
  {
    slug: 'istanbul',
    name: 'Istanbul',
    country: 'Turkey',
    region: 'Turkey',
    tagline: 'Where Two Continents Meet',
    gradient: 'linear-gradient(160deg,#001018,#001c2d,#002840)',
    image: '/images/middle-east/istanbul.jpg',
    highlights: ['Hagia Sophia', 'Grand Bazaar', 'Bosphorus Cruise', 'Topkapi Palace', 'Spice Market'],
    bestTime: 'Apr–Jun · Sep–Oct',
    duration: '4–6 nights',
    from: '$240',
    description: "Istanbul is the only city in the world that straddles two continents — and that duality runs through everything. Byzantine churches became Ottoman mosques. Ancient bazaars trade alongside Michelin-starred restaurants. Hagia Sophia, built in 537 AD as a cathedral, then a mosque, now a museum, is one of the world's greatest architectural achievements. The Grand Bazaar has 4,000 shops. Topkapi Palace was home to Ottoman sultans for 400 years. This is a city that overwhelms the senses in the best possible way.",
    experiences: [
      'Hagia Sophia history tour',
      'Grand Bazaar shopping',
      'Bosphorus sunset cruise',
      'Topkapi Palace and harem',
      'Spice Market and Turkish delight',
    ],
    camps: ['Four Seasons Bosphorus', 'Çırağan Palace Kempinski', 'Sultanahmet Palace', 'Ritz-Carlton Istanbul', 'Pera Palace'],
    unesco: true,
  },
  {
    slug: 'cappadocia',
    name: 'Cappadocia',
    country: 'Turkey',
    region: 'Turkey',
    tagline: 'A Landscape From Another World',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/middle-east/cappadocia.jpg',
    highlights: ['Hot Air Balloon Sunrise', 'Fairy Chimneys', 'Cave Hotels', 'Underground Cities', 'Rose Valley'],
    bestTime: 'Apr–Jun · Sep–Nov',
    duration: '3–4 nights',
    from: '$280',
    description: "Cappadocia is genuinely one of the world's most surreal landscapes — thousands of tufa rock formations shaped by millions of years of volcanic activity, riddled with ancient cave churches and honeycombed with underground cities. The hot air balloon sunrise is one of travel's great experiences, with 100+ balloons floating over the fairy chimneys at dawn. Stay in a cave hotel carved into the rock, explore the underground cities of Derinkuyu and Kaymakli (8 levels deep, housing 20,000 people), and hike the Rose Valley's pink-hued canyons.",
    experiences: [
      'Hot air balloon ride at sunrise',
      'Göreme Open Air Museum cave churches',
      'Stay in a cave hotel',
      'Derinkuyu underground city tour',
      'Rose Valley sunset hike',
    ],
    camps: ['Museum Hotel', 'Kayakapi Premium Caves', 'Argos in Cappadocia', 'Sultan Cave Suites', 'Kelebek Special Cave Hotel'],
    unesco: true,
  },
  {
    slug: 'pamukkale',
    name: 'Pamukkale',
    country: 'Turkey',
    region: 'Turkey',
    tagline: 'The Cotton Castle',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/middle-east/pamukkale.jpg',
    highlights: ['Travertine Pools', 'Hierapolis', 'Sunset Views', 'Hot Springs', 'Cleopatra\'s Pool'],
    bestTime: 'Apr–Oct',
    duration: '1–2 nights',
    from: '$200',
    description: "Pamukkale (meaning 'Cotton Castle' in Turkish) is a natural wonder of white travertine terraces formed by calcium-rich hot springs cascading down a 200-meter cliff. Walk barefoot across the terraces (water shoes recommended), bathe in the warm, mineral-rich pools, and watch the sunset turn the white cliffs golden. Above the terraces lies the ancient city of Hierapolis, a UNESCO World Heritage site with a well-preserved theater, necropolis, and Cleopatra's Pool (where you can swim among ancient ruins).",
    experiences: [
      'Travertine terrace walk',
      'Sunset over white cliffs',
      'Hierapolis ancient theater',
      'Cleopatra\'s Pool swim',
      'Hierapolis archaeology museum',
    ],
    camps: ['Doga Thermal Hotel', 'Venus Suite Hotel', 'Pamukkale Thermal Ece Otel', 'Melrose House', 'Spa Hotel Colossae'],
    unesco: true,
  },
  {
    slug: 'ephesus',
    name: 'Ephesus',
    country: 'Turkey',
    region: 'Turkey',
    tagline: 'The Best-Preserved Roman City',
    gradient: 'linear-gradient(160deg,#1c1000,#2c1a00,#402600)',
    image: '/images/middle-east/ephesus.jpg',
    highlights: ['Library of Celsus', 'Great Theater', 'Temple of Artemis', 'Terrace Houses', 'Basilica of St. John'],
    bestTime: 'Apr–Oct',
    duration: '1–2 nights',
    from: '$180',
    description: "Ephesus is one of the world's best-preserved ancient cities — a Roman metropolis on the Aegean coast. Walk down the marble-paved Curetes Street, past the Library of Celsus (one of the most photographed ancient structures in the world), the Great Theater (capacity 25,000, where St. Paul preached), and the Terrace Houses (luxury Roman villas with intact mosaics and frescoes). The Temple of Artemis was one of the Seven Wonders of the Ancient World (only one column remains). The Basilica of St. John marks the apostle's burial site.",
    experiences: [
      'Library of Celsus photo opportunity',
      'Great Theater acoustics demonstration',
      'Terrace Houses mosaic walk',
      'Temple of Artemis single column',
      'Basilica of St. John pilgrimage',
    ],
    camps: ['Ayasoluk Hotel', 'Cella Boutique Hotel', 'Ephesus Hillside Hotel', 'Saint John Hotel', 'Nilya Hotel'],
    unesco: true,
  },
  {
    slug: 'antalya',
    name: 'Antalya',
    country: 'Turkey',
    region: 'Turkey',
    tagline: 'The Turquoise Coast',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/middle-east/antalya.jpg',
    highlights: ['Kaleiçi Old Town', 'Hadrian\'s Gate', 'Düden Waterfalls', 'Konyaaltı Beach', 'Aspendos Theater'],
    bestTime: 'Apr–Jun · Sep–Oct',
    duration: '3–5 nights',
    from: '$260',
    description: "Antalya is the gateway to Turkey's Turquoise Coast (the 'Turkish Riviera'), a stretch of Mediterranean coastline with crystal-clear water, Roman ruins, and beautiful beaches. The old town (Kaleiçi) is a maze of cobblestone streets, Ottoman-era houses, and the Roman-era Hadrian's Gate. Düden Waterfalls plunge directly into the sea. Aspendos has one of the best-preserved Roman theaters in the world (still hosting performances). The region is also home to the Lycian Way, a long-distance hiking trail.",
    experiences: [
      'Kaleiçi old town walking tour',
      'Boat trip to Düden Waterfalls',
      'Aspendos Roman theater visit',
      'Konyaaltı Beach afternoon',
      'Olympos ancient city and flaming rock',
    ],
    camps: ['Akra Antalya', 'Rixos Downtown', 'Tuvana Hotel', 'Kempinski The Dome', 'White Garden Hotel'],
    unesco: false,
  },
  {
    slug: 'mount-nemrut',
    name: 'Mount Nemrut',
    country: 'Turkey',
    region: 'Turkey',
    tagline: 'The Throne of the Gods',
    gradient: 'linear-gradient(160deg,#2a1a00,#402800,#563600)',
    image: '/images/middle-east/nemrut.jpg',
    highlights: ['Sunrise Statues', 'Kommagene Kingdom', 'East & West Terraces', 'Lion Horoscope', 'Greek-Persian Art'],
    bestTime: 'May–Oct',
    duration: '1–2 nights',
    from: '$220',
    description: "Mount Nemrut is one of Turkey's most mysterious and spectacular sites — a 2,150-meter mountain topped with a tumulus (artificial peak) flanked by colossal statues of Greek-Persian gods and King Antiochus I of the Kommagene kingdom. The heads of Zeus, Apollo, Hercules, Tyche, and Antiochus himself once stood 8-9 meters tall, but earthquakes have separated heads from bodies, scattering them across the terraces. Sunrise is the magical hour when the golden light illuminates the statues, creating a scene that feels sacred and ancient.",
    experiences: [
      'Sunrise viewing of the statues',
      'East and West terrace exploration',
      'Lion horoscope zodiac discovery',
      'Kommagene kingdom history',
      'UNESCO World Heritage site walk',
    ],
    camps: ['Nemrut Karadut Hotel', 'Zeus Hotel', 'Sofram Hotel', 'Güneş Hotel', 'Karadut Pansiyon'],
    unesco: true,
  },
]