export const uaeDestinations = [
  {
    slug: 'dubai',
    name: 'Dubai',
    country: 'UAE',
    region: 'UAE',
    tagline: 'The City That Refused to Be Ordinary',
    gradient: 'linear-gradient(160deg,#1a0e00,#2a1c00,#3a2800)',
    image: '/images/middle-east/dubai.jpg',
    highlights: ['Burj Khalifa', 'Luxury Shopping', 'Desert Safari', 'Fine Dining', 'Palm Jumeirah'],
    bestTime: 'Nov–Mar',
    duration: '4–7 nights',
    from: '$380',
    description: "Dubai is a city of relentless ambition — the world's tallest building, most extravagant hotels, and a desert that turns gold at sunset. From the observation deck of Burj Khalifa (828 meters high) to the man-made Palm Jumeirah visible from space, Dubai has reinvented itself into one of the world's great travel destinations. Beyond the glitz, you'll find traditional souks, authentic Emirati cuisine, and desert adventures from dune bashing to camel riding.",
    experiences: [
      'Burj Khalifa observation deck (124th & 148th floors)',
      'Desert safari with dune bashing and BBQ dinner',
      'Dubai Mall and Dubai Fountain show',
      'Traditional abra boat ride in Dubai Creek',
      'Palm Jumeirah monorail and Atlantis Aquaventure',
    ],
    camps: ['Burj Al Arab Jumeirah', 'Atlantis The Palm', 'Armani Hotel Dubai', 'One&Only The Palm', 'Address Downtown'],
    unesco: false,
  },
  {
    slug: 'abu-dhabi',
    name: 'Abu Dhabi',
    country: 'UAE',
    region: 'UAE',
    tagline: 'Culture Meets Modern Grandeur',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/middle-east/abu-dhabi.jpg',
    highlights: ['Sheikh Zayed Mosque', 'Louvre Abu Dhabi', 'Yas Island', 'Desert Liwa', 'Saadiyat Beach'],
    bestTime: 'Nov–Mar',
    duration: '3–5 nights',
    from: '$340',
    description: "Abu Dhabi is the UAE's thoughtful sibling — less flashy than Dubai but richer in culture. The Sheikh Zayed Grand Mosque is one of the world's most beautiful buildings, with 82 white marble domes and the world's largest hand-knotted carpet. The Louvre Abu Dhabi, designed by Jean Nouvel, is genuinely world-class, with a spectacular 'rain of light' dome and loans from the Louvre Paris. Yas Island offers Ferrari World, Warner Bros World, and the Yas Marina Circuit.",
    experiences: [
      'Sheikh Zayed Grand Mosque guided tour',
      'Louvre Abu Dhabi art galleries',
      'Ferrari World roller coasters',
      'Mangrove National Park kayaking',
      'Liwa Desert overnight camp',
    ],
    camps: ['Emirates Palace', 'Four Seasons Al Maryah', 'St. Regis Saadiyat', 'Waldorf Astoria Yas Island', 'Al Wathba Desert Resort'],
    unesco: false,
  },
  {
    slug: 'sharjah',
    name: 'Sharjah',
    country: 'UAE',
    region: 'UAE',
    tagline: 'The UAE\'s Cultural Capital',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/middle-east/sharjah.jpg',
    highlights: ['Sharjah Museum of Islamic Civilization', 'Al Noor Mosque', 'Rain Room', 'Blue Souk', 'Al Qasba'],
    bestTime: 'Nov–Mar',
    duration: '2–3 nights',
    from: '$250',
    description: "Sharjah is the UAE's cultural heart, named UNESCO World Book Capital in 2019. The Sharjah Museum of Islamic Civilization houses thousands of artifacts spanning 1,400 years. The Al Noor Mosque is one of the few in the UAE open to non-Muslim visitors. The Rain Room is an immersive art installation where you walk through rain without getting wet. The Blue Souk (Central Market) offers traditional shopping in stunning architecture.",
    experiences: [
      'Sharjah Museum of Islamic Civilization',
      'Al Noor Mosque guided tour',
      'Rain Room immersive art experience',
      'Blue Souk gold and textile shopping',
      'Al Qasba canal walk and ferris wheel',
    ],
    camps: ['Sheraton Sharjah', 'Chedi Al Bait', 'Radisson Blu Sharjah', 'Hilton Sharjah', 'Al Hayat Hotel Apartments'],
    unesco: true,
  },
  {
    slug: 'ras-al-khaimah',
    name: 'Ras Al Khaimah',
    country: 'UAE',
    region: 'UAE',
    tagline: 'Adventure in the Northern Emirates',
    gradient: 'linear-gradient(160deg,#2a1a00,#402800,#563600)',
    image: '/images/middle-east/ras-al-khaimah.jpg',
    highlights: ['Jebel Jais', 'Longest Zipline', 'Dhayah Fort', 'Suwaidi Pearls', 'Desert Camps'],
    bestTime: 'Oct–Apr',
    duration: '2–4 nights',
    from: '$280',
    description: "Ras Al Khaimah is the UAE's adventure capital, home to Jebel Jais — the country's highest mountain at 1,934 meters. The Jebel Jais Flight is the world's longest zipline (2.83 kilometers). Dhayah Fort offers stunning views of date palms and mountains. Suwaidi Pearls gives insight into the region's pearl diving history. The desert camps here are more authentic and less commercial than Dubai's.",
    experiences: [
      'Jebel Jais mountain drive',
      'World\'s longest zipline experience',
      'Dhayah Fort sunset hike',
      'Suwaidi Pearls cultural tour',
      'Bedouin desert camp overnight',
    ],
    camps: ['The Ritz-Carlton Al Wadi', 'Waldorf Astoria Ras Al Khaimah', 'Longbeach Campground', 'Banyan Tree Ras Al Khaimah', 'Bear Grylls Explorers Camp'],
    unesco: false,
  },
]