export const austriaDestinations = [
  {
    slug: 'vienna',
    name: 'Vienna',
    country: 'Austria',
    region: 'Austria',
    tagline: 'Imperial Palace & Coffeehouse Culture',
    gradient: 'linear-gradient(160deg,#1a0e00,#2a1c00,#3a2800)',
    image: '/images/europe/vienna.jpg',
    highlights: ['Schönbrunn Palace', 'St. Stephen\'s Cathedral', 'Hofburg Palace', 'Belvedere Museum', 'Viennese Coffee', 'Opera Ball'],
    bestTime: 'Apr–Oct',
    duration: '3–5 nights',
    from: '$160',
    description: "Vienna (Wien) is the imperial capital of the Habsburgs — a city of grand palaces, world-class museums, waltz music, and coffeehouse culture that UNESCO declared an Intangible Cultural Heritage. Schönbrunn Palace was the summer residence of Empress Maria Theresa — 1,441 rooms, with the Great Gallery and Hall of Mirrors among the most beautiful. The gardens are free — explore the Gloriette (hilltop pavilion with city views), the Privy Garden, and the world's oldest zoo (Tiergarten Schönbrunn, founded 1752). St. Stephen's Cathedral (Stephansdom) has a tiled roof and the Pummerin bell (21,383 kg). The Hofburg Palace was the winter residence — visit the Imperial Apartments, the Sisi Museum (about Empress Elisabeth), and the Spanish Riding School (Lipizzaner stallions). The Belvedere Palace holds the world's largest collection of Gustav Klimt, including 'The Kiss.' Viennese coffeehouses are UNESCO Intangible Heritage — order a Melange (espresso with milk foam) with a slice of Sachertorte (chocolate cake with apricot jam).",
    experiences: [
      'Schönbrunn Palace tour',
      'St. Stephen\'s tower climb',
      'Hofburg Sisi Museum',
      'Belvedere Klimt collection',
      'Spanish Riding School',
      'Coffeehouse Melange & Sachertorte',
    ],
    camps: ['Hotel Sacher', 'Ritz-Carlton Vienna', 'Palais Coburg', 'Grand Hotel Wien', 'Rosewood Vienna'],
    unesco: true,
  },
  {
    slug: 'salzburg',
    name: 'Salzburg',
    country: 'Austria',
    region: 'Austria',
    tagline: 'The Sound of Music & Mozart\'s Birthplace',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/europe/salzburg.jpg',
    highlights: ['Hohensalzburg Fortress', 'Mirabell Gardens', 'Mozart\'s Birthplace', 'Getreidegasse', 'Salzburg Cathedral', 'Sound of Music Tour'],
    bestTime: 'May–Sep',
    duration: '2–4 nights',
    from: '$150',
    description: "Salzburg is Austria's most beautiful city — a baroque masterpiece on the Salzach River, framed by the Alps, birthplace of Mozart, and filming location of 'The Sound of Music.' Hohensalzburg Fortress towers over the city — reachable by funicular, the fortress has never been conquered, with the Prince's Chambers (furnished in 1500) and a museum of medieval weaponry. Mirabell Gardens were featured in 'The Sound of Music' — the von Trapp children sang 'Do-Re-Mi' around the Pegasus Fountain and on the marble steps. Mozart's Birthplace is at Getreidegasse 9 — a museum with his childhood violin, manuscripts, and portraits. Getreidegasse is the most famous shopping street — wrought-iron guild signs still hang above the entrances. Salzburg Cathedral is a masterpiece of Italian baroque — the baptism font where Mozart was baptized is inside. The 'Sound of Music' bus tour visits Leopoldskron Palace (von Trapp residence), Nonnberg Abbey (where Maria was a nun), and the gazebo (now at Schloss Hellbrunn).",
    experiences: [
      'Hohensalzburg Fortress',
      'Mirabell Gardens sing-along',
      'Mozart\'s birthplace museum',
      'Getreidegasse shopping',
      'Salzburg Cathedral',
      'Sound of Music tour',
    ],
    camps: ['Hotel Sacher Salzburg', 'Schloss Mönchstein', 'Hotel Goldener Hirsch', 'Hinterbräu', 'Hotel Bristol'],
    unesco: true,
  },
  {
    slug: 'innsbruck',
    name: 'Innsbruck',
    country: 'Austria',
    region: 'Austria',
    tagline: 'Capital of the Alps',
    gradient: 'linear-gradient(160deg,#0e1800,#182400,#223000)',
    image: '/images/europe/innsbruck.jpg',
    highlights: ['Nordkette Cable Car', 'Golden Roof', 'Hofburg Palace', 'Bergisel Ski Jump', 'Swarovski Crystal World', 'Olympic History'],
    bestTime: 'Jun–Sep · Dec–Mar',
    duration: '2–4 nights',
    from: '$170',
    description: "Innsbruck is the capital of the Alps — surrounded by mountains (nine over 2,500m), twice host of the Winter Olympics (1964, 1976), and a city where alpine adventure meets imperial architecture. The Nordkette Cable Car is the most spectacular city-to-peak ride in the Alps — from the city center (565m) to Hafelekar (2,334m) in 20 minutes, with views of the Inn Valley and surrounding peaks. The Hungerburg Station (designed by Zaha Hadid) is an architectural highlight. The Golden Roof (Goldenes Dachl) is Innsbruck's most famous landmark — 2,657 fire-gilded copper tiles covering a balcony built for Emperor Maximilian I. The Hofburg Palace was the Habsburgs' imperial residence — visit the Giant's Hall (one of Austria's most beautiful baroque rooms). The Bergisel Ski Jump is Zaha Hadid's futuristic tower (2002) — ride the funicular to the top, walk out to the jump platform (the 60-degree angle is terrifying), and see the view over Innsbruck. Swarovski Crystal World is 15 minutes from Innsbruck — a museum of crystal art and a garden with giants and a grotto.",
    experiences: [
      'Nordkette cable car',
      'Golden Roof balcony',
      'Hofburg Giant\'s Hall',
      'Bergisel ski jump tower',
      'Swarovski Crystal World',
      'Olympiaworld museum',
    ],
    camps: ['Grand Hotel Europa', 'The Penz Hotel', 'Hotel Innsbruck', 'Nala Individuellhotel', 'Weisses Kreuz'],
    unesco: false,
  },
  {
    slug: 'hallstatt',
    name: 'Hallstatt',
    country: 'Austria',
    region: 'Austria',
    tagline: 'The Most Beautiful Village in the Alps',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/europe/hallstatt.jpg',
    highlights: ['Hallstatt Skywalk', 'Salt Mine', 'Evangelical Church', 'Market Square', 'Lake Hallstatt', 'Bone House'],
    bestTime: 'May–Sep',
    duration: '1–2 nights',
    from: '$220',
    description: "Hallstatt is the most photographed village in Austria — a fairy-tale lakeside settlement with a 7,000-year history of salt mining, tucked between Lake Hallstatt and the Dachstein mountains. The village has just 800 residents but millions of Instagram posts — the classic view is from the footbridge at the southern end of the market square. The Hallstatt Skywalk is a viewing platform 350 meters above the village — reached by funicular (start at the salt mine entrance), the platform offers panoramic views of the lake and surrounding mountains. The Salt Mine (Salzwelten Hallstatt) is the oldest in the world — wear traditional mining overalls, slide down wooden miner's slides, and see the 'Man in Salt' (a preserved prehistoric miner). The Evangelical Church's white spire defines the Hallstatt skyline — the church interior is simple but the view from outside is iconic. The Bone House (Beinhaus) is a small chapel with 1,200 painted skulls arranged by family — limited space on the village's small graveyard meant bones were exhumed and stored this way after 10 years.",
    experiences: [
      'Classic viewpoint photo',
      'Hallstatt Skywalk',
      'Salt mine tour',
      'Lake boat rental',
      'Bone house visit',
      'Dachstein glacier',
    ],
    camps: ['Heritage Hotel Hallstatt', 'Seehotel Grüner Baum', 'Hallstatt Hideaway', 'Gasthof Simony', 'Sommerhaus'],
    unesco: true,
  },
]
