export const franceDestinations = [
  {
    slug: 'paris',
    name: 'Paris',
    country: 'France',
    region: 'France',
    tagline: 'The City of Light',
    gradient: 'linear-gradient(160deg,#0a0a15,#1a1a2e,#16213e)',
    image: '/images/europe/paris.jpg',
    highlights: ['Eiffel Tower', 'Louvre Museum', 'Seine Cruise', 'Montmartre', 'Le Marais', 'Pastries'],
    bestTime: 'Apr–Jun · Sep–Oct',
    duration: '3–5 nights',
    from: '$180',
    description: "Paris is the world's most iconic city — a timeless blend of romance, art, cuisine, and architecture that has inspired generations. The Eiffel Tower, built for the 1889 World's Fair, remains the symbol of France and offers breathtaking views from its three levels. The Louvre Museum, housed in a former royal palace, is the world's largest art museum and home to the Mona Lisa, Venus de Milo, and thousands of other masterpieces. A cruise on the Seine River at sunset reveals the city's most beautiful landmarks: Notre-Dame Cathedral, the Musée d'Orsay, and the Conciergerie. Montmartre, with its cobblestone streets and the white-domed Sacré-Cœur Basilica, has been an artist's haven for over a century. Le Marais district offers medieval architecture, trendy boutiques, and some of Paris's best falafel. French cuisine is a UNESCO intangible cultural heritage — from buttery croissants and crusty baguettes to rich coq au vin and delicate macarons. Paris is not just a destination; it's an emotion, a way of life that celebrates beauty, pleasure, and joie de vivre.",
    experiences: [
      'Eiffel Tower summit at sunset',
      'Louvre Museum masterpieces tour',
      'Seine River dinner cruise',
      'Montmartre artists quarter walk',
      'Le Marais food tour',
      'Versailles Palace day trip',
    ],
    camps: ['Four Seasons George V', 'Ritz Paris', 'Le Meurice', 'Shangri-La Paris', 'La Réserve Paris'],
    unesco: true,
  },
  {
    slug: 'provence',
    name: 'Provence',
    country: 'France',
    region: 'France',
    tagline: 'Lavender Fields & Hilltop Villages',
    gradient: 'linear-gradient(160deg,#1a0f18,#2d1a25,#3d2635)',
    image: '/images/europe/provence.jpg',
    highlights: ['Lavender Fields', 'Gordes', 'Roussillon', 'Pont du Gard', 'Aix-en-Provence', 'Market Days'],
    bestTime: 'Jun–Aug (Lavender) · Apr–May & Sep–Oct',
    duration: '4–6 nights',
    from: '$200',
    description: "Provence is the soul of southern France — a landscape of rolling lavender fields, olive groves, sun-drenched vineyards, and hilltop villages that have changed little in centuries. The Luberon Valley is dotted with perched villages like Gordes (built entirely of white stone) and Roussillon (famous for its red ochre cliffs). The Roman aqueduct Pont du Gard is a UNESCO World Heritage site and an engineering marvel. Aix-en-Provence, the former capital of Provence, offers elegant boulevards, fountains, and the atelier of Paul Cézanne. The weekly markets sell everything from fresh goat cheese and honey to handmade pottery and lavender sachets. Provence inspired Van Gogh's most vibrant paintings, and you'll understand why when you see the light — it's different here, softer and golden, especially at sunset over the Alpilles mountains.",
    experiences: [
      'Lavender fields photography at sunset',
      'Gordes hilltop village walk',
      'Roussillon ochre trail hike',
      'Pont du Gard Roman aqueduct',
      'Aix-en-Provence market day',
      'Wine tasting in Châteauneuf-du-Pape',
    ],
    camps: ["Le Couvent des Minimes", 'Villa La Coste', 'La Mirande', 'Domaine Les Roullets', 'Château de Berne'],
    unesco: true,
  },
  {
    slug: 'french-riviera',
    name: 'French Riviera',
    country: 'France',
    region: 'France',
    tagline: 'Glamour & Mediterranean Beauty',
    gradient: 'linear-gradient(160deg,#001f3f,#003366,#004080)',
    image: '/images/europe/cotedazur.jpg',
    highlights: ['Nice Promenade', 'Monte Carlo', 'Saint-Tropez', 'Cannes', 'Èze', 'Villefranche'],
    bestTime: 'May–Jun · Sep–Oct',
    duration: '5–7 nights',
    from: '$350',
    description: "The French Riviera (Côte d'Azur) has been a playground for the rich and famous since the 19th century — a 115-kilometer stretch of Mediterranean coastline from Saint-Tropez to Menton. Nice's Promenade des Anglais is perfect for sunset walks, with the Baie des Anges stretching to the horizon. Monaco's Monte Carlo Casino, Formula 1 circuit, and Prince's Palace define old-money glamour. Saint-Tropez, once a quiet fishing village, became a jet-set icon after Brigitte Bardot. Cannes is synonymous with its film festival and luxury hotels. The medieval village of Èze clings to a cliff 429 meters above the sea, offering the most spectacular views on the coast. Villefranche-sur-Mer has one of the deepest natural harbors in the Mediterranean. The Riviera light has inspired artists from Matisse to Chagall — both have museums in Nice dedicated to their work.",
    experiences: [
      'Nice Promenade sunrise walk',
      'Monaco Grand Prix circuit drive',
      'Èze village and exotic garden',
      'Saint-Tropez beach day',
      'Cannes Croisette luxury shopping',
      'Villefranche harbor swimming',
    ],
    camps: ['Hôtel du Cap-Eden-Roc', 'Grand-Hôtel du Cap-Ferrat', 'Hotel Negresco', 'Château Eza', 'Maybourne Riviera'],
    unesco: false,
  },
  {
    slug: 'bordeaux',
    name: 'Bordeaux',
    country: 'France',
    region: 'France',
    tagline: 'The Wine Capital of the World',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/europe/bordeaux.jpg',
    highlights: ['Cité du Vin', 'Place de la Bourse', 'Saint-Émilion', 'Wine Châteaux', 'Mirror d\'Eau'],
    bestTime: 'May–Oct',
    duration: '3–4 nights',
    from: '$170',
    description: "Bordeaux is the wine capital of the world — a UNESCO-listed city of 18th-century architecture, where the Garonne River curves through the center and 350 historic buildings glow golden at sunset. The Cité du Vin is a stunning modern wine museum with interactive exhibits and a rooftop bar with panoramic views. Place de la Bourse and the Miroir d'Eau (the world's largest reflecting pool) are the city's most photographed spot. Just outside the city, the vineyards of Saint-Émilion produce some of the world's most expensive wines — the village itself is a UNESCO World Heritage site, with underground catacombs carved from limestone. Bordeaux is also a food city — the Marché des Capucins is a paradise for oysters, foie gras, and canelés (the city's signature rum-vanilla pastry).",
    experiences: [
      'Cité du Vin wine museum',
      'Saint-Émilion vineyard tour',
      'Mirror d\'Eau sunset photos',
      'Marché des Capucins food tour',
      'Garonne river cruise',
      'Wine château tasting and lunch',
    ],
    camps: ['Les Sources de Caudalie', 'Hôtel Burdigala', 'InterContinental Bordeaux', 'Yndo Hôtel', 'La Maison Bord’eaux'],
    unesco: true,
  },
  {
    slug: 'loire-valley',
    name: 'Loire Valley',
    country: 'France',
    region: 'France',
    tagline: 'Fairytale Châteaux & Vineyards',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/europe/loire.jpg',
    highlights: ['Château de Chambord', 'Chenonceau', 'Cheverny', 'Amboise', 'Villandry Gardens'],
    bestTime: 'Apr–Oct',
    duration: '3–5 nights',
    from: '$190',
    description: "The Loire Valley is France's 'Garden of Eden' — a UNESCO World Heritage landscape of fairytale châteaux, rolling vineyards, and medieval villages strung along France's longest river. Château de Chambord is the largest and most extravagant, with 440 rooms, 365 chimneys, and a double-spiral staircase attributed to Leonardo da Vinci. Château de Chenonceau stretches across the Cher River, its graceful arches reflected in the water — it was home to some of the most powerful women in French history. Cheverny inspired the castle in Hergé's Tintin comics. Villandry is famous for its three-tiered Renaissance gardens. The valley is also perfect for cycling — the Loire à Vélo bike trail runs 800 kilometers through vineyards and villages. Sample local wines like Sancerre, Vouvray, and Chinon at family-run domaines.",
    experiences: [
      'Chambord staircase and rooftop',
      'Chenonceau river crossing',
      'Villandry gardens tour',
      'Loire à Vélo bike rental',
      'Sancerre wine tasting',
      'Amboise Clos Lucé (da Vinci\'s home)',
    ],
    camps: ['Château de la Barre', 'Fleur de Loire', 'Domaine des Hauts de Loire', 'Château de Brissac', 'Les Hautes Roches'],
    unesco: true,
  },
]