export const germanyDestinations = [
  {
    slug: 'berlin',
    name: 'Berlin',
    country: 'Germany',
    region: 'Germany',
    tagline: 'History, Art & Cool',
    gradient: 'linear-gradient(160deg,#1a0a0a,#2d1414,#3d1e1e)',
    image: '/images/europe/berlin.jpg',
    highlights: ['Brandenburg Gate', 'Berlin Wall', 'Reichstag Dome', 'Museum Island', 'East Side Gallery', 'Currywurst'],
    bestTime: 'May–Sep',
    duration: '3–5 nights',
    from: '$140',
    description: "Berlin is a city that has remade itself again and again — from Prussian capital to Nazi headquarters to divided Cold War city to reunited creative capital of Europe. The Brandenburg Gate is Berlin's most famous landmark — it stood in no-man's-land during the Cold War, a symbol of division before becoming the symbol of reunification in 1989. The Berlin Wall's longest remaining section is the East Side Gallery — 1.3 kilometers of murals painted by 118 artists. The Reichstag Building is the home of German parliament — climb Norman Foster's glass dome for 360-degree views and a glimpse into democracy. Museum Island is a UNESCO World Heritage site — five museums (the Pergamon's Ishtar Gate and the Neues Museum's bust of Nefertiti are unmissable). Berlin is a food city — currywurst (sausage with curry ketchup and curry powder) is the local specialty. Berlin is also Europe's coolest club city — Berghain is legendary, but there are hundreds of other clubs, bars, and abandoned industrial spaces turned into art venues.",
    experiences: [
      'Brandenburg Gate photo',
      'East Side Gallery art walk',
      'Reichstag Dome climb',
      'Pergamon Museum Ishtar Gate',
      'Berlin Wall memorial',
      'Currywurst at Konnopke\'s',
    ],
    camps: ['Hotel Adlon Kempinski', 'Ritz-Carlton Berlin', 'The Mandala', 'SO/ Berlin Das Stue', 'Orania.Berlin'],
    unesco: true,
  },
  {
    slug: 'munich',
    name: 'Munich',
    country: 'Germany',
    region: 'Germany',
    tagline: 'Bavarian Charm & Oktoberfest',
    gradient: 'linear-gradient(160deg,#1c1000,#2c1a00,#402600)',
    image: '/images/europe/munich.jpg',
    highlights: ['Marienplatz', 'Hofbräuhaus', 'Nymphenburg Palace', 'English Garden', 'Dachau Memorial', 'Oktoberfest'],
    bestTime: 'May–Sep',
    duration: '3–5 nights',
    from: '$160',
    description: "Munich (München) is the capital of Bavaria — a city of beer gardens, lederhosen, and world-class museums, with the Alps on the horizon. Marienplatz is Munich's central square — the New Town Hall's Glockenspiel reenacts a 16th-century wedding with dancing cooper figures. The Hofbräuhaus is Munich's most famous beer hall — tourists and locals fill the massive hall drinking one-liter Maß of beer and eating pretzels, sausages, and roast pork. Nymphenburg Palace was the summer residence of Bavarian kings — the 'Schloss' and its gardens are magnificent. The English Garden is larger than Central Park — surfers ride the man-made wave on the Eisbach River. Dachau Concentration Camp Memorial is 20 minutes from the city — the first Nazi concentration camp, now a sobering memorial and museum. September's Oktoberfest is the world's largest Volksfest — 6 million visitors drink 7 million liters of beer in 14 tents over 16 days. Munich also has world-class art — the Alte Pinakothek has Dürer's 'Self-Portrait' in fur.",
    experiences: [
      'Marienplatz Glockenspiel',
      'Hofbräuhaus beer hall',
      'Nymphenburg Palace',
      'English Garden surfers',
      'Dachau Memorial tour',
      'Oktoberfest visit (Sep)',
    ],
    camps: ['Bayerischer Hof', 'Mandarin Oriental', 'Hotel Vier Jahreszeiten', 'Rosewood Munich', 'Louis Hotel'],
    unesco: false,
  },
  {
    slug: 'neuschwanstein',
    name: 'Neuschwanstein Castle',
    country: 'Germany',
    region: 'Germany',
    tagline: 'The Fairytale Castle',
    gradient: 'linear-gradient(160deg,#0e1400,#182000,#222c00)',
    image: '/images/europe/neuschwanstein.jpg',
    highlights: ['Neuschwanstein', 'Hohenschwangau', 'Marienbrücke Bridge', 'Alpsee Lake', 'Wittelsbach Crown Jewels'],
    bestTime: 'Apr–Oct',
    duration: '1–2 nights',
    from: '$200',
    description: "Neuschwanstein Castle is the fairytale castle that inspired Walt Disney — perched on a rugged hill in the Bavarian Alps, built by King Ludwig II of Bavaria as a fantasy retreat from the real world. The castle's Romanesque Revival towers and turrets were never finished — Ludwig died under mysterious circumstances in 1886, having lived in the castle for only 11 nights. The interior is spectacular — the Throne Room (never completed) has a 13-meter chandelier, and the Singer's Hall is modeled on a medieval knights' hall. The Marienbrücke (Mary's Bridge) is the best viewpoint for the classic postcard photo of the castle. Combine your visit with Hohenschwangau Castle (where Ludwig grew up), a walk around Alpsee Lake, or a hike to Tegelberg (1,720m) with paragliding. Book tickets online months in advance — Neuschwanstein gets 1.5 million visitors a year. The castle is a 2-hour drive from Munich or a scenic train ride via Füssen.",
    experiences: [
      'Neuschwanstein throne room',
      'Marienbrücke view',
      'Hohenschwangau Castle',
      'Alpsee lake walk',
      'Tegelberg cable car',
      'Füssen old town',
    ],
    camps: ['Schlossrestaurant Neuschwanstein', 'Hotel Alpenstuben', 'Villa Ludwig', 'Hotel Schlosskrone', 'Plattl\'s'],
    unesco: false,
  },
  {
    slug: 'rhine-valley',
    name: 'Rhine Valley',
    country: 'Germany',
    region: 'Germany',
    tagline: 'Castles, Vineyards & Romantic River',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/europe/rhine.jpg',
    highlights: ['Lorelei Rock', 'Marksburg Castle', 'KD River Cruise', 'Bacharach', 'Rüdesheim', 'Wine Tasting'],
    bestTime: 'Apr–Oct',
    duration: '2–3 nights',
    from: '$170',
    description: "The Rhine Valley is Germany's most romantic landscape — a 65-kilometer stretch of the Rhine River between Bingen and Koblenz, dotted with medieval castles, terraced vineyards, and half-timbered villages. The Lorelei is a 132-meter slate rock where, according to legend, a siren distracted sailors with her singing — the rock creates an echo that once made navigation dangerous. Marksburg Castle is the only hilltop castle on the Middle Rhine never destroyed — you can see the kitchen, armory, and torture chamber. The best way to see the valley is on a KD Rhine River cruise — pass 40 castles between Rüdesheim and Koblenz. Bacharach is the most beautiful town — explore its medieval walls, gothic churches, and timber-framed houses. Rüdesheim is the wine capital — ride the cable car to the Niederwald Monument for valley views, then taste Riesling from family-owned wineries. The valley is a UNESCO World Heritage site — visit in October for the wine festival or Christmas for the markets.",
    experiences: [
      'Lorelei rock viewpoint',
      'Marksburg Castle tour',
      'KD Rhine cruise',
      'Bacharach old town',
      'Rüdesheim cable car',
      'Riesling wine tasting',
    ],
    camps: ['Hotel Burg Stahleck', 'Romantik Hotel Im Rößle', 'Hotel Lindenwirt', 'Kronenschlösschen', 'Hotel am Markt'],
    unesco: true,
  },
  {
    slug: 'black-forest',
    name: 'Black Forest',
    country: 'Germany',
    region: 'Germany',
    tagline: 'Cuckoo Clocks & Cherry Cake',
    gradient: 'linear-gradient(160deg,#001c14,#002c1e,#004028)',
    image: '/images/europe/black-forest.jpg',
    highlights: ['Titisee Lake', 'Triberg Waterfalls', 'Cuckoo Clocks', 'Black Forest Cake', 'Schluchsee', 'Hiking'],
    bestTime: 'May–Oct',
    duration: '3–4 nights',
    from: '$150',
    description: "The Black Forest (Schwarzwald) is Germany's most famous forest — a mountainous region of dense pine forests, crystal-clear lakes, traditional half-timbered villages, and the home of cuckoo clocks and Black Forest cake (Schwarzwälder Kirschtorte). Triberg is the cuckoo clock capital — see the world's largest cuckoo clock and watch craftsmen carve the traditional timepieces. Triberg Waterfalls is one of Germany's highest waterfalls (163 meters, over 7 tiers). Titisee is the most popular lake — swim, paddle a 'Bötle' (small boat), or walk the shoreline path to the neighboring village of Neustadt. Schluchsee is the largest lake (1.3 km wide, 7.5 km long) — perfect for sailing, SUP boarding, and swimming in clear water. The Black Forest is a hiking paradise with 23,000 kilometers of marked trails — the Westweg (285 km from Pforzheim to Basel) is the most famous. Eat Black Forest cake (chocolate sponge, cherry filling, whipped cream, Kirsch cherry brandish) in a traditional Gasthof.",
    experiences: [
      'Triberg cuckoo clock shop',
      'Waterfalls hike',
      'Titisee rowboat',
      'Schluchsee paddleboard',
      'Westweg day hike',
      'Black Forest cake tasting',
    ],
    camps: ['Parkhotel Adler', 'Hotel Saigerhof', 'Seehotel Wiesler', 'Hotel Jägerhaus', 'Alemannenhof'],
    unesco: false,
  },
]