export const greeceDestinations = [
  {
    slug: 'santorini',
    name: 'Santorini',
    country: 'Greece',
    region: 'Greece',
    tagline: 'Aegean Luxury & Sunsets',
    gradient: 'linear-gradient(160deg,#001f3f,#003366,#004080)',
    image: '/images/europe/santorini.jpg',
    highlights: ['Oia Sunset', 'Blue Domes', 'Caldera Views', 'Volcanic Beaches', 'Winery Tours', 'Akrotiri'],
    bestTime: 'May–Jun · Sep–Oct',
    duration: '3–5 nights',
    from: '$220',
    description: "Santorini (Thira) is the crown jewel of the Cyclades — a volcanic island with a caldera so dramatic that many believe it inspired the myth of Atlantis. The island's east coast was blown away by a massive eruption in 1600 BC, leaving a crescent-shaped ring of cliffs 300 meters high, with whitewashed villages perched on the edge. Oia is the sunset capital of the world — photographers gather two hours before sunset to capture the iconic view of blue-domed churches and white houses glowing orange in the fading light. The caldera-facing villages — Fira, Firostefani, and Imerovigli — offer the best views over the sea-filled crater (the volcano is visible in the middle). The island's volcanic beaches have black sand (Perissa, Kamari) or red sand (Red Beach, near Akrotiri). Santorini wine is unique — the volcanic soil produces Assyrtiko grapes for crisp white wines; visit wineries like SantoWines (with caldera views). Akrotiri is a Minoan Bronze Age settlement preserved under volcanic ash (like Pompeii), dating to 1600 BC.",
    experiences: [
      'Oia sunset two hours early',
      'Caldera cliff walk',
      'Black sand beach day',
      'Wine tasting at SantoWines',
      'Akrotiri excavation',
      'Volcano boat tour',
    ],
    camps: ['Grace Hotel', 'Canaves Oia Epitome', 'Katikies Santorini', 'Andronis Luxury Suites', 'Mystique Santorini'],
    unesco: true,
  },
  {
    slug: 'athens',
    name: 'Athens',
    country: 'Greece',
    region: 'Greece',
    tagline: 'Cradle of Western Civilization',
    gradient: 'linear-gradient(160deg,#1c1000,#2c1a00,#402600)',
    image: '/images/europe/acropolis.jpg',
    highlights: ['Acropolis', 'Parthenon', 'Acropolis Museum', 'Plaka', 'Temple of Olympian Zeus', 'Souvlaki'],
    bestTime: 'Apr–Jun · Sep–Oct',
    duration: '3–4 nights',
    from: '$140',
    description: "Athens is the cradle of Western civilization — a sprawling metropolis where the 2,500-year-old Acropolis dominates the modern city. The Acropolis is the highest point of ancient Athens — the Parthenon is the iconic temple to Athena, built between 447 and 432 BC, with 46 outer columns and a statue of Athena made of gold and ivory (12 meters tall) inside. The Erechtheion is the temple with the Porch of Maidens (six female statues serving as columns — the originals are in the Acropolis Museum). The Acropolis Museum (opened 2009) is essential — the glass floor reveals archaeological excavations, and the Parthenon Gallery displays the surviving sculptures in full natural light. The Plaka is the old neighborhood at the foot of the Acropolis — buy souvenirs, drink coffee in hidden squares, and see the Roman Agora and Hadrian's Library. The Temple of Olympian Zeus had 104 Corinthian columns (15 remain), one of the largest temples in the ancient world. Eat souvlaki (grilled meat skewers) or gyros in a pita at a taverna — with €5, you can eat well.",
    experiences: [
      'Acropolis sunrise',
      'Parthenon photo',
      'Acropolis Museum',
      'Plaka stroll',
      'Temple of Olympian Zeus',
      'Souvlaki dinner',
    ],
    camps: ['Hotel Grande Bretagne', 'King George Hotel', 'The Dolli', 'Brettos Hotel', 'Andronis Athens'],
    unesco: true,
  },
  {
    slug: 'crete',
    name: 'Crete',
    country: 'Greece',
    region: 'Greece',
    tagline: 'Ancient Minoan Palaces & Pink Sand Beaches',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/europe/crete.jpg',
    highlights: ['Knossos Palace', 'Elafonisi Beach', 'Samaria Gorge', 'Chania Old Town', 'Spinalonga Island', 'Cretan Diet'],
    bestTime: 'May–Oct',
    duration: '5–7 nights',
    from: '$170',
    description: "Crete is the largest Greek island — a land of ancient Minoan palaces, rugged mountains, white-sand beaches with pink coral, and the famously healthy Cretan diet. Knossos Palace is the most important archaeological site in Greece — the ceremonial and political center of the Minoan civilization (2000-1350 BC), with a labyrinth of rooms that may have inspired the myth of the Minotaur. Elafonisi Beach is the most famous pink sand beach — the coral has pulverized into the sand, creating a pink hue against turquoise water (the lagoon is shallow, perfect for families). Samaria Gorge is one of Europe's longest gorges (16 km) — a 5-7 hour hike from the Omalos Plateau to Agia Roumeli on the Libyan Sea, passing through the 'Iron Gates' (only 3 meters wide and 300 meters high). Chania is Crete's most beautiful city — Venetian harbor, Ottoman mosque, Egyptian lighthouse, and maze of alleys. Spinalonga Island is a former leper colony (1903-1957) — take a boat from Elounda, see the abandoned village and fort. The Cretan diet (olive oil, fresh vegetables, wine, wild greens) is one of the world's healthiest.",
    experiences: [
      'Knossos throne room',
      'Elafonisi pink sand',
      'Samaria Gorge hike',
      'Chania harbor sunset',
      'Spinalonga boat',
      'Cretan diet dinner',
    ],
    camps: ['Blue Palace', 'Domes of Elounda', 'St. Nicolas Bay', 'The Royal Senses', 'Ammos Residence'],
    unesco: true,
  },
  {
    slug: 'mykonos',
    name: 'Mykonos',
    country: 'Greece',
    region: 'Greece',
    tagline: 'Party Island & White-Washed Beauty',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/europe/mykonos.jpg',
    highlights: ['Little Venice', 'Windmills', 'Paradise Beach', 'Delos Island', 'Nammos', 'Psarou Beach'],
    bestTime: 'Jun–Sep',
    duration: '3–5 nights',
    from: '$280',
    description: "Mykonos is the most famous Greek party island — but also a beautiful Cycladic town of white-washed cubes, blue doors, and bougainvillea-draped alleys. Little Venice is Mykonos Town's most picturesque quarter — houses built right on the water's edge, now home to bars and restaurants with sunset views (but expensive drinks). The Windmills (Kato Mili) are Mykonos's most photographed landmark — 16 windmills built by the Venetians in the 16th century, lined up on a hill overlooking the sea. Paradise Beach is the main party beach — Super Paradise (gay-friendly), Paranga (chill), and Scorpios (boho). Psarou Beach is the celebrity beach — Nammos is the beach club to see and be seen (book a sunbed in advance, bring €100+ for lunch). Delos Island is a 30-minute boat trip — one of the most important archaeological sites in Greece (UNESCO), birthplace of Apollo and Artemis, a sacred island where no one is allowed to live. Mykonos is expensive — expect to pay €50 for a taxi from the port, €15 for a beer, and €200+ for a night's accommodation in high season.",
    experiences: [
      'Little Venice sunset',
      'Windmills photo',
      'Paradise Beach day',
      'Psarou Beach Nammos',
      'Delos archaeological tour',
      'Mykonos Town alleys',
    ],
    camps: ['Bill & Coo Suites', 'Cavo Tagoo', 'Kalesma Mykonos', 'Santa Marina', 'Mykonos Theoxenia'],
    unesco: false,
  },
  {
    slug: 'rhodes',
    name: 'Rhodes',
    country: 'Greece',
    region: 'Greece',
    tagline: 'Medieval Knights & Ancient Ruins',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/europe/rhodes.jpg',
    highlights: ['Medieval Town', 'Palace of Grand Master', 'Lindos Acropolis', 'Valley of Butterflies', 'Anthony Quinn Bay'],
    bestTime: 'May–Oct',
    duration: '4–6 nights',
    from: '$150',
    description: "Rhodes is one of Greece's largest islands — famous for its UNESCO-listed medieval capital, the ancient Acropolis of Lindos, and beautiful coves. The Medieval Town of Rhodes is the best-preserved fortified city in Europe — the Knights of St. John built 4-kilometer walls in the 14th century, inside is a maze of cobblestone alleys, Gothic buildings, and the Palace of the Grand Master (restored in 1937 by the Italians). Lindos is a 2,500-year-old acropolis on a 116-meter rock — climb the 250 steps (or donkeys) for views over the white-washed village and St. Paul's Bay, with a 4th-century BC Temple of Athena Lindia. The Valley of Butterflies (Petaloudes) has thousands of Jersey tiger moths from June to September — the area is a nature reserve with waterfalls and pools. Anthony Quinn Bay is a pebble cove with turquoise water, named after the actor who bought the land (he fell in love with it while filming 'The Guns of Navarone' in 1960). Prasonisi is a peninsula at the southern tip where the Aegean and Mediterranean meet — in summer, a sandbar connects the peninsula to the main island, with windsurfing on one side and kiteboarding on the other.",
    experiences: [
      'Medieval Town walls',
      'Palace of Grand Master',
      'Lindos Acropolis climb',
      'Butterfly Valley walk',
      'Anthony Quinn swim',
      'Prasonisi windsurfing',
    ],
    camps: ['Katikies Rhodes', 'Lindos Blu', 'Sheraton Rhodes', 'Electra Palace', 'Atrium Platinum'],
    unesco: true,
  },
]
