export const icelandDestinations = [
  {
    slug: 'golden-circle',
    name: 'Golden Circle',
    country: 'Iceland',
    region: 'Iceland',
    tagline: 'Iceland\'s Most Famous Route',
    gradient: 'linear-gradient(160deg,#00082a,#001040,#001858)',
    image: '/images/europe/golden-circle.jpg',
    highlights: ['Gullfoss', 'Geysir', 'Þingvellir', 'Kerid Crater', 'Faxi Waterfall', 'Secret Lagoon'],
    bestTime: 'Jun–Aug · Sep–Mar (Aurora)',
    duration: '1 day trip',
    from: '$120',
    description: "The Golden Circle is Iceland's most famous driving route — a 300-kilometer loop from Reykjavik that visits three of Iceland's most spectacular natural wonders in a single day. Gullfoss ('Golden Falls') is a 32-meter, two-tiered waterfall that drops into a dramatic canyon — on sunny days, a rainbow appears in the spray. Geysir is the original geyser (all others are named after it) — it now erupts rarely, but neighboring Strokkur erupts every 5-10 minutes, blasting boiling water 30 meters into the air. Þingvellir National Park is a UNESCO World Heritage site — the rift valley where the North American and Eurasian tectonic plates are pulling apart (the canyon is the Almannagjá fault). The park was the site of Iceland's parliament from 930 AD (the world's oldest continuous parliament). Kerid Crater is a 3,000-year-old volcanic crater lake with bright blue water and red volcanic rock — you can walk the rim in 15 minutes. The Secret Lagoon (Gamla Laugin) is the oldest swimming pool in Iceland (built 1891), a geothermal pool less crowded than the Blue Lagoon.",
    experiences: [
      'Gullfoss spray rainbow',
      'Strokkur geyser eruption',
      'Þingvellir rift walk',
      'Kerid crater rim',
      'Faxi waterfall',
      'Secret Lagoon soak',
    ],
    camps: ['Ion Adventure Hotel', 'Hotel Rangá', 'Frost and Fire Hotel', 'Nesjavellir', 'Skálakot Manor Hotel'],
    unesco: true,
  },
  {
    slug: 'south-coast',
    name: 'South Coast',
    country: 'Iceland',
    region: 'Iceland',
    tagline: 'Waterfalls, Black Sand & Glaciers',
    gradient: 'linear-gradient(160deg,#001018,#001c2d,#002840)',
    image: '/images/europe/south-coast.jpg',
    highlights: ['Skógafoss', 'Seljalandsfoss', 'Reynisfjara Black Sand Beach', 'Jökulsárlón', 'Vatnajökull', 'Diamond Beach'],
    bestTime: 'Jun–Sep',
    duration: '2–3 days',
    from: '$250',
    description: "Iceland's South Coast is a 400-kilometer stretch of waterfalls, black sand beaches, glaciers, and the country's most dramatic landscapes. Skógafoss is a 60-meter waterfall with a drop so wide you'll feel the spray 200 meters away — the 'Rainbow Waterfall' (on sunny days, a double rainbow appears). Seljalandsfoss is the waterfall you can walk behind — a 65-meter drop into a pool, with a path that goes completely behind the cascade (waterproofs essential). Reynisfjara Black Sand Beach is famous for its basalt columns (like organ pipes), roaring waves (sneaker waves are dangerous — don't turn your back on the ocean), and Reynisdrangar sea stacks (trolls turned to stone by the rising sun). Jökulsárlón is the glacier lagoon — icebergs calve from Breiðamerkurjökull glacier (a tongue of Vatnajökull, Europe's largest glacier), float into the lagoon, and wash up on the black sand of Diamond Beach (where they look like diamonds). Glacier hiking and ice cave tours leave from the lagoon area in winter (Nov–Mar).",
    experiences: [
      'Skógafoss rainbow',
      'Behind Seljalandsfoss',
      'Reynisfjara black sand',
      'Jökulsárlón icebergs',
      'Diamond Beach photos',
      'Vatnajökull hike (winter)',
    ],
    camps: ['Fosshotel Glacier Lagoon', 'Hótel Klaustur', 'Magma Hotel', 'Umi Hotel', 'Old Airline Guesthouse'],
    unesco: true,
  },
  {
    slug: 'blue-lagoon',
    name: 'Blue Lagoon',
    country: 'Iceland',
    region: 'Iceland',
    tagline: 'Geothermal Spa in a Lava Field',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/europe/blue-lagoon.jpg',
    highlights: ['Geothermal Water', 'Silica Mud Mask', 'Steam Caves', 'In-Water Bar', 'The Retreat Spa', 'Lava Views'],
    bestTime: 'Year-round',
    duration: 'half day',
    from: '$80',
    description: "The Blue Lagoon (Bláa Lónið) is Iceland's most famous attraction — a geothermal spa in a lava field on the Reykjanes Peninsula, 20 minutes from Keflavík Airport and 40 minutes from Reykjavík. The water is milky blue (not naturally — it's the silica and minerals suspended in the 37-40°C water), with an average depth of 1.2 meters. The lagoon is man-made — it's actually runoff from the Svartsengi geothermal power plant, which pumps superheated water from 2,000 meters below ground and uses it to generate electricity and heat for nearby towns before sending the mineral-rich water to the lagoon. The silica mud mask is free — apply the white silica to your face (it exfoliates and cleanses), leave for 10 minutes, then rinse. The Blue Lagoon has steam caves (caves filled with steam), an in-water bar (order a smoothie or beer while floating), and a sauna with floor-to-ceiling windows overlooking the lava field. The Retreat Spa (extra cost) is a more exclusive experience — private changing rooms, a separate lagoon, and a spa treatment. Book your Blue Lagoon ticket weeks or months ahead — the time-slots sell out, especially in summer.",
    experiences: [
      'Milky blue water swim',
      'Silica mud mask',
      'Steam cave relax',
      'In-water smoothie',
      'Lava field walk',
      'The Retreat (luxury)',
    ],
    camps: ['The Retreat at Blue Lagoon', 'Northern Light Inn', 'Hotel Berg', 'Marriott Keflavik', 'Reykjavik Konsulat'],
    unesco: false,
  },
]