export const italyDestinations = [
  {
    slug: 'rome',
    name: 'Rome',
    country: 'Italy',
    region: 'Italy',
    tagline: 'The Eternal City',
    gradient: 'linear-gradient(160deg,#1a0f0a,#2d1b14,#3d2b1f)',
    image: '/images/europe/rome.jpg',
    highlights: ['Colosseum', 'Vatican City', 'Trevi Fountain', 'Pantheon', 'Trastevere', 'Gelato'],
    bestTime: 'Apr–May · Sep–Oct',
    duration: '4–6 nights',
    from: '$160',
    description: "Rome is the Eternal City — a sprawling open-air museum where 2,800 years of history unfold at every turn. The Colosseum, the largest amphitheater ever built, once held 50,000 spectators watching gladiators. The Roman Forum was the center of public life, where Caesar spoke and emperors triumphed. Vatican City, the world's smallest sovereign state, contains St. Peter's Basilica (the largest church on earth) and the Sistine Chapel, where Michelangelo's ceiling is one of the greatest achievements of Western art. The Pantheon's unreinforced concrete dome remains the world's largest, 1,900 years after it was built. Throw a coin into the Trevi Fountain to ensure your return. Beyond the monuments, Rome is alive — trattorias serve pasta cacio e pepe, pizzerias bake thin-crust Roman pizza, and gelaterias offer the world's best ice cream.",
    experiences: [
      'Colosseum underground tour',
      'Vatican Museums early entry',
      'Trevi Fountain at midnight',
      'Trastevere food walking tour',
      'Roman Forum & Palatine Hill',
      'Pasta making class',
    ],
    camps: ['Hotel de Russie', 'Hotel Hassler', 'J.K. Place Roma', 'Hotel Eden', 'Portrait Roma'],
    unesco: true,
  },
  {
    slug: 'florence',
    name: 'Florence',
    country: 'Italy',
    region: 'Italy',
    tagline: 'Birthplace of the Renaissance',
    gradient: 'linear-gradient(160deg,#1c1000,#2c1a00,#402600)',
    image: '/images/europe/florence.jpg',
    highlights: ['Duomo', 'Uffizi Gallery', 'David', 'Ponte Vecchio', 'Piazzale Michelangelo', 'Tuscan Food'],
    bestTime: 'Apr–Jun · Sep–Oct',
    duration: '3–5 nights',
    from: '$190',
    description: "Florence (Firenze) is the birthplace of the Renaissance — a city that changed the course of Western art and thought. The Duomo (Cathedral of Santa Maria del Fiore) is a masterpiece of Gothic architecture, with Brunelleschi's dome the largest brick dome ever built. The Uffizi Gallery houses Botticelli's 'Birth of Venus' and da Vinci's 'Annunciation'. The Accademia Gallery is home to Michelangelo's 'David' — a 17-foot marble giant that embodies Renaissance ideals of human perfection. The Ponte Vecchio is a medieval bridge lined with goldsmith shops, the only Florentine bridge to survive WWII. Sunset at Piazzale Michelangelo offers the iconic view of the city's red-tiled roofs and domes. Beyond art, Florence is Tuscan food — bistecca alla fiorentina (T-bone steak), ribollita (bread soup), and gelato from the legendary Vivoli.",
    experiences: [
      'Duomo climb to the dome',
      'Uffizi Gallery masterpieces',
      'Michelangelo\'s David viewing',
      'Ponte Vecchio sunset',
      'Piazzale Michelangelo panorama',
      'Tuscan cooking class',
    ],
    camps: ['Four Seasons Florence', 'St. Regis Florence', 'Villa Cora', 'Portrait Firenze', 'Savoia Excelsior'],
    unesco: true,
  },
  {
    slug: 'venice',
    name: 'Venice',
    country: 'Italy',
    region: 'Italy',
    tagline: 'The Floating City',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/europe/venice.jpg',
    highlights: ['Grand Canal', 'St. Mark\'s Square', 'Rialto Bridge', 'Gondola Ride', 'Doge\'s Palace', 'Murano'],
    bestTime: 'Apr–Jun · Sep–Oct',
    duration: '2–4 nights',
    from: '$220',
    description: "Venice is a miracle — 118 islands, 400 bridges, and 150 canals woven into the most beautiful city ever built on water. The Grand Canal is the main artery, lined with Byzantine, Gothic, and Renaissance palaces that seem to float. St. Mark's Square is the city's living room, dominated by St. Mark's Basilica (covered in gold mosaics) and the Doge's Palace, where the Venetian Republic ruled for 1,000 years. The Rialto Bridge is the oldest of the four bridges crossing the Grand Canal, lined with shops. A gondola ride is touristy but essential — the back canals reveal hidden gardens and crumbling palazzos away from the crowds. Venice is sinking — some say it won't exist in 100 years. Visit now. Take a vaporetto to Murano for glassblowing, Burano for rainbow-colored houses and lace, and Torcello for Byzantine mosaics.",
    experiences: [
      'Grand Canal vaporetto ride',
      'St. Mark\'s Basilica mosaics',
      'Doge\'s Palace secret itineraries tour',
      'Rialto Bridge at sunrise',
      'Gondola ride through back canals',
      'Murano glassblowing demo',
    ],
    camps: ['Belmond Hotel Cipriani', 'Aman Venice', 'St. Regis Venice', 'Gritti Palace', 'Bauer Palazzo'],
    unesco: true,
  },
  {
    slug: 'amalfi-coast',
    name: 'Amalfi Coast',
    country: 'Italy',
    region: 'Italy',
    tagline: 'Dramatic Cliffs & Pastel Villages',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/europe/amalfi.jpg',
    highlights: ['Positano', 'Amalfi', 'Ravello', 'Path of the Gods', 'Capri', 'Limoncello'],
    bestTime: 'May–Jun · Sep–Oct',
    duration: '4–6 nights',
    from: '$300',
    description: "The Amalfi Coast is Italy's most dramatic coastline — a UNESCO World Heritage site of vertical cliffs, pastel villages, and turquoise water that inspired John Steinbeck to write 'Positano bites deep.' Positano tumbles down the mountain toward the sea, its houses stacked like a colorful staircase. Amalfi was a maritime republic rivaling Venice and Pisa — the Duomo's bronze doors came from Constantinople. Ravello sits high above, with gardens that inspired Wagner and the world's most beautiful concert venue. The Path of the Gods (Sentiero degli Dei) is a hiking trail with views that justify the name. Capri, an island off the coast, was Emperor Tiberius's playground — the Blue Grotto's electric blue water is unforgettable. The coast is famous for lemons — try limoncello, lemon cake, and anything else made from Sfusato Amalfitano lemons.",
    experiences: [
      'Positano stairs descent',
      'Path of the Gods hiking',
      'Ravello gardens concert',
      'Amalfi Duomo and piazza',
      'Capri Blue Grotto boat',
      'Limoncello tasting',
    ],
    camps: ['Le Sirenuse', 'Il San Pietro di Positano', 'Hotel Caruso', 'Belmond Hotel Caruso', 'Santa Caterina'],
    unesco: true,
  },
  {
    slug: 'tuscany',
    name: 'Tuscany',
    country: 'Italy',
    region: 'Italy',
    tagline: 'Rolling Hills & Medieval Towns',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/europe/tuscany.jpg',
    highlights: ['Val d\'Orcia', 'Siena', 'San Gimignano', 'Chianti Wine', 'Florence Day Trip', 'Agriturismo'],
    bestTime: 'Apr–Oct',
    duration: '5–7 nights',
    from: '$250',
    description: "Tuscany (Toscana) is the Italy of your imagination — rolling hills, cypress-lined roads, medieval hilltop towns, and some of the world's greatest wine and food. The Val d'Orcia is the quintessential Tuscan landscape, a UNESCO World Heritage site of golden wheat fields and slender cypress trees. Siena rivals Florence as a Gothic masterpiece — the Piazza del Campo is one of Europe's most beautiful squares, host to the Palio horse race twice a year. San Gimignano still has 14 of its original 72 medieval towers, earning it the nickname 'Manhattan of the Middle Ages.' Chianti wine country produces Brunello, Vino Nobile, and Chianti Classico — visit family-run cantine for tastings. Stay in an agriturismo (farm stay) to experience real Tuscan hospitality, home-cooked meals, and olive oil pressed from groves on the property.",
    experiences: [
      'Val d\'Orcia sunrise photography',
      'Siena Duomo and Campo',
      'San Gimignano tower climb',
      'Chianti wine tasting',
      'Thermal baths at Bagno Vignoni',
      'Agriturismo cooking class',
    ],
    camps: ['Rosewood Castiglion del Bosco', 'Borgo Santo Pietro', 'Fonteverde', 'Lupaia', 'Castello di Vicarello'],
    unesco: true,
  },
  {
    slug: 'lake-como',
    name: 'Lake Como',
    country: 'Italy',
    region: 'Italy',
    tagline: 'Italian Lakes & Alpine Glamour',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/europe/lake-como.jpg',
    highlights: ['Bellagio', 'Varenna', 'Villa Balbianello', 'Como Town', 'Funicular', 'George Clooney\'s Villa'],
    bestTime: 'Apr–Oct',
    duration: '3–5 nights',
    from: '$280',
    description: "Lake Como (Lago di Como) is Italy's most glamorous lake — a Y-shaped body of water at the foot of the Alps, lined with elegant villas, lush gardens, and towns that have attracted aristocrats and celebrities for centuries. Bellagio is the 'Pearl of the Lake,' where the lake's two legs meet — its cobblestone lanes are filled with designer boutiques and lake-view restaurants. Varenna is quieter and more romantic, with a castle, a lovely promenade, and Villa Monastero's gardens. Villa Balbianello is the most beautiful villa on the lake — its loggia has appeared in 'Star Wars' and 'James Bond: Casino Royale.' Take the funicular from Como town to Brunate for panoramic views over the lake and Alps. Milan is just an hour away by train, making Lake Como a perfect escape from the city. George Clooney owns a villa here — you might not spot him, but you'll understand why he stays.",
    experiences: [
      'Bellagio ferry ride',
      'Villa Balbianello garden tour',
      'Varenna lakeside walk',
      'Como-Brunate funicular',
      'Lake Como boat rental',
      'Silk museum in Como',
    ],
    camps: ['Grand Hotel Tremezzo', 'Villa d\'Este', 'Mandarin Oriental Lago di Como', 'Hotel Passalacqua', 'Il Sereno'],
    unesco: false,
  },
]