export const netherlandsDestinations = [
  {
    slug: 'amsterdam',
    name: 'Amsterdam',
    country: 'Netherlands',
    region: 'Netherlands',
    tagline: 'Canals, Museums & Bicycles',
    gradient: 'linear-gradient(160deg,#001018,#001c2d,#002840)',
    image: '/images/europe/amsterdam.jpg',
    highlights: ['Canal Ring', 'Rijksmuseum', 'Van Gogh Museum', 'Anne Frank House', 'Jordaan', 'Bicycle Culture'],
    bestTime: 'Apr–May · Sep–Oct',
    duration: '3–5 nights',
    from: '$180',
    description: "Amsterdam is the city of canals, museums, and bicycles — a 17th-century masterpiece of urban planning, where 165 canals create a horseshoe of concentric rings crossed by 1,500 bridges. The Canal Ring is a UNESCO World Heritage site — take a canal cruise or rent a boat to see the merchant houses with their gabled facades, many leaning forward (to protect goods pulled up by rope). The Rijksmuseum is the Netherlands' national museum — Rembrandt's 'The Night Watch' is the star, but also see Vermeer's 'The Milkmaid' and an extensive collection of Dutch Golden Age paintings. The Van Gogh Museum holds the largest collection of Van Gogh's paintings (200+), including 'Sunflowers,' 'Almond Blossom,' and 'The Bedroom.' The Anne Frank House is the secret annex where Anne Frank wrote her diary during WWII — book tickets weeks or months ahead (online only, time slots). The Jordaan is the most beautiful neighborhood — narrow streets, independent shops, brown cafes, and the Noordermarkt flea market. Amsterdam has more bikes than people — join the locals cycling, but watch out for trams and cars.",
    experiences: [
      'Canal boat tour',
      'Rijksmuseum Night Watch',
      'Van Gogh Museum self-portraits',
      'Anne Frank House online booking',
      'Jordaan brown cafe',
      'Bike rental to Vondelpark',
    ],
    camps: ['The Dylan', 'Waldorf Astoria Amsterdam', 'Pulitzer Amsterdam', 'De L\'Europe', 'Andaz Amsterdam'],
    unesco: true,
  },
  {
    slug: 'keukenhof',
    name: 'Keukenhof Gardens',
    country: 'Netherlands',
    region: 'Netherlands',
    tagline: 'The Garden of Europe',
    gradient: 'linear-gradient(160deg,#001c10,#002c1a,#003c22)',
    image: '/images/europe/keukenhof.jpg',
    highlights: ['Tulip Fields', 'Indoor Flower Show', 'Windmill', 'Sculpture Garden', 'Bicycle Rental', 'Flower Parade'],
    bestTime: 'Mid-Mar–Mid-May',
    duration: '1 day trip',
    from: '$50',
    description: "Keukenhof is the world's most beautiful spring garden — 79 acres of blooming tulips, daffodils, hyacinths, and other bulbs, open only eight weeks each year (mid-March to mid-May). The park has 7 million flower bulbs planted annually by 100 different growers — the colors are almost too bright to believe. The indoor flower shows change weekly — each week features a different flower (tulips, lilies, roses, orchids). The windmill (built 1892) is at the park's highest point — climb it for the classic view over the tulip fields. The sculpture garden has 40 works by Dutch artists among the flowers. Renting a bike at Keukenhof lets you explore the surrounding tulip fields — the 35-kilometer route passes through bulb-growing villages. The Flower Parade (Bloemencorso) occurs on the last Saturday of April — floats made of millions of flowers pass through Keukenhof. Keukenhof is located in Lisse, 40 minutes from Amsterdam by bus (the 858 Keukenhof Express).",
    experiences: [
      '7 million tulips',
      'Indoor flower show',
      'Windmill photography',
      'Sculpture garden',
      'Tulip field bike ride',
      'Flower parade (Apr)',
    ],
    camps: ['De Nachtegaal', 'Boutique Hotel Huys van Leyden', 'Hof ter Duinen', 'City Hotel Rijswijk', 'Boutique Hotel de Logerij'],
    unesco: false,
  },
  {
    slug: 'rotterdam',
    name: 'Rotterdam',
    country: 'Netherlands',
    region: 'Netherlands',
    tagline: 'Modern Architecture & Europe\'s Largest Port',
    gradient: 'linear-gradient(160deg,#1a0a0a,#2d1414,#3d1e1e)',
    image: '/images/europe/rotterdam.jpg',
    highlights: ['Cube Houses', 'Markthal', 'Erasmus Bridge', 'Euromast', 'Kunsthal', 'World Port'],
    bestTime: 'Apr–Oct',
    duration: '2–3 nights',
    from: '$140',
    description: "Rotterdam is Europe's most modern city — rebuilt after WWII bombing (the city center was destroyed in 1940) with experimental architecture, a massive port, and a can-do attitude. The Cube Houses (Kubuswoningen) are a forest of tilted yellow cubes designed by Piet Blom — one is open as a show house (the Kijk-Kubus), and there's a hostel inside another (Stayokay). The Markthal is a horseshoe-shaped indoor market covered with a giant mural of fruits and vegetables (Arti et Amicitiae) — apartments wrap around the outside, and 96 market stalls inside sell Dutch cheese, stroopwafels, herring, and international food. The Erasmus Bridge ('The Swan') is the city's iconic bridge — a 139-meter white pylon leaning over a 800-meter-long cable-stayed bridge. The Euromast is a 185-meter observation tower — take the 'Euroscoop' glass elevator to the top for 360-degree views of the city and port. The Kunsthal (Art Hall) is an Renzo Piano-designed building with changing exhibitions. Rotterdam has Europe's largest port — take the 'Spido' harbor cruise to see container terminals and shipyards.",
    experiences: [
      'Cube Houses show cube',
      'Markthal food sampling',
      'Erasmus Bridge walk',
      'Euromast glass elevator',
      'Kunsthal exhibit',
      'Spido harbor cruise',
    ],
    camps: ['Mainport Hotel', 'The James Rotterdam', 'Hotel New York', 'Nhow Rotterdam', 'CitizenM Rotterdam'],
    unesco: false,
  },
]