export const portugalDestinations = [
  {
    slug: 'lisbon',
    name: 'Lisbon',
    country: 'Portugal',
    region: 'Portugal',
    tagline: 'The City of Seven Hills',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/europe/lisbon.jpg',
    highlights: ['Alfama', 'Tram 28', 'Belém Tower', 'São Jorge Castle', 'LX Factory', 'Pastéis de Belém'],
    bestTime: 'Mar–May · Sep–Oct',
    duration: '3–5 nights',
    from: '$130',
    description: "Lisbon (Lisboa) is Europe's most underrated capital — a city of seven hills, pastel-colored buildings, soulful Fado music, and more sunshine than almost any other European capital. The Alfama district is the oldest neighborhood, a maze of narrow alleys, tiny squares, and laundry hanging from windows — it survived the 1755 earthquake that destroyed most of Lisbon. Tram 28 rattles through the city's most picturesque neighborhoods (hang on tight — it gets crowded). Belém is the district of Portuguese discoveries — the Jerónimos Monastery (UNESCO) is Manueline architecture at its finest, and the Belém Tower guards the Tagus River. Pasteis de Belém is the only place to eat the original custard tarts — the recipe is a secret guarded for over 180 years. São Jorge Castle offers the best views of the city and river. LX Factory is a creative hub in a former industrial complex, with street art, bookstores, and rooftop bars.",
    experiences: [
      'Tram 28 ride',
      'Alfama Fado dinner',
      'Belém Tower visit',
      'Pastéis de Belém tasting',
      'São Jorge Castle views',
      'LX Factory shopping',
    ],
    camps: ['Ritz Four Seasons Lisbon', 'Bairro Alto Hotel', 'Palácio Ludovice', 'The Ivens', 'Santiago de Alfama'],
    unesco: true,
  },
  {
    slug: 'porto',
    name: 'Porto',
    country: 'Portugal',
    region: 'Portugal',
    tagline: 'The City of Bridges & Port Wine',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/europe/porto.jpg',
    highlights: ['Dom Luís I Bridge', 'Ribeira', 'Port Wine Cellars', 'Livraria Lello', 'Serralves Museum', 'Francesinha'],
    bestTime: 'Mar–May · Sep–Oct',
    duration: '3–4 nights',
    from: '$120',
    description: "Porto (Oporto) is Portugal's second city, famous for its port wine, stunning bridges, and photogenic riverside. The Dom Luís I Bridge, designed by a student of Gustave Eiffel, spans the Douro River with two decks — the upper deck is for trams and pedestrians, offering the best view of the Ribeira district (a UNESCO World Heritage site of colorful houses and port barges). Across the river in Vila Nova de Gaia, you'll find the Port Wine Cellars — visit Sandeman, Graham's, or Taylor's for tastings of tawny and ruby port. Livraria Lello is one of the world's most beautiful bookstores — its red staircase inspired the Harry Potter series (J.K. Rowling lived in Porto). Serralves Museum is a stunning contemporary art museum in a 1930s Art Deco villa. Eat a Francesinha — Porto's signature sandwich of bread, ham, sausage, steak, melted cheese, and tomato-beer sauce.",
    experiences: [
      'Dom Luís Bridge walk',
      'Ribeira riverfront cruise',
      'Port wine cellar tasting',
      'Livraria Lello visit',
      'Serralves garden walk',
      'Francesinha dinner',
    ],
    camps: ['The Yeatman', 'Six Senses Douro Valley', 'Maison Albar', 'Torel Palace Porto', 'InterContinental Porto'],
    unesco: true,
  },
  {
    slug: 'douro-valley',
    name: 'Douro Valley',
    country: 'Portugal',
    region: 'Portugal',
    tagline: 'Port Wine\'s Terraced Homeland',
    gradient: 'linear-gradient(160deg,#001c14,#002c1e,#004028)',
    image: '/images/europe/douro.jpg',
    highlights: ['River Cruise', 'Wine Estates', 'Terraced Vineyards', 'Pinhão Railway', 'Lamego Sanctuary'],
    bestTime: 'Apr–Oct',
    duration: '3–4 nights',
    from: '$220',
    description: "The Douro Valley is one of the world's oldest wine regions — a UNESCO World Heritage site of terraced vineyards carved into steep mountainsides, following the Douro River from the Spanish border to Porto. The valley produces port wine and increasingly world-class dry reds. A river cruise is the best way to see the landscape — traditional rabelo boats (the barges that once carried port barrels) or modern riverboats. Quinta visits (wine estates) are essential — many have guesthouses for overnight stays, tasting rooms, and restaurants overlooking the river. The Pinhão railway station is covered in azulejo tiles depicting the valley's history. Lamego's Sanctuary of Our Lady of Remedies is a baroque masterpiece with a 686-step staircase. Stay in a renovated quinta — many have pools, gardens, and home-cooked meals using produce from their own farms.",
    experiences: [
      'Douro River cruise',
      'Quinta wine tasting',
      'Pinhão tile station',
      'Lamego sanctuary climb',
      'Vineyard hike',
      'Sunset viewpoints',
    ],
    camps: ['Six Senses Douro Valley', 'Quinta do Bomfim', 'Quinta da Pacheca', 'Quinta do Vallado', 'Vintage House Hotel'],
    unesco: true,
  },
  {
    slug: 'algarve',
    name: 'Algarve',
    country: 'Portugal',
    region: 'Portugal',
    tagline: 'Europe\'s Best Beaches',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/europe/algarve.jpg',
    highlights: ['Benagil Cave', 'Pontada Piedade', 'Lagos Old Town', 'Sagres', 'Seven Hanging Valleys Trail'],
    bestTime: 'May–Oct',
    duration: '5–7 nights',
    from: '$150',
    description: "The Algarve is Portugal's southern coast — famous for golden cliffs, hidden caves, and some of Europe's best beaches. Benagil Cave (Algar de Benagil) is the most iconic — a sea cave with a hole in its ceiling, accessible only by boat, kayak, or paddleboard. Ponta da Piedade in Lagos is a maze of sea stacks, grottoes, and natural arches with green-gold water. The Seven Hanging Valleys Trail is a 12-kilometer coastal walk between Marinha Beach and Vale de Centeanes, passing limestone cliffs and hidden coves. Lagos Old Town has cobblestone streets, historical walls, and excellent seafood restaurants. Sagres is the southwestern tip of Portugal, where cliffs drop 60 meters into the Atlantic — the sunsets are spectacular. The Algarve is also a golf destination (over 30 courses) and a birdwatching hotspot in the Ria Formosa lagoon.",
    experiences: [
      'Benagil Cave kayaking',
      'Ponta da Piedade boat tour',
      'Seven Hanging Valleys hike',
      'Lagos old town dinner',
      'Sagres sunset',
      'Ria Formosa birdwatching',
    ],
    camps: ['Vila Vita Parc', 'Anantara Vilamoura', 'Conrad Algarve', 'Martinhal Sagres', 'Bela Vista Hotel'],
    unesco: false,
  },
]