export const spainDestinations = [
  {
    slug: 'barcelona',
    name: 'Barcelona',
    country: 'Spain',
    region: 'Spain',
    tagline: 'Gaudí\'s Masterpiece by the Sea',
    gradient: 'linear-gradient(160deg,#001f3f,#003366,#004080)',
    image: '/images/europe/barcelona.jpg',
    highlights: ['Sagrada Família', 'Park Güell', 'Gothic Quarter', 'La Rambla', 'Barceloneta Beach', 'Tapas'],
    bestTime: 'Apr–Jun · Sep–Oct',
    duration: '3–5 nights',
    from: '$170',
    description: "Barcelona is Gaudí's city — a Mediterranean capital of Modernist architecture, Gothic history, and beachside energy. The Sagrada Família is Gaudí's unfinished masterpiece, a basilica unlike any other on earth — its 18 towers symbolize Jesus, the Virgin Mary, and the 12 apostles. Park Güell is a whimsical public park of gingerbread houses, mosaic lizards, and panoramic city views. The Gothic Quarter (Barri Gòtic) is a labyrinth of narrow streets, hidden squares, and the Barcelona Cathedral. La Rambla is the city's most famous boulevard, lined with street performers, flower stalls, and the historic Boqueria Market (eat jamón ibérico and fresh seafood at the counter). Barceloneta Beach is just steps from the city center. Barcelona is also a food city — Catalonia is known for paella, cava (sparkling wine), and 'pan con tomate' (bread with tomato, olive oil, and salt).",
    experiences: [
      'Sagrada Família towers climb',
      'Park Güell mosaic walk',
      'Gothic Quarter walking tour',
      'Boqueria Market tapas crawl',
      'Barceloneta beach sunset',
      'Montjuïc cable car view',
    ],
    camps: ['Majestic Hotel & Spa', 'El Palace Barcelona', 'The Serras', 'Almanac Barcelona', 'Mercer Hotel'],
    unesco: true,
  },
  {
    slug: 'madrid',
    name: 'Madrid',
    country: 'Spain',
    region: 'Spain',
    tagline: 'Art, Royalty & Nightlife',
    gradient: 'linear-gradient(160deg,#1a0e00,#2a1c00,#3a2800)',
    image: '/images/europe/madrid.jpg',
    highlights: ['Prado Museum', 'Royal Palace', 'Retiro Park', 'Plaza Mayor', 'Santiago Bernabéu', 'Churros'],
    bestTime: 'Mar–May · Sep–Nov',
    duration: '3–5 nights',
    from: '$160',
    description: "Madrid is Spain's capital and soul — a city of world-class art, royal grandeur, electric nightlife, and the best churros on earth. The Prado Museum is one of the world's greatest art galleries, home to masterpieces by Velázquez (including 'Las Meninas'), Goya, El Greco, and Rubens. The Royal Palace (Palacio Real) is the official residence of the Spanish royal family, with over 3,000 rooms — the changing of the guard is spectacular. Retiro Park (Parque del Buen Retiro) is Madrid's green lung, with a boating lake, rose garden, and the stunning Palacio de Cristal. Plaza Mayor is the city's grandest square, perfect for people-watching with a coffee. Real Madrid fans must visit the Santiago Bernabéu Stadium. After dark, Madrid comes alive — have late-night dinner (Spanish eat after 10 pm), then join the locals for churros con chocolate at Chocolatería San Ginés (open since 1894).",
    experiences: [
      'Prado Museum masterpieces',
      'Royal Palace guided tour',
      'Retiro Park boat rental',
      'Plaza Mayor coffee break',
      'Santiago Bernabéu tour',
      'Late-night churros at San Ginés',
    ],
    camps: ['Four Seasons Madrid', 'Rosewood Villa Magna', 'Mandarin Oriental Ritz', 'The Principal Madrid', 'Santo Mauro'],
    unesco: true,
  },
  {
    slug: 'granada',
    name: 'Granada',
    country: 'Spain',
    region: 'Spain',
    tagline: 'The Alhambra\'s Moorish Palace',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/europe/alhambra.jpg',
    highlights: ['Alhambra', 'Generalife Gardens', 'Nasrid Palaces', 'Albayzín', 'Sacromonte Caves', 'Free Tapas'],
    bestTime: 'Mar–May · Sep–Nov',
    duration: '2–3 nights',
    from: '$140',
    description: "Granada is the soul of Moorish Spain — the last Muslim kingdom to fall to the Catholic Monarchs in 1492. The Alhambra is Europe's most extraordinary Islamic palace, a UNESCO World Heritage site of intricate stucco, geometric tiles, and peaceful courtyards with fountains. The Nasrid Palaces are the highlight — the Court of the Lions and the Hall of the Ambassadors are masterpieces of Islamic art. The Generalife Gardens were the sultans' summer retreat, with manicured hedges, flowing water, and stunning views over the city. The Albayzín is Granada's old Muslim quarter, a labyrinth of whitewashed alleys, tea shops, and miradors (viewpoints) looking up at the Alhambra. The Sacromonte neighborhood is famous for cave houses where flamenco dancers perform authentic 'zambras.' Granada has a unique tradition: order a drink, and you'll get a free tapa with it — some bars serve generous portions for the price of a beer.",
    experiences: [
      'Alhambra Nasrid Palaces',
      'Generalife Gardens walk',
      'Albayzín sunset view',
      'Sacromonte flamenco show',
      'Free tapas bar crawl',
      'Sierra Nevada day trip',
    ],
    camps: ['Parador de Granada', 'Alhambra Palace Hotel', 'Palacio de Santa Inés', 'Barceló Carmen Granada', 'Eurostars Puerta Real'],
    unesco: true,
  },
  {
    slug: 'seville',
    name: 'Seville',
    country: 'Spain',
    region: 'Spain',
    tagline: 'Flamenco, Orange Blossoms & Moorish Splendor',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/europe/seville.jpg',
    highlights: ['Alcázar Palace', 'Seville Cathedral', 'Giralda Tower', 'Plaza de España', 'Santa Cruz', 'Flamenco'],
    bestTime: 'Mar–May · Oct–Nov',
    duration: '3–4 nights',
    from: '$150',
    description: "Seville (Sevilla) is the heart of Andalusia — a city of orange blossom scent, flamenco rhythms, and Moorish and Renaissance architecture. The Alcázar of Seville is one of Spain's most beautiful palaces, a Mudejar masterpiece where the Dorne scenes of 'Game of Thrones' were filmed — its courtyards, tilework, and gardens are breathtaking. Seville Cathedral is the largest Gothic cathedral in the world, built on the site of a 12th-century mosque — climb the Giralda Tower (formerly the minaret) for panoramic city views. The tomb of Christopher Columbus is inside the cathedral. Plaza de España is a 1929 fairytale plaza with tiled alcoves representing each Spanish province — it's perfect for a rowboat ride on its canal. Santa Cruz is the old Jewish quarter, a maze of narrow alleys filled with orange trees, boutique hotels, and tapas bars. Seville is the birthplace of flamenco — book a show in a traditional tablao.",
    experiences: [
      'Alcázar palace tour',
      'Seville Cathedral and Giralda',
      'Plaza de España rowboat',
      'Santa Cruz alley walk',
      'Flamenco show in Triana',
      'Tapas crawl in El Arenal',
    ],
    camps: ['Hotel Alfonso XIII', 'Palacio de Villapanés', 'Gran Meliá Colón', 'Hotel Palacio de Villapanés', 'Boutique Hotel Corral del Rey'],
    unesco: true,
  },
  {
    slug: 'mallorca',
    name: 'Mallorca',
    country: 'Spain',
    region: 'Spain',
    tagline: 'Mediterranean Beauty Beyond the Beaches',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/europe/mallorca.jpg',
    highlights: ['Palma Cathedral', 'Tramuntana Mountains', 'Sóller Train', 'Valldemossa', 'Caló des Moro'],
    bestTime: 'May–Jun · Sep–Oct',
    duration: '5–7 nights',
    from: '$230',
    description: "Mallorca (Majorca) is the largest of the Balearic Islands — a Mediterranean paradise of hidden coves, dramatic mountains, and a capital city with a stunning Gothic cathedral. Palma's Cathedral (La Seu) is one of Spain's most beautiful, perched on the waterfront with rose windows designed by Gaudí. The Tramuntana Mountains are a UNESCO World Heritage site — drive the winding MA-10 road for spectacular sea and mountain views. Take the historic Sóller Train from Palma to Sóller, a wooden tram that has run since 1912 through citrus groves and mountains. Valldemossa is a picture-perfect hill village where Chopin spent a winter. Caló des Moro is a small cove with turquoise water, one of the island's most photographed spots. Mallorca also has a sophisticated food scene — Michelin-starred restaurants, local wineries, and ensaïmada (a spiral pastry).",
    experiences: [
      'Palma Cathedral towers',
      'Sóller Train journey',
      'Tramuntana mountain drive',
      'Valldemossa monastery visit',
      'Caló des Moro swimming',
      'Wine tasting in Binissalem',
    ],
    camps: ['Cap Rocat', 'Belmond La Residencia', 'St. Regis Mardavall', 'Grand Hotel Son Net', 'Hotel de Mar'],
    unesco: true,
  },
  {
    slug: 'ibiza',
    name: 'Ibiza',
    country: 'Spain',
    region: 'Spain',
    tagline: 'World-Famous Clubs & Bohemian Beaches',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/europe/ibiza.jpg',
    highlights: ['Dalt Vila', 'Café del Mar', 'Pacha', 'Cala Comte', 'Es Vedrà', 'Formentera Day Trip'],
    bestTime: 'May–Oct',
    duration: '4–6 nights',
    from: '$300',
    description: "Ibiza is the world's party island — but also so much more. The Dalt Vila (Old Town) is a UNESCO World Heritage site, a fortified hilltop of cobblestone alleys, Renaissance walls, and the Cathedral of Santa Maria. The sunset at Café del Mar in San Antonio is a ritual, with crowds gathering to watch the sun drop into the sea. The world's best nightclubs — Pacha, Amnesia, Ushuaïa, DC-10 — attract top DJs from May to October. But Ibiza also has quiet beauty: Cala Comte (clear turquoise water, red sunsets), Cala d'Hort (views of the mystical Es Vedrà rock island), and the bohemian hippie markets (Las Dalias on Saturdays). Take a 30-minute ferry to Formentera, the quieter sister island, for the Caribbean-style beaches of Ses Illetes. Ibiza's food has also been transformed — there are now multiple Michelin-starred restaurants.",
    experiences: [
      'Dalt Vila sunset walk',
      'Café del Mar sunset',
      'Pacha or Amnesia nightclub',
      'Cala Comte beach day',
      'Formentera day trip',
      'Las Dalias hippie market',
    ],
    camps: ['Six Senses Ibiza', 'Nobu Hotel Ibiza', 'Atzaró Agroturismo', 'Hacienda Na Xamena', 'Cas Gasi'],
    unesco: true,
  },
]