export const switzerlandDestinations = [
  {
    slug: 'jungfraujoch',
    name: 'Jungfraujoch',
    country: 'Switzerland',
    region: 'Switzerland',
    tagline: 'Top of Europe',
    gradient: 'linear-gradient(160deg,#001428,#001e3d,#002852)',
    image: '/images/europe/jungfraujoch.jpg',
    highlights: ['Jungfraujoch Station', 'Ice Palace', 'Sphinx Observatory', 'Aletsch Glacier', 'Grindelwald', 'Lauterbrunnen'],
    bestTime: 'Jun–Sep',
    duration: '1 day trip',
    from: '$240',
    description: "Jungfraujoch is the 'Top of Europe' — a 3,454-meter saddle between the Jungfrau and Mönch mountains, reached by a cogwheel train through a tunnel carved into the Eiger mountain. The railway is a marvel of early 20th-century engineering (built 1896-1912) — the 9-kilometer ascent from Grindelwald takes 1.5 hours, passing the Eiger's North Face (7,000 climbers have died here). At the top, the Sphinx Observatory offers 360-degree views of the Aletsch Glacier (23 km long, Europe's largest) and the peaks of the Swiss Alps. The Ice Palace is a tunnel carved into the glacier itself — ice sculptures, a crevasse walk, and the temperature is permanently -3°C. Grindelwald is the most popular base — the 'Glacier Village' with mountain views, adventure sports, and a cable car to the Jungfraujoch route. Lauterbrunnen is the valley of 72 waterfalls — Staubbach Falls drops 297 meters, and the valley inspired Tolkien's Rivendell. Jungfraujoch is expensive but unforgettable — dress warmly even in summer.",
    experiences: [
      'Jungfraubahn train journey',
      'Sphinx Observatory view',
      'Ice Palace glacier walk',
      'Aletsch Glacier vista',
      'Grindelwald First cliff walk',
      'Lauterbrunnen valley hike',
    ],
    camps: ['Hotel Jungfraublick', 'Victoria-Jungfrau Grand', 'Boutique Hotel Bellevue', 'The Alpina Grindelwald', 'Hotel Oberland'],
    unesco: true,
  },
  {
    slug: 'matterhorn-zermatt',
    name: 'Matterhorn & Zermatt',
    country: 'Switzerland',
    region: 'Switzerland',
    tagline: 'Switzerland\'s Iconic Peak',
    gradient: 'linear-gradient(160deg,#0e1800,#182400,#223000)',
    image: '/images/europe/matterhorn.jpg',
    highlights: ['Matterhorn Peak', 'Zermatt Village', 'Gornergrat Railway', 'Matterhorn Glacier Paradise', 'Sunnegga', 'Five Lakes Walk'],
    bestTime: 'Jun–Sep',
    duration: '3–5 nights',
    from: '$350',
    description: "The Matterhorn is the most iconic mountain in the Alps — a 4,478-meter pyramid of rock on the Swiss-Italian border, and the most photographed peak in the world. Zermatt is the car-free village at its base, a picture-perfect town of traditional wooden chalets, luxury hotels, and 100km of ski runs (winter) and 400km of hiking trails (summer). The Gornergrat Railway is the best way to see the Matterhorn — the open-air cogwheel train climbs to 3,089 meters in 30 minutes, with views of 29 peaks over 4,000 meters, including the Matterhorn reflected in Lake Riffelsee. The Matterhorn Glacier Paradise is Europe's highest cable car station (3,883m) — the 15-minute ride from Trockener Steg is spectacular. Sunnegga (2,288m) is the easiest viewpoint — a funicular from Zermatt, then walk to the Leisee lake for Matterhorn reflection photos. The Five Lakes Walk from Blauherd to Sunnegga passes five crystal-clear lakes, each with Matterhorn views.",
    experiences: [
      'Matterhorn sunrise',
      'Gornergrat railway',
      'Riffelsee reflection',
      'Glacier Paradise cable car',
      'Sunnegga funicular',
      'Five Lakes Walk hike',
    ],
    camps: ['Grand Hotel Zermatterhof', 'Cervo Mountain Resort', 'Riffelhaus 1853', 'The Omnia', 'Mont Cervin Palace'],
    unesco: false,
  },
  {
    slug: 'lucerne',
    name: 'Lucerne',
    country: 'Switzerland',
    region: 'Switzerland',
    tagline: 'Medieval Chapel Bridge & Lake Lucerne',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/europe/lucerne.jpg',
    highlights: ['Chapel Bridge', 'Lion Monument', 'Lake Lucerne', 'Mount Pilatus', 'Mount Rigi', 'Old Town'],
    bestTime: 'Apr–Oct',
    duration: '2–4 nights',
    from: '$220',
    description: "Lucerne (Luzern) is Switzerland's most beautiful city — a medieval town on the shores of Lake Lucerne, surrounded by mountains, with the Reuss River flowing through its heart. The Chapel Bridge (Kapellbrücke) is Europe's oldest covered wooden bridge (built 1333) — the triangular paintings under the roof depict Swiss history (many were destroyed in a 1993 fire but restored). The Water Tower (Wasserturm) was a prison and torture chamber. The Lion Monument is a 10-meter sculpture of a dying lion carved into a sandstone cliff, commemorating the Swiss Guards killed during the French Revolution — Mark Twain called it 'the most mournful and moving piece of stone in the world.' Lake Lucerne is 114 square kilometers with 40 fjord-like arms — take a boat cruise to see the surrounding mountains (Pilatus, Rigi, Stanserhorn). Mount Pilatus (2,128m) is best reached by the 'Golden Round Trip' — boat from Lucerne to Alpnachstad, cogwheel train (steepest in the world, 48%), cable car back, bus to Lucerne. Mount Rigi (1,797m) is the 'Queen of the Mountains' — the view of 13 lakes is spectacular.",
    experiences: [
      'Chapel Bridge walk',
      'Lion Monument visit',
      'Lake Lucerne cruise',
      'Pilatus Golden Round Trip',
      'Rigi cogwheel train',
      'Old Town Musegg Wall',
    ],
    camps: ['Hotel Schweizerhof', 'Mandarin Oriental Lucerne', 'Hotel des Balances', 'The Hotel Lucerne', 'Art Deco Hotel Montana'],
    unesco: false,
  },
  {
    slug: 'interlaken',
    name: 'Interlaken',
    country: 'Switzerland',
    region: 'Switzerland',
    tagline: 'Adventure Capital of the Alps',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/europe/interlaken.jpg',
    highlights: ['Harder Kulm', 'Höhematte', 'Adventure Sports', 'Brienz & Thun Lakes', 'Jungfrau View', 'Paragliding'],
    bestTime: 'Jun–Sep',
    duration: '3–5 nights',
    from: '$280',
    description: "Interlaken is Switzerland's adventure capital — a town nestled between Lake Thun and Lake Brienz, with the Jungfrau and other peaks visible from its streets. Harder Kulm (1,322m) is Interlaken's home mountain — a 10-minute funicular ride for panoramic views of both lakes, the city, and the mountains (the two golden eagles at the viewing platform are a great photo op). Höhematte is a large park in the center of Interlaken — it's where parachuters land, and there are cows with bells grazing right in the middle of town. Paragliding is the #1 adventure activity — tandem flights launch from Beatenberg (1,350m) and land on Höhematte, with views of the Jungfrau and both lakes. Skydiving, canyoning, white-water rafting, and bungee jumping are also available. Lake Brienz has turquoise water (from glacial silt) — take the historic steam paddleboat. Lake Thun is larger — the town of Thun has a castle and a romantic old town. The Jungfrau can be seen from Interlaken — but you'll need the train to get closer.",
    experiences: [
      'Harder Kulm view',
      'Höhematte paragliding landing',
      'Tandem paragliding flight',
      'Lake Brienz paddleboat',
      'Lake Thun castle walk',
      'Jungfrau photography',
    ],
    camps: ['Victoria-Jungfrau Grand', 'Lindner Grand Hotel Beau Rivage', 'Hotel Royal St Georges', 'Boutique Hotel Bellevue', 'Hotel Lötschberg'],
    unesco: false,
  },
]