export const ukDestinations = [
  {
    slug: 'london',
    name: 'London',
    country: 'United Kingdom',
    region: 'United Kingdom',
    tagline: 'Global Capital of Heritage & Cool',
    gradient: 'linear-gradient(160deg,#0a0a15,#1a1a2e,#16213e)',
    image: '/images/europe/london.jpg',
    highlights: ['Big Ben', 'Tower of London', 'British Museum', 'London Eye', 'Camden Market', 'West End'],
    bestTime: 'May–Sep',
    duration: '4–7 nights',
    from: '$200',
    description: "London is one of the world's great cities — a 2,000-year-old metropolis where Roman walls stand beside Norman towers, Georgian squares neighbor futuristic skyscrapers, and 300 languages are spoken. The Houses of Parliament and Big Ben are London's most iconic sights, best seen from Westminster Bridge or the London Eye. The Tower of London has served as a royal palace, prison, and zoo — see the Crown Jewels and hear stories of Anne Boleyn and the Princes in the Tower. The British Museum houses the Rosetta Stone, the Elgin Marbles, and Egyptian mummies (free entry). The London Eye is a giant observation wheel on the South Bank, offering panoramic city views. Camden Market is alternative London — punk fashion, street food, and vintage shops. The West End is London's Broadway — book ahead for hit musicals like Hamilton, Les Misérables, or The Lion King. London's food scene has been transformed — curry houses in Brick Lane, Michelin-starred dining, and food halls everywhere.",
    experiences: [
      'Westminster Bridge photo',
      'Tower of London Crown Jewels',
      'British Museum Rosetta Stone',
      'London Eye sunset ride',
      'Camden Market food tour',
      'West End musical evening',
    ],
    camps: ['Claridge\'s', 'The Connaught', 'Rosewood London', 'Shangri-La The Shard', 'The Ned'],
    unesco: true,
  },
  {
    slug: 'edinburgh',
    name: 'Edinburgh',
    country: 'United Kingdom',
    region: 'United Kingdom',
    tagline: 'Scotland\'s Dramatic Capital',
    gradient: 'linear-gradient(160deg,#1a0f0a,#2d1b14,#3d2b1f)',
    image: '/images/europe/edinburgh.jpg',
    highlights: ['Edinburgh Castle', 'Royal Mile', 'Arthur\'s Seat', 'Holyrood Palace', 'National Museum', 'Fringe Festival'],
    bestTime: 'May–Sep',
    duration: '3–5 nights',
    from: '$180',
    description: "Edinburgh is Scotland's dramatic capital — a city built on a volcanic rock, with a medieval castle at its heart and a skyline of spires, domes, and Arthur's Seat (an extinct volcano offering the best city views). Edinburgh Castle dominates the city from Castle Rock — see the Crown Jewels of Scotland, the Stone of Destiny (used to crown Scottish kings), and the 1 o'clock gun (still fired daily). The Royal Mile is Edinburgh's historic spine, connecting the castle to Holyrood Palace (the Queen's official Scottish residence). Arthur's Seat is an easy hike from the center — the summit has 360-degree views over the city, the Firth of Forth, and the hills beyond. The National Museum of Scotland is one of Europe's best (free entry). August is Edinburgh's festival season — the Fringe is the world's largest arts festival, with thousands of performances. January 25 is Burns Night, celebrating Scotland's national poet with haggis and whisky.",
    experiences: [
      'Edinburgh Castle crown jewels',
      'Royal Mile walk',
      'Arthur\'s Seat sunrise hike',
      'Holyrood Palace tour',
      'National Museum free entry',
      'Whisky tasting',
    ],
    camps: ['The Balmoral', 'Gleneagles Townhouse', 'Virgin Hotels Edinburgh', 'Waldorf Astoria Edinburgh', 'Prestonfield House'],
    unesco: true,
  },
  {
    slug: 'scottish-highlands',
    name: 'Scottish Highlands',
    country: 'United Kingdom',
    region: 'United Kingdom',
    tagline: 'Lochs, Glens & Castles',
    gradient: 'linear-gradient(160deg,#001c14,#002c1e,#004028)',
    image: '/images/europe/highlands.jpg',
    highlights: ['Loch Ness', 'Isle of Skye', 'Glencoe', 'Eilean Donan Castle', 'Jacobite Steam Train', 'Munros'],
    bestTime: 'May–Sep',
    duration: '5–7 nights',
    from: '$250',
    description: "The Scottish Highlands are Europe's last great wilderness — a landscape of deep lochs, sweeping glens, dramatic peaks, and medieval castles. Loch Ness is the most famous loch, known for Nessie — cruise the 23-mile lake and visit Urquhart Castle. The Isle of Skye is the most spectacular part of the Highlands — the Old Man of Storr (rock pinnacle), the Quiraing (landslide plateau), and the Fairy Pools (crystal-clear pools and waterfalls). Glencoe is the most dramatic valley — a volcanic caldera surrounded by mountains where the MacDonald massacre occurred in 1692. Eilean Donan Castle is the most photographed castle in Scotland, sitting on a tidal island at the meeting of three lochs. The Jacobite Steam Train is the 'Hogwarts Express' — the 84-mile round trip from Fort William to Mallaig crosses the Glenfinnan Viaduct. Hikers climb 'Munros' (mountains over 3,000 feet) — Ben Nevis (1,345m) is the UK's highest peak.",
    experiences: [
      'Loch Ness monster hunt',
      'Isle of Skye Quiraing hike',
      'Glencoe valley drive',
      'Eilean Donan Castle',
      'Jacobite steam train',
      'Whisky distillery tour',
    ],
    camps: ['Inverlochy Castle', 'Kingshouse Hotel', 'The Torridon', 'Glencoe House', 'Three Chimneys Isle of Skye'],
    unesco: true,
  },
  {
    slug: 'bath',
    name: 'Bath',
    country: 'United Kingdom',
    region: 'United Kingdom',
    tagline: 'Roman Baths & Georgian Elegance',
    gradient: 'linear-gradient(160deg,#1c1000,#2c1a00,#402600)',
    image: '/images/europe/bath.jpg',
    highlights: ['Roman Baths', 'Bath Abbey', 'Royal Crescent', 'Pulteney Bridge', 'Thermae Spa', 'Jane Austen'],
    bestTime: 'May–Sep',
    duration: '1–2 nights',
    from: '$150',
    description: "Bath is England's most beautiful small city — a UNESCO World Heritage site with Roman baths, Georgian architecture, and a connection to Jane Austen. The Roman Baths are the best-preserved ancient religious spas in northern Europe — walk on original Roman pavements, see the steaming sacred spring, and taste the spa water (contains 43 minerals). Bath Abbey is a Gothic masterpiece with a spectacular fan-vaulted ceiling — climb the tower for city views. The Royal Crescent is the most famous Georgian architecture — a sweeping arc of 30 terraced houses built between 1767 and 1774. Pulteney Bridge is one of only four bridges in the world with shops built into it on both sides (inspired by Florence's Ponte Vecchio). Thermae Bath Spa is Britain's only natural thermal spa — swim on the rooftop pool with views over Bath. Jane Austen lived in Bath from 1801 to 1806 — the Jane Austen Centre has costumes, exhibits, and Regency tea.",
    experiences: [
      'Roman Baths museum',
      'Bath Abbey tower climb',
      'Royal Crescent photo',
      'Pulteney Bridge walk',
      'Thermae rooftop pool',
      'Jane Austen Centre tea',
    ],
    camps: ['The Gainsborough', 'The Royal Crescent Hotel', 'No. 15 Great Pulteney', 'The Bird Bath', 'The Francis Hotel'],
    unesco: true,
  },
  {
    slug: 'lake-district',
    name: 'Lake District',
    country: 'United Kingdom',
    region: 'United Kingdom',
    tagline: 'England\'s Most Beautiful National Park',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/europe/lake-district.jpg',
    highlights: ['Windermere', 'Derwentwater', 'Beatrix Potter', 'Keswick', 'Scafell Pike', 'Mountain Hikes'],
    bestTime: 'May–Sep',
    duration: '3–5 nights',
    from: '$160',
    description: "The Lake District is England's most beautiful national park — a UNESCO World Heritage site of glacial lakes, rolling hills (fells), and picturesque villages that inspired William Wordsworth and Beatrix Potter. Windermere is the largest lake — take a steamer cruise from Bowness to Ambleside, with views of the surrounding fells. Derwentwater is the most beautiful lake — framed by the Borrowdale Valley, with a ring of mountains reflected in its waters. Beatrix Potter's Hill Top farm is in Near Sawrey — the house and garden look exactly as they do in her books (Peter Rabbit, Jemima Puddle-Duck). Keswick is the best base — hiking, mountain biking, and the Theatre by the Lake. Scafell Pike (978m) is England's highest mountain — a challenging hike with panoramic views on a clear day. Borrowdale Valley has England's highest waterfall (Scale Force) and the Bowder Stone (a 2,000-ton boulder balanced on its edge).",
    experiences: [
      'Windermere lake cruise',
      'Derwentwater walk',
      'Hill Top Beatrix Potter',
      'Scafell Pike hike',
      'Borrowdale waterfall',
      'Ambleside village dinner',
    ],
    camps: ['Gilpin Hotel & Lake House', 'Rothay Garden Hotel', 'Lodore Falls Hotel', 'Another Place', 'Lakeside Hotel'],
    unesco: true,
  },
  {
    slug: 'cornwall',
    name: 'Cornwall',
    country: 'United Kingdom',
    region: 'United Kingdom',
    tagline: 'Poldark Coast & Clifftop Walks',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/europe/cornwall.jpg',
    highlights: ['St Ives', 'Minack Theatre', 'Land\'s End', 'Eden Project', 'Tintagel Castle', 'Cornish Pasties'],
    bestTime: 'May–Sep',
    duration: '5–7 nights',
    from: '$170',
    description: "Cornwall is England's southwestern tip — a Celtic land of rugged cliffs, hidden coves, fishing villages, and subtropical gardens warmed by the Gulf Stream. St Ives is Cornwall's most beautiful town — whitewashed cottages, turquoise water, and a world-class art gallery (Tate St Ives) dedicated to artists who lived here (Barbara Hepworth, Ben Nicholson). The Minack Theatre is a spectacular open-air theatre carved into a granite cliff overlooking the Atlantic — book ahead for a performance. Land's End is Britain's most southwesterly point — the 63-mile walk from Land's End to St Ives is the most beautiful stretch of the South West Coast Path. The Eden Project is a miracle of engineering — two giant biomes recreate rainforest and Mediterranean climates inside former clay pits. Tintagel Castle is legendary birthplace of King Arthur — cross the new bridge to the 13th-century ruins on the island. Eat a Cornish pasty (minced beef, potato, swede, onion wrapped in pastry) and drink Cornish cider.",
    experiences: [
      'St Ives seaside walk',
      'Minack Theatre performance',
      'Land\'s End clifftop',
      'Eden Project biomes',
      'Tintagel King Arthur',
      'Cornish pasty tasting',
    ],
    camps: ['The Gannet Inn', 'Unyoked St Ives', 'The Nare', 'St Moritz Hotel', 'The Pig at Harlyn Bay'],
    unesco: false,
  },
]