export const centralAfricaDestinations = [
  {
    slug: 'odzala',
    name: 'Odzala-Kokoua',
    country: 'Congo',
    region: 'Central Africa',
    tagline: 'Rainforest Gorillas & Forest Elephants',
    gradient: 'linear-gradient(160deg,#001c10,#00301a,#004422)',
    image: '/images/africa/odzala.jpg',
    highlights: ['Gorillas', 'Forest Elephants', 'Remote', 'Lodge-Based'],
    bestTime: 'Dec–Feb & Jun–Aug',
    duration: '6–8 nights',
    from: '$5,500',
    description: "Odzala-Kokoua National Park is one of Africa's oldest and most biodiverse rainforests, home to western lowland gorillas, forest elephants, and chimpanzees. This is hardcore adventure — tracking gorillas through dense jungle, sleeping in incredible eco-lodges, and experiencing true wilderness without crowds.",
    experiences: ['Gorilla tracking', 'Forest elephant viewing', 'Baï wildlife viewing platforms', 'Night jungle walks', 'River safaris'],
    camps: ['Ngaga Camp', 'Lango Camp', 'Mboko Camp', 'Odzala Discovery Camp'],
    unesco: true,
  },
  {
    slug: 'loango',
    name: 'Loango National Park',
    country: 'Gabon',
    region: 'Central Africa',
    tagline: 'Africa\'s Last Eden',
    gradient: 'linear-gradient(160deg,#001c14,#00301e,#004428)',
    image: '/images/africa/loango.jpg',
    highlights: ['Surfing Hippos', 'Forest Elephants', 'Beaches', 'Whales'],
    bestTime: 'Jun–Sep',
    duration: '5–7 nights',
    from: '$4,200',
    description: "Loango National Park is famous for one of Africa's strangest sights: hippos surfing in the Atlantic waves. This unique park combines rainforest, savannah, lagoons, and pristine beaches — where forest elephants emerge onto empty sands and humpback whales breach offshore.",
    experiences: ['Surfing hippos', 'Forest elephant beach walks', 'Whale watching', 'Lagoons kayaking', 'Gorilla trekking'],
    camps: ['Loango Lodge', 'Akaka Camp', 'Evengue Island Camp'],
    unesco: false,
  },
  {
    slug: 'virunga-drc',
    name: 'Virunga National Park',
    country: 'DR Congo',
    region: 'Central Africa',
    tagline: 'Mountain Gorillas & Active Volcano',
    gradient: 'linear-gradient(160deg,#002010,#003018,#004020)',
    image: '/images/africa/virunga-drc.jpg',
    highlights: ['Gorillas', 'Nyiragongo Volcano', 'Hiking', 'Conservation'],
    bestTime: 'Jun–Aug & Dec–Feb',
    duration: '4–7 nights',
    from: '$2,400',
    description: "Virunga National Park is Africa's oldest national park (1925) and a UNESCO World Heritage site. It's home to mountain gorillas, the active Nyiragongo volcano (with the world's largest lava lake), and the endangered okapi. Despite challenges, Virunga offers one of Africa's most dramatic and rewarding adventures.",
    experiences: ['Nyiragongo lava lake hike', 'Mountain gorilla trekking', 'Mikeno Lodge stay', 'Ranger-led walks', 'Senkwekwe Centre gorilla orphanage'],
    camps: ['Mikeno Lodge', 'Nyiragongo Summit Shelters', 'Bukima Tented Camp', 'Lulimbi Tented Camp'],
    unesco: true,
  },
  {
    slug: 'dzanga-sangha',
    name: 'Dzanga-Sangha',
    country: 'Central African Republic',
    region: 'Central Africa',
    tagline: 'Baï of the Forest Elephants',
    gradient: 'linear-gradient(160deg,#001c0c,#003016,#004420)',
    image: '/images/africa/dzanga-sangha.jpg',
    highlights: ['Forest Elephants', 'Gorillas', 'Baï', 'Remote'],
    bestTime: 'Nov–May',
    duration: '5–8 nights',
    from: '$3,800',
    description: "Dzanga-Sangha is one of Africa's most remote and pristine rainforest parks, centered around the Dzanga Bai — a forest clearing where up to 100 elephants gather daily to drink mineral-rich water. You'll observe from a raised hide, sometimes meters away from gentle forest elephants.",
    experiences: ['Dzanga Bai elephant viewing', 'Gorilla habituation', 'Pygmy village visits', 'Forest night walks', 'Sangha River pirogue trips'],
    camps: ['Dzanga Sangha Lodge', 'Bai Camp', 'Forest Huts'],
    unesco: true,
  },
]