export const eastAfricaDestinations = [
  {
    slug: 'serengeti',
    name: 'Serengeti',
    country: 'Tanzania',
    region: 'East Africa',
    tagline: 'The Greatest Wildlife Show on Earth',
    gradient: 'linear-gradient(160deg,#1a1000,#2a1c00,#3a2800)',
    image: '/images/africa/serengeti.jpg',
    highlights: ['Great Migration', 'Big Five', 'Luxury Tented Camps', 'Balloon Safaris'],
    bestTime: 'Jul–Oct (Migration) · Jan–Feb (Calving)',
    duration: '5–10 nights',
    from: '$3,200',
    description: "The Serengeti is Africa's most famous ecosystem — two million wildebeest, 500,000 zebra, and the world's highest concentration of predators. The annual Great Migration is the largest overland mammal movement on Earth, with river crossings that are nature's most dramatic spectacle. Beyond the migration, the Serengeti offers year-round Big Five sightings, luxury tented camps under endless skies, and hot air balloon safaris at sunrise.",
    experiences: ['Great Migration river crossings', 'Hot air balloon safari', 'Walking safari', 'Night game drives', 'Luxury glamping'],
    camps: ['Singita Grumeti', "&Beyond Klein's Camp", 'Four Seasons Serengeti', 'Sayari Camp', 'Nomad Lamai'],
    unesco: true,
  },
  {
    slug: 'ngorongoro',
    name: 'Ngorongoro Crater',
    country: 'Tanzania',
    region: 'East Africa',
    tagline: 'The Natural Wonder That Holds a World',
    gradient: 'linear-gradient(160deg,#0e1400,#182000,#222c00)',
    image: '/images/africa/ngorongoro.jpg',
    highlights: ['Black Rhino', 'Big Five Density', 'Crater Floor Drive', 'Masai Heritage'],
    bestTime: 'Year-Round · Jun–Sep Best',
    duration: '2–4 nights',
    from: '$1,800',
    description: "The Ngorongoro Crater is the world's largest intact volcanic caldera, spanning 260 square kilometers and hosting over 25,000 large animals in a self-contained ecosystem. This UNESCO World Heritage site offers the highest density of Big Five in Africa, including endangered black rhinos you can spot on the crater floor.",
    experiences: ['Crater floor game drives', 'Black rhino spotting', 'Hippo pool picnics', 'Masai village visits', 'Crater rim sunsets'],
    camps: ['Ngorongoro Crater Lodge', 'The Manor at Ngorongoro', 'Serena Lodge', 'Entamanu Ngorongoro'],
    unesco: true,
  },
  {
    slug: 'zanzibar',
    name: 'Zanzibar',
    country: 'Tanzania',
    region: 'East Africa',
    tagline: 'Spice Islands & White Sand Beaches',
    gradient: 'linear-gradient(160deg,#001a12,#002d1e,#00402a)',
    image: '/images/africa/zanzibar.jpg',
    highlights: ['Beaches', 'Stone Town', 'Diving', 'Spice Tours'],
    bestTime: 'Jun–Oct & Dec–Feb',
    duration: '5–8 nights',
    from: '$1,400',
    description: "Zanzibar is an archipelago off the coast of Tanzania, known as the 'Spice Islands' for its clove, nutmeg, and cinnamon plantations. Stone Town, a UNESCO World Heritage site, is a labyrinth of narrow alleys, carved wooden doors, and bustling bazaars reflecting Swahili, Arab, Persian, Indian, and European influences.",
    experiences: ['Mnemba snorkeling', 'Spice farm tours', 'Dhow sunset cruises', 'Stone Town walks', 'Dolphin trips'],
    camps: ['The Residence', 'Zuri Zanzibar', 'Mnemba Island Lodge', '&Beyond Mnemba', 'Park Hyatt Zanzibar'],
    unesco: true,
  },
  {
    slug: 'masai-mara',
    name: 'Masai Mara',
    country: 'Kenya',
    region: 'East Africa',
    tagline: "Kenya's Crown Jewel of Wildlife",
    gradient: 'linear-gradient(160deg,#180e00,#2a1800,#3c2200)',
    image: '/images/africa/masai-mara.jpg',
    highlights: ['Big Five', 'Mara River Crossings', 'Masai Culture', 'Year-Round Wildlife'],
    bestTime: 'Jul–Oct (Crossings) · Jan–Mar (Predators)',
    duration: '4–8 nights',
    from: '$2,800',
    description: "The Masai Mara is Kenya's most famous reserve, forming the northern continuation of the Serengeti ecosystem. July to October brings the Great Migration's most dramatic event — the Mara River crossings, where thousands of wildebeest and zebra hurl themselves into crocodile-infested waters.",
    experiences: ['Mara River wildebeest crossings', 'Big Five game drives', 'Masai village visit', 'Bush breakfast', 'Hot air balloon'],
    camps: ["Mahali Mzuri", "Governors' Camp", 'Angama Mara', '&Beyond Bateleur', "Cottar's Camp"],
    unesco: false,
  },
  {
    slug: 'amboseli',
    name: 'Amboseli',
    country: 'Kenya',
    region: 'East Africa',
    tagline: 'Elephants with Kilimanjaro Views',
    gradient: 'linear-gradient(160deg,#1a1200,#2a1c00,#3a2600)',
    image: '/images/africa/amboseli.jpg',
    highlights: ['Elephant Herds', 'Kilimanjaro Views', 'Birding', 'Swamp Wildlife'],
    bestTime: 'Jun–Oct',
    duration: '3–5 nights',
    from: '$1,600',
    description: "Amboseli National Park is famous for two things: massive elephant herds and the best views of Mount Kilimanjaro in Africa. The park's swampy ground water attracts hundreds of elephants, often photographed with Africa's highest peak as a backdrop. Amboseli is also one of the best places in Africa for birdwatching, with over 400 species.",
    experiences: ['Elephant photography', 'Observation Hill hike', 'Swamp birdwatching', 'Masai cultural visits', 'Kilimanjaro sunrise'],
    camps: ['Amboseli Serena Lodge', 'Tortilis Camp', 'Ol Tukai Lodge', 'Elephant Peak Lodge'],
    unesco: false,
  },
  {
    slug: 'samburu',
    name: 'Samburu',
    country: 'Kenya',
    region: 'East Africa',
    tagline: 'Unique Northern Species',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/africa/samburu.jpg',
    highlights: ['Reticulated Giraffe', "Grevy's Zebra", 'Somali Ostrich', 'Samburu Culture'],
    bestTime: 'Jun–Oct',
    duration: '3–5 nights',
    from: '$1,900',
    description: "Samburu National Reserve is located in Kenya's northern frontier, a semi-arid landscape along the Ewaso Ng'iro River. It's home to the 'Samburu Special Five' — species rarely seen elsewhere: the reticulated giraffe, Grevy's zebra, Somali ostrich, beisa oryx, and gerenuk.",
    experiences: ['Special Five game drives', 'Ewaso River viewing', 'Samburu village visits', 'Night game drives', 'Leopard tracking'],
    camps: ['Saruni Samburu', 'Elephant Bedroom Camp', 'Sasaab Lodge', 'Larsens Camp'],
    unesco: false,
  },
  {
    slug: 'rwanda-gorillas',
    name: 'Volcanoes National Park',
    country: 'Rwanda',
    region: 'East Africa',
    tagline: 'Face to Face with Mountain Gorillas',
    gradient: 'linear-gradient(160deg,#001800,#002800,#003800)',
    image: '/images/africa/volcanoes-rwanda.jpg',
    highlights: ['Gorilla Trekking', 'Golden Monkeys', 'Volcano Hikes', 'Conservation'],
    bestTime: 'Jun–Sep & Dec–Feb',
    duration: '3–5 nights',
    from: '$3,600',
    description: "Volcanoes National Park is one of only three places in the world where you can trek to see endangered mountain gorillas. Located in Rwanda's northwest, the park protects the Virunga Mountains — a chain of eight volcanoes covered in bamboo forest and Afro-alpine vegetation. Gorilla trekking here is an unforgettable experience.",
    experiences: ['Gorilla trekking', 'Golden monkey tracking', 'Volcano hikes', 'Kigali memorial', 'Dian Fossey Centre'],
    camps: ['One&Only Gorilla’s Nest', 'Bisate Lodge', 'Virunga Lodge', 'Sabyinyo Lodge'],
    unesco: true,
  },
  {
    slug: 'bwindi',
    name: 'Bwindi Forest',
    country: 'Uganda',
    region: 'East Africa',
    tagline: 'The Pearl of Africas Gorilla Kingdom',
    gradient: 'linear-gradient(160deg,#001c10,#00301a,#004422)',
    image: '/images/africa/bwindi.jpg',
    highlights: ['Gorilla Trekking', 'Chimpanzees', 'Batwa Culture', 'Birding'],
    bestTime: 'Jun–Aug & Dec–Feb',
    duration: '3–5 nights',
    from: '$2,900',
    description: "Bwindi Impenetrable National Park is Uganda's premier gorilla trekking destination, home to nearly half of the world's remaining mountain gorillas. The name 'Impenetrable' is accurate — this ancient rainforest is a tangled maze of vines, bamboo, and hardwood trees.",
    experiences: ['Gorilla trekking', 'Batwa pygmy cultural experience', 'Bird watching', 'Forest nature walks', 'Waterfall hiking'],
    camps: ['Sanctuary Gorilla Forest Camp', 'Buhoma Lodge', 'Mahogany Springs', 'Engagi Lodge'],
    unesco: true,
  },
  {
    slug: 'kibale',
    name: 'Kibale Forest',
    country: 'Uganda',
    region: 'East Africa',
    tagline: 'Primate Capital of the World',
    gradient: 'linear-gradient(160deg,#002010,#003018,#004020)',
    image: '/images/africa/kibale.jpg',
    highlights: ['Chimpanzee Tracking', '13 Primate Species', 'Forest Walks', 'Nocturnal Primates'],
    bestTime: 'Dec–Feb & Jun–Aug',
    duration: '3–4 nights',
    from: '$1,800',
    description: "Kibale National Park is Uganda's best destination for chimpanzee tracking, with over 1,500 chimps living in its 795 square kilometers of rainforest. It's called the 'Primate Capital of the World' because it hosts 13 primate species — more than any other African forest.",
    experiences: ['Chimpanzee habituation', 'Night primate walks', 'Bigodi wetland birding', 'Forest canopy hikes', 'Tea plantation visits'],
    camps: ['Kibale Forest Camp', 'Primate Lodge', 'Crater Safari Lodge', 'Papaya Lake Lodge'],
    unesco: false,
  },
  {
    slug: 'lalibela',
    name: 'Lalibela',
    country: 'Ethiopia',
    region: 'East Africa',
    tagline: 'Rock-Hewn Churches & Ancient History',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/africa/lalibela.jpg',
    highlights: ['Rock Churches', 'Pilgrimage', 'Orthodox Festivals', 'History'],
    bestTime: 'Oct–May',
    duration: '3–5 nights',
    from: '$1,500',
    description: "Lalibela is Ethiopia's holiest city, famous for its 11 medieval rock-hewn churches carved from solid red volcanic rock in the 12th century. The churches are connected by tunnels and trenches, with Biete Medhani Alem being the largest monolithic church on Earth.",
    experiences: ['Rock church exploration', 'Timkat festival', 'Asheten Maryam hike', 'Local priest blessings', 'Tunnel walks'],
    camps: ['Mezena Lodge', 'Mountain View Hotel', 'Lalibela Lodge', 'Sora Lodge'],
    unesco: true,
  },
  {
    slug: 'simien-mountains',
    name: 'Simien Mountains',
    country: 'Ethiopia',
    region: 'East Africa',
    tagline: 'Gelada Baboons & Dramatic Peaks',
    gradient: 'linear-gradient(160deg,#0e1800,#182400,#223000)',
    image: '/images/africa/simien.jpg',
    highlights: ['Gelada Baboons', 'Mountain Hikes', 'Ras Dashen', 'Ethiopian Wolves'],
    bestTime: 'Oct–May',
    duration: '4–6 nights',
    from: '$1,200',
    description: "The Simien Mountains National Park is a UNESCO World Heritage site and one of Africa's most dramatic landscapes — jagged peaks, deep valleys, and precipices dropping 1,500 meters. It's home to the gelada baboon, the rare Ethiopian wolf, and the walia ibex.",
    experiences: ['Gelada baboon encounters', 'Escarpment sunrise treks', 'Ras Dashen trek', 'Ethiopian wolf spotting', 'Local guide stories'],
    camps: ['Limalimo Lodge', 'Semien Lodge', 'Simien Park Hotel', 'Gondar Hills Resort'],
    unesco: true,
  },
  {
    slug: 'danakil',
    name: 'Danakil Depression',
    country: 'Ethiopia',
    region: 'East Africa',
    tagline: 'The Hottest Place on Earth',
    gradient: 'linear-gradient(160deg,#2a1000,#3e1c00,#522800)',
    image: '/images/africa/danakil.jpg',
    highlights: ['Dallol Volcano', 'Salt Flats', 'Erta Ale Lava Lake', 'Afar Culture'],
    bestTime: 'Nov–Feb',
    duration: '3–5 nights',
    from: '$1,400',
    description: "The Danakil Depression is one of Earth's most extreme environments — temperatures over 50°C, neon-colored hydrothermal fields, salt flats stretching to the horizon, and a permanent lava lake at Erta Ale volcano. This is an adventure into a landscape that feels like another planet.",
    experiences: ['Dallol hydrothermal fields', 'Erta Ale lava lake night hike', 'Salt flat camel caravans', 'Afar village visits', 'Lake Asale sunrise'],
    camps: ['Erta Ale Base Camp', 'Hamedela Camp', 'Mekele Hotels', 'Semera Lodge'],
    unesco: false,
  },
]