export const islandEscapesDestinations = [
  {
    slug: 'mauritius',
    name: 'Mauritius',
    country: 'Mauritius',
    region: 'East Africa',
    tagline: 'Indian Ocean Luxury Paradise',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/africa/mauritius.jpg',
    highlights: ['Beaches', 'Luxury Resorts', 'Honeymoon', 'Underwater Waterfall'],
    bestTime: 'May–Dec',
    duration: '5–9 nights',
    from: '$1,900',
    description: "Mauritius is the Indian Ocean's most developed luxury destination — a volcanic island surrounded by coral reefs, home to palm-fringed beaches, turquoise lagoons, and the world's most spectacular optical illusion: the 'underwater waterfall' visible from helicopter. It's the perfect beach extension after a South African safari.",
    experiences: ['Helicopter over underwater waterfall', 'Seven Colored Earths', 'Ile aux Cerfs day trip', 'Port Louis market', 'Luxury resort pool days'],
    camps: ['One&Only Le Saint Géran', 'Four Seasons Mauritius', 'Shangri-La Le Touessrok', 'Royal Palm', 'LUX Grand Gaube'],
    unesco: false,
  },
  {
    slug: 'seychelles',
    name: 'Seychelles',
    country: 'Seychelles',
    region: 'East Africa',
    tagline: "World's Most Beautiful Beaches",
    gradient: 'linear-gradient(160deg,#002428,#003838,#004c4c)',
    image: '/images/africa/seychelles.jpg',
    highlights: ['Anse Source d\'Argent', 'Giant Tortoises', 'Snorkeling', 'Island Hopping'],
    bestTime: 'Apr–May & Oct–Nov',
    duration: '6–10 nights',
    from: '$2,300',
    description: "The Seychelles archipelago is the definition of tropical perfection — granite boulders tumbling into turquoise water, powdery white sand, giant tortoises roaming free, and coral reefs teeming with life. Anse Source d'Argent on La Digue is consistently ranked the world's most beautiful beach.",
    experiences: ['Anse Source d\'Argent beach', 'Aldabra tortoise feeding', 'Morne Seychellois hike', 'Sainte Anne Marine Park snorkeling', 'Island hopping by ferry'],
    camps: ['North Island', 'Four Seasons Seychelles', 'Six Senses Zil Pasyon', 'Raffles Praslin', 'Constance Ephelia'],
    unesco: true,
  },
  {
    slug: 'praslin',
    name: 'Praslin Island',
    country: 'Seychelles',
    region: 'East Africa',
    tagline: 'Vallee de Mai & Coco de Mer',
    gradient: 'linear-gradient(160deg,#001c18,#003028,#004438)',
    image: '/images/africa/praslin.jpg',
    highlights: ['Vallee de Mai', 'Coco de Mer', 'Anse Lazio', 'Praslin Beaches'],
    bestTime: 'Apr–May & Oct–Nov',
    duration: '4–6 nights',
    from: '$2,100',
    description: "Praslin is the Seychelles' second-largest island, home to the UNESCO-listed Vallée de Mai — a primeval forest of giant coco de mer palms that produce the world's largest seed (the 'love nut'). The island also boasts Anse Lazio, consistently rated among the world's top 10 beaches.",
    experiences: ['Vallee de Mai nature trail', 'Coco de mer viewing', 'Anse Lazio beach day', 'Praslin island tour', 'Curieuse Island tortoise visit'],
    camps: ['Raffles Praslin', 'Constance Lémuria', 'Paradise Sun', 'Coco de Mer Hotel', 'Acajou Beach Resort'],
    unesco: true,
  },
  {
    slug: 'nosy-be',
    name: 'Nosy Be',
    country: 'Madagascar',
    region: 'East Africa',
    tagline: 'Perfume Island',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/africa/nosy-be.jpg',
    highlights: ['Beaches', 'Lemurs', 'Marine Life', 'Ylang-Ylang'],
    bestTime: 'Apr–Nov',
    duration: '5–7 nights',
    from: '$1,600',
    description: "Nosy Be is Madagascar's premier beach destination — a volcanic island off the northwest coast known as 'Perfume Island' for its ylang-ylang plantations. The island offers beautiful beaches, world-class snorkeling, lemur spotting in Lokobe Reserve, and a laid-back Creole atmosphere.",
    experiences: ['Lokobe Reserve lemur trek', 'Nosy Tanikely snorkeling', 'Ylang-ylang distillery tour', 'Nosy Komba day trip', 'Vezo fishing village visit'],
    camps: ['Ravintsara Wellness', 'Anjiamarango Beach Resort', 'Constance Tsarabanjina', 'Vanila Hotel', 'Madirokely Lodge'],
    unesco: false,
  },
  {
    slug: 'madagascar-wildlife',
    name: 'Madagascar Wildlife Circuit',
    country: 'Madagascar',
    region: 'East Africa',
    tagline: 'Lemurs & Baobabs',
    gradient: 'linear-gradient(160deg,#001c0c,#003016,#004420)',
    image: '/images/africa/madagascar-wildlife.jpg',
    highlights: ['Lemurs', 'Baobabs', 'Rainforests', 'Unique Wildlife'],
    bestTime: 'Apr–Oct',
    duration: '7–12 nights',
    from: '$2,100',
    description: "Madagascar's wildlife circuit is a journey through one of Earth's most unique ecosystems — 90% of its wildlife exists nowhere else. Spot indri lemurs singing in Andasibe rainforest, see ring-tailed lemurs in Isalo, watch dancing sifakas in Kirindy, and photograph the iconic Avenue of the Baobabs at sunset.",
    experiences: ['Avenue of Baobabs sunset', 'Indri lemur spotting', 'Tsiribihina River cruise', 'Isalo National Park trekking', 'Spiny forest night walk'],
    camps: ['Vakona Forest Lodge', 'Relais de la Reine', 'Baobab Cafe', 'Le Jardin du Roy', 'Princesse Tsarasoa'],
    unesco: true,
  },
  {
    slug: 'bazaruto',
    name: 'Bazaruto Archipelago',
    country: 'Mozambique',
    region: 'Southern Africa',
    tagline: 'Untouched Marine Paradise',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/africa/bazaruto.jpg',
    highlights: ['Diving', 'Dugongs', 'Island Hopping', 'Sand Dunes'],
    bestTime: 'May–Nov',
    duration: '5–8 nights',
    from: '$2,000',
    description: "The Bazaruto Archipelago is Mozambique's protected marine national park — a string of sandy islands with no permanent population, surrounded by some of the Indian Ocean's healthiest coral reefs. It's one of the last places to see dugongs in East Africa, and the diving rivals the Maldives.",
    experiences: ['Dugong spotting', 'Dive reef walls', 'Snorkel with turtles', 'Sand dune climb', 'Island beach picnics'],
    camps: ['Anantara Bazaruto', 'Kisawa Sanctuary', 'Azura Quilalea', 'Bazaruto Lodge'],
    unesco: false,
  },
  {
    slug: 'comoros',
    name: 'Comoros Islands',
    country: 'Comoros',
    region: 'East Africa',
    tagline: 'The Fragrant Islands',
    gradient: 'linear-gradient(160deg,#001c14,#00301e,#004428)',
    image: '/images/africa/comoros.jpg',
    highlights: ['Volcanoes', 'Beaches', 'Culture', 'Vanilla'],
    bestTime: 'May–Nov',
    duration: '5–7 nights',
    from: '$1,500',
    description: "The Comoros archipelago is one of Africa's least-visited nations — a peaceful blend of African, Arab, and French cultures, with volcanic peaks, fragrant vanilla plantations, and near-empty beaches. Hike the active volcano at Lac Sale, explore Moroni's medina, and discover a land that time forgot.",
    experiences: ['Karthala volcano trek', 'Lac Sale crater lake', 'Moroni medina walk', 'Vanilla plantation tour', 'Lakada Beach swimming'],
    camps: ['Retaj Moroni', 'Moheli Laka Lodge', 'Galawa Beach Resort', 'Itsandra Beach Hotel'],
    unesco: false,
  },
]