export const northAfricaDestinations = [
  {
    slug: 'egypt-cairo',
    name: 'Cairo & Giza',
    country: 'Egypt',
    region: 'North Africa',
    tagline: 'The Ancient Pyramids',
    gradient: 'linear-gradient(160deg,#1c0e00,#2e1800,#402200)',
    image: '/images/africa/cairo.jpg',
    highlights: ['Pyramids', 'Sphinx', 'Egyptian Museum', 'Islamic Cairo'],
    bestTime: 'Oct–Apr',
    duration: '4–6 nights',
    from: '$1,500',
    description: "Cairo is the gateway to ancient Egypt, home to the last surviving Wonder of the Ancient World — the Pyramids of Giza. Stand before the Great Pyramid of Khufu, gaze at the Sphinx, and explore the treasures of Tutankhamun at the Egyptian Museum. Islamic Cairo offers bustling bazaars, medieval mosques, and the historic Khan el-Khalili market.",
    experiences: ['Pyramids & Sphinx tour', 'Egyptian Museum visit', 'Khan el-Khalili market', 'Nile felucca ride', 'Islamic Cairo walk'],
    camps: ['Marriott Mena House', 'Four Seasons Nile Plaza', 'The Nile Ritz-Carlton', 'Kempinski Nile'],
    unesco: true,
  },
  {
    slug: 'luxor',
    name: 'Luxor',
    country: 'Egypt',
    region: 'North Africa',
    tagline: "The World's Greatest Open-Air Museum",
    gradient: 'linear-gradient(160deg,#1c1000,#2c1a00,#402600)',
    image: '/images/africa/luxor.jpg',
    highlights: ['Valley of Kings', 'Karnak Temple', 'Hot Air Balloon', 'Luxor Temple'],
    bestTime: 'Oct–Apr',
    duration: '3–5 nights',
    from: '$1,300',
    description: "Luxor is often called the world's greatest open-air museum. The east bank holds the magnificent Karnak and Luxor Temples, while the west bank is home to the Valley of the Kings (where Tutankhamun's tomb was found), the Valley of the Queens, and the mortuary temple of Hatshepsut.",
    experiences: ['Valley of Kings tombs', 'Karnak Temple sound & light', 'Hot air balloon at sunrise', 'Hatshepsut Temple', 'Luxor Temple at night'],
    camps: ['Sofitel Winter Palace', 'Al Moudira Hotel', 'Hilton Luxor', 'Steigenberger Nile Palace'],
    unesco: true,
  },
  {
    slug: 'red-sea',
    name: 'Red Sea Riviera',
    country: 'Egypt',
    region: 'North Africa',
    tagline: 'World-Class Diving & Beaches',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/africa/red-sea.jpg',
    highlights: ['Diving', 'Snorkeling', 'Resorts', 'Coral Reefs'],
    bestTime: 'Mar–Nov',
    duration: '5–8 nights',
    from: '$1,400',
    description: "The Red Sea is one of the world's top diving destinations, with crystal-clear waters, vibrant coral reefs, and abundant marine life. Sharm el-Sheikh, Hurghada, and Marsa Alam offer world-class resorts, while the Thistlegorm wreck and Ras Mohammed National Park are bucket-list dives.",
    experiences: ['Reef snorkeling', 'Thistlegorm wreck dive', 'Glass bottom boat', 'Desert quad biking', 'Luxury resort stays'],
    camps: ['Four Seasons Sharm', 'Rixos Premium', 'Steigenberger Coraya', 'Kempinski Soma Bay'],
    unesco: false,
  },
  {
    slug: 'marrakech',
    name: 'Marrakech',
    country: 'Morocco',
    region: 'North Africa',
    tagline: 'The Red City of Magic',
    gradient: 'linear-gradient(160deg,#2a1800,#402600,#563400)',
    image: '/images/africa/marrakech.jpg',
    highlights: ['Medina', 'Souks', 'Jemaa el-Fnaa', 'Palaces'],
    bestTime: 'Mar–May & Sep–Nov',
    duration: '4–6 nights',
    from: '$1,200',
    description: "Marrakech is Morocco's most intoxicating city — a sensory overload of snake charmers in Jemaa el-Fnaa square, the labyrinthine souks of the medina, the ornate Bahia Palace, and the peaceful gardens of Majorelle. At night, the square transforms into an open-air restaurant with storytellers, musicians, and food stalls.",
    experiences: ['Jemaa el-Fnaa at night', 'Medina souk shopping', 'Bahia Palace tour', 'Majorelle Garden', 'Atlas Mountains day trip'],
    camps: ['La Mamounia', 'Royal Mansour', 'Riad Fes', 'El Fenn', 'Four Seasons Marrakech'],
    unesco: false,
  },
  {
    slug: 'sahara-morocco',
    name: 'Sahara Desert',
    country: 'Morocco',
    region: 'North Africa',
    tagline: 'Merzouga & Erg Chebbi',
    gradient: 'linear-gradient(160deg,#2a1a00,#402800,#563600)',
    image: '/images/africa/sahara-morocco.jpg',
    highlights: ['Camel Trekking', 'Desert Camps', 'Stargazing', 'Sandboarding'],
    bestTime: 'Oct–Apr',
    duration: '2–4 nights',
    from: '$800',
    description: "The Moroccan Sahara is the quintessential desert experience — riding camels over rolling sand dunes, sleeping in luxury Berber camps under a blanket of stars, and watching the sunrise paint the Erg Chebbi dunes in shades of orange and gold. It's a journey into silence and immensity.",
    experiences: ['Camel trek at sunset', 'Luxury desert camp', 'Sandboarding down dunes', 'Stargazing with guides', 'Berber music under stars'],
    camps: ['Merzouga Luxury Desert Camp', 'Erg Chebbi Camp', 'Sahara Majestic Camp', 'Berber Camp'],
    unesco: false,
  },
  {
    slug: 'chefchaouen',
    name: 'Chefchaouen',
    country: 'Morocco',
    region: 'North Africa',
    tagline: 'The Blue Pearl',
    gradient: 'linear-gradient(160deg,#001c24,#003038,#00444c)',
    image: '/images/africa/chefchaouen.jpg',
    highlights: ['Blue Streets', 'Mountain Views', 'Photography', 'Relaxation'],
    bestTime: 'Apr–Oct',
    duration: '2–3 nights',
    from: '$600',
    description: "Chefchaouen is Morocco's most photogenic town — a maze of cobblestone streets painted in every shade of blue, set against the backdrop of the Rif Mountains. It's a place to wander without a map, discover hidden doorways, browse local wool and leather goods, and enjoy the slow pace of mountain life.",
    experiences: ['Blue street photography', 'Spanish Mosque hike', 'Local market shopping', 'Mountain views', 'Relaxed cafe life'],
    camps: ['Lina Ryad & Spa', 'Dar Elrio', 'Casa Sabila', 'Riad Cherifa'],
    unesco: false,
  },
]
