export const southernAfricaDestinations = [
  {
    slug: 'okavango',
    name: 'Okavango Delta',
    country: 'Botswana',
    region: 'Southern Africa',
    tagline: "The World's Largest Inland Delta",
    gradient: 'linear-gradient(160deg,#001c10,#002c1a,#003c22)',
    image: '/images/africa/okavango.jpg',
    highlights: ['Mokoro Canoe', 'Walking Safaris', 'Wild Dogs', 'Fly-In Luxury'],
    bestTime: 'May–Oct',
    duration: '5–8 nights',
    from: '$4,200',
    description: "The Okavango Delta is a UNESCO World Heritage site and one of Africa's last great wilderness areas. This vast inland delta fans out into a labyrinth of lagoons, channels, and islands teeming with wildlife. The best way to explore is by mokoro (traditional dugout canoe), gliding silently past hippos, elephants, and crocodiles.",
    experiences: ['Mokoro canoe safaris', 'Walking safaris', 'Fly-in aircraft transfers', 'Wild dog tracking', 'Elephant waterhole viewing'],
    camps: ['andBeyond Xaranna', 'Wilderness Vumbura Plains', 'Mombo Camp', 'Duba Plains', 'Belmond Eagle Island Lodge'],
    unesco: true,
  },
  {
    slug: 'chobe',
    name: 'Chobe National Park',
    country: 'Botswana',
    region: 'Southern Africa',
    tagline: "Africa's Elephant Capital",
    gradient: 'linear-gradient(160deg,#001c0c,#002c16,#003c20)',
    image: '/images/africa/chobe.jpg',
    highlights: ['Elephant Herds', 'River Cruises', 'Big Five', 'Birding'],
    bestTime: 'May–Oct',
    duration: '3–5 nights',
    from: '$2,500',
    description: "Chobe National Park is famous for having the largest elephant population in Africa — over 50,000 elephants roam its plains. The Chobe Riverfront is the park's highlight, where boat safaris bring you within meters of elephants swimming between islands, hippos yawning, and crocodiles basking on sandbanks.",
    experiences: ['Chobe River boat safaris', 'Elephant photography', '4x4 game drives', 'Sunset river cruises', 'Wild dog tracking'],
    camps: ['Chobe Game Lodge', 'Chobe Elephant Camp', 'Ngoma Safari Lodge', 'Sanctuary Chobe Chilwero'],
    unesco: false,
  },
  {
    slug: 'kruger',
    name: 'Kruger National Park',
    country: 'South Africa',
    region: 'Southern Africa',
    tagline: 'Africa’s Most Accessible Safari',
    gradient: 'linear-gradient(160deg,#180e00,#2a1800,#3c2200)',
    image: '/images/africa/kruger.jpg',
    highlights: ['Big Five', 'Self-Drive Safari', 'Private Concessions', 'Cape Town Add-On'],
    bestTime: 'May–Sep',
    duration: '4–7 nights',
    from: '$1,400',
    description: "Kruger National Park is Africa's best park for self-drive safaris — nearly 2 million hectares with an excellent road network, rest camps, and affordable entry fees. You can see the Big Five in a weekend, plus cheetahs, wild dogs, and over 500 bird species.",
    experiences: ['Self-drive safari routes', 'Private reserve game drives', 'Night drives', 'Bush walks', 'Leopard sightings'],
    camps: ['Singita Sabi Sand', 'Lion Sands Ivory Lodge', 'Londolozi Tree Camp', "&Beyond Kirkman's Kamp", 'Inyati Game Lodge'],
    unesco: false,
  },
  {
    slug: 'cape-town',
    name: 'Cape Town',
    country: 'South Africa',
    region: 'Southern Africa',
    tagline: 'Where Mountains Meet Ocean',
    gradient: 'linear-gradient(160deg,#001018,#001c2d,#002840)',
    image: '/images/africa/cape-town.jpg',
    highlights: ['Table Mountain', 'Winelands', 'Penguins', 'Cape Point'],
    bestTime: 'Oct–Apr',
    duration: '5–8 nights',
    from: '$1,800',
    description: "Cape Town is one of the world's most beautiful cities, dominated by the flat-topped Table Mountain and the Atlantic Ocean. Take the cable car up Table Mountain for panoramic views, visit Robben Island, explore the colorful Bo-Kaap neighborhood, and drive the Chapman's Peak coastal road.",
    experiences: ['Table Mountain hike', 'Cape Point drive', 'Penguin colony visit', 'Wine tasting', 'Waterfront dining'],
    camps: ['The Silo Hotel', 'Ellerman House', 'Cape Grace', 'Mount Nelson', '12 Apostles Hotel'],
    unesco: true,
  },
  {
    slug: 'garden-route',
    name: 'Garden Route',
    country: 'South Africa',
    region: 'Southern Africa',
    tagline: 'The Ultimate African Road Trip',
    gradient: 'linear-gradient(160deg,#001c14,#002c1e,#004028)',
    image: '/images/africa/garden-route.jpg',
    highlights: ['Coastal Drive', 'Knysna', 'Tsitsikamma', 'Ostrich Farms'],
    bestTime: 'Oct–Apr',
    duration: '4–8 nights',
    from: '$1,100',
    description: "The Garden Route is South Africa's most scenic drive, stretching 300 kilometers from Mossel Bay to Storms River. You'll pass pristine beaches, ancient forests, lagoons, and dramatic coastal cliffs. Stop in Knysna for oysters and lagoon cruises, hike the Robberg Peninsula, and bungee jump from Bloukrans Bridge.",
    experiences: ['Robberg Peninsula hike', 'Knysna lagoon cruise', 'Tsitsikamma canopy tour', 'Bloukrans bungee jump', 'Cango Caves tour'],
    camps: ['The Plettenberg', 'Tsala Treetop Lodge', "Hunter's Country House", "Loerie's Call"],
    unesco: false,
  },
  {
    slug: 'south-luangwa',
    name: 'South Luangwa',
    country: 'Zambia',
    region: 'Southern Africa',
    tagline: 'Birthplace of the Walking Safari',
    gradient: 'linear-gradient(160deg,#001c10,#002c1a,#003c22)',
    image: '/images/africa/south-luangwa.jpg',
    highlights: ['Walking Safaris', 'Leopards', 'Night Drives', 'Remote Wilderness'],
    bestTime: 'May–Oct',
    duration: '4–7 nights',
    from: '$2,500',
    description: "South Luangwa National Park is Zambia's premier safari destination, credited as the birthplace of the walking safari. Here, you'll leave the vehicle behind and track wildlife on foot with armed guides — a completely different experience from game drives. The park is famous for its leopard population, one of Africa's highest.",
    experiences: ['Walking safaris', 'Night game drives', 'Leopard tracking', 'Thornicroft giraffe viewing', 'Luangwa River cruises'],
    camps: ['Time + Tide Chinzombo', 'Kafunta River Lodge', 'Mfuwe Lodge', "Robin's House", 'Zikomo Safari Camp'],
    unesco: false,
  },
  {
    slug: 'victoria-falls',
    name: 'Victoria Falls',
    country: 'Zimbabwe',
    region: 'Southern Africa',
    tagline: 'The Smoke That Thunders',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/africa/victoria-falls.jpg',
    highlights: ['Victoria Falls', 'Zambezi Cruises', 'Helicopter Tours', 'Bungee Jumping'],
    bestTime: 'Apr–Oct',
    duration: '3–5 nights',
    from: '$2,200',
    description: "Victoria Falls is one of the world's greatest natural wonders — 1.7 kilometers wide and plunging 108 meters into the Zambezi Gorge. Known locally as 'Mosi-oa-Tunya' (The Smoke that Thunders), the spray can be seen from 50 kilometers away.",
    experiences: ['Helicopter flight', 'Zambezi sunset cruise', 'Bungee jump (111m)', "Devil's Pool swim", 'White water rafting'],
    camps: ['Victoria Falls Hotel', 'The Stanley & Livingstone', 'Elephants Eye Lodge', 'Ilala Lodge'],
    unesco: true,
  },
  {
    slug: 'hwange',
    name: 'Hwange National Park',
    country: 'Zimbabwe',
    region: 'Southern Africa',
    tagline: 'Massive Elephant Herds',
    gradient: 'linear-gradient(160deg,#1a1200,#2c1c00,#3e2600)',
    image: '/images/africa/hwange.jpg',
    highlights: ['Elephants', 'Big Five', 'Wild Dogs', 'Waterhole Viewing'],
    bestTime: 'Jul–Oct',
    duration: '4–6 nights',
    from: '$1,800',
    description: "Hwange National Park is Zimbabwe's largest reserve, with over 40,000 elephants — one of the largest concentrations in Africa. The park is famous for its waterhole viewing, especially at Mandavu and Masuma dams, where you can watch elephants, lions, and buffalo gather to drink.",
    experiences: ['Waterhole wildlife viewing', 'Wild dog tracking', 'Night game drives', 'Lion research', 'Walking safaris'],
    camps: ['Linkwasha Camp', 'Somalisa Camp', 'Hwange Safari Lodge', 'The Hide', 'Ivory Lodge'],
    unesco: false,
  },
  {
    slug: 'etosha',
    name: 'Etosha National Park',
    country: 'Namibia',
    region: 'Southern Africa',
    tagline: 'Otherworldy Salt Pan Wildlife',
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/africa/etosha.jpg',
    highlights: ['Waterhole Viewing', 'Rhinos', 'Self-Drive', 'Etosha Pan'],
    bestTime: 'Jun–Oct',
    duration: '4–7 nights',
    from: '$2,000',
    description: "Etosha National Park is centered around a massive salt pan so large it's visible from space. The pan is dry and white for most of the year, but wildlife concentrates around the permanent springs along its edge, making waterhole viewing spectacular. Etosha is one of Africa's best places to see black and white rhinos.",
    experiences: ['Floodlit waterhole viewing', 'Etosha Pan drive', 'Rhino photography', 'Ongava walking safaris', 'Birdwatching'],
    camps: ['Ongava Lodge', 'Etosha Safari Camp', 'Mushara Lodge', 'Onduli Ridge', 'Mokuti Etosha Lodge'],
    unesco: false,
  },
  {
    slug: 'sossusvlei',
    name: 'Sossusvlei',
    country: 'Namibia',
    region: 'Southern Africa',
    tagline: "Africa's Most Dramatic Landscapes",
    gradient: 'linear-gradient(160deg,#2a1a00,#402800,#563600)',
    image: '/images/africa/sossusvlei.jpg',
    highlights: ['Red Sand Dunes', 'Stargazing', 'Photography', 'Deadvlei'],
    bestTime: 'May–Oct',
    duration: '3–5 nights',
    from: '$2,600',
    description: "Sossusvlei is Namibia's most iconic landscape — towering red sand dunes that are among the highest in the world (up to 325 meters). At sunrise and sunset, the dunes glow in shades of red, orange, and purple, creating a photographer's paradise. Deadvlei, with its dead 900-year-old camel thorn trees, is one of Africa's most photographed locations.",
    experiences: ['Deadvlei photography', 'Dune 45 sunrise climb', 'Balloon flight', 'Stargazing', 'Quad biking'],
    camps: ['Sossusvlei Lodge', 'Little Kulala', 'Sossus Dune Lodge', 'Dead Valley Lodge', 'Zannier Reserve'],
    unesco: true,
  },
]