export const westAfricaDestinations = [
  {
    slug: 'ghana-coast',
    name: 'Cape Coast & Accra',
    country: 'Ghana',
    region: 'West Africa',
    tagline: "West Africa's Gateway",
    gradient: 'linear-gradient(160deg,#1c1000,#2c1a00,#402400)',
    image: '/images/africa/ghana-coast.jpg',
    highlights: ['Cape Coast Castle', 'Kakum Park', 'Accra Culture', 'Independence Square'],
    bestTime: 'Nov–Mar',
    duration: '4–7 nights',
    from: '$1,300',
    description: "Ghana is West Africa's most welcoming country, offering a profound journey through the history of the transatlantic slave trade at Cape Coast Castle, the rainforest canopy walk at Kakum National Park, and the vibrant streets of Accra, where contemporary African culture thrives.",
    experiences: ['Cape Coast Castle tour', 'Kakum canopy walk', 'Accra market tour', 'Labadi Beach', 'Kwame Nkrumah Mausoleum'],
    camps: ['Labadi Beach Hotel', 'Kempinski Gold Coast City', 'Movenpick Ambassador', 'Elmina Beach Resort'],
    unesco: true,
  },
  {
    slug: 'kakum',
    name: 'Kakum National Park',
    country: 'Ghana',
    region: 'West Africa',
    tagline: 'Rainforest Canopy Walk',
    gradient: 'linear-gradient(160deg,#001c10,#00301a,#004422)',
    image: '/images/africa/kakum.jpg',
    highlights: ['Canopy Walk', 'Monkeys', 'Birding', 'Forest Elephants'],
    bestTime: 'Nov–Mar',
    duration: '2–3 nights',
    from: '$900',
    description: "Kakum National Park is one of West Africa's last remaining coastal rainforests, famous for its 350-meter-long canopy walkway suspended 30 meters above the forest floor. The park is home to forest elephants, monkeys, antelopes, and over 250 bird species.",
    experiences: ['Canopy walkway', 'Forest elephant tracking', 'Bird watching', 'Night nature walks', 'Local guide stories'],
    camps: ['Rainforest Lodge', 'Hansa Hotel', 'Coconut Grove Beach Resort', 'Elmina Beach Resort'],
    unesco: false,
  },
  {
    slug: 'lagos',
    name: 'Lagos',
    country: 'Nigeria',
    region: 'West Africa',
    tagline: "Africa's Giant of Energy & Culture",
    gradient: 'linear-gradient(160deg,#1c1400,#2c2000,#3c2c00)',
    image: '/images/africa/lagos.jpg',
    highlights: ['Nightlife', 'Art Scene', 'Beaches', 'Afrobeats'],
    bestTime: 'Nov–Feb',
    duration: '4–7 nights',
    from: '$1,200',
    description: "Lagos is Africa's most energetic city — a chaotic, creative, and unstoppable megacity where Afrobeats was born, tech startups thrive, and the art scene rivals any in the world. Explore the floating slum of Makoko, the galleries of Victoria Island, and the beaches of Tarkwa Bay.",
    experiences: ['Nike Art Gallery', 'Makoko boat tour', 'Lekki Conservation Centre', 'Tarkwa Bay Beach', 'Afrobeats club night'],
    camps: ['Eko Hotels', 'Four Points Victoria Island', 'Radisson Blu', 'The George', 'Lagos Marriott'],
    unesco: false,
  },
  {
    slug: 'obudu',
    name: 'Obudu Mountain Resort',
    country: 'Nigeria',
    region: 'West Africa',
    tagline: 'Mountain Escape & Cable Cars',
    gradient: 'linear-gradient(160deg,#002010,#003018,#004020)',
    image: '/images/africa/obudu.jpg',
    highlights: ['Cable Cars', 'Mountain Hikes', 'Waterfalls', 'Golf'],
    bestTime: 'Nov–Feb',
    duration: '3–5 nights',
    from: '$1,000',
    description: "Obudu Mountain Resort sits on the Obudu Plateau at 1,576 meters above sea level, offering Nigeria's coolest climate and most spectacular mountain scenery. Take Africa's longest cable car up the escarpment, hike to waterfalls, and enjoy stunning views across Cameroon.",
    experiences: ['Cable car ascent', 'Waterfall trekking', 'Mountain hiking', 'Golf course', 'Wildlife viewing'],
    camps: ['Obudu Mountain Resort', 'Bebi Airstrip Camp', 'Calabar Hotels'],
    unesco: false,
  },
  {
    slug: 'goree-island',
    name: 'Gorée Island',
    country: 'Senegal',
    region: 'West Africa',
    tagline: 'History & Atlantic Beauty',
    gradient: 'linear-gradient(160deg,#001c1c,#003028,#004434)',
    image: '/images/africa/goree.jpg',
    highlights: ['Slave History', 'French Colonial', 'Beaches', 'Art Studios'],
    bestTime: 'Nov–May',
    duration: '2–3 nights',
    from: '$1,200',
    description: "Gorée Island is a UNESCO World Heritage site just off the coast of Dakar, known as the 'Slave Island' for its role in the Atlantic slave trade. The House of Slaves museum, with its 'Door of No Return', is a profoundly moving memorial. The island's car-free streets are lined with colonial architecture and artist studios.",
    experiences: ['House of Slaves tour', 'Colonial architecture walk', 'Artist studio visits', 'Beach swimming', 'Ferry crossing from Dakar'],
    camps: ['Radisson Blu Dakar', 'Terrou-Bi Beach Resort', 'Pulma Beach Resort'],
    unesco: true,
  },
  {
    slug: 'abidjan',
    name: 'Abidjan',
    country: 'Ivory Coast',
    region: 'West Africa',
    tagline: "Paris of West Africa",
    gradient: 'linear-gradient(160deg,#1a1800,#2a2800,#3a3800)',
    image: '/images/africa/abidjan.jpg',
    highlights: ['St. Paul\'s Cathedral', 'Nightlife', 'Markets', 'Lagoon'],
    bestTime: 'Dec–Apr',
    duration: '3–5 nights',
    from: '$1,100',
    description: "Abidjan is Ivory Coast's vibrant economic capital, known as the 'Paris of West Africa' for its sophisticated architecture, French-influenced cuisine, and lively nightlife. Explore the futuristic St. Paul's Cathedral, cross the Houphouët-Boigny Bridge, and visit the sprawling Treichville market.",
    experiences: ['St. Paul\'s Cathedral', 'Treichville market', 'Plateau district walk', 'Banco National Park', 'Lagoon cruise'],
    camps: ['Hotel Ivoire', 'Radisson Blu Abidjan', 'Seen Hotel Abidjan', 'Pullman Abidjan'],
    unesco: false,
  },
]