-- ══════════════════════════════════════════════════════════════════
-- [YOUR BRAND] — Full Countries Seed (195 Countries)
-- Run in Supabase SQL Editor AFTER schema.sql
-- ══════════════════════════════════════════════════════════════════

INSERT INTO public.countries (name, iso_code, iso3_code, continent, currency, currency_code, language, flag_emoji, phone_code) VALUES

-- ── AFRICA (54 countries) ──
('Algeria','DZ','DZA','Africa','Dinar','DZD','Arabic','🇩🇿','+213'),
('Angola','AO','AGO','Africa','Kwanza','AOA','Portuguese','🇦🇴','+244'),
('Benin','BJ','BEN','Africa','CFA Franc','XOF','French','🇧🇯','+229'),
('Botswana','BW','BWA','Africa','Pula','BWP','English','🇧🇼','+267'),
('Burkina Faso','BF','BFA','Africa','CFA Franc','XOF','French','🇧🇫','+226'),
('Burundi','BI','BDI','Africa','Franc','BIF','French','🇧🇮','+257'),
('Cabo Verde','CV','CPV','Africa','Escudo','CVE','Portuguese','🇨🇻','+238'),
('Cameroon','CM','CMR','Africa','CFA Franc','XAF','French','🇨🇲','+237'),
('Central African Republic','CF','CAF','Africa','CFA Franc','XAF','French','🇨🇫','+236'),
('Chad','TD','TCD','Africa','CFA Franc','XAF','French','🇹🇩','+235'),
('Comoros','KM','COM','Africa','Franc','KMF','Arabic','🇰🇲','+269'),
('Congo','CG','COG','Africa','CFA Franc','XAF','French','🇨🇬','+242'),
('DR Congo','CD','COD','Africa','Franc','CDF','French','🇨🇩','+243'),
('Djibouti','DJ','DJI','Africa','Franc','DJF','French','🇩🇯','+253'),
('Egypt','EG','EGY','Africa','Pound','EGP','Arabic','🇪🇬','+20'),
('Equatorial Guinea','GQ','GNQ','Africa','CFA Franc','XAF','Spanish','🇬🇶','+240'),
('Eritrea','ER','ERI','Africa','Nakfa','ERN','Tigrinya','🇪🇷','+291'),
('Eswatini','SZ','SWZ','Africa','Lilangeni','SZL','English','🇸🇿','+268'),
('Ethiopia','ET','ETH','Africa','Birr','ETB','Amharic','🇪🇹','+251'),
('Gabon','GA','GAB','Africa','CFA Franc','XAF','French','🇬🇦','+241'),
('Gambia','GM','GMB','Africa','Dalasi','GMD','English','🇬🇲','+220'),
('Ghana','GH','GHA','Africa','Cedi','GHS','English','🇬🇭','+233'),
('Guinea','GN','GIN','Africa','Franc','GNF','French','🇬🇳','+224'),
('Guinea-Bissau','GW','GNB','Africa','CFA Franc','XOF','Portuguese','🇬🇼','+245'),
('Ivory Coast','CI','CIV','Africa','CFA Franc','XOF','French','🇨🇮','+225'),
('Kenya','KE','KEN','Africa','Shilling','KES','Swahili','🇰🇪','+254'),
('Lesotho','LS','LSO','Africa','Loti','LSL','English','🇱🇸','+266'),
('Liberia','LR','LBR','Africa','Dollar','LRD','English','🇱🇷','+231'),
('Libya','LY','LBY','Africa','Dinar','LYD','Arabic','🇱🇾','+218'),
('Madagascar','MG','MDG','Africa','Ariary','MGA','French','🇲🇬','+261'),
('Malawi','MW','MWI','Africa','Kwacha','MWK','English','🇲🇼','+265'),
('Mali','ML','MLI','Africa','CFA Franc','XOF','French','🇲🇱','+223'),
('Mauritania','MR','MRT','Africa','Ouguiya','MRU','Arabic','🇲🇷','+222'),
('Mauritius','MU','MUS','Africa','Rupee','MUR','English','🇲🇺','+230'),
('Morocco','MA','MAR','Africa','Dirham','MAD','Arabic','🇲🇦','+212'),
('Mozambique','MZ','MOZ','Africa','Metical','MZN','Portuguese','🇲🇿','+258'),
('Namibia','NA','NAM','Africa','Dollar','NAD','English','🇳🇦','+264'),
('Niger','NE','NER','Africa','CFA Franc','XOF','French','🇳🇪','+227'),
('Nigeria','NG','NGA','Africa','Naira','NGN','English','🇳🇬','+234'),
('Rwanda','RW','RWA','Africa','Franc','RWF','English','🇷🇼','+250'),
('São Tomé and Príncipe','ST','STP','Africa','Dobra','STN','Portuguese','🇸🇹','+239'),
('Senegal','SN','SEN','Africa','CFA Franc','XOF','French','🇸🇳','+221'),
('Seychelles','SC','SYC','Africa','Rupee','SCR','English','🇸🇨','+248'),
('Sierra Leone','SL','SLE','Africa','Leone','SLL','English','🇸🇱','+232'),
('Somalia','SO','SOM','Africa','Shilling','SOS','Somali','🇸🇴','+252'),
('South Africa','ZA','ZAF','Africa','Rand','ZAR','English','🇿🇦','+27'),
('South Sudan','SS','SSD','Africa','Pound','SSP','English','🇸🇸','+211'),
('Sudan','SD','SDN','Africa','Pound','SDG','Arabic','🇸🇩','+249'),
('Tanzania','TZ','TZA','Africa','Shilling','TZS','Swahili','🇹🇿','+255'),
('Togo','TG','TGO','Africa','CFA Franc','XOF','French','🇹🇬','+228'),
('Tunisia','TN','TUN','Africa','Dinar','TND','Arabic','🇹🇳','+216'),
('Uganda','UG','UGA','Africa','Shilling','UGX','English','🇺🇬','+256'),
('Zambia','ZM','ZMB','Africa','Kwacha','ZMW','English','🇿🇲','+260'),
('Zimbabwe','ZW','ZWE','Africa','Dollar','ZWL','English','🇿🇼','+263'),

-- ── ASIA (48 countries) ──
('Afghanistan','AF','AFG','Asia','Afghani','AFN','Pashto','🇦🇫','+93'),
('Armenia','AM','ARM','Asia','Dram','AMD','Armenian','🇦🇲','+374'),
('Azerbaijan','AZ','AZE','Asia','Manat','AZN','Azerbaijani','🇦🇿','+994'),
('Bahrain','BH','BHR','Middle East','Dinar','BHD','Arabic','🇧🇭','+973'),
('Bangladesh','BD','BGD','Asia','Taka','BDT','Bengali','🇧🇩','+880'),
('Bhutan','BT','BTN','Asia','Ngultrum','BTN','Dzongkha','🇧🇹','+975'),
('Brunei','BN','BRN','Asia','Dollar','BND','Malay','🇧🇳','+673'),
('Cambodia','KH','KHM','Asia','Riel','KHR','Khmer','🇰🇭','+855'),
('China','CN','CHN','Asia','Yuan','CNY','Mandarin','🇨🇳','+86'),
('Cyprus','CY','CYP','Europe','Euro','EUR','Greek','🇨🇾','+357'),
('Georgia','GE','GEO','Asia','Lari','GEL','Georgian','🇬🇪','+995'),
('India','IN','IND','Asia','Rupee','INR','Hindi','🇮🇳','+91'),
('Indonesia','ID','IDN','Asia','Rupiah','IDR','Indonesian','🇮🇩','+62'),
('Iran','IR','IRN','Asia','Rial','IRR','Persian','🇮🇷','+98'),
('Iraq','IQ','IRQ','Middle East','Dinar','IQD','Arabic','🇮🇶','+964'),
('Israel','IL','ISR','Middle East','Shekel','ILS','Hebrew','🇮🇱','+972'),
('Japan','JP','JPN','Asia','Yen','JPY','Japanese','🇯🇵','+81'),
('Jordan','JO','JOR','Middle East','Dinar','JOD','Arabic','🇯🇴','+962'),
('Kazakhstan','KZ','KAZ','Asia','Tenge','KZT','Kazakh','🇰🇿','+7'),
('Kuwait','KW','KWT','Middle East','Dinar','KWD','Arabic','🇰🇼','+965'),
('Kyrgyzstan','KG','KGZ','Asia','Som','KGS','Kyrgyz','🇰🇬','+996'),
('Laos','LA','LAO','Asia','Kip','LAK','Lao','🇱🇦','+856'),
('Lebanon','LB','LBN','Middle East','Pound','LBP','Arabic','🇱🇧','+961'),
('Malaysia','MY','MYS','Asia','Ringgit','MYR','Malay','🇲🇾','+60'),
('Maldives','MV','MDV','Asia','Rufiyaa','MVR','Dhivehi','🇲🇻','+960'),
('Mongolia','MN','MNG','Asia','Tögrög','MNT','Mongolian','🇲🇳','+976'),
('Myanmar','MM','MMR','Asia','Kyat','MMK','Burmese','🇲🇲','+95'),
('Nepal','NP','NPL','Asia','Rupee','NPR','Nepali','🇳🇵','+977'),
('North Korea','KP','PRK','Asia','Won','KPW','Korean','🇰🇵','+850'),
('Oman','OM','OMN','Middle East','Rial','OMR','Arabic','🇴🇲','+968'),
('Pakistan','PK','PAK','Asia','Rupee','PKR','Urdu','🇵🇰','+92'),
('Palestine','PS','PSE','Middle East','Shekel','ILS','Arabic','🇵🇸','+970'),
('Philippines','PH','PHL','Asia','Peso','PHP','Filipino','🇵🇭','+63'),
('Qatar','QA','QAT','Middle East','Riyal','QAR','Arabic','🇶🇦','+974'),
('Saudi Arabia','SA','SAU','Middle East','Riyal','SAR','Arabic','🇸🇦','+966'),
('Singapore','SG','SGP','Asia','Dollar','SGD','English','🇸🇬','+65'),
('South Korea','KR','KOR','Asia','Won','KRW','Korean','🇰🇷','+82'),
('Sri Lanka','LK','LKA','Asia','Rupee','LKR','Sinhala','🇱🇰','+94'),
('Syria','SY','SYR','Middle East','Pound','SYP','Arabic','🇸🇾','+963'),
('Taiwan','TW','TWN','Asia','Dollar','TWD','Mandarin','🇹🇼','+886'),
('Tajikistan','TJ','TJK','Asia','Somoni','TJS','Tajik','🇹🇯','+992'),
('Thailand','TH','THA','Asia','Baht','THB','Thai','🇹🇭','+66'),
('Timor-Leste','TL','TLS','Asia','Dollar','USD','Tetum','🇹🇱','+670'),
('Turkmenistan','TM','TKM','Asia','Manat','TMT','Turkmen','🇹🇲','+993'),
('United Arab Emirates','AE','ARE','Middle East','Dirham','AED','Arabic','🇦🇪','+971'),
('Uzbekistan','UZ','UZB','Asia','Som','UZS','Uzbek','🇺🇿','+998'),
('Vietnam','VN','VNM','Asia','Dong','VND','Vietnamese','🇻🇳','+84'),
('Yemen','YE','YEM','Middle East','Rial','YER','Arabic','🇾🇪','+967'),

-- ── EUROPE (44 countries) ──
('Albania','AL','ALB','Europe','Lek','ALL','Albanian','🇦🇱','+355'),
('Andorra','AD','AND','Europe','Euro','EUR','Catalan','🇦🇩','+376'),
('Austria','AT','AUT','Europe','Euro','EUR','German','🇦🇹','+43'),
('Belarus','BY','BLR','Europe','Ruble','BYN','Belarusian','🇧🇾','+375'),
('Belgium','BE','BEL','Europe','Euro','EUR','Dutch','🇧🇪','+32'),
('Bosnia and Herzegovina','BA','BIH','Europe','Mark','BAM','Bosnian','🇧🇦','+387'),
('Bulgaria','BG','BGR','Europe','Lev','BGN','Bulgarian','🇧🇬','+359'),
('Croatia','HR','HRV','Europe','Euro','EUR','Croatian','🇭🇷','+385'),
('Czech Republic','CZ','CZE','Europe','Koruna','CZK','Czech','🇨🇿','+420'),
('Denmark','DK','DNK','Europe','Krone','DKK','Danish','🇩🇰','+45'),
('Estonia','EE','EST','Europe','Euro','EUR','Estonian','🇪🇪','+372'),
('Finland','FI','FIN','Europe','Euro','EUR','Finnish','🇫🇮','+358'),
('France','FR','FRA','Europe','Euro','EUR','French','🇫🇷','+33'),
('Germany','DE','DEU','Europe','Euro','EUR','German','🇩🇪','+49'),
('Greece','GR','GRC','Europe','Euro','EUR','Greek','🇬🇷','+30'),
('Hungary','HU','HUN','Europe','Forint','HUF','Hungarian','🇭🇺','+36'),
('Iceland','IS','ISL','Arctic','Krona','ISK','Icelandic','🇮🇸','+354'),
('Ireland','IE','IRL','Europe','Euro','EUR','English','🇮🇪','+353'),
('Italy','IT','ITA','Europe','Euro','EUR','Italian','🇮🇹','+39'),
('Kosovo','XK','XKX','Europe','Euro','EUR','Albanian','🇽🇰','+383'),
('Latvia','LV','LVA','Europe','Euro','EUR','Latvian','🇱🇻','+371'),
('Liechtenstein','LI','LIE','Europe','Franc','CHF','German','🇱🇮','+423'),
('Lithuania','LT','LTU','Europe','Euro','EUR','Lithuanian','🇱🇹','+370'),
('Luxembourg','LU','LUX','Europe','Euro','EUR','Luxembourgish','🇱🇺','+352'),
('Malta','MT','MLT','Europe','Euro','EUR','Maltese','🇲🇹','+356'),
('Moldova','MD','MDA','Europe','Leu','MDL','Romanian','🇲🇩','+373'),
('Monaco','MC','MCO','Europe','Euro','EUR','French','🇲🇨','+377'),
('Montenegro','ME','MNE','Europe','Euro','EUR','Montenegrin','🇲🇪','+382'),
('Netherlands','NL','NLD','Europe','Euro','EUR','Dutch','🇳🇱','+31'),
('North Macedonia','MK','MKD','Europe','Denar','MKD','Macedonian','🇲🇰','+389'),
('Norway','NO','NOR','Arctic','Krone','NOK','Norwegian','🇳🇴','+47'),
('Poland','PL','POL','Europe','Zloty','PLN','Polish','🇵🇱','+48'),
('Portugal','PT','PRT','Europe','Euro','EUR','Portuguese','🇵🇹','+351'),
('Romania','RO','ROU','Europe','Leu','RON','Romanian','🇷🇴','+40'),
('Russia','RU','RUS','Europe','Ruble','RUB','Russian','🇷🇺','+7'),
('San Marino','SM','SMR','Europe','Euro','EUR','Italian','🇸🇲','+378'),
('Serbia','RS','SRB','Europe','Dinar','RSD','Serbian','🇷🇸','+381'),
('Slovakia','SK','SVK','Europe','Euro','EUR','Slovak','🇸🇰','+421'),
('Slovenia','SI','SVN','Europe','Euro','EUR','Slovenian','🇸🇮','+386'),
('Spain','ES','ESP','Europe','Euro','EUR','Spanish','🇪🇸','+34'),
('Sweden','SE','SWE','Europe','Krona','SEK','Swedish','🇸🇪','+46'),
('Switzerland','CH','CHE','Europe','Franc','CHF','German','🇨🇭','+41'),
('Ukraine','UA','UKR','Europe','Hryvnia','UAH','Ukrainian','🇺🇦','+380'),
('United Kingdom','GB','GBR','Europe','Pound','GBP','English','🇬🇧','+44'),
('Vatican City','VA','VAT','Europe','Euro','EUR','Italian','🇻🇦','+379'),

-- ── AMERICAS (35 countries) ──
('Antigua and Barbuda','AG','ATG','Americas','Dollar','XCD','English','🇦🇬','+1'),
('Argentina','AR','ARG','Americas','Peso','ARS','Spanish','🇦🇷','+54'),
('Bahamas','BS','BHS','Americas','Dollar','BSD','English','🇧🇸','+1'),
('Barbados','BB','BRB','Americas','Dollar','BBD','English','🇧🇧','+1'),
('Belize','BZ','BLZ','Americas','Dollar','BZD','English','🇧🇿','+501'),
('Bolivia','BO','BOL','Americas','Boliviano','BOB','Spanish','🇧🇴','+591'),
('Brazil','BR','BRA','Americas','Real','BRL','Portuguese','🇧🇷','+55'),
('Canada','CA','CAN','Americas','Dollar','CAD','English','🇨🇦','+1'),
('Chile','CL','CHL','Americas','Peso','CLP','Spanish','🇨🇱','+56'),
('Colombia','CO','COL','Americas','Peso','COP','Spanish','🇨🇴','+57'),
('Costa Rica','CR','CRI','Americas','Colón','CRC','Spanish','🇨🇷','+506'),
('Cuba','CU','CUB','Americas','Peso','CUP','Spanish','🇨🇺','+53'),
('Dominica','DM','DMA','Americas','Dollar','XCD','English','🇩🇲','+1'),
('Dominican Republic','DO','DOM','Americas','Peso','DOP','Spanish','🇩🇴','+1'),
('Ecuador','EC','ECU','Americas','Dollar','USD','Spanish','🇪🇨','+593'),
('El Salvador','SV','SLV','Americas','Dollar','USD','Spanish','🇸🇻','+503'),
('Grenada','GD','GRD','Americas','Dollar','XCD','English','🇬🇩','+1'),
('Guatemala','GT','GTM','Americas','Quetzal','GTQ','Spanish','🇬🇹','+502'),
('Guyana','GY','GUY','Americas','Dollar','GYD','English','🇬🇾','+592'),
('Haiti','HT','HTI','Americas','Gourde','HTG','French','🇭🇹','+509'),
('Honduras','HN','HND','Americas','Lempira','HNL','Spanish','🇭🇳','+504'),
('Jamaica','JM','JAM','Americas','Dollar','JMD','English','🇯🇲','+1'),
('Mexico','MX','MEX','Americas','Peso','MXN','Spanish','🇲🇽','+52'),
('Nicaragua','NI','NIC','Americas','Córdoba','NIO','Spanish','🇳🇮','+505'),
('Panama','PA','PAN','Americas','Balboa','PAB','Spanish','🇵🇦','+507'),
('Paraguay','PY','PRY','Americas','Guaraní','PYG','Spanish','🇵🇾','+595'),
('Peru','PE','PER','Americas','Sol','PEN','Spanish','🇵🇪','+51'),
('Saint Kitts and Nevis','KN','KNA','Americas','Dollar','XCD','English','🇰🇳','+1'),
('Saint Lucia','LC','LCA','Americas','Dollar','XCD','English','🇱🇨','+1'),
('Saint Vincent and the Grenadines','VC','VCT','Americas','Dollar','XCD','English','🇻🇨','+1'),
('Suriname','SR','SUR','Americas','Dollar','SRD','Dutch','🇸🇷','+597'),
('Trinidad and Tobago','TT','TTO','Americas','Dollar','TTD','English','🇹🇹','+1'),
('United States','US','USA','Americas','Dollar','USD','English','🇺🇸','+1'),
('Uruguay','UY','URY','Americas','Peso','UYU','Spanish','🇺🇾','+598'),
('Venezuela','VE','VEN','Americas','Bolívar','VES','Spanish','🇻🇪','+58'),

-- ── OCEANIA (14 countries) ──
('Australia','AU','AUS','Oceania','Dollar','AUD','English','🇦🇺','+61'),
('Fiji','FJ','FJI','Oceania','Dollar','FJD','English','🇫🇯','+679'),
('Kiribati','KI','KIR','Oceania','Dollar','AUD','English','🇰🇮','+686'),
('Marshall Islands','MH','MHL','Oceania','Dollar','USD','Marshallese','🇲🇭','+692'),
('Micronesia','FM','FSM','Oceania','Dollar','USD','English','🇫🇲','+691'),
('Nauru','NR','NRU','Oceania','Dollar','AUD','Nauruan','🇳🇷','+674'),
('New Zealand','NZ','NZL','Oceania','Dollar','NZD','English','🇳🇿','+64'),
('Palau','PW','PLW','Oceania','Dollar','USD','Palauan','🇵🇼','+680'),
('Papua New Guinea','PG','PNG','Oceania','Kina','PGK','English','🇵🇬','+675'),
('Samoa','WS','WSM','Oceania','Tālā','WST','Samoan','🇼🇸','+685'),
('Solomon Islands','SB','SLB','Oceania','Dollar','SBD','English','🇸🇧','+677'),
('Tonga','TO','TON','Oceania','Paʻanga','TOP','Tongan','🇹🇴','+676'),
('Tuvalu','TV','TUV','Oceania','Dollar','AUD','Tuvaluan','🇹🇻','+688'),
('Vanuatu','VU','VUT','Oceania','Vatu','VUV','Bislama','🇻🇺','+678')

ON CONFLICT (iso_code) DO UPDATE SET
  name = EXCLUDED.name,
  continent = EXCLUDED.continent,
  currency = EXCLUDED.currency,
  currency_code = EXCLUDED.currency_code,
  language = EXCLUDED.language,
  flag_emoji = EXCLUDED.flag_emoji,
  phone_code = EXCLUDED.phone_code;

-- ── SUMMARY ──
SELECT continent, COUNT(*) AS country_count
FROM public.countries
GROUP BY continent
ORDER BY country_count DESC;
