-- Seed data for the /tours and /tours/[slug] routes. Safe to re-run —
-- upserted on slug.

INSERT INTO public.tours_activities
  (name, slug, category, description, long_desc, cover_image, gallery,
   duration_hours, max_group_size, min_age, difficulty, includes, excludes,
   meeting_point, languages, base_price, currency, avg_rating, review_count,
   is_featured, is_published)
VALUES
  (
    'Serengeti Big Five Safari',
    'serengeti-big-five-safari',
    'wildlife',
    'A full-day game drive through the central Serengeti tracking lion, leopard, elephant, rhino, and buffalo with a resident naturalist guide.',
    'Depart at dawn for the best light and wildlife activity. Your guide tracks the Big Five across open plains and riverine forest, with a bush breakfast stop and picnic lunch included. Small-group vehicles only, with pop-up roofs for unobstructed photography.',
    'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&q=80',
    ARRAY['https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&q=80','https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=1200&q=80'],
    9, 6, 8, 'easy',
    ARRAY['Professional guide', 'Safari vehicle', 'Bush breakfast', 'Picnic lunch', 'Park fees'],
    ARRAY['Hotel transfers', 'Gratuities'],
    'Lodge reception, central Serengeti',
    ARRAY['English', 'Swahili'],
    340, 'USD', 4.9, 88, TRUE, TRUE
  ),
  (
    'Santorini Sunset Sailing',
    'santorini-sunset-sailing',
    'cruise',
    'A catamaran cruise around the caldera with swimming stops at the volcanic hot springs and a barbecue dinner as the sun sets behind Oia.',
    'Sail past the red and white beaches of Santorini before anchoring at the volcanic hot springs for a swim. The crew prepares a Greek barbecue on board while you watch the sun set behind the caldera cliffs — widely considered one of the best sunset views in the world.',
    'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=1200&q=80',
    ARRAY['https://images.unsplash.com/photo-1533105079780-92b9be482077?w=1200&q=80'],
    5, 20, 5, 'easy',
    ARRAY['Catamaran cruise', 'BBQ dinner', 'Local wine', 'Snorkeling gear'],
    ARRAY['Hotel transfers'],
    'Vlychada Marina, Santorini',
    ARRAY['English', 'Greek'],
    95, 'USD', 4.8, 214, TRUE, TRUE
  ),
  (
    'Kyoto Temples & Tea Ceremony',
    'kyoto-temples-tea-ceremony',
    'cultural',
    'A guided walk through Higashiyama''s historic temples, ending with a traditional tea ceremony led by a certified tea master.',
    'Wander the preserved streets of Higashiyama past Kiyomizu-dera and Yasaka Shrine with a local guide who explains the history and etiquette of each site. The afternoon closes with a formal tea ceremony in a 200-year-old machiya house, guided by a certified tea master.',
    'https://images.unsplash.com/photo-1545389336-cf090694435e?w=1200&q=80',
    ARRAY['https://images.unsplash.com/photo-1545389336-cf090694435e?w=1200&q=80','https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=1200&q=80'],
    4, 8, 10, 'easy',
    ARRAY['Local guide', 'Temple entrance fees', 'Tea ceremony', 'Traditional sweets'],
    ARRAY['Hotel transfers', 'Lunch'],
    'Kiyomizu-dera main gate, Kyoto',
    ARRAY['English', 'Japanese'],
    120, 'USD', 4.9, 156, FALSE, TRUE
  ),
  (
    'Sahara Overnight Camel Trek',
    'sahara-overnight-camel-trek',
    'adventure',
    'Ride camels into the Agafay dunes at sunset, camp overnight under the stars, and return after a Berber breakfast.',
    'A caravan of camels carries you into the dunes as the desert light turns gold. Settle into a traditional camp for a Berber dinner around the fire, with music and stargazing before sleeping in a private tent. Wake for sunrise and a simple breakfast before the return trek.',
    'https://images.unsplash.com/photo-1489493887464-892be6d1daae?w=1200&q=80',
    ARRAY['https://images.unsplash.com/photo-1489493887464-892be6d1daae?w=1200&q=80'],
    18, 12, 6, 'moderate',
    ARRAY['Camel trek', 'Overnight camp', 'Dinner and breakfast', 'Berber guide'],
    ARRAY['Hotel transfers', 'Drinks'],
    'Agafay Desert basecamp, near Marrakech',
    ARRAY['English', 'French', 'Arabic'],
    180, 'USD', 4.7, 92, FALSE, TRUE
  ),
  (
    'Amalfi Coast Cooking Class',
    'amalfi-coast-cooking-class',
    'food',
    'Learn to make fresh pasta and a classic Neapolitan sauce in a family-run kitchen overlooking the coast, followed by a shared meal.',
    'Join a local family in their hillside kitchen to hand-roll pasta and prepare a traditional sauce from scratch, using produce from their own lemon and tomato garden. The class ends with everyone sitting down together to eat what you''ve made, paired with local wine.',
    'https://images.unsplash.com/photo-1533617804797-91a4bf27fb98?w=1200&q=80',
    ARRAY['https://images.unsplash.com/photo-1533617804797-91a4bf27fb98?w=1200&q=80'],
    3.5, 10, 12, 'easy',
    ARRAY['Ingredients', 'Wine pairing', 'Recipe booklet', 'Shared meal'],
    ARRAY['Hotel transfers'],
    'Private villa kitchen, Positano',
    ARRAY['English', 'Italian'],
    110, 'USD', 4.8, 61, FALSE, TRUE
  ),
  (
    'Maldives Snorkeling & Dolphin Cruise',
    'maldives-snorkeling-dolphin-cruise',
    'day_tour',
    'A half-day boat trip to a private reef for snorkeling with reef sharks and turtles, followed by a sunset dolphin-watching cruise.',
    'Start at a protected house reef known for reef sharks, turtles, and colorful coral gardens — all snorkeling gear and guidance included. As the light turns golden, the boat heads out to open water where spinner dolphin pods are regularly spotted riding the bow wake.',
    'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=1200&q=80',
    ARRAY['https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=1200&q=80','https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=1200&q=80'],
    4, 14, 6, 'easy',
    ARRAY['Snorkeling gear', 'Boat crew and guide', 'Soft drinks', 'Fruit platter'],
    ARRAY['Resort transfers'],
    'Resort water sports jetty',
    ARRAY['English'],
    75, 'USD', 4.9, 178, TRUE, TRUE
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  long_desc = EXCLUDED.long_desc,
  cover_image = EXCLUDED.cover_image,
  gallery = EXCLUDED.gallery,
  duration_hours = EXCLUDED.duration_hours,
  max_group_size = EXCLUDED.max_group_size,
  min_age = EXCLUDED.min_age,
  difficulty = EXCLUDED.difficulty,
  includes = EXCLUDED.includes,
  excludes = EXCLUDED.excludes,
  meeting_point = EXCLUDED.meeting_point,
  languages = EXCLUDED.languages,
  base_price = EXCLUDED.base_price,
  currency = EXCLUDED.currency,
  avg_rating = EXCLUDED.avg_rating,
  review_count = EXCLUDED.review_count,
  is_featured = EXCLUDED.is_featured,
  is_published = EXCLUDED.is_published;
